import { SupportedCity } from "../../../lib/trip-domain";
import { BudgetBasketId } from "../domain/types";

export interface AccommodationCandidateSpot {
  id: string;
  cityCode: SupportedCity;
  basketId: BudgetBasketId;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  nightlyPriceKrw: number;
  locationKo: string;
  locationEn: string;
  tag: string;
  emoji: string;
  gradientBg: string;
}

export const ACCOMMODATION_SPOTS_CATALOG: AccommodationCandidateSpot[] = [
  // === SEOUL (서울) ===
  {
    id: "seoul_acc_hongdae_hostel",
    cityCode: "SEOUL",
    basketId: "BUDGET_STAY",
    nameKo: "홍대 가성비 호스텔 & 도미토리",
    nameEn: "Hongdae Budget Hostel & Dormitory",
    descKo: "홍대입구역 도보 3분, 청결하고 아늑한 전 세계 여행자 교류 호스텔",
    descEn: "Cozy traveler hostel 3 mins walk from Hongik Univ Station",
    nightlyPriceKrw: 45000,
    locationKo: "홍대/신촌",
    locationEn: "Hongdae",
    tag: "가성비/역세권",
    emoji: "🛏️",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },
  {
    id: "seoul_acc_myeongdong_standard",
    cityCode: "SEOUL",
    basketId: "STANDARD_HOTEL",
    nameKo: "명동 시티뷰 스탠다드 호텔",
    nameEn: "Myeongdong Standard City Hotel",
    descKo: "명동 쇼핑거리 중심, 시티뷰 감성과 깔끔한 비즈니스 룸 컨디션",
    descEn: "Modern city view hotel in the heart of Myeongdong shopping district",
    nightlyPriceKrw: 110000,
    locationKo: "명동",
    locationEn: "Myeongdong",
    tag: "쇼핑/시티뷰",
    emoji: "🏨",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "seoul_acc_gangnam_standard",
    cityCode: "SEOUL",
    basketId: "STANDARD_HOTEL",
    nameKo: "강남 모던 비즈니스 호텔",
    nameEn: "Gangnam Modern Business Hotel",
    descKo: "강남역 서초대로변 위치, 트렌디한 인테리어와 모던 피트니스 시설",
    descEn: "Stylish business hotel near Gangnam Station with fitness center",
    nightlyPriceKrw: 140000,
    locationKo: "강남",
    locationEn: "Gangnam",
    tag: "모던/강남역",
    emoji: "🏢",
    gradientBg: "from-sky-500/15 to-blue-600/15",
  },
  {
    id: "seoul_acc_bukchon_hanok",
    cityCode: "SEOUL",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "북촌 고즈넉 한옥 프라이빗 스테이",
    nameEn: "Bukchon Hanok Private Heritage Stay",
    descKo: "북촌 한옥마을 정취 속 독채 다도 툇마루를 즐기는 프리미엄 한옥",
    descEn: "Traditional private Hanok house with authentic tea terrace in Bukchon",
    nightlyPriceKrw: 180000,
    locationKo: "북촌",
    locationEn: "Bukchon",
    tag: "전통/독채한옥",
    emoji: "🏡",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "seoul_acc_gwanghwamun_luxury",
    cityCode: "SEOUL",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "광화문 5성급 럭셔리 스파 호텔",
    nameEn: "Gwanghwamun 5-Star Luxury Spa Hotel",
    descKo: "경복궁과 청계천이 내려다보이는 초럭셔리 다이닝 & 실내 스파",
    descEn: "5-star luxury hotel overlooking Gyeongbokgung with indoor spa",
    nightlyPriceKrw: 290000,
    locationKo: "광화문",
    locationEn: "Gwanghwamun",
    tag: "5성급/럭셔리",
    emoji: "👑",
    gradientBg: "from-rose-500/15 to-pink-500/15",
  },
  {
    id: "seoul_acc_seongsu_capsule",
    cityCode: "SEOUL",
    basketId: "BUDGET_STAY",
    nameKo: "성수 미니멀 감성 캡슐 스테이",
    nameEn: "Seongsu Minimalist Capsule Stay",
    descKo: "성수 힙스터 카페거리 라인, 프라이빗 캡슐 팟과 감성 라운지",
    descEn: "Minimal capsule stay near Seongsu cafe street with private pod",
    nightlyPriceKrw: 38000,
    locationKo: "성수",
    locationEn: "Seongsu",
    tag: "성수동/미니멀",
    emoji: "💊",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
  },

  // === BUSAN (부산) ===
  {
    id: "busan_acc_jagalchi_guesthouse",
    cityCode: "BUSAN",
    basketId: "BUDGET_STAY",
    nameKo: "자갈치 오션 가성비 게스트하우스",
    nameEn: "Jagalchi Ocean Budget Guesthouse",
    descKo: "자갈치시장 & 남포동 먹자골목 도보 이동, 바다 정취의 가성비 게하",
    descEn: "Budget guesthouse near Jagalchi market with seaside view",
    nightlyPriceKrw: 40000,
    locationKo: "자갈치/남포",
    locationEn: "Jagalchi",
    tag: "시장근처/알뜰",
    emoji: "⚓",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
  },
  {
    id: "busan_acc_gwangalli_standard",
    cityCode: "BUSAN",
    basketId: "STANDARD_HOTEL",
    nameKo: "광안리 오션뷰 힐링 호텔",
    nameEn: "Gwangalli Oceanview Healing Hotel",
    descKo: "광안대교 드론쇼가 객실에서 바로 보이는 프라이빗 테라스 호텔",
    descEn: "Hotel room directly facing Gwangandaegyo bridge and ocean",
    nightlyPriceKrw: 100000,
    locationKo: "광안리",
    locationEn: "Gwangalli",
    tag: "광안대교/오션뷰",
    emoji: "🌉",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },
  {
    id: "busan_acc_seomyeon_standard",
    cityCode: "BUSAN",
    basketId: "STANDARD_HOTEL",
    nameKo: "서면 중심 시티 모던 호텔",
    nameEn: "Seomyeon Central City Hotel",
    descKo: "부산 교통의 중심 서면역 도보 2분, 전포 카페거리 접근성 최고",
    descEn: "Modern hotel 2 mins walk from Seomyeon transit hub",
    nightlyPriceKrw: 90000,
    locationKo: "서면",
    locationEn: "Seomyeon",
    tag: "교통요충지/카페거리",
    emoji: "🏙️",
    gradientBg: "from-slate-500/15 to-slate-700/15",
  },
  {
    id: "busan_acc_haeundae_resort",
    cityCode: "BUSAN",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "해운대 최고급 인피니티풀 오션 리조트",
    nameEn: "Haeundae Luxury Infinity Pool Ocean Resort",
    descKo: "해운대 해변과 맞닿은 럭셔리 인피니티 풀과 VIP 클럽 라운지",
    descEn: "Top luxury beachfront resort with ocean infinity pool",
    nightlyPriceKrw: 260000,
    locationKo: "해운대",
    locationEn: "Haeundae",
    tag: "인피니티풀/해운대",
    emoji: "🏊",
    gradientBg: "from-sky-500/15 to-emerald-500/15",
  },
  {
    id: "busan_acc_songjeong_surf",
    cityCode: "BUSAN",
    basketId: "BUDGET_STAY",
    nameKo: "송정 해변 서핑 감성 스테이",
    nameEn: "Songjeong Beach Surf Vibe Stay",
    descKo: "송정 서핑 핫스팟 바로 앞, 트렌디한 서퍼 쉼터 & 루프탑 바",
    descEn: "Beachfront stay right in front of Songjeong surfing spot",
    nightlyPriceKrw: 45000,
    locationKo: "송정",
    locationEn: "Songjeong",
    tag: "서핑/감성루프탑",
    emoji: "🏄",
    gradientBg: "from-teal-500/15 to-cyan-500/15",
  },
  {
    id: "busan_acc_haeundae_villa",
    cityCode: "BUSAN",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "해운대 프라이빗 오션 풀빌라",
    nameEn: "Haeundae Private Ocean Pool Villa",
    descKo: "달맞이길언덕에 위치한 최고급 프라이빗 수영장 & 테라스 스파",
    descEn: "Exclusive hill-side private pool villa on Dalmaji-gil",
    nightlyPriceKrw: 350000,
    locationKo: "달맞이길",
    locationEn: "Dalmaji-gil",
    tag: "프라이빗/풀빌라",
    emoji: "🏛️",
    gradientBg: "from-amber-500/15 to-rose-500/15",
  },

  // === JEJU (제주) ===
  {
    id: "jeju_acc_airport_guesthouse",
    cityCode: "JEJU",
    basketId: "BUDGET_STAY",
    nameKo: "제주공항 근처 아담한 게스트하우스",
    nameEn: "Jeju Airport Cozy Guesthouse",
    descKo: "공항 10분 거리, 첫날과 마지막 날 부담 없는 깔끔한 오션 로드 게하",
    descEn: "Convenient cozy guesthouse 10 mins from Jeju Airport",
    nightlyPriceKrw: 35000,
    locationKo: "제주공항",
    locationEn: "Jeju Airport",
    tag: "공항근처/알뜰",
    emoji: "✈️",
    gradientBg: "from-sky-500/15 to-blue-500/15",
  },
  {
    id: "jeju_acc_aewol_standard",
    cityCode: "JEJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "애월 오션뷰 힐링 리조트",
    nameEn: "Aewol Oceanview Healing Resort",
    descKo: "애월 한담해안산책로 도보 5분, 노을이 아름다운 모던 오션 리조트",
    descEn: "Sunset-view resort near Aewol coastal walking trail",
    nightlyPriceKrw: 120000,
    locationKo: "애월",
    locationEn: "Aewol",
    tag: "애월노을/오션뷰",
    emoji: "🌅",
    gradientBg: "from-amber-500/15 to-red-500/15",
  },
  {
    id: "jeju_acc_hamdeok_pension",
    cityCode: "JEJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "함덕 에메랄드 해변 감성 펜션",
    nameEn: "Hamdeok Emerald Beach Pension",
    descKo: "에메랄드빛 함덕 서우봉 해변이 시원하게 트인 잔디 정원 펜션",
    descEn: "Charming garden pension facing emerald Hamdeok beach",
    nightlyPriceKrw: 95000,
    locationKo: "함덕",
    locationEn: "Hamdeok",
    tag: "에메랄드해변/정원",
    emoji: "🏖️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "jeju_acc_jungmun_luxury",
    cityCode: "JEJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "중문 5성급 럭셔리 풀빌라 리조트",
    nameEn: "Jungmun 5-Star Luxury Pool Villa Resort",
    descKo: "중문관광단지 해안 절벽 위, 열대 정원 온수풀 & 럭셔리 스파",
    descEn: "5-star cliffside luxury resort in Jungmun with heated pool",
    nightlyPriceKrw: 310000,
    locationKo: "중문",
    locationEn: "Jungmun",
    tag: "5성급/열대정원",
    emoji: "🌺",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "jeju_acc_seogwipo_oreum",
    cityCode: "JEJU",
    basketId: "BUDGET_STAY",
    nameKo: "서귀포 올레길 오름 스테이",
    nameEn: "Seogwipo Olle Trail Oreum Stay",
    descKo: "서귀포 매일올레시장 및 외돌개 올레길 코스 인근 아늑한 스테이",
    descEn: "Cozy nature stay near Seogwipo Olle trail market",
    nightlyPriceKrw: 45000,
    locationKo: "서귀포",
    locationEn: "Seogwipo",
    tag: "올레길/자연휴식",
    emoji: "🍊",
    gradientBg: "from-orange-500/15 to-amber-500/15",
  },
  {
    id: "jeju_acc_seongsan_heritage",
    cityCode: "JEJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "성산일출봉 프라이빗 헤리티지 스테이",
    nameEn: "Seongsan Sunrise Heritage Private Stay",
    descKo: "성산일출봉 전경을 단독 조망하는 최고급 감성 돌담 독채 리조트",
    descEn: "Exclusive stone-wall villa with private view of Seongsan Ilchulbong",
    nightlyPriceKrw: 240000,
    locationKo: "성산",
    locationEn: "Seongsan",
    tag: "일출봉뷰/돌담독채",
    emoji: "🌋",
    gradientBg: "from-stone-500/15 to-emerald-600/15",
  },

  // === INCHEON (인천) ===
  {
    id: "incheon_acc_songdo_budget",
    cityCode: "INCHEON",
    basketId: "BUDGET_STAY",
    nameKo: "송도 가성비 비즈니스 스테이",
    nameEn: "Songdo Budget Business Stay",
    descKo: "송도 테크노파크역 인근, 깔끔하고 실속 있는 모던 싱글/트윈 스테이",
    descEn: "Clean budget business stay near Songdo Technopark Station",
    nightlyPriceKrw: 50000,
    locationKo: "송도",
    locationEn: "Songdo",
    tag: "가성비/비즈니스",
    emoji: "🏙️",
    gradientBg: "from-blue-500/15 to-slate-500/15",
  },
  {
    id: "incheon_acc_songdo_standard",
    cityCode: "INCHEON",
    basketId: "STANDARD_HOTEL",
    nameKo: "송도 센트럴파크 시티뷰 호텔",
    nameEn: "Songdo Central Park City View Hotel",
    descKo: "송도 센트럴파크 해돋이 공원이 내려다보이는 스카이라인 시티뷰 호텔",
    descEn: "Skyline view hotel overlooking Songdo Central Park lake",
    nightlyPriceKrw: 115000,
    locationKo: "송도",
    locationEn: "Songdo",
    tag: "센트럴파크/시티뷰",
    emoji: "🌳",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },
  {
    id: "incheon_acc_yeongjong_paradise",
    cityCode: "INCHEON",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "영종도 5성급 럭셔리 아트 리조트",
    nameEn: "Yeongjongdo 5-Star Luxury Art Resort",
    descKo: "인천공항 10분, 대형 스파 수영장과 세계적 아트 컬렉션 럭셔리 휴양지",
    descEn: "5-star luxury art resort near Incheon Airport with spa pool",
    nightlyPriceKrw: 330000,
    locationKo: "영종도",
    locationEn: "Yeongjongdo",
    tag: "5성급/아트스파",
    emoji: "🎨",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },
  {
    id: "incheon_acc_wolmido_pension",
    cityCode: "INCHEON",
    basketId: "STANDARD_HOTEL",
    nameKo: "월미도 해안 감성 펜션",
    nameEn: "Wolmido Oceanfront Pension",
    descKo: "월미도 문화거리 및 인천 바다 선착장이 트인 바다 감성 펜션",
    descEn: "Oceanfront pension next to Wolmido culture street pier",
    nightlyPriceKrw: 85000,
    locationKo: "월미도",
    locationEn: "Wolmido",
    tag: "월미도/바다감성",
    emoji: "🎡",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
  },
  {
    id: "incheon_acc_airport_capsule",
    cityCode: "INCHEON",
    basketId: "BUDGET_STAY",
    nameKo: "인천공항 터미널 캡슐 스테이",
    nameEn: "Incheon Airport Terminal Capsule Stay",
    descKo: "공항 터미널 직접 연계, 새벽 출국 및 이른 입국 시 편리한 캡슐호텔",
    descEn: "Direct airport terminal connected clean capsule hotel",
    nightlyPriceKrw: 42000,
    locationKo: "인천공항",
    locationEn: "Incheon Airport",
    tag: "공항터미널/편의",
    emoji: "🧳",
    gradientBg: "from-sky-500/15 to-indigo-500/15",
  },
  {
    id: "incheon_acc_songdo_hanok",
    cityCode: "INCHEON",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "송도 센트럴 한옥 호텔 & 스위트",
    nameEn: "Songdo Central Hanok Hotel & Suites",
    descKo: "송도 센트럴파크 한옥마을 내 위치한 고품격 럭셔리 한옥 스위트",
    descEn: "Luxury Hanok suites inside Songdo Central Park Hanok Village",
    nightlyPriceKrw: 220000,
    locationKo: "송도한옥마을",
    locationEn: "Songdo Hanok",
    tag: "한옥스위트/공원",
    emoji: "🏯",
    gradientBg: "from-rose-500/15 to-amber-500/15",
  },

  // === SUWON (수원) ===
  {
    id: "suwon_acc_haenggung_guesthouse",
    cityCode: "SUWON",
    basketId: "BUDGET_STAY",
    nameKo: "수원 화성 행궁동 감성 게스트하우스",
    nameEn: "Suwon Haenggung-dong Vibe Guesthouse",
    descKo: "행리단길 카페거리 및 수원화성 성곽길 바로 옆 아기자기한 게하",
    descEn: "Cute cozy guesthouse near Haengnidan-gil cafe street and fortress",
    nightlyPriceKrw: 42000,
    locationKo: "행궁동",
    locationEn: "Haenggung",
    tag: "행리단길/성곽길",
    emoji: "🏰",
    gradientBg: "from-amber-500/15 to-emerald-500/15",
  },
  {
    id: "suwon_acc_gwanggyo_standard",
    cityCode: "SUWON",
    basketId: "STANDARD_HOTEL",
    nameKo: "수원 광교 호수뷰 시티 호텔",
    nameEn: "Suwon Gwanggyo Lakeview City Hotel",
    descKo: "광교 호수공원 야경 조망, 갤러리아 및 컨벤션 센터 인근 시티 호텔",
    descEn: "City hotel overlooking Gwanggyo Lake Park and convention center",
    nightlyPriceKrw: 105000,
    locationKo: "광교",
    locationEn: "Gwanggyo",
    tag: "광교호수/시티뷰",
    emoji: "🏞️",
    gradientBg: "from-blue-500/15 to-teal-500/15",
  },
  {
    id: "suwon_acc_marriott_luxury",
    cityCode: "SUWON",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "수원 5성급 메리어트 럭셔리 호텔",
    nameEn: "Suwon 5-Star Marriott Luxury Hotel",
    descKo: "수원 도심 최고급 수영장과 라운지 뷔페를 갖춘 5성급 라인 프리미엄",
    descEn: "5-star luxury hotel in Suwon with indoor pool and executive lounge",
    nightlyPriceKrw: 240000,
    locationKo: "인계동/광교",
    locationEn: "Ingye-dong",
    tag: "5성급/럭셔리",
    emoji: "⭐",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },
  {
    id: "suwon_acc_fortress_stay",
    cityCode: "SUWON",
    basketId: "BUDGET_STAY",
    nameKo: "수원화성 방화수류정 미니 스테이",
    nameEn: "Suwon Hwaseong Banghwasuryujeong Mini Stay",
    descKo: "방화수류정 용연 연못 야경 산책이 편리한 가성비 미니 스테이",
    descEn: "Affordable stay near Banghwasuryujeong pond night walk",
    nightlyPriceKrw: 48000,
    locationKo: "방화수류정",
    locationEn: "Banghwasuryujeong",
    tag: "야경산책/가성비",
    emoji: "🌙",
    gradientBg: "from-indigo-500/15 to-blue-500/15",
  },
  {
    id: "suwon_acc_yeongtong_standard",
    cityCode: "SUWON",
    basketId: "STANDARD_HOTEL",
    nameKo: "영통 모던 비즈니스 호텔",
    nameEn: "Yeongtong Modern Business Hotel",
    descKo: "영통역 중심상권 위치, 쾌적하고 깔끔한 비즈니스 룸 컨디션",
    descEn: "Comfortable business hotel near Yeongtong Station commercial area",
    nightlyPriceKrw: 95000,
    locationKo: "영통",
    locationEn: "Yeongtong",
    tag: "역세권/비즈니스",
    emoji: "🏢",
    gradientBg: "from-slate-500/15 to-blue-500/15",
  },
  {
    id: "suwon_acc_gwanggyo_residence",
    cityCode: "SUWON",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "광교 호수공원 프라이빗 레지던스",
    nameEn: "Gwanggyo Lakeview Private Residence",
    descKo: "광교 호수공원 전망 테라스와 주방 취사가 가능한 고품격 레지던스",
    descEn: "High-end lakeview residence with terrace kitchen facilities",
    nightlyPriceKrw: 210000,
    locationKo: "광교호수",
    locationEn: "Gwanggyo Lake",
    tag: "호수전망/레지던스",
    emoji: "🏛️",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },

  // === JEONJU (전주) ===
  {
    id: "jeonju_acc_hanok_guesthouse",
    cityCode: "JEONJU",
    basketId: "BUDGET_STAY",
    nameKo: "전주 한옥마을 전통 뜰채 게스트하우스",
    nameEn: "Jeonju Hanok Village Courtyard Guesthouse",
    descKo: "경기전 도보 3분, 전통 마당 정원과 따스한 온돌 마루 게스트하우스",
    descEn: "Charming traditional courtyard Ondol guesthouse near Gyeonggijeon",
    nightlyPriceKrw: 45000,
    locationKo: "한옥마을",
    locationEn: "Hanok Village",
    tag: "온돌마루/마당정원",
    emoji: "🎋",
    gradientBg: "from-amber-500/15 to-emerald-500/15",
  },
  {
    id: "jeonju_acc_hanok_stay_standard",
    cityCode: "JEONJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "전주 한옥마을 정취 한옥 독채 스테이",
    nameEn: "Jeonju Traditional Hanok Private Stay",
    descKo: "고즈넉한 기와지붕 아래 현대식 욕실과 개별 툇마루가 갖춰진 독채 한옥",
    descEn: "Traditional roof tile private Hanok with modern ensuite bathroom",
    nightlyPriceKrw: 125000,
    locationKo: "한옥마을",
    locationEn: "Hanok Village",
    tag: "한옥독채/툇마루",
    emoji: "🏡",
    gradientBg: "from-orange-500/15 to-amber-600/15",
  },
  {
    id: "jeonju_acc_hanok_resort_luxury",
    cityCode: "JEONJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "전주 럭셔리 한옥 리조트 & 다도 스위트",
    nameEn: "Jeonju Luxury Hanok Resort & Tea Suite",
    descKo: "전주 한옥 명인의 건축, 프라이빗 자쿠지 노천탕과 최고급 다도 서비스",
    descEn: "Master-crafted luxury Hanok resort with private jacuzzi open bath",
    nightlyPriceKrw: 270000,
    locationKo: "한옥마을",
    locationEn: "Hanok Village",
    tag: "럭셔리노천탕/명인한옥",
    emoji: "🍵",
    gradientBg: "from-rose-500/15 to-amber-500/15",
  },
  {
    id: "jeonju_acc_gaeksa_boutique",
    cityCode: "JEONJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "전주 객사길 모던 부티크 호텔",
    nameEn: "Jeonju Gaeksa-gil Modern Boutique Hotel",
    descKo: "객리단길 핫플 카페 & 식당가 인근, 깔끔하고 현대적인 부티크 호텔",
    descEn: "Modern boutique hotel near Gaekridan-gil hot restaurants",
    nightlyPriceKrw: 90000,
    locationKo: "객사/객리단길",
    locationEn: "Gaeksa",
    tag: "객리단길/부티크",
    emoji: "🛍️",
    gradientBg: "from-purple-500/15 to-pink-500/15",
  },
  {
    id: "jeonju_acc_deokjin_stay",
    cityCode: "JEONJU",
    basketId: "BUDGET_STAY",
    nameKo: "전주 덕진공원 연꽃 감성 스테이",
    nameEn: "Jeonju Deokjin Park Lotus Vibe Stay",
    descKo: "덕진공원 연못 한옥도서관 산책이 훌륭한 산뜻한 가성비 스테이",
    descEn: "Affordable nature stay near Deokjin Park lotus pond library",
    nightlyPriceKrw: 40000,
    locationKo: "덕진공원",
    locationEn: "Deokjin Park",
    tag: "연못산책/가성비",
    emoji: "🪷",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "jeonju_acc_tea_suite_luxury",
    cityCode: "JEONJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "전주 전통 다도 & 한옥 VIP 스위트",
    nameEn: "Jeonju Traditional Tea & Hanok VIP Suite",
    descKo: "전통 다도 클래스와 고급 한정식 브런치가 포함된 VIP 한옥 스위트",
    descEn: "VIP Hanok suite including traditional tea ceremony and Hanjeongsik",
    nightlyPriceKrw: 230000,
    locationKo: "한옥마을",
    locationEn: "Hanok Village",
    tag: "다도클래스/VIP스위트",
    emoji: "👑",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },

  // === GYEONGJU (경주) ===
  {
    id: "gyeongju_acc_hwangridan_guesthouse",
    cityCode: "GYEONGJU",
    basketId: "BUDGET_STAY",
    nameKo: "황리단길 감성 한옥 게스트하우스",
    nameEn: "Hwangridan-gil Hanok Guesthouse",
    descKo: "황리단길 메인거리 도보 1분, 대릉원 고분이 조망되는 감성 게하",
    descEn: "Trendy Hanok guesthouse 1 min walk from Hwangridan-gil street",
    nightlyPriceKrw: 45000,
    locationKo: "황리단길",
    locationEn: "Hwangridan-gil",
    tag: "황리단길/대릉원뷰",
    emoji: "🌸",
    gradientBg: "from-amber-500/15 to-rose-500/15",
  },
  {
    id: "gyeongju_acc_bomun_standard",
    cityCode: "GYEONGJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "경주 보문단지 호수뷰 힐링 호텔",
    nameEn: "Gyeongju Bomun Lakeview Healing Hotel",
    descKo: "보문호수 산책로와 벚꽃 산책길이 맞닿은 조용하고 아늑한 힐링 호텔",
    descEn: "Quiet lakeview hotel connected to Bomun lake cherry blossom walk",
    nightlyPriceKrw: 115000,
    locationKo: "보문단지",
    locationEn: "Bomun Lake",
    tag: "보문호수/벚꽃산책",
    emoji: "🌸",
    gradientBg: "from-pink-500/15 to-rose-500/15",
  },
  {
    id: "gyeongju_acc_bomun_luxury",
    cityCode: "GYEONGJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "경주 보문단지 5성급 럭셔리 리조트",
    nameEn: "Gyeongju Bomun 5-Star Luxury Resort",
    descKo: "신라 왕궁의 품격을 현대적으로 재해석한 호수 인피니티풀 & 스파",
    descEn: "5-star luxury resort reinterpreting Silla royal palace architecture",
    nightlyPriceKrw: 260000,
    locationKo: "보문단지",
    locationEn: "Bomun Lake",
    tag: "5성급/인피니티풀",
    emoji: "👑",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },
  {
    id: "gyeongju_acc_hwangnam_hanok",
    cityCode: "GYEONGJU",
    basketId: "STANDARD_HOTEL",
    nameKo: "첨성대 근처 황남 전통 한옥 스테이",
    nameEn: "Hwangnam Hanok Stay near Cheomseongdae",
    descKo: "첨성대 및 동궁과월지 야경 투어가 편리한 전통 기와 한옥 스테이",
    descEn: "Traditional Hanok stay convenient for Cheomseongdae night tour",
    nightlyPriceKrw: 130000,
    locationKo: "황남동",
    locationEn: "Hwangnam",
    tag: "첨성대/야경투어",
    emoji: "🌙",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },
  {
    id: "gyeongju_acc_city_hostel",
    cityCode: "GYEONGJU",
    basketId: "BUDGET_STAY",
    nameKo: "경주 시내 알뜰 시티 호스텔",
    nameEn: "Gyeongju Downtown Budget Hostel",
    descKo: "경주역 및 버스터미널 가까운 위치, 배낭여행객을 위한 알뜰 호스텔",
    descEn: "Budget downtown hostel near bus terminal for backpackers",
    nightlyPriceKrw: 38000,
    locationKo: "경주시내",
    locationEn: "Gyeongju Downtown",
    tag: "터미널근처/알뜰",
    emoji: "🎒",
    gradientBg: "from-slate-500/15 to-blue-500/15",
  },
  {
    id: "gyeongju_acc_bulguksa_villa",
    cityCode: "GYEONGJU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "불국사 산자락 프라이빗 풀빌라",
    nameEn: "Bulguksa Mountain Private Pool Villa",
    descKo: "토함산 자락 자연 숲속에 위치한 단독 수영장과 히노끼 스파 리조트",
    descEn: "Private forest pool villa with Hinoki spa near Mt. Toham",
    nightlyPriceKrw: 300000,
    locationKo: "불국사/토함산",
    locationEn: "Bulguksa",
    tag: "히노끼스파/숲속독채",
    emoji: "🌲",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },

  // === GANGNEUNG (강릉) ===
  {
    id: "gangneung_acc_anmok_stay",
    cityCode: "GANGNEUNG",
    basketId: "BUDGET_STAY",
    nameKo: "안목해변 미니멀 오션뷰 스테이",
    nameEn: "Anmok Beach Minimal Oceanview Stay",
    descKo: "강릉 안목 커피거리 해변 바로 앞, 커피 향 가득한 미니멀 오션 스테이",
    descEn: "Minimal beach stay right in front of Anmok Coffee Street beach",
    nightlyPriceKrw: 48000,
    locationKo: "안목해변",
    locationEn: "Anmok Beach",
    tag: "커피거리/오션뷰",
    emoji: "☕",
    gradientBg: "from-amber-500/15 to-blue-500/15",
  },
  {
    id: "gangneung_acc_gyeongpo_hotel",
    cityCode: "GANGNEUNG",
    basketId: "STANDARD_HOTEL",
    nameKo: "경포대 오션뷰 모던 호텔",
    nameEn: "Gyeongpo Beach Oceanview Modern Hotel",
    descKo: "경포해수욕장 중앙 백사장 전경, 시원한 바다 파도 소리의 호텔",
    descEn: "Ocean view modern hotel right on Gyeongpo Beach sand trail",
    nightlyPriceKrw: 120000,
    locationKo: "경포대",
    locationEn: "Gyeongpo",
    tag: "경포해변/백사장",
    emoji: "🌊",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
  },
  {
    id: "gangneung_acc_jeongdongjin_resort",
    cityCode: "GANGNEUNG",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "정동진 럭셔리 인피니티풀 오션 리조트",
    nameEn: "Jeongdongjin Luxury Infinity Pool Resort",
    descKo: "해돋이 절경 정동진 해안 절벽 위, 압도적 동해 바다 럭셔리 뷰",
    descEn: "Cliffside ocean infinity pool resort with breathtaking sunrise view",
    nightlyPriceKrw: 290000,
    locationKo: "정동진",
    locationEn: "Jeongdongjin",
    tag: "일출명소/인피니티풀",
    emoji: "🌅",
    gradientBg: "from-rose-500/15 to-amber-500/15",
  },
  {
    id: "gangneung_acc_station_hotel",
    cityCode: "GANGNEUNG",
    basketId: "STANDARD_HOTEL",
    nameKo: "강릉역 근처 시티 비즈니스 호텔",
    nameEn: "Gangneung Station City Business Hotel",
    descKo: "KTX 강릉역 도보 5분, 중앙시장 맛집 투어가 편리한 시티 호텔",
    descEn: "Convenient city hotel 5 mins walk from KTX Gangneung Station",
    nightlyPriceKrw: 88000,
    locationKo: "강릉역",
    locationEn: "Gangneung Station",
    tag: "KTX역세권/중앙시장",
    emoji: "🚅",
    gradientBg: "from-slate-500/15 to-indigo-500/15",
  },
  {
    id: "gangneung_acc_jumunjin_guesthouse",
    cityCode: "GANGNEUNG",
    basketId: "BUDGET_STAY",
    nameKo: "주문진 감성 바다 게스트하우스",
    nameEn: "Jumunjin Ocean Vibe Guesthouse",
    descKo: "주문진 수산시장 및 도깨비 방파제 촬영지 인근 바다 게하",
    descEn: "Ocean guesthouse near Jumunjin market and famous breakwater",
    nightlyPriceKrw: 40000,
    locationKo: "주문진",
    locationEn: "Jumunjin",
    tag: "방파제/수산시장",
    emoji: "🐟",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
  },
  {
    id: "gangneung_acc_gyeongpo_villa",
    cityCode: "GANGNEUNG",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "경포호수 스파 & 프라이빗 풀빌라 리조트",
    nameEn: "Gyeongpo Lake Spa & Private Pool Villa Resort",
    descKo: "경포호수 숲길과 바다가 이어지는 최고급 야외 테라스 스파 풀빌라",
    descEn: "Luxury terrace spa pool villa resort by Gyeongpo Lake forest trail",
    nightlyPriceKrw: 250000,
    locationKo: "경포호수",
    locationEn: "Gyeongpo Lake",
    tag: "경포호수/테라스스파",
    emoji: "🏞️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },

  // === SOKCHO (속초) ===
  {
    id: "sokcho_acc_market_stay",
    cityCode: "SOKCHO",
    basketId: "BUDGET_STAY",
    nameKo: "속초 중앙시장 근처 가성비 스테이",
    nameEn: "Sokcho Central Market Budget Stay",
    descKo: "속초 중앙시장 닭강정 거리 도보 2분, 시장 먹방 투어 최적의 숙소",
    descEn: "Budget stay 2 mins walk from Sokcho Central Market street food",
    nightlyPriceKrw: 42000,
    locationKo: "중앙시장",
    locationEn: "Central Market",
    tag: "중앙시장/먹방투어",
    emoji: "🍗",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "sokcho_acc_beach_hotel",
    cityCode: "SOKCHO",
    basketId: "STANDARD_HOTEL",
    nameKo: "속초 해수욕장 오션뷰 힐링 호텔",
    nameEn: "Sokcho Beach Oceanview Healing Hotel",
    descKo: "속초아이 관람차가 바로 보이는 속초해변 바로 앞 오션뷰 호텔",
    descEn: "Oceanview hotel right in front of Sokcho Beach Ferris wheel",
    nightlyPriceKrw: 110000,
    locationKo: "속초해변",
    locationEn: "Sokcho Beach",
    tag: "속초아이/속초해변",
    emoji: "🎡",
    gradientBg: "from-blue-500/15 to-sky-500/15",
  },
  {
    id: "sokcho_acc_spa_resort",
    cityCode: "SOKCHO",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "속초 럭셔리 온천 천연 스파 리조트",
    nameEn: "Sokcho Luxury Hot Spring Spa Resort",
    descKo: "설악산 울산바위 병풍 조망과 천연 미네랄 온천 워터파크 리조트",
    descEn: "Luxury mineral hot spring resort with view of Mt. Seorak peak",
    nightlyPriceKrw: 270000,
    locationKo: "설악산/노학",
    locationEn: "Mt. Seorak",
    tag: "천연온천/울산바위뷰",
    emoji: "♨️",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },
  {
    id: "sokcho_acc_abai_guesthouse",
    cityCode: "SOKCHO",
    basketId: "BUDGET_STAY",
    nameKo: "아바이마을 정취 바다 게스트하우스",
    nameEn: "Abai Village Ocean Guesthouse",
    descKo: "아바이마을 갯배 선착장 인근, 오징어순대와 바다 정취 가득한 게하",
    descEn: "Cozy ocean guesthouse near Abai village Gaetbae ferry pier",
    nightlyPriceKrw: 39000,
    locationKo: "아바이마을",
    locationEn: "Abai Village",
    tag: "갯배선착장/아바이마을",
    emoji: "⛵",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
  },
  {
    id: "sokcho_acc_yeonglang_residence",
    cityCode: "SOKCHO",
    basketId: "STANDARD_HOTEL",
    nameKo: "영랑호 호수뷰 스탠다드 레지던스",
    nameEn: "Yeonglang Lakeview Standard Residence",
    descKo: "영랑호 부교 산책로가 보이는 아늑하고 넓은 모던 레지던스 호텔",
    descEn: "Spacious residence hotel overlooking Yeonglang Lake floating bridge",
    nightlyPriceKrw: 95000,
    locationKo: "영랑호",
    locationEn: "Yeonglang Lake",
    tag: "영랑호/호수산책",
    emoji: "🏞️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "sokcho_acc_marina_suite",
    cityCode: "SOKCHO",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "속초 마리나 요트 오션 VIP 스위트",
    nameEn: "Sokcho Marina Yacht Ocean VIP Suite",
    descKo: "동명항 마리나 클럽 하우스 전용 요트 투어가 제공되는 VIP 스위트",
    descEn: "VIP ocean suite including private yacht tour from Dongmyeong port",
    nightlyPriceKrw: 310000,
    locationKo: "동명항",
    locationEn: "Dongmyeong Port",
    tag: "요트투어/VIP스위트",
    emoji: "⛵",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },

  // === YEOSU (여수) ===
  {
    id: "yeosu_acc_pocha_guesthouse",
    cityCode: "YEOSU",
    basketId: "BUDGET_STAY",
    nameKo: "여수 낭만포차 가성비 게스트하우스",
    nameEn: "Yeosu Romantic Pocha Budget Guesthouse",
    descKo: "여수 밤바다 낭만포차 거리를 걸어서 즐기는 아늑한 게스트하우스",
    descEn: "Cozy guesthouse walking distance to Yeosu Romantic Pocha night sea",
    nightlyPriceKrw: 40000,
    locationKo: "낭만포차",
    locationEn: "Romantic Pocha",
    tag: "낭만포차/밤바다",
    emoji: "🌃",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
  },
  {
    id: "yeosu_acc_dolsan_pension",
    cityCode: "YEOSU",
    basketId: "STANDARD_HOTEL",
    nameKo: "여수 돌산 오션뷰 힐링 펜션",
    nameEn: "Yeosu Dolsan Oceanview Healing Pension",
    descKo: "돌산대교 야경과 남해 바다가 한눈에 내려다보이는 테라스 펜션",
    descEn: "Terrace pension with view of Dolsan Bridge night skyline",
    nightlyPriceKrw: 115000,
    locationKo: "돌산",
    locationEn: "Dolsan",
    tag: "돌산대교/야경펜션",
    emoji: "🌉",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },
  {
    id: "yeosu_acc_sono_resort",
    cityCode: "YEOSU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "여수 5성급 오션 럭셔리 리조트",
    nameEn: "Yeosu 5-Star Ocean Luxury Resort",
    descKo: "오동도와 여수 엑스포 해안이 파노라마로 펼쳐지는 5성급 리조트",
    descEn: "5-star luxury resort with panoramic view of Odongdo Island",
    nightlyPriceKrw: 280000,
    locationKo: "수정동/오동도",
    locationEn: "Odongdo",
    tag: "5성급/오동도뷰",
    emoji: "🏰",
    gradientBg: "from-rose-500/15 to-pink-500/15",
  },
  {
    id: "yeosu_acc_square_boutique",
    cityCode: "YEOSU",
    basketId: "STANDARD_HOTEL",
    nameKo: "이순신광장 시티 부티크 호텔",
    nameEn: "Yi Sun-sin Square City Boutique Hotel",
    descKo: "이순신광장 먹거리 거리 중심, 수제 바게트버거 & 게장 골목 접근성",
    descEn: "Boutique hotel located in the heart of Yi Sun-sin Square food street",
    nightlyPriceKrw: 92000,
    locationKo: "이순신광장",
    locationEn: "Square Central",
    tag: "먹거리거리/부티크",
    emoji: "🍔",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "yeosu_acc_ungcheon_stay",
    cityCode: "YEOSU",
    basketId: "BUDGET_STAY",
    nameKo: "웅천 요트마리나 미니 스테이",
    nameEn: "Ungcheon Yacht Marina Mini Stay",
    descKo: "웅천 요트 마리나 해변 공원 앞, 트렌디하고 깨끗한 미니 스테이",
    descEn: "Clean mini stay facing Ungcheon Yacht Marina beach park",
    nightlyPriceKrw: 45000,
    locationKo: "웅천",
    locationEn: "Ungcheon",
    tag: "요트공원/트렌디",
    emoji: "⛵",
    gradientBg: "from-teal-500/15 to-cyan-500/15",
  },
  {
    id: "yeosu_acc_dolsan_poolvilla",
    cityCode: "YEOSU",
    basketId: "PREMIUM_HERITAGE",
    nameKo: "여수 돌산 프라이빗 풀빌라 & 스파",
    nameEn: "Yeosu Dolsan Private Pool Villa & Spa",
    descKo: "돌산 해안 절벽 단독 수영장과 사계절 온수풀 프라이빗 독채",
    descEn: "Exclusive cliffside private pool villa with 4-season heated pool",
    nightlyPriceKrw: 340000,
    locationKo: "돌산해안",
    locationEn: "Dolsan Coast",
    tag: "온수풀/프라이빗",
    emoji: "🏊",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
];
