import { SupportedCity } from "../../../lib/trip-domain";

export type AttractionCategoryType = "명소" | "자연" | "엔터" | "쇼핑";

export type PriceStatus = "FREE" | "PAID" | "PARTIALLY_PAID" | "UNCONFIRMED";

export interface AttractionSpot {
  id: string;
  cityCode: SupportedCity;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  price: number;
  priceStatus: PriceStatus;
  tag: string;
  emoji: string;
  gradientBg: string;
  isFeatured: boolean;
  subwayInfo?: string;
  subwayInfoKo?: string;
  subwayInfoEn?: string;
  openingHours?: string;
  openingHoursKo?: string;
  openingHoursEn?: string;
  closedDays?: string;
  closedDaysKo?: string;
  closedDaysEn?: string;
  officialUrl?: string;
  imageUrl?: string;
  deepLink?: string;
  categoryType?: AttractionCategoryType;
}

export interface BilingualSpotDetail {
  categoryType?: AttractionCategoryType;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  subwayKo?: string;
  subwayEn?: string;
  hoursKo?: string;
  hoursEn?: string;
  closedKo?: string;
  closedEn?: string;
  imageUrl?: string;
}

/**
 * 정규화된 관광지 ID를 반환합니다. (seoul_rep_, kto_, kto_custom_ 접두사를 통일)
 */
export function normalizeSpotKey(id?: string): string {
  if (!id) return "";
  return id
    .replace(/^seoul_rep_/, "")
    .replace(/^kto_custom_/, "")
    .replace(/^kto_/, "")
    .trim();
}

/**
 * 서로 다른 접두사를 가진 장소 ID가 동일한 관광지를 가리키는지 판별합니다.
 */
export function isSameSpot(idA?: string, idB?: string): boolean {
  if (!idA || !idB) return false;
  if (idA === idB) return true;
  return normalizeSpotKey(idA) === normalizeSpotKey(idB);
}

export const SEOUL_LANDMARK_BILINGUAL_MAP: Record<string, BilingualSpotDetail> = {
  seoul_gyeongbokgung: {
    categoryType: "명소",
    nameKo: "경복궁",
    nameEn: "Gyeongbokgung Palace",
    descKo: "조선 왕조 제1의 법궁으로 수문장 교대의식과 한복 착용 시 무료 입장이 가능한 필수 명소입니다.",
    descEn: "The main royal palace of the Joseon dynasty built in 1395, famous for Hanbok experiences and royal guard ceremonies.",
    subwayKo: "3호선 경복궁역 5번 출구 (도보 3분) / 5호선 광화문역 2번 출구",
    subwayEn: "Line 3 Gyeongbokgung Stn. Exit 5 (3 min walk) / Line 5 Gwanghwamun Stn. Exit 2",
    hoursKo: "09:00 ~ 18:00 (입장마감 17:00, 계절별 상이)",
    hoursEn: "09:00 ~ 18:00 (Last entry 17:00)",
    closedKo: "매주 화요일 휴관",
    closedEn: "Closed on Tuesdays",
    imageUrl: "/assets/gyeongbokgung-main.jpg",
  },
  seoul_nseoultower: {
    categoryType: "명소",
    nameKo: "N서울타워 전망대",
    nameEn: "N Seoul Tower Observatory",
    descKo: "남산 정상에서 360도로 서울 시내 파노라마와 로맨틱한 야경을 한눈에 조망하는 대표 랜드마크입니다.",
    descEn: "Iconic tower atop Namsan Mountain offering panoramic 360-degree views of Seoul and romantic nightscapes.",
    subwayKo: "4호선 명동역 3번 출구 (남산케이블카 도보 10분) / 충무로역 01번 순환버스",
    subwayEn: "Line 4 Myeong-dong Stn. Exit 3 (Cable car 10 min) / Chungmuro Stn. Bus 01",
    hoursKo: "10:00 ~ 22:30 (주말 23:00까지)",
    hoursEn: "10:00 ~ 22:30 (Weekends until 23:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "/assets/n-seoul-tower.jpg",
  },
  seoul_lotteworldtower: {
    categoryType: "명소",
    nameKo: "롯데월드타워 서울스카이",
    nameEn: "Lotte World Tower Seoul Sky",
    descKo: "세계 5위 높이(555m) 118층 초고층 타워에서 만나는 압도적인 스카이데크 유리 바닥 전망대입니다.",
    descEn: "The 5th tallest building in the world (555m) featuring glass-floor sky decks and sweeping skyline views.",
    subwayKo: "2·8호선 잠실역 1, 2번 지하 연결",
    subwayEn: "Line 2/8 Jamsil Stn. Exit 1, 2 underground connection",
    hoursKo: "10:30 ~ 22:00 (금·토 23:00)",
    hoursEn: "10:30 ~ 22:00 (Fri/Sat until 23:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/66/3092766_image2_1.jpg",
  },
  seoul_changdeokgung: {
    categoryType: "명소",
    nameKo: "창덕궁과 후원",
    nameEn: "Changdeokgung Palace & Secret Garden",
    descKo: "자연과 조화롭게 어우러진 유네스코 세계문화유산 궁궐로, 인정전과 왕실 정원 후원을 품고 있습니다.",
    descEn: "UNESCO World Heritage palace renowned for its harmonious nature, Injeongjeon hall, and scenic Secret Garden.",
    subwayKo: "3호선 안국역 3번 출구 (도보 5분) / 1·3·5호선 종로3가역 6번 출구",
    subwayEn: "Line 3 Anguk Stn. Exit 3 (5 min walk) / Line 1/3/5 Jongno 3-ga Stn. Exit 6",
    hoursKo: "09:00 ~ 18:00 (후원 사전예약 권장)",
    hoursEn: "09:00 ~ 18:00 (Secret Garden reservation recommended)",
    closedKo: "매주 월요일 휴관",
    closedEn: "Closed on Mondays",
    imageUrl: "/assets/changdeokgung-hall.jpg",
  },
  seoul_deoksugung: {
    categoryType: "명소",
    nameKo: "덕수궁 & 돌담길",
    nameEn: "Deoksugung Palace & Stonewall Path",
    descKo: "도심 속 서양식 석조전과 전통 전각이 공존하며 낭만적인 밤 산책로 돌담길이 펼쳐지는 궁궐입니다.",
    descEn: "Historic royal palace combining traditional and neoclassical architectures along the famous romantic stonewall path.",
    subwayKo: "1·2호선 시청역 1, 2번 출구 (도보 1분)",
    subwayEn: "Line 1/2 City Hall Stn. Exit 1, 2 (1 min walk)",
    hoursKo: "09:00 ~ 21:00 (야간개장 상시, 입장마감 20:00)",
    hoursEn: "09:00 ~ 21:00 (Night opening, last entry 20:00)",
    closedKo: "매주 월요일 휴관 (돌담길 24시간)",
    closedEn: "Closed on Mondays (Stonewall Path open 24h)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2658350_image2_1.jpg",
  },
  seoul_ddp: {
    categoryType: "명소",
    nameKo: "동대문디자인플라자 (DDP)",
    nameEn: "Dongdaemun Design Plaza (DDP)",
    descKo: "자하 하디드가 설계한 은빛 비정형 곡선 건축물로 글로벌 패션위크와 미디어아트 축제가 열립니다.",
    descEn: "Futuristic landmark designed by Zaha Hadid, hosting global fashion weeks and spectacular Seoul Light festivals.",
    subwayKo: "2·4·5호선 동대문역사문화공원역 1번 출구 연결",
    subwayEn: "Line 2/4/5 Dongdaemun History & Culture Park Stn. Exit 1 direct",
    hoursKo: "10:00 ~ 20:00 (야외공간 24시간 개방)",
    hoursEn: "10:00 ~ 20:00 (Outdoor plaza open 24 hours)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/60/4105560_image2_1.jpg",
  },
  seoul_bukchon: {
    categoryType: "명소",
    nameKo: "북촌한옥마을",
    nameEn: "Bukchon Hanok Village",
    descKo: "경복궁과 창덕궁 사이 600년 역사를 간직한 수백 채의 전통 기와집과 감고당길 골목 투어 명소입니다.",
    descEn: "Historic village nestled between royal palaces, home to hundreds of traditional Korean tile-roofed houses.",
    subwayKo: "3호선 안국역 2, 3번 출구 (도보 7분)",
    subwayEn: "Line 3 Anguk Stn. Exit 2, 3 (7 min walk)",
    hoursKo: "10:00 ~ 17:00 (주민 생활권 보호 권장시간)",
    hoursEn: "10:00 ~ 17:00 (Recommended visiting hours)",
    closedKo: "일요일 골목길 관광 자제",
    closedEn: "Visiting restricted on Sundays",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/04/3304404_image2_1.jpg",
  },
  seoul_seongsu: {
    categoryType: "쇼핑",
    nameKo: "성수동 연무장길",
    nameEn: "Seongsu-dong Yeonmujang-gil",
    descKo: "서울의 브루클린으로 불리며 감각적인 패션 플래그십 팝업스토어와 트렌디한 베이커리 카페가 모여있습니다.",
    descEn: "The 'Brooklyn of Seoul' buzzing with iconic fashion flagship pop-ups, artisanal cafes, and trendy bakeries.",
    subwayKo: "2호선 성수역 4번 출구 / 뚝섬역 5번 출구",
    subwayEn: "Line 2 Seongsu Stn. Exit 4 / Ttukseom Stn. Exit 5",
    hoursKo: "11:00 ~ 21:00 (팝업/카페별 상이)",
    hoursEn: "11:00 ~ 21:00 (Varies by store)",
    closedKo: "연중무휴 (매장별 상이)",
    closedEn: "Open year-round (Varies by store)",
    imageUrl: "/assets/seongsu-street.jpg",
  },
  seoul_hongdae: {
    categoryType: "엔터",
    nameKo: "홍대 걷고싶은거리",
    nameEn: "Hongdae Walking Street",
    descKo: "청춘과 버스킹의 중심지로 K-Pop 댄스 거리공연과 개성 넘치는 인디 숍들이 활기를 띠는 명소입니다.",
    descEn: "Korea's youth culture hub packed with spontaneous K-Pop busking performances, indie art shops, and nightlife.",
    subwayKo: "2호선·공항철도·경의중앙선 홍대입구역 8, 9번 출구",
    subwayEn: "Line 2/Airport Railroad/Gyeongui-Jungang Hongik Univ. Stn. Exit 8, 9",
    hoursKo: "24시간 상시 (버스킹 집중 18:00~22:00)",
    hoursEn: "Open 24 hours (Busking peaks 18:00~22:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "/assets/hongdae-street.jpg",
  },
  seoul_gwangjang: {
    categoryType: "쇼핑",
    nameKo: "광장시장",
    nameEn: "Gwangjang Market",
    descKo: "100년 전통의 대표 먹거리 시장으로 바삭한 녹두빈대떡, 마약김밥, 신선한 육회 탕탕이가 유명합니다.",
    descEn: "Over 100 years of authentic street food heritage, famous for crispy bindaetteok, mayak gimbap, and fresh yukhoe.",
    subwayKo: "1호선 종로5가역 8번 출구 / 2·5호선 을지로4가역 4번 출구",
    subwayEn: "Line 1 Jongno 5-ga Stn. Exit 8 / Line 2/5 Euljiro 4-ga Stn. Exit 4",
    hoursKo: "09:00 ~ 23:00 (먹자골목 연중무휴)",
    hoursEn: "09:00 ~ 23:00 (Food alley open daily)",
    closedKo: "일요일 일부 일반점포 휴무 (먹자골목 연중무휴)",
    closedEn: "Sundays partially closed (Food stalls open 365 days)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/81/2668981_image2_1.jpg",
  },
  seoul_namdaemun: {
    categoryType: "쇼핑",
    nameKo: "남대문시장",
    nameEn: "Namdaemun Market",
    descKo: "600년 역사의 대한민국 최대 전통시장으로 갈치조림골목, 칼국수, 잡채호떡 등 먹거리와 잡화가 가득합니다.",
    descEn: "Korea's largest traditional market packed with over 10,000 stalls offering local delicacies, fashion, and souvenirs.",
    subwayKo: "4호선 회현역 5번 출구 (도보 1분)",
    subwayEn: "Line 4 Hoehyeon Stn. Exit 5 (1 min walk)",
    hoursKo: "24시간 상시 (일반 소매 09:00 ~ 18:00)",
    hoursEn: "24 hours (Retail 09:00 ~ 18:00)",
    closedKo: "매주 일요일 휴무 (일부 먹거리존 제외)",
    closedEn: "Closed on Sundays (Food zones open)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/67/2612867_image2_1.jpg",
  },
  seoul_yeouido_hangang: {
    categoryType: "자연",
    nameKo: "여의도 한강공원",
    nameEn: "Yeouido Hangang Park",
    descKo: "잔디밭 피크닉, 즉석 한강 라면 먹방, 로맨틱한 한강 유람선을 즐기는 서울의 대표 수변 쉼터입니다.",
    descEn: "Premier riverside leisure spot loved for lawn picnics, instant Hangang ramen dining, and night cruise tours.",
    subwayKo: "5호선 여의나루역 2, 3번 출구 (도보 2분)",
    subwayEn: "Line 5 Yeouinaru Stn. Exit 2, 3 (2 min walk)",
    hoursKo: "24시간 상시 개방",
    hoursEn: "Open 24 hours",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://hangang.seoul.go.kr/resources/zeroCMS/site/main/images/park_view_photo_9.jpg",
  },
  seoul_museum_korea: {
    categoryType: "명소",
    nameKo: "국립중앙박물관",
    nameEn: "National Museum of Korea",
    descKo: "국보 반가사유상이 전시된 '사유의 방'을 비롯해 한국의 역사와 찬란한 문화재를 관람하는 무료 박물관입니다.",
    descEn: "World-class museum housing priceless national treasures including the meditative Pensive Bodhisattva statues.",
    subwayKo: "4호선·경의중앙선 이촌역 2번 출구 박물관 나들길 지하연결",
    subwayEn: "Line 4/Gyeongui-Jungang Ichon Stn. Exit 2 direct walkway",
    hoursKo: "10:00 ~ 18:00 (수·토 21:00 야간개장)",
    hoursEn: "10:00 ~ 18:00 (Wed/Sat until 21:00)",
    closedKo: "1월 1일, 설날, 추석 당일 휴관",
    closedEn: "Closed Jan 1, Lunar New Year, Chuseok",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/12/3495012_image2_1.jpg",
  },
  seoul_cheonggyecheon: {
    categoryType: "자연",
    nameKo: "청계천",
    nameEn: "Cheonggyecheon Stream",
    descKo: "광화문에서 동대문까지 이어지는 11km 도심 생태하천으로 밤이면 징검다리와 조명이 어우러진 산책로입니다.",
    descEn: "An 11km tranquil ecological stream flowing through downtown Seoul, adorned with night illuminations.",
    subwayKo: "5호선 광화문역 5번 출구 / 1·2호선 시청역 4번 출구",
    subwayEn: "Line 5 Gwanghwamun Stn. Exit 5 / Line 1/2 City Hall Stn. Exit 4",
    hoursKo: "24시간 상시 개방",
    hoursEn: "Open 24 hours",
    closedKo: "연중무휴 (기상악화 시 통제)",
    closedEn: "Open year-round (Controlled during heavy rain)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/90/2544890_image2_1.jpg",
  },
  seoul_coex_starfield_library: {
    categoryType: "명소",
    nameKo: "코엑스 별마당도서관",
    nameEn: "Starfield Library COEX",
    descKo: "코엑스몰 중심에 위치한 13m 높이의 웅장한 곡선 서가와 수만 권의 책이 펼쳐진 도심 속 열린 문화공간입니다.",
    descEn: "A monumental open public library inside Starfield COEX Mall featuring magnificent 13-meter tall curved bookshelves.",
    subwayKo: "2호선 삼성역 5, 6번 출구 연결 / 9호선 봉은사역 7번 출구",
    subwayEn: "Line 2 Samseong Stn. Exit 5, 6 direct / Line 9 Bongeunsa Stn. Exit 7",
    hoursKo: "10:30 ~ 22:00",
    hoursEn: "10:30 ~ 22:00",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/3584529_image2_1.jpg",
  },
  seoul_banpo_rainbow_fountain: {
    categoryType: "엔터",
    nameKo: "반포대교 달빛무지개분수",
    nameEn: "Banpo Bridge Moonlight Rainbow Fountain",
    descKo: "기네스북에 등재된 세계 최장 교량 분수로 아름다운 음악과 조명에 맞추어 시원한 물줄기가 뿜어져 나오는 야경 명소입니다.",
    descEn: "Guinness-recorded longest bridge fountain illuminating the night skyline with synchronized music and water jets.",
    subwayKo: "3·7·9호선 고속터미널역 8-1번 출구 (도보 15분)",
    subwayEn: "Line 3/7/9 Express Bus Terminal Stn. Exit 8-1 (15 min walk)",
    hoursKo: "분수 가동: 12:00, 19:30, 20:00, 20:30, 21:00 (4~10월)",
    hoursEn: "Shows: 12:00, 19:30, 20:00, 20:30, 21:00 (Apr-Oct)",
    closedKo: "동절기(11~3월) 및 우천 시 미가동",
    closedEn: "Suspended in winter (Nov-Mar) and rain",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/46/3515046_image2_1.jpg",
  },
  seoul_seokchonhosu_lake: {
    categoryType: "자연",
    nameKo: "석촌호수",
    nameEn: "Seokchon Lake",
    descKo: "롯데월드 매직아일랜드와 롯데월드타워를 둘러싼 아름다운 도심 호수로, 동호와 서호로 이어지는 수변 산책로와 봄철 벚꽃 축제 및 가을 단풍으로 사랑받는 서울 대표 힐링 명소입니다.",
    descEn: "Scenic twin-lake park wrapping around Lotte World Magic Island and Lotte World Tower, world-famous for its peaceful walking trail and vibrant spring cherry blossoms.",
    subwayKo: "2·8호선 잠실역 2, 3번 출구 (도보 5분) / 8·9호선 석촌역 1, 8번 출구",
    subwayEn: "Line 2/8 Jamsil Stn. Exit 2, 3 (5 min walk) / Line 8/9 Seokchon Stn.",
    hoursKo: "24시간 상시 개방",
    hoursEn: "Open 24 hours",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/686ee7a7-f3ea-4955-9beb-2744ca9f942b/it11",
  },
  seoul_some_sevit: {
    categoryType: "엔터",
    nameKo: "세빛섬",
    nameEn: "Some Sevit Floating Islands",
    descKo: "반포한강공원 위 3개의 인공 부유섬으로 야간 미디어아트 조명과 튜브스터 보트 체험을 즐길 수 있습니다.",
    descEn: "World-class artificial floating islands in the Han River featuring artistic architecture and luminous evening vistas.",
    subwayKo: "3·7·9호선 고속터미널역 8-1번 출구 반포한강공원 방면",
    subwayEn: "Line 3/7/9 Express Bus Terminal Stn. Exit 8-1 toward Hangang Park",
    hoursKo: "11:00 ~ 22:00 (업장별 상이)",
    hoursEn: "11:00 ~ 22:00 (Varies by venue)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=7331c90a-e6e3-4b63-9ec6-69aa9ab1426f",
  },
  seoul_ttukseom_hangang: {
    categoryType: "자연",
    nameKo: "뚝섬한강공원",
    nameEn: "Ttukseom Hangang Park",
    descKo: "원통형 자벌레 복합문화공간, 윈드서핑존, 넓은 수변 잔디밭과 계절별 테마 축제가 열리는 시민 공원입니다.",
    descEn: "Popular recreational waterside park with cylindrical J-Bug cultural complex, windsurfing, and outdoor swimming.",
    subwayKo: "7호선 자양(뚝섬한강공원)역 2, 3번 출구 연결",
    subwayEn: "Line 7 Jayang (Ttukseom Hangang Park) Stn. Exit 2, 3 direct",
    hoursKo: "24시간 상시 개방",
    hoursEn: "Open 24 hours",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://hangang.seoul.go.kr/resources/zeroCMS/site/main/images/park_view_photo_4.jpg",
  },
  seoul_childrens_grand_park: {
    categoryType: "엔터",
    nameKo: "롯데월드 어드벤처",
    nameEn: "Lotte World Adventure",
    descKo: "세계 최대 규모의 실내 테마파크 어드벤처와 석촌호수 위 야외 매직아일랜드에서 스릴 넘치는 놀이기구와 환상적인 퍼레이드를 즐기는 글로벌 테마파크입니다.",
    descEn: "World-class theme park featuring massive indoor Adventure zones and outdoor Magic Island on Seokchon Lake with thrilling rides and festive parades.",
    subwayKo: "2·8호선 잠실역 3, 4번 출구 지하 직결",
    subwayEn: "Line 2/8 Jamsil Stn. Exit 3, 4 (Direct underground connection)",
    hoursKo: "10:00 ~ 21:00 (금·토 22:00까지)",
    hoursEn: "10:00 ~ 21:00 (Fri/Sat until 22:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=8da3ed81-4ae3-40f6-8fad-9cfb67aad3c5",
  },
  seoul_lotteworld: {
    categoryType: "엔터",
    nameKo: "롯데월드 어드벤처",
    nameEn: "Lotte World Adventure",
    descKo: "세계 최대 규모의 실내 테마파크 어드벤처와 석촌호수 위 야외 매직아일랜드에서 스릴 넘치는 놀이기구와 환상적인 퍼레이드를 즐기는 글로벌 테마파크입니다.",
    descEn: "World-class theme park featuring massive indoor Adventure zones and outdoor Magic Island on Seokchon Lake with thrilling rides and festive parades.",
    subwayKo: "2·8호선 잠실역 3, 4번 출구 지하 직결",
    subwayEn: "Line 2/8 Jamsil Stn. Exit 3, 4 (Direct underground connection)",
    hoursKo: "10:00 ~ 21:00 (금·토 22:00까지)",
    hoursEn: "10:00 ~ 21:00 (Fri/Sat until 22:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=8da3ed81-4ae3-40f6-8fad-9cfb67aad3c5",
  },
  seoul_changgyeonggung: {
    categoryType: "명소",
    nameKo: "창경궁 & 대온실",
    nameEn: "Changgyeonggung Palace & Grand Greenhouse",
    descKo: "한국 최초의 서양식 식물원 대온실과 낭만적인 춘당지 연못의 은은한 야경을 감상할 수 있는 조선 궁궐입니다.",
    descEn: "Joseon royal palace featuring Korea's first Western-style botanical greenhouse and romantic Chundangji pond.",
    subwayKo: "4호선 혜화역 4번 출구 (도보 10분)",
    subwayEn: "Line 4 Hyehwa Stn. Exit 4 (10 min walk)",
    hoursKo: "09:00 ~ 21:00 (야간상시개방, 입장마감 20:00)",
    hoursEn: "09:00 ~ 21:00 (Night opening, last entry 20:00)",
    closedKo: "매주 월요일 휴관",
    closedEn: "Closed on Mondays",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/96/3384896_image2_1.JPG",
  },
  seoul_jongmyo: {
    categoryType: "명소",
    nameKo: "종묘",
    nameEn: "Jongmyo Shrine",
    descKo: "조선 역대 왕과 왕비의 신주를 모신 유네스코 세계유산 유교 사당으로 정전의 웅장한 건축미가 돋보입니다.",
    descEn: "UNESCO World Heritage royal Confucian sanctuary dedicated to the ancestral tablets of Joseon monarchs.",
    subwayKo: "1·3·5호선 종로3가역 8번 출구 (도보 3분)",
    subwayEn: "Line 1/3/5 Jongno 3-ga Stn. Exit 8 (3 min walk)",
    hoursKo: "09:00 ~ 18:00 (시간제 안내관람, 주말 자유관람)",
    hoursEn: "09:00 ~ 18:00 (Timed tours on weekdays, free on weekends)",
    closedKo: "매주 화요일 휴관",
    closedEn: "Closed on Tuesdays",
    imageUrl: "/assets/jongmyo-main.jpg",
  },
  seoul_namsangol: {
    categoryType: "명소",
    nameKo: "남산골한옥마을",
    nameEn: "Namsangol Hanok Village",
    descKo: "남산 북쪽 기슭에 복원된 조선 사대부 가옥들과 전통 정원, 국악당이 어우러진 도심 속 전통문화 쉼터입니다.",
    descEn: "Scenic village at the foot of Namsan featuring restored Joseon noble houses and traditional Korean cultural experiences.",
    subwayKo: "3·4호선 충무로역 3, 4번 출구 (도보 3분)",
    subwayEn: "Line 3/4 Chungmuro Stn. Exit 3, 4 (3 min walk)",
    hoursKo: "09:00 ~ 21:00",
    hoursEn: "09:00 ~ 21:00",
    closedKo: "매주 월요일 휴관",
    closedEn: "Closed on Mondays",
    imageUrl: "/assets/namsangol-hanok.jpg",
  },
  seoul_insadong_ssamzigil: {
    categoryType: "쇼핑",
    nameKo: "인사동 쌈지길 & 안녕인사동",
    nameEn: "Insadong Ssamzigil & Anyoung Insadong",
    descKo: "전통 공예품과 찻집, 아기자기한 디자인 공방과 갤러리가 나선형 골목을 따라 이어지는 복합문화거리입니다.",
    descEn: "Dynamic cultural shopping street filled with traditional Korean handicrafts, art galleries, and tea houses.",
    subwayKo: "3호선 안국역 6번 출구 (도보 2분) / 1호선 종각역 3-1번 출구",
    subwayEn: "Line 3 Anguk Stn. Exit 6 (2 min walk) / Line 1 Jonggak Stn. Exit 3-1",
    hoursKo: "10:30 ~ 20:30",
    hoursEn: "10:30 ~ 20:30",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "/assets/insadong-ssamzigil.jpg",
  },
  seoul_63square: {
    categoryType: "엔터",
    nameKo: "63스퀘어 & 63전망대",
    nameEn: "63 Square & Sky Observatory",
    descKo: "여의도의 황금빛 마천루로 한강의 아름다운 일몰과 스카이라인을 조망할 수 있는 예술 전시 공간입니다.",
    descEn: "Yeouido's golden skyscraper landmark boasting art exhibitions and sweeping sunset vistas across the Han River.",
    subwayKo: "9호선 샛강역 3번 출구 / 5호선 여의나루역 1번 출구 (버스 연계)",
    subwayEn: "Line 9 Saetgang Stn. Exit 3 / Line 5 Yeouinaru Stn. Exit 1",
    hoursKo: "10:00 ~ 22:00",
    hoursEn: "10:00 ~ 22:00",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://korean.visitseoul.net/comm/getImage?srvcId=MEDIA&parentSn=68046&fileTy=MEDIA&fileNo=1&thumbTy=L",
  },
  seoul_myeongdong_shopping: {
    categoryType: "쇼핑",
    nameKo: "명동 쇼핑거리",
    nameEn: "Myeongdong Shopping Street",
    descKo: "K-뷰티 플래그십 스토어와 글로벌 패션, 저녁마다 열리는 다채로운 길거리 음식 노점이 가득한 쇼핑 성지입니다.",
    descEn: "Korea's premier shopping & K-beauty district packed with global cosmetics flagships, street food stalls, and fashion boutiques.",
    subwayKo: "4호선 명동역 6번 출구 (도보 1분) / 2호선 을지로입구역 5, 6번 출구",
    subwayEn: "Line 4 Myeong-dong Stn. Exit 6 (1 min walk) / Line 2 Euljiro 1-ga Stn. Exit 5, 6",
    hoursKo: "10:00 ~ 22:00 (노점 먹거리 16:00~23:00)",
    hoursEn: "10:00 ~ 22:00 (Street food stalls 16:00~23:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "/assets/myeongdong-street.jpg",
  },
  seoul_mmca_contemporary: {
    categoryType: "명소",
    nameKo: "국립현대미술관 서울관",
    nameEn: "MMCA Seoul - Contemporary Art",
    descKo: "삼청동에 위치하여 경복궁과 마주보며 동시대 한국과 세계의 첨단 현대미술 전시를 선보이는 복합문화예술관입니다.",
    descEn: "Premier contemporary art institution in Samcheong-dong showcasing cutting-edge Korean and international exhibits.",
    subwayKo: "3호선 안국역 1번 출구 (도보 10분) / 3호선 경복궁역 5번 출구",
    subwayEn: "Line 3 Anguk Stn. Exit 1 (10 min walk) / Line 3 Gyeongbokgung Stn. Exit 5",
    hoursKo: "10:00 ~ 18:00 (수·토 21:00 야간 무료)",
    hoursEn: "10:00 ~ 18:00 (Wed/Sat until 21:00 free)",
    closedKo: "1월 1일, 설날, 추석 당일 휴관",
    closedEn: "Closed Jan 1, Lunar New Year, Chuseok",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=c5fc3bbb-b17e-4327-93c7-7e7dbafd34da",
  },
  seoul_euljiro_nogari: {
    categoryType: "엔터",
    nameKo: "을지로 노가리골목 힙지로",
    nameEn: "Euljiro Nogari Alley - Hipjiro",
    descKo: "골목길 야외 테이블에서 시원한 생맥주와 고소한 노가리를 즐기는 레트로 감성 가득한 야간 핫플레이스입니다.",
    descEn: "Vibrant retro outdoor nightlife alley where visitors enjoy ice-cold draft beer and grilled dried pollack.",
    subwayKo: "2·3호선 을지로3가역 3, 4번 출구 (도보 1분)",
    subwayEn: "Line 2/3 Euljiro 3-ga Stn. Exit 3, 4 (1 min walk)",
    hoursKo: "17:00 ~ 24:00",
    hoursEn: "17:00 ~ 24:00",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=da4c46b9-4f87-457c-89fa-e738cbd92603",
  },
  seoul_haneul_park: {
    categoryType: "자연",
    nameKo: "하늘공원 & 억새밭",
    nameEn: "Haneul Park - World Cup Park",
    descKo: "월드컵공원 가장 높은 곳에 자리하여 가을 은빛 억새 군락과 메타세쿼이아길, 한강 노을을 한눈에 담는 생태공원입니다.",
    descEn: "Breathtaking hilltop ecological park famed for silver grass fields, metasequoia paths, and panoramic sunset views.",
    subwayKo: "6호선 월드컵경기장역 1번 출구 (맹꽁이전기차 이용 가능)",
    subwayEn: "Line 6 World Cup Stadium Stn. Exit 1 (Electric shuttle available)",
    hoursKo: "05:00 ~ 22:00",
    hoursEn: "05:00 ~ 22:00",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=08fee415-c6dc-49db-8617-3cbf0a199183",
  },
  seoul_gwanghwamun_square: {
    categoryType: "명소",
    nameKo: "광화문광장 & 세종대왕 동상",
    nameEn: "Gwanghwamun Square & King Sejong",
    descKo: "세종대왕과 이순신 장군 동상이 자리하고 북악산과 경복궁이 한눈에 펼쳐지는 대한민국의 역사·문화 중심 광장입니다.",
    descEn: "The historic heart of Seoul featuring iconic statues of King Sejong the Great and Admiral Yi Sun-sin against Bukhansan Mountain.",
    subwayKo: "5호선 광화문역 2, 7번 출구 광장 직결",
    subwayEn: "Line 5 Gwanghwamun Stn. Exit 2, 7 direct",
    hoursKo: "24시간 상시 개방",
    hoursEn: "Open 24 hours",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "/assets/gwanghwamun-square.jpg",
  },
};

export const BUSAN_LANDMARK_BILINGUAL_MAP: Record<string, BilingualSpotDetail> = {
  busan_haeundae: {
    categoryType: "자연",
    nameKo: "해운대 해수욕장",
    nameEn: "Haeundae Beach",
    descKo: "부산을 대표하는 세계적인 도심 해변으로 탁 트인 백사장과 해안 산책로, 빌딩 숲이 어우러진 휴양 명소입니다.",
    descEn: "Busan's most iconic coastal beach with a vast sandy shore, seaside promenade, and vibrant skyline.",
    subwayKo: "2호선 해운대역 3번 or 5번 출구 (도보 8분)",
    subwayEn: "Line 2 Haeundae Stn. Exit 3 or 5 (8 min walk)",
    hoursKo: "연중 상시 개방 (해수욕장 개장 기간 09:00 ~ 18:00)",
    hoursEn: "Open 24/7 (Swimming hours 09:00 - 18:00 during summer)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/34/3090534_image2_1.JPG",
  },
  busan_gamcheon: {
    categoryType: "명소",
    nameKo: "감천문화마을",
    nameEn: "Gamcheon Culture Village",
    descKo: "계단식으로 늘어선 알록달록한 파스텔톤 가옥과 미로 골목, 어린왕자 포토존이 아름다운 부산의 마추픽추입니다.",
    descEn: "Vibrant hillside village featuring colorful pastel houses, maze-like alleys, and the famous Little Prince photo spot.",
    subwayKo: "1호선 토성역 6번 출구 → 사하1-1, 서구2, 서구2-2 마을버스 환승",
    subwayEn: "Line 1 Toseong Stn. Exit 6 → Transfer to local bus Saha 1-1, Seogu 2",
    hoursKo: "09:00 ~ 18:00 (마을 주민 주거지로 일몰 후 조용히 관람)",
    hoursEn: "09:00 ~ 18:00 (Residential area; quiet visiting after sunset)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/91/3365491_image2_1.jpg",
  },
  busan_gwangalli: {
    categoryType: "명소",
    nameKo: "광안리 해수욕장 & 드론쇼",
    nameEn: "Gwangalli Beach & Drone Light Show",
    descKo: "다이아몬드 브릿지 광안대교의 환상적인 야경과 매주 토요일 밤 펼쳐지는 대한민국 대표 드론 라이트 쇼 명소입니다.",
    descEn: "Famous for panoramic Gwangan Bridge night views and the signature Saturday night drone light show.",
    subwayKo: "2호선 광안역 3번 or 5번 출구 (도보 10분) / 금련산역 1번 or 3번 출구",
    subwayEn: "Line 2 Gwangan Stn. Exit 3 or 5 (10 min walk) / Geumnyeonsan Stn.",
    hoursKo: "연중 상시 개방 (드론쇼: 매주 토요일 2회)",
    hoursEn: "Open 24/7 (Drone show: Saturdays, 2 sessions)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/45/3311245_image2_1.jpg",
  },
  busan_haedong: {
    categoryType: "명소",
    nameKo: "해동용궁사",
    nameEn: "Haedong Yonggungsa Temple",
    descKo: "푸른 동해 바다 깎아지른 절벽 위에 세워져 파도 소리와 함께 일출을 감상하는 유일무이한 해안 사찰입니다.",
    descEn: "A rare and stunning Buddhist temple perched directly on seaside cliffs, renowned for sunrise views.",
    subwayKo: "동해선 오시리아역 1번 출구 → 139, 1001번 버스 환승 (용궁사국립수산과학원 하차)",
    subwayEn: "Donghae Line Osiria Stn. Exit 1 → Bus 139 or 1001",
    hoursKo: "04:30 ~ 20:30 (입장 마감 19:50)",
    hoursEn: "04:30 ~ 20:30 (Last admission 19:50)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/35/3499335_image2_1.jpg",
  },
  busan_blueline: {
    categoryType: "엔터",
    nameKo: "해운대 블루라인파크",
    nameEn: "Haeundae Blueline Park",
    descKo: "미포에서 청사포, 송정까지 동해남부선 옛 철길을 따라 해변열차와 공중 스카이캡슐을 타고 달리는 해안 액티비티입니다.",
    descEn: "Scenic coastal train and aerial Sky Capsule ride running along the ocean tracks from Mipo to Songjeong.",
    subwayKo: "2호선 중동역 7번 출구 (미포정거장 도보 12분)",
    subwayEn: "Line 2 Jung-dong Stn. Exit 7 (12 min walk to Mipo Station)",
    hoursKo: "09:30 ~ 19:00 (계절별 일몰 시간에 따라 연장 운행)",
    hoursEn: "09:30 ~ 19:00 (Extended during peak season)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/99/3546099_image2_1.jpg",
  },
  busan_jagalchi: {
    categoryType: "쇼핑",
    nameKo: "자갈치시장",
    nameEn: "Jagalchi Fish Market",
    descKo: "부산을 상징하는 대한민국 최대 수산시장으로, 싱싱한 활어회와 해산물 포장마차의 활기찬 에너지를 경험합니다.",
    descEn: "Korea's largest seafood market where you can experience lively fish auctions and freshly prepared sashimi.",
    subwayKo: "1호선 자갈치역 10번 출구 (도보 3분) / 남포역 2번 출구",
    subwayEn: "Line 1 Jagalchi Stn. Exit 10 (3 min walk) / Nampo Stn. Exit 2",
    hoursKo: "05:00 ~ 22:00 (회센터 09:00 ~ 22:00)",
    hoursEn: "05:00 ~ 22:00 (Restaurants: 09:00 ~ 22:00)",
    closedKo: "매월 첫째·셋째 주 화요일 (신동아 및 자갈치 본관)",
    closedEn: "1st & 3rd Tuesday of each month",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/46/3049246_image2_1.JPG",
  },
  busan_biff_gukje: {
    categoryType: "쇼핑",
    nameKo: "BIFF 광장 & 국제시장",
    nameEn: "BIFF Square & Gukje Market",
    descKo: "부산국제영화제의 태동지이자 명물 씨앗호떡, 비빔당면 등 K-스트리트 푸드와 레트로 만물 쇼핑의 천국입니다.",
    descEn: "Historic movie district and vibrant traditional bazaar famous for Busan sweet seed hotteok and vintage shopping.",
    subwayKo: "1호선 자갈치역 7번 출구 (도보 2분) / 남포역 1번 출구",
    subwayEn: "Line 1 Jagalchi Stn. Exit 7 (2 min walk) / Nampo Stn. Exit 1",
    hoursKo: "09:00 ~ 20:00 (식음료 포장마차 22:00까지)",
    hoursEn: "09:00 ~ 20:00 (Street food stalls until 22:00)",
    closedKo: "매월 첫째·셋째 주 일요일 (일부 점포 상이)",
    closedEn: "1st & 3rd Sunday of each month (Varies by shop)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/49/3498549_image2_1.jpg",
  },
  busan_huinnyeoul: {
    categoryType: "명소",
    nameKo: "흰여울문화마을",
    nameEn: "Huinnyeoul Culture Village",
    descKo: "영도 해안 절벽을 따라 늘어선 하얀 집들과 바다를 마주한 골목길, 감성 오션뷰 카페와 해안터널 포토존 명소입니다.",
    descEn: "Picturesque cliffside village in Yeongdo overlooking the sea, filled with cozy cafes and a coastal tunnel.",
    subwayKo: "1호선 남포역 6번 출구 → 6, 7, 9, 70, 71, 508번 버스 환승 (흰여울문화마을 정류장 하차)",
    subwayEn: "Line 1 Nampo Stn. Exit 6 → Bus 6, 7, 70, 71, 508 (15 min)",
    hoursKo: "연중 상시 개방 (상점가 10:00 ~ 19:00)",
    hoursEn: "Open 24/7 (Cafes & shops: 10:00 ~ 19:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/74/3495874_image2_1.jpg",
  },
  busan_songdo_cablecar: {
    categoryType: "엔터",
    nameKo: "송도 해상케이블카 & 구름산책로",
    nameEn: "Songdo Marine Cable Car & Skywalk",
    descKo: "송도해수욕장 바다 위 86m 상공을 가로지르는 크리스탈 캐빈 케이블카와 바다 위를 걷는 곡선형 스카이워크입니다.",
    descEn: "Glide 86m above the ocean in a glass-bottom cable car across Songdo Beach and walk the curving skywalk.",
    subwayKo: "1호선 자갈치역 1번 출구 or 남포역 8번 출구 → 26, 30, 71번 버스 (송도해수욕장 하차)",
    subwayEn: "Line 1 Jagalchi/Nampo Stn. → Bus 26, 30, 71 to Songdo Beach",
    hoursKo: "09:00 ~ 21:00 (탑승마감 20:30)",
    hoursEn: "09:00 ~ 21:00 (Last boarding 20:30)",
    closedKo: "연중무휴 (기상악화 시 운행 중단)",
    closedEn: "Open year-round (Weather permitting)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/11/3413711_image2_1.jpg",
  },
  busan_xthesky: {
    categoryType: "명소",
    nameKo: "부산 엑스더스카이 (BUSAN X the SKY)",
    nameEn: "BUSAN X the SKY Observatory",
    descKo: "해운대 엘시티 랜드마크 타워 100층에서 해운대 해변과 광안대교 야경을 내려다보는 대한민국 2위 높이의 전망대입니다.",
    descEn: "Soar to the 100th floor of Haeundae LCT Tower for 360-degree ocean views and the world's highest Starbucks.",
    subwayKo: "2호선 중동역 7번 출구 (도보 10분) / 해운대역 3번 출구",
    subwayEn: "Line 2 Jung-dong Stn. Exit 7 (10 min walk) / Haeundae Stn.",
    hoursKo: "10:00 ~ 21:00 (발권 및 입장 마감 20:30)",
    hoursEn: "10:00 ~ 21:00 (Last entry 20:30)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/16/3350316_image2_1.jpg",
  },
  busan_taejongdae: {
    categoryType: "자연",
    nameKo: "태종대 유원지",
    nameEn: "Taejongdae Resort Park",
    descKo: "울창한 해송 숲과 기암괴석 절벽, 영도 등대와 푸른 바다가 파노라마로 펼쳐지는 부산 제1의 해안 명승지입니다.",
    descEn: "Famous coastal scenic park featuring dramatic rock cliffs, lush pine forests, and the Danubi circular train.",
    subwayKo: "1호선 남포역 6번 출구 → 8, 30, 66, 88, 186번 버스 (태종대 종점 하차)",
    subwayEn: "Line 1 Nampo Stn. Exit 6 → Bus 8, 30, 66, 88 (to Taejongdae terminal)",
    hoursKo: "05:00 ~ 24:00 (다누비열차 09:20 ~ 17:30)",
    hoursEn: "05:00 ~ 24:00 (Danubi Train 09:20 ~ 17:30)",
    closedKo: "연중무휴 (다누비열차 우천 시 운행 중단)",
    closedEn: "Open year-round (Danubi train halts on rainy days)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/83/3506383_image2_1.jpg",
  },
  busan_thebay101: {
    categoryType: "명소",
    nameKo: "더베이101 & 마린시티",
    nameEn: "The Bay 101 & Marine City",
    descKo: "물웅덩이에 반사되는 마린시티 초고층 빌딩 숲의 환상적인 반영 사진과 피시앤칩스, 요트 투어로 유명한 야경 핫플입니다.",
    descEn: "Iconic nightspot renowned for sparkling reflections of Marine City skyscrapers and sunset yacht tours.",
    subwayKo: "2호선 동백역 1번 출구 (도보 10분)",
    subwayEn: "Line 2 Dongbaek Stn. Exit 1 (10 min walk)",
    hoursKo: "09:00 ~ 24:00 (매장별 상이)",
    hoursEn: "09:00 ~ 24:00 (Varies by restaurant)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/41/3407941_image2_1.png",
  },
  busan_centum_spaland: {
    categoryType: "쇼핑",
    nameKo: "신세계 센텀시티 & 스파랜드",
    nameEn: "Shinsegae Centum City & Spa Land",
    descKo: "세계 최대 백화점으로 기네스북에 등재된 쇼핑 메카와 천연 온천수 기반 18개 테마 온천욕을 즐기는 최고급 찜질스파입니다.",
    descEn: "World's largest department store complex featuring Spa Land, a luxury Korean jimjilbang with natural hot springs.",
    subwayKo: "2호선 센텀시티역 지하 12번 출구 직결",
    subwayEn: "Line 2 Centum City Stn. Exit 12 directly connected underground",
    hoursKo: "백화점 10:30 ~ 20:00 (스파랜드 09:00 ~ 22:00)",
    hoursEn: "Mall: 10:30 ~ 20:00 (Spa Land: 09:00 ~ 22:00)",
    closedKo: "스파랜드 연중무휴 (백화점 월 1회 휴무)",
    closedEn: "Spa Land open daily (Mall closed 1 day/month)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/02/3544802_image2_1.JPEG",
  },
  busan_tower: {
    categoryType: "명소",
    nameKo: "부산타워 & 용두산공원",
    nameEn: "Busan Tower (Diamond Tower) & Yongdusan Park",
    descKo: "부산 원도심 한복판 용두산 정상에서 부산항 대교, 자갈치 시장, 남포동 거리를 360도로 조망하는 랜드마크 타워입니다.",
    descEn: "Panoramic observation tower standing high in Yongdusan Park, overlooking Busan Port and downtown Nampo.",
    subwayKo: "1호선 남포역 1번 출구 (광복로 패션거리 에스컬레이터 이용)",
    subwayEn: "Line 1 Nampo Stn. Exit 1 (Take outdoor escalator via Gwangbok-ro)",
    hoursKo: "10:00 ~ 22:00 (발권마감 21:30)",
    hoursEn: "10:00 ~ 22:00 (Last ticket 21:30)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/66/4096266_image2_1.jpg",
  },
  busan_oryukdo: {
    categoryType: "자연",
    nameKo: "오륙도 스카이워크 & 해맞이공원",
    nameEn: "Oryukdo Skywalk & Sunrise Park",
    descKo: "동해와 남해의 분기점이 되는 35m 해안 절벽 위에 세워진 U자형 투명 유리 다리로 아찔한 바다 위를 걷습니다.",
    descEn: "Thrilling U-shaped glass-bottom walkway set atop 35m cliffs dividing the East Sea and South Sea.",
    subwayKo: "2호선 경성대·부경대역 5번 출구 → 24, 27, 131번 버스 (오륙도SK뷰 후문 하차)",
    subwayEn: "Line 2 Kyungsung Univ. Stn. Exit 5 → Bus 24, 27 to Oryukdo",
    hoursKo: "09:00 ~ 18:00 (입장마감 17:50)",
    hoursEn: "09:00 ~ 18:00 (Last entry 17:50)",
    closedKo: "연중무휴 (눈·비·강풍 시 개방 제한)",
    closedEn: "Open year-round (Closed during rain/high wind)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/69/3492369_image2_1.jpg",
  },
  busan_jeonpo_cafe: {
    categoryType: "쇼핑",
    nameKo: "전포 카페거리 & 서면",
    nameEn: "Jeonpo Cafe Street & Seomyeon",
    descKo: "뉴욕타임스 선정 추천 명소로 공구 골목에서 감각적인 로스터리 카페와 소품숍, K-패션 상권으로 변신한 트렌드 중심지입니다.",
    descEn: "Trendy hub converted from industrial alleys, praised by NYT for hip artisan cafes, boutiques, and bakeries.",
    subwayKo: "2호선 전포역 7번 or 8번 출구 (도보 2분) / 1·2호선 서면역 2번 출구",
    subwayEn: "Line 2 Jeonpo Stn. Exit 7 or 8 (2 min walk) / Line 1/2 Seomyeon Stn.",
    hoursKo: "11:00 ~ 22:00 (매장별 상이)",
    hoursEn: "11:00 ~ 22:00 (Varies by cafe)",
    closedKo: "매장별 상이 (보통 연중무휴)",
    closedEn: "Varies by cafe (Mostly open daily)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/60/3496960_image2_1.jpg",
  },
  busan_cheongsapo: {
    categoryType: "명소",
    nameKo: "청사포 다릿돌전망대",
    nameEn: "Cheongsapo Daritdol Observatory",
    descKo: "푸른 바다 위로 73m 뻗어나간 해상 전망대와 감성 가득한 쌍둥이 등대, 조개구이 골목이 있는 정겨운 포구 마을입니다.",
    descEn: "73m sea skywalk projecting over ocean reefs, famous for twin lighthouses and grilled clam seaside dinners.",
    subwayKo: "2호선 장산역 7번 출구 → 해운대구2 마을버스 환승 (청사포 종점 하차)",
    subwayEn: "Line 2 Jangsan Stn. Exit 7 → Local Bus Haeundae-gu 2",
    hoursKo: "09:00 ~ 18:00 (하절기 20:00까지, 입장마감 30분 전)",
    hoursEn: "09:00 ~ 18:00 (Summer until 20:00)",
    closedKo: "연중무휴 (기상악화 시 통제)",
    closedEn: "Open year-round (Weather permitting)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/30/3495930_image2_1.jpg",
  },
  busan_ahopsan: {
    categoryType: "자연",
    nameKo: "아홉산숲",
    nameEn: "Ahopsan Forest",
    descKo: "400년간 한 가문이 가꿔온 자연 생태 숲으로, 거대한 맹종죽 대나무 숲길과 영화·드라마(더 킹, 군도 등) 촬영 명소입니다.",
    descEn: "A pristine 400-year-old preserved bamboo forest featured in famous K-dramas like 'The King: Eternal Monarch'.",
    subwayKo: "동해선 좌천역 or 기장역 → 기장군 2-3번 마을버스 환승 (미동마을 하차)",
    subwayEn: "Donghae Line Gijang Stn. → Local bus Gijang-gun 2-3 to Midong Village",
    hoursKo: "09:00 ~ 18:00 (마지막 입장 17:00)",
    hoursEn: "09:00 ~ 18:00 (Last entry 17:00)",
    closedKo: "매주 월요일 정기휴무",
    closedEn: "Closed on Mondays",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/91/3309791_image2_1.jpg",
  },
  busan_lotteworld: {
    categoryType: "엔터",
    nameKo: "롯데월드 어드벤처 부산",
    nameEn: "Lotte World Adventure Busan",
    descKo: "동화 속 로리 왕국을 테마로 한 영남권 최대 야외 테마파크로 짜릿한 자이언트 롤러코스터와 화려한 퍼레이드를 즐깁니다.",
    descEn: "Largest outdoor theme park in southeastern Korea featuring thrilling roller coasters and fairytale parades.",
    subwayKo: "동해선 오시리아역 1번 출구 (도보 10분)",
    subwayEn: "Donghae Line Osiria Stn. Exit 1 (10 min walk)",
    hoursKo: "10:00 ~ 20:00 (주말 및 성수기 21:00까지)",
    hoursEn: "10:00 ~ 20:00 (Weekends until 21:00)",
    closedKo: "연중무휴",
    closedEn: "Open year-round",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/21/2815721_image2_1.jpg",
  },
  busan_f1963: {
    categoryType: "명소",
    nameKo: "F1963 복합문화공간",
    nameEn: "F1963 Cultural Complex",
    descKo: "과거 와이어 로프 공장을 감각적인 문화공간으로 재생한 곳으로, 테라로사 커피, 예스24 중고서점, 예술 전시를 품고 있습니다.",
    descEn: "An eco-friendly cultural factory revitalized from a wire plant, housing Terarosa Coffee, galleries, and bookstores.",
    subwayKo: "3호선 망미역 2번 출구 → 수영구2 마을버스 (산정아파트 하차 도보 3분)",
    subwayEn: "Line 3 Mangmi Stn. Exit 2 → Local Bus Suyeong-gu 2",
    hoursKo: "09:00 ~ 21:00 (매장/전시별 상이)",
    hoursEn: "09:00 ~ 21:00 (Varies by venue)",
    closedKo: "연중무휴 (일부 갤러리 월요일 휴관)",
    closedEn: "Open year-round (Some galleries closed on Mondays)",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/3350961_image2_1.jpg",
  },
};

// SEOUL 맵에 BUSAN 맵을 자동 통합하여 기존 컴포넌트 호환성을 완벽 유지
Object.assign(SEOUL_LANDMARK_BILINGUAL_MAP, BUSAN_LANDMARK_BILINGUAL_MAP);

export const ALL_LANDMARK_BILINGUAL_MAP: Record<string, BilingualSpotDetail> = {
  ...SEOUL_LANDMARK_BILINGUAL_MAP,
  ...BUSAN_LANDMARK_BILINGUAL_MAP,
};


/**
 * desc_en 문자열에서 || SUBWAY: ..., || HOURS: ..., || CLOSED: ..., || WEB: ...
 * 태그를 파싱하여 메타데이터와 순수 설명을 분리합니다.
 */
export function parseAttractionMetadata(rawDesc: string): {
  cleanDesc: string;
  subwayInfo?: string;
  openingHours?: string;
  closedDays?: string;
  officialUrl?: string;
} {
  if (!rawDesc) return { cleanDesc: "" };

  const subwayMatch = rawDesc.match(/\|\|\s*SUBWAY:\s*([^|]+)/i);
  const hoursMatch = rawDesc.match(/\|\|\s*HOURS:\s*([^|]+)/i);
  const closedMatch = rawDesc.match(/\|\|\s*CLOSED:\s*([^|]+)/i);
  const webMatch = rawDesc.match(/\|\|\s*WEB:\s*([^|]+)/i);

  // 태그 제거한 순수 설명
  const cleanDesc = rawDesc.split("||")[0].trim();

  return {
    cleanDesc,
    subwayInfo: subwayMatch ? subwayMatch[1].trim() : undefined,
    openingHours: hoursMatch ? hoursMatch[1].trim() : undefined,
    closedDays: closedMatch ? closedMatch[1].trim() : undefined,
    officialUrl: webMatch ? webMatch[1].trim() : undefined,
  };
}

export interface TourCoursePreset {
  id: string;
  cityCode: SupportedCity;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  spotIds: string[];
  estimatedHours: number;
  courseType: "AREA_ROUTE" | "CITY_HIGHLIGHT";
}

export const ATTRACTION_SPOTS_CATALOG: AttractionSpot[] = [
  // === SEOUL ===
  {
    id: "seoul_gyeongbokgung",
    cityCode: "SEOUL",
    nameKo: "경복궁",
    nameEn: "Gyeongbokgung Palace",
    descKo: "조선 왕조 제1의 법궁으로 수문장 교대의식과 한복 착용 시 무료 입장이 가능한 필수 명소",
    descEn: "The main royal palace of Joseon dynasty with free entry in Hanbok and royal guard ceremonies",
    price: 0,
    priceStatus: "FREE",
    tag: "명소",
    emoji: "🏯",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_nseoultower",
    cityCode: "SEOUL",
    nameKo: "N서울타워 전망대",
    nameEn: "N Seoul Tower Observatory",
    descKo: "서울 시내 전체를 360도로 한눈에 조망하는 대표 야경 랜드마크",
    descEn: "360-degree panoramic skyline view of Seoul",
    price: 21000,
    priceStatus: "PAID",
    tag: "전망/야경",
    emoji: "🗼",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_gwanghwamun",
    cityCode: "SEOUL",
    nameKo: "광화문광장 & 세종대왕 동상",
    nameEn: "Gwanghwamun Square & King Sejong",
    descKo: "세종대왕과 이순신 장군 동상이 자리하고 북악산과 경복궁이 한눈에 펼쳐지는 역사·문화 중심 광장",
    descEn: "The historic heart of Seoul featuring iconic statues of King Sejong the Great and Admiral Yi Sun-sin",
    price: 0,
    priceStatus: "FREE",
    tag: "명소",
    emoji: "🏞️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_seoulsky",
    cityCode: "SEOUL",
    nameKo: "롯데월드타워 서울스카이",
    nameEn: "Lotte World Tower Seoul Sky",
    descKo: "세계 5위 높이(555m) 118층 초고층 타워에서 만나는 압도적인 스카이데크 유리 바닥 전망대",
    descEn: "The 5th tallest building in the world (555m) featuring glass-floor sky decks and sweeping skyline views",
    price: 29000,
    priceStatus: "PAID",
    tag: "랜드마크",
    emoji: "🏙️",
    gradientBg: "from-sky-500/15 to-blue-600/15",
    isFeatured: true,
  },
  {
    id: "seoul_bukchon",
    cityCode: "SEOUL",
    nameKo: "북촌한옥마을",
    nameEn: "Bukchon Hanok Village",
    descKo: "경복궁과 창덕궁 사이 600년 역사를 간직한 수백 채의 전통 기와집과 감고당길 골목 투어 명소",
    descEn: "Historic village nestled between royal palaces, home to hundreds of traditional Korean tile-roofed houses",
    price: 0,
    priceStatus: "FREE",
    tag: "명소",
    emoji: "🏘️",
    gradientBg: "from-amber-600/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "seoul_seongsu",
    cityCode: "SEOUL",
    nameKo: "성수동 연무장길",
    nameEn: "Seongsu-dong Yeonmujang-gil",
    descKo: "서울의 브루클린으로 불리며 감각적인 패션 플래그십 팝업스토어와 트렌디한 베이커리 카페 거리",
    descEn: "The 'Brooklyn of Seoul' buzzing with iconic fashion flagship pop-ups, artisanal cafes, and trendy bakeries",
    price: 0,
    priceStatus: "FREE",
    tag: "쇼핑",
    emoji: "☕",
    gradientBg: "from-rose-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_hongdae",
    cityCode: "SEOUL",
    nameKo: "홍대 걷고싶은거리",
    nameEn: "Hongdae Walking Street",
    descKo: "청춘과 버스킹의 중심지로 K-Pop 댄스 거리공연과 개성 넘치는 인디 숍들이 활기를 띠는 명소",
    descEn: "Korea's youth culture hub packed with spontaneous K-Pop busking performances, indie art shops, and nightlife",
    price: 0,
    priceStatus: "FREE",
    tag: "엔터",
    emoji: "🎸",
    gradientBg: "from-purple-500/15 to-violet-500/15",
    isFeatured: false,
  },
  {
    id: "seoul_gwangjang",
    cityCode: "SEOUL",
    nameKo: "광장시장",
    nameEn: "Gwangjang Market",
    descKo: "100년 전통의 대표 먹거리 시장으로 바삭한 녹두빈대떡, 마약김밥, 육회가 유명한 전통시장",
    descEn: "Over 100 years of authentic street food heritage, famous for bindaetteok and mayak gimbap",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🥢",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/81/2668981_image2_1.jpg",
    subwayInfo: "1호선 종로5가역 8번 출구 / 2·5호선 을지로4가역 4번 출구",
    subwayInfoKo: "1호선 종로5가역 8번 출구 / 2·5호선 을지로4가역 4번 출구",
    subwayInfoEn: "Line 1 Jongno 5-ga Stn. Exit 8 / Line 2/5 Euljiro 4-ga Stn. Exit 4",
    openingHours: "09:00 ~ 23:00 (먹자골목 연중무휴)",
    openingHoursKo: "09:00 ~ 23:00 (먹자골목 연중무휴)",
    openingHoursEn: "09:00 ~ 23:00 (Food alley open daily)",
    closedDays: "일요일 일부 일반점포 휴무 (먹자골목 연중무휴)",
    closedDaysKo: "일요일 일부 일반점포 휴무 (먹자골목 연중무휴)",
    closedDaysEn: "Sundays partially closed (Food stalls open 365 days)",
    officialUrl: "http://www.kwangjangmarket.co.kr",
  },
  {
    id: "seoul_namdaemun",
    cityCode: "SEOUL",
    nameKo: "남대문시장",
    nameEn: "Namdaemun Market",
    descKo: "600년 역사의 대한민국 최대 전통시장으로 갈치조림골목, 칼국수, 잡채호떡 등 먹거리와 잡화 쇼핑",
    descEn: "Korea's largest traditional market with over 10,000 stalls offering local delicacies, fashion, and goods",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🥟",
    gradientBg: "from-rose-500/15 to-red-500/15",
    isFeatured: true,
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/67/2612867_image2_1.jpg",
    subwayInfo: "4호선 회현역 5번 출구 (도보 1분)",
    subwayInfoKo: "4호선 회현역 5번 출구 (도보 1분)",
    subwayInfoEn: "Line 4 Hoehyeon Stn. Exit 5 (1 min walk)",
    openingHours: "24시간 상시 (일반 소매 09:00 ~ 18:00)",
    openingHoursKo: "24시간 상시 (일반 소매 09:00 ~ 18:00)",
    openingHoursEn: "24 hours (Retail 09:00 ~ 18:00)",
    closedDays: "매주 일요일 휴무 (일부 먹거리존 제외)",
    closedDaysKo: "매주 일요일 휴무 (일부 먹거리존 제외)",
    closedDaysEn: "Closed on Sundays (Food zones open)",
    officialUrl: "https://english.visitseoul.net/attractions/Namdaemun-Market-Tourist-Information-Center/ENP027219",
  },
  {
    id: "seoul_yeouido_hangang",
    cityCode: "SEOUL",
    nameKo: "여의도 한강공원",
    nameEn: "Yeouido Hangang Park",
    descKo: "잔디밭 피크닉, 즉석 한강 라면 먹방, 로맨틱한 한강 유람선을 즐기는 서울의 대표 수변 쉼터",
    descEn: "Premier riverside leisure spot loved for lawn picnics, instant Hangang ramen dining, and river cruise tours",
    price: 0,
    priceStatus: "FREE",
    tag: "체험/휴식",
    emoji: "🍜",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
    isFeatured: true,
    imageUrl: "https://hangang.seoul.go.kr/resources/zeroCMS/site/main/images/park_view_photo_9.jpg",
    subwayInfo: "5호선 여의나루역 2, 3번 출구 (도보 2분)",
    subwayInfoKo: "5호선 여의나루역 2, 3번 출구 (도보 2분)",
    subwayInfoEn: "Line 5 Yeouinaru Stn. Exit 2, 3 (2 min walk)",
    openingHours: "24시간 상시 개방",
    openingHoursKo: "24시간 상시 개방",
    openingHoursEn: "Open 24 hours",
    closedDays: "연중무휴",
    closedDaysKo: "연중무휴",
    closedDaysEn: "Open year-round",
    officialUrl: "https://hangang.seoul.go.kr",
  },
  {
    id: "seoul_national_museum",
    cityCode: "SEOUL",
    nameKo: "국립중앙박물관 (사유의 방)",
    nameEn: "National Museum of Korea",
    descKo: "반가사유상이 모셔진 한국 최고의 국립 박물관",
    descEn: "Korea's flagship national museum featuring Room of Quiet Contemplation",
    price: 0,
    priceStatus: "FREE",
    tag: "박물관",
    emoji: "🏛️",
    gradientBg: "from-slate-500/15 to-zinc-500/15",
    isFeatured: false,
  },

  // === BUSAN ===
  {
    id: "busan_haeundae",
    cityCode: "BUSAN",
    nameKo: "해운대 해수욕장",
    nameEn: "Haeundae Beach",
    descKo: "부산을 대표하는 세계적인 도심 해변으로 탁 트인 백사장과 해안 산책로, 빌딩 숲이 어우러진 휴양 명소",
    descEn: "Busan's most iconic coastal beach with vast sand, seaside promenade, and vibrant skyline",
    price: 0,
    priceStatus: "FREE",
    tag: "해변/휴양",
    emoji: "🏖️",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
    categoryType: "자연",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/34/3090534_image2_1.JPG",
    subwayInfo: "2호선 해운대역 3, 5번 출구 (도보 8분)",
    openingHours: "연중 상시 개방",
    closedDays: "연중무휴",
  },
  {
    id: "busan_gamcheon",
    cityCode: "BUSAN",
    nameKo: "감천문화마을",
    nameEn: "Gamcheon Culture Village",
    descKo: "계단식 파스텔톤 가옥과 미로 골목, 어린왕자 포토존이 매력적인 문화마을",
    descEn: "Vibrant hillside village featuring pastel houses, maze alleys, and Little Prince photo spot",
    price: 0,
    priceStatus: "FREE",
    tag: "문화/포토존",
    emoji: "🎨",
    gradientBg: "from-amber-500/15 to-rose-500/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/91/3365491_image2_1.jpg",
    subwayInfo: "1호선 토성역 6번 출구 → 사하1-1, 서구2 마을버스 환승",
    openingHours: "09:00 ~ 18:00 (마을 주민 주거지)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_gwangalli",
    cityCode: "BUSAN",
    nameKo: "광안리 해수욕장 & 드론쇼",
    nameEn: "Gwangalli Beach & Drone Light Show",
    descKo: "광안대교 다이아몬드 야경과 토요일 밤을 수놓는 환상적인 드론 라이트 쇼",
    descEn: "Iconic Gwangan Bridge night views and Saturday night drone light show",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/해변",
    emoji: "🌉",
    gradientBg: "from-blue-600/15 to-purple-600/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/45/3311245_image2_1.jpg",
    subwayInfo: "2호선 광안역 3, 5번 출구 (도보 10분) / 금련산역",
    openingHours: "연중 상시 개방 (드론쇼 토요일 2회)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_haedong",
    cityCode: "BUSAN",
    nameKo: "해동용궁사",
    nameEn: "Haedong Yonggungsa Temple",
    descKo: "푸른 동해 바다 깎아지른 바위 절벽 위에 세워진 신비로운 해안 사찰",
    descEn: "Stunning Buddhist temple perched directly on seaside cliffs with sunrise views",
    price: 0,
    priceStatus: "FREE",
    tag: "사찰/자연",
    emoji: "🛕",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/35/3499335_image2_1.jpg",
    subwayInfo: "동해선 오시리아역 1번 출구 → 139, 1001번 버스 환승",
    openingHours: "04:30 ~ 20:30 (입장 마감 19:50)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_blueline",
    cityCode: "BUSAN",
    nameKo: "해운대 블루라인파크",
    nameEn: "Haeundae Blueline Park",
    descKo: "옛 철길을 따라 바다 위를 달리는 해변열차와 공중 스카이캡슐 액티비티",
    descEn: "Scenic coastal train and aerial Sky Capsule ride along ocean tracks",
    price: 16000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "🚃",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
    categoryType: "엔터",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/99/3546099_image2_1.jpg",
    subwayInfo: "2호선 중동역 7번 출구 (미포정거장 도보 12분)",
    openingHours: "09:30 ~ 19:00 (계절별 상이)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_jagalchi",
    cityCode: "BUSAN",
    nameKo: "자갈치시장",
    nameEn: "Jagalchi Fish Market",
    descKo: "대한민국 최대 수산시장으로 싱싱한 활어회와 포장마차의 활기찬 에너지",
    descEn: "Korea's largest seafood market with fresh sashimi and lively stalls",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🐟",
    gradientBg: "from-orange-500/15 to-amber-500/15",
    isFeatured: true,
    categoryType: "쇼핑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/46/3049246_image2_1.JPG",
    subwayInfo: "1호선 자갈치역 10번 출구 (도보 3분) / 남포역 2번 출구",
    openingHours: "05:00 ~ 22:00 (회센터 09:00 ~ 22:00)",
    closedDays: "매월 첫째·셋째 화요일",
  },
  {
    id: "busan_biff_gukje",
    cityCode: "BUSAN",
    nameKo: "BIFF 광장 & 국제시장",
    nameEn: "BIFF Square & Gukje Market",
    descKo: "명물 씨앗호떡 등 길거리 K-푸드와 레트로 만물 쇼핑의 천국",
    descEn: "Iconic street food hub famous for Busan seed hotteok and vintage shopping",
    price: 0,
    priceStatus: "FREE",
    tag: "스트리트푸드",
    emoji: "🍢",
    gradientBg: "from-rose-500/15 to-orange-500/15",
    isFeatured: true,
    categoryType: "쇼핑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/49/3498549_image2_1.jpg",
    subwayInfo: "1호선 자갈치역 7번 출구 (도보 2분) / 남포역 1번 출구",
    openingHours: "09:00 ~ 20:00 (먹거리 노점 22:00까지)",
    closedDays: "매월 첫째·셋째 일요일 (일부 점포 상이)",
  },
  {
    id: "busan_huinnyeoul",
    cityCode: "BUSAN",
    nameKo: "흰여울문화마을",
    nameEn: "Huinnyeoul Culture Village",
    descKo: "영도 해안 절벽 골목길과 오션뷰 카페, 해안터널 포토존 명소",
    descEn: "Scenic cliffside village in Yeongdo with cozy cafes and coastal tunnel",
    price: 0,
    priceStatus: "FREE",
    tag: "해안마을/카페",
    emoji: "🌊",
    gradientBg: "from-sky-500/15 to-indigo-500/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/74/3495874_image2_1.jpg",
    subwayInfo: "1호선 남포역 6번 출구 → 6, 7, 70, 71, 508번 버스 환승",
    openingHours: "연중 상시 개방 (상점가 10:00 ~ 19:00)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_songdo_cablecar",
    cityCode: "BUSAN",
    nameKo: "송도 해상케이블카 & 구름산책로",
    nameEn: "Songdo Marine Cable Car & Skywalk",
    descKo: "바다 위 86m를 가로지르는 크리스탈 케이블카와 곡선형 해상 스카이워크",
    descEn: "Glide above the ocean in a glass-bottom cable car across Songdo Beach",
    price: 17000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "🚡",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
    isFeatured: true,
    categoryType: "엔터",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/11/3413711_image2_1.jpg",
    subwayInfo: "1호선 자갈치/남포역 → 26, 30, 71번 버스 환승 (송도해수욕장)",
    openingHours: "09:00 ~ 21:00 (탑승마감 20:30)",
    closedDays: "연중무휴 (기상악화 시 중단)",
  },
  {
    id: "busan_xthesky",
    cityCode: "BUSAN",
    nameKo: "부산 엑스더스카이 (BUSAN X the SKY)",
    nameEn: "BUSAN X the SKY Observatory",
    descKo: "엘시티 100층에서 해운대 해변과 광안대교를 조망하는 초고층 전망대",
    descEn: "100th-floor observation deck offering 360-degree Busan ocean views",
    price: 27000,
    priceStatus: "PAID",
    tag: "전망대",
    emoji: "🏙️",
    gradientBg: "from-blue-600/15 to-indigo-600/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/16/3350316_image2_1.jpg",
    subwayInfo: "2호선 중동역 7번 출구 (도보 10분) / 해운대역",
    openingHours: "10:00 ~ 21:00 (입장마감 20:30)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_taejongdae",
    cityCode: "BUSAN",
    nameKo: "태종대 유원지",
    nameEn: "Taejongdae Resort Park",
    descKo: "울창한 해송 숲과 기암괴석 절벽, 영도 등대와 다누비 순환열차",
    descEn: "Dramatic coastal cliffs, ocean lighthouse, and scenic Danubi train",
    price: 4000,
    priceStatus: "PAID",
    tag: "해안절경",
    emoji: "🌲",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
    categoryType: "자연",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/83/3506383_image2_1.jpg",
    subwayInfo: "1호선 남포역 6번 출구 → 8, 30, 66, 88번 버스 (태종대 종점)",
    openingHours: "05:00 ~ 24:00 (다누비열차 09:20 ~ 17:30)",
    closedDays: "연중무휴 (우천 시 열차 중단)",
  },
  {
    id: "busan_thebay101",
    cityCode: "BUSAN",
    nameKo: "더베이101 & 마린시티",
    nameEn: "The Bay 101 & Marine City",
    descKo: "마천루 빌딩 숲의 환상적인 반영 야경과 요트 투어, 다이닝 핫플",
    descEn: "Iconic waterfront for Marine City skyline reflection photos and sunset yachts",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/요트",
    emoji: "🛥️",
    gradientBg: "from-slate-700/15 to-indigo-700/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/41/3407941_image2_1.png",
    subwayInfo: "2호선 동백역 1번 출구 (도보 10분)",
    openingHours: "09:00 ~ 24:00 (매장별 상이)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_centum_spaland",
    cityCode: "BUSAN",
    nameKo: "신세계 센텀시티 & 스파랜드",
    nameEn: "Shinsegae Centum City & Spa Land",
    descKo: "기네스 등재 세계 최대 백화점과 18개 테마 온천욕의 최고급 찜질스파",
    descEn: "World's largest mall featuring luxury Korean Spa Land hot springs",
    price: 23000,
    priceStatus: "PAID",
    tag: "쇼핑/K스파",
    emoji: "♨️",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
    categoryType: "쇼핑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/02/3544802_image2_1.JPEG",
    subwayInfo: "2호선 센텀시티역 지하 12번 출구 직결",
    openingHours: "백화점 10:30~20:00 (스파랜드 09:00~22:00)",
    closedDays: "스파랜드 연중무휴 (백화점 월 1회 휴무)",
  },
  {
    id: "busan_tower",
    cityCode: "BUSAN",
    nameKo: "부산타워 & 용두산공원",
    nameEn: "Busan Tower & Yongdusan Park",
    descKo: "원도심 정상에서 부산항 대교와 남포동 거리를 360도로 조망하는 전망 타워",
    descEn: "Panoramic observation tower overlooking Busan Port and downtown Nampo",
    price: 12000,
    priceStatus: "PAID",
    tag: "전망대/공원",
    emoji: "🗼",
    gradientBg: "from-indigo-500/15 to-blue-500/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/66/4096266_image2_1.jpg",
    subwayInfo: "1호선 남포역 1번 출구 (광복로 에스컬레이터)",
    openingHours: "10:00 ~ 22:00 (발권마감 21:30)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_oryukdo",
    cityCode: "BUSAN",
    nameKo: "오륙도 스카이워크 & 해맞이공원",
    nameEn: "Oryukdo Skywalk & Sunrise Park",
    descKo: "동해와 남해의 분기점 절벽 위 U자형 투명 유리 다리와 해안 절경",
    descEn: "Thrilling glass walkway set atop coastal cliffs dividing two seas",
    price: 0,
    priceStatus: "FREE",
    tag: "자연/전망",
    emoji: "🪨",
    gradientBg: "from-blue-500/15 to-teal-500/15",
    isFeatured: true,
    categoryType: "자연",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/69/3492369_image2_1.jpg",
    subwayInfo: "2호선 경성대부경대역 5번 출구 → 24, 27번 버스 (오륙도SK뷰)",
    openingHours: "09:00 ~ 18:00 (입장마감 17:50)",
    closedDays: "연중무휴 (우천/강풍 시 제한)",
  },
  {
    id: "busan_jeonpo_cafe",
    cityCode: "BUSAN",
    nameKo: "전포 카페거리 & 서면",
    nameEn: "Jeonpo Cafe Street & Seomyeon",
    descKo: "NYT 선정 추천 명소로 감각적인 로스터리 카페와 베이커리, K-패션 상권",
    descEn: "Hip artisan cafe district praised by NYT, filled with trendy coffee shops",
    price: 0,
    priceStatus: "FREE",
    tag: "카페거리/K트렌드",
    emoji: "☕",
    gradientBg: "from-amber-600/15 to-yellow-500/15",
    isFeatured: true,
    categoryType: "쇼핑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/60/3496960_image2_1.jpg",
    subwayInfo: "2호선 전포역 7, 8번 출구 (도보 2분) / 서면역 2번 출구",
    openingHours: "11:00 ~ 22:00 (매장별 상이)",
    closedDays: "매장별 상이",
  },
  {
    id: "busan_cheongsapo",
    cityCode: "BUSAN",
    nameKo: "청사포 다릿돌전망대",
    nameEn: "Cheongsapo Daritdol Observatory",
    descKo: "바다 위로 뻗어나간 해상 전망대와 감성 쌍둥이 등대, 해변 조개구이 골목",
    descEn: "Ocean skywalk projecting over reefs, famous for twin lighthouses & seafood",
    price: 0,
    priceStatus: "FREE",
    tag: "전망대/포구",
    emoji: "⚓",
    gradientBg: "from-cyan-600/15 to-blue-600/15",
    isFeatured: true,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/30/3495930_image2_1.jpg",
    subwayInfo: "2호선 장산역 7번 출구 → 해운대구2 마을버스 (청사포 종점)",
    openingHours: "09:00 ~ 18:00 (하절기 20:00까지)",
    closedDays: "연중무휴 (기상악화 시 통제)",
  },
  {
    id: "busan_ahopsan",
    cityCode: "BUSAN",
    nameKo: "아홉산숲",
    nameEn: "Ahopsan Forest",
    descKo: "400년 역사의 울창한 맹종죽 대나무 숲길과 영화·드라마 촬영 명소",
    descEn: "Pristine 400-year-old preserved bamboo forest featured in major K-dramas",
    price: 5000,
    priceStatus: "PAID",
    tag: "힐링숲/대나무",
    emoji: "🎋",
    gradientBg: "from-emerald-600/15 to-green-600/15",
    isFeatured: false,
    categoryType: "자연",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/91/3309791_image2_1.jpg",
    subwayInfo: "동해선 좌천/기장역 → 기장군 2-3번 마을버스 (미동마을)",
    openingHours: "09:00 ~ 18:00 (마지막 입장 17:00)",
    closedDays: "매주 월요일 정기휴무",
  },
  {
    id: "busan_lotteworld",
    cityCode: "BUSAN",
    nameKo: "롯데월드 어드벤처 부산",
    nameEn: "Lotte World Adventure Busan",
    descKo: "동화 왕국을 테마로 한 영남 최대 테마파크와 익스트림 롤러코스터",
    descEn: "Largest theme park in southeast Korea with giant coasters and parades",
    price: 47000,
    priceStatus: "PAID",
    tag: "테마파크",
    emoji: "🎢",
    gradientBg: "from-purple-500/15 to-pink-500/15",
    isFeatured: false,
    categoryType: "엔터",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/21/2815721_image2_1.jpg",
    subwayInfo: "동해선 오시리아역 1번 출구 (도보 10분)",
    openingHours: "10:00 ~ 20:00 (주말/성수기 21:00까지)",
    closedDays: "연중무휴",
  },
  {
    id: "busan_f1963",
    cityCode: "BUSAN",
    nameKo: "F1963 복합문화공간",
    nameEn: "F1963 Cultural Complex",
    descKo: "옛 와이어 공장을 재생한 공간으로 테라로사 커피, 갤러리, 힐링 대나무 뜰",
    descEn: "Revitalized eco-factory housing Terarosa Coffee, art galleries, and bookstores",
    price: 0,
    priceStatus: "FREE",
    tag: "복합문화/카페",
    emoji: "🏭",
    gradientBg: "from-stone-600/15 to-zinc-600/15",
    isFeatured: false,
    categoryType: "명소",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/3350961_image2_1.jpg",
    subwayInfo: "3호선 망미역 2번 출구 → 수영구2 마을버스 (산정아파트)",
    openingHours: "09:00 ~ 21:00 (매장/전시별 상이)",
    closedDays: "연중무휴",
  },

  // === JEJU ===
  {
    id: "jeju_seongsan",
    cityCode: "JEJU",
    nameKo: "성산일출봉 탐방",
    nameEn: "Seongsan Ilchulbong Tuff Cone",
    descKo: "유네스코 세계자연유산으로 지정된 해돋이 명소 화산구",
    descEn: "UNESCO World Natural Heritage volcanic tuff cone",
    price: 5000,
    priceStatus: "PAID",
    tag: "유네스코자연",
    emoji: "🌋",
    gradientBg: "from-emerald-600/15 to-green-600/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "jeju_udo",
    cityCode: "JEJU",
    nameKo: "우도 도항선 & 전기차 투어",
    nameEn: "Udo Island Ferry & Electric Bike",
    descKo: "에메랄드빛 바다와 땅콩 아이스크림이 기다리는 섬 속의 섬",
    descEn: "Island off Jeju famous for turquoise waters and peanut ice cream",
    price: 10500,
    priceStatus: "PAID",
    tag: "섬투어/액티비티",
    emoji: "🏝️",
    gradientBg: "from-cyan-500/15 to-teal-500/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "jeju_hyeopjae",
    cityCode: "JEJU",
    nameKo: "협재 해수욕장 & 비양도 전망",
    nameEn: "Hyeopjae Beach & Biyangdo",
    descKo: "투명한 모래사장에서 바라보는 비양도와 푸른 바다",
    descEn: "Pristine sandy beach looking out to Biyangdo Island",
    price: 0,
    priceStatus: "FREE",
    tag: "해변/휴식",
    emoji: "🏖️",
    gradientBg: "from-sky-500/15 to-blue-400/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "jeju_snoopy",
    cityCode: "JEJU",
    nameKo: "스누피가든 체험",
    nameEn: "Snoopy Garden Jeju",
    descKo: "제주의 자연 오름과 스누피 테마가 어우러진 넓은 감성 정원",
    descEn: "Charming Peanuts-themed indoor & outdoor botanical garden",
    price: 18000,
    priceStatus: "PAID",
    tag: "테마파크",
    emoji: "🐶",
    gradientBg: "from-yellow-500/15 to-orange-400/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "jeju_dongmun",
    cityCode: "JEJU",
    nameKo: "동문재래시장 야시장",
    nameEn: "Dongmun Traditional Night Market",
    descKo: "제주 특산물과 야시장 푸드트럭 먹거리가 가득한 대형 시장",
    descEn: "Vibrant traditional market famous for street food and citrus",
    price: 0,
    priceStatus: "FREE",
    tag: "야시장",
    emoji: "🍊",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "jeju_arte",
    cityCode: "JEJU",
    nameKo: "아르떼뮤지엄 제주",
    nameEn: "Arte Museum Jeju",
    descKo: "빛과 소리가 선사하는 몰입형 미디어아트 전시관",
    descEn: "Immersive media art exhibition hall presenting nature themes",
    price: 17000,
    priceStatus: "PAID",
    tag: "미디어아트",
    emoji: "🎨",
    gradientBg: "from-purple-600/15 to-pink-600/15",
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
  },

  // === INCHEON ===
  {
    id: "incheon_chinatown",
    cityCode: "INCHEON",
    nameKo: "인천 차이나타운 & 송월동 동화마을",
    nameEn: "Incheon Chinatown & Fairy Tale Village",
    descKo: "짜장면의 본고장이자 아기자기한 동화 벽화 거리",
    descEn: "Birthplace of Jajangmyeon and colorful fairytale street art",
    price: 0,
    priceStatus: "FREE",
    tag: "문화/음식",
    emoji: "🏮",
    gradientBg: "from-red-500/15 to-amber-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_songdo_central",
    cityCode: "INCHEON",
    nameKo: "송도 센트럴파크 수상택시",
    nameEn: "Songdo Central Park Water Taxi",
    descKo: "미래도시 빌딩 숲 사이 해수로에서 즐기는 보트 체험",
    descEn: "Scenic boat ride along seawater canal in futuristic Songdo",
    price: 5000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "⛵",
    gradientBg: "from-blue-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_wolmi_myland",
    cityCode: "INCHEON",
    nameKo: "월미도 마이랜드 디스코팡팡",
    nameEn: "Wolmido MyLand Theme Park",
    descKo: "바닷가 월미문화의거리와 유쾌한 놀이기구 체험",
    descEn: "Waterfront amusement rides and lively sea walkway",
    price: 6000,
    priceStatus: "PAID",
    tag: "놀이공원",
    emoji: "🎡",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_openport",
    cityCode: "INCHEON",
    nameKo: "개항장 근대역사거리",
    nameEn: "Open Port Modern History Street",
    descKo: "19세기 근대 건축물들이 잘 보존된 역사적인 가쿠라 거리",
    descEn: "Historic district with preserved 19th-century architecture",
    price: 0,
    priceStatus: "FREE",
    tag: "역사",
    emoji: "🏛️",
    gradientBg: "from-amber-600/15 to-stone-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_triple_street",
    cityCode: "INCHEON",
    nameKo: "송도 트리플스트리트",
    nameEn: "Songdo Triple Street",
    descKo: "쇼핑과 문화, 프리미엄 다이닝이 정돈된 복합 문화 공간",
    descEn: "Modern lifestyle and shopping complex in Songdo",
    price: 0,
    priceStatus: "FREE",
    tag: "쇼핑",
    emoji: "🛍️",
    gradientBg: "from-pink-500/15 to-rose-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_incheon_bridge",
    cityCode: "INCHEON",
    nameKo: "인천대교 전망대 (오션스코프)",
    nameEn: "Incheon Bridge Observatory",
    descKo: "서해 바다와 웅장한 인천대교의 일몰을 바라보는 야경 명소",
    descEn: "Sunset and ocean views overlooking Incheon Grand Bridge",
    price: 0,
    priceStatus: "FREE",
    tag: "일몰/전망",
    emoji: "🌅",
    gradientBg: "from-orange-500/15 to-yellow-500/15",
    isFeatured: true,
  },

  // === SUWON ===
  {
    id: "suwon_fortress",
    cityCode: "SUWON",
    nameKo: "수원화성 성곽길 산책",
    nameEn: "Suwon Hwaseong Fortress Wall Walk",
    descKo: "정조 대왕의 효심과 조선 과학기술의 정수가 담긴 성곽길",
    descEn: "UNESCO World Heritage fortress wall offering scenic walks",
    price: 0,
    priceStatus: "FREE",
    tag: "유네스코 유산",
    emoji: "🏯",
    gradientBg: "from-emerald-600/15 to-teal-600/15",
    isFeatured: true,
  },
  {
    id: "suwon_haenggung",
    cityCode: "SUWON",
    nameKo: "화성행궁 관람",
    nameEn: "Hwaseong Haenggung Palace",
    descKo: "조선 시대 왕이 지방에 머물던 궁궐 중 가장 크고 웅장한 곳",
    descEn: "Largest temporary palace used by Joseon Dynasty Kings",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "👑",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
    isFeatured: true,
  },
  {
    id: "suwon_haengnidan",
    cityCode: "SUWON",
    nameKo: "행리단길 카페거리",
    nameEn: "Haengnidan-gil Cafe Street",
    descKo: "옛 한옥과 감성 카페, 소품샵들이 성벽 아래 밀집한 골목",
    descEn: "Charming alleyways packed with boutique cafes near fortress walls",
    price: 0,
    priceStatus: "FREE",
    tag: "카페/트렌드",
    emoji: "☕",
    gradientBg: "from-orange-500/15 to-amber-400/15",
    isFeatured: true,
  },
  {
    id: "suwon_flying_suwon",
    cityCode: "SUWON",
    nameKo: "플라잉수원 열기구 체험",
    nameEn: "Flying Suwon Hot Air Balloon",
    descKo: "150m 상공에서 수원화성의 야경을 조망하는 계류식 열기구",
    descEn: "Tethered helium balloon ride overlooking Suwon at night",
    price: 20000,
    priceStatus: "PAID",
    tag: "액티비티/야경",
    emoji: "🎈",
    gradientBg: "from-sky-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "suwon_starfield",
    cityCode: "SUWON",
    nameKo: "스타필드 수원 별마당 도서관",
    nameEn: "Starfield Suwon Byeolmadang Library",
    descKo: "웅장한 행성 구조물과 초대형 서가가 돋보이는 랜드마크 도서관",
    descEn: "Massive iconic multi-story open library inside Starfield mall",
    price: 0,
    priceStatus: "FREE",
    tag: "랜드마크",
    emoji: "📚",
    gradientBg: "from-blue-600/15 to-purple-600/15",
    isFeatured: true,
  },
  {
    id: "suwon_chicken_street",
    cityCode: "SUWON",
    nameKo: "수원 통닭거리",
    nameEn: "Suwon Chicken Street",
    descKo: "가마솥에서 튀겨내는 전통 통닭과 왕갈비통닭 명물 거리",
    descEn: "Famous street dedicated to traditional cauldron-fried chicken",
    price: 0,
    priceStatus: "FREE",
    tag: "미식",
    emoji: "🍗",
    gradientBg: "from-amber-600/15 to-orange-500/15",
    isFeatured: true,
  },

  // === JEONJU ===
  {
    id: "jeonju_hanok_village",
    cityCode: "JEONJU",
    nameKo: "전주 한옥마을 산책",
    nameEn: "Jeonju Hanok Village",
    descKo: "700여 채의 한옥이 모여있는 한국 대표 슬로시티 한옥마을",
    descEn: "Traditional Hanok Village with 700+ preserved Korean houses",
    price: 0,
    priceStatus: "FREE",
    tag: "한옥/문화",
    emoji: "🏠",
    gradientBg: "from-amber-600/15 to-stone-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_gyeonggijeon",
    cityCode: "JEONJU",
    nameKo: "경기전 (태조 이성계 어진)",
    nameEn: "Gyeonggijeon Shrine",
    descKo: "조선 태조 이성계의 초상화가 모셔진 역사 깊은 성지",
    descEn: "Historic shrine housing the official portrait of King Taejo",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "📜",
    gradientBg: "from-red-500/15 to-amber-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_jammanyi",
    cityCode: "JEONJU",
    nameKo: "자만벽화마을",
    nameEn: "Jaman Mural Village",
    descKo: "한옥마을 맞은편 언덕길을 따라 이어지는 귀여운 벽화 거리",
    descEn: "Hillside art village filled with anime & colorful murals",
    price: 0,
    priceStatus: "FREE",
    tag: "포토존",
    emoji: "🖼️",
    gradientBg: "from-pink-500/15 to-purple-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_jeondong",
    cityCode: "JEONJU",
    nameKo: "전동성당",
    nameEn: "Jeondong Cathedral",
    descKo: "호남 지역 최초의 로마네스크 양식 아름다운 성당",
    descEn: "Stunning 1914 Romanesque cathedral at entrance of Hanok Village",
    price: 0,
    priceStatus: "FREE",
    tag: "건축",
    emoji: "⛪",
    gradientBg: "from-slate-500/15 to-blue-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_traditional_wine",
    cityCode: "JEONJU",
    nameKo: "전주 모주 시음 & 한식 체험",
    nameEn: "Jeonju Moju Tasting & Food",
    descKo: "은은한 계피향 모주와 비빔밥 파전의 참맛 체험",
    descEn: "Tasting local traditional herbal rice wine (Moju) with Pajeon",
    price: 8000,
    priceStatus: "PAID",
    tag: "미식체험",
    emoji: "🍶",
    gradientBg: "from-amber-700/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "jeonju_deokjin",
    cityCode: "JEONJU",
    nameKo: "덕진공원 연꽃 자전거",
    nameEn: "Deokjin Park Lotus Pond",
    descKo: "여름철 연꽃이 장관을 이루는 도심 속 전통 호수 공원",
    descEn: "Traditional park centered around a historic lotus pond",
    price: 0,
    priceStatus: "FREE",
    tag: "자연/공원",
    emoji: "🪷",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },

  // === GYEONGJU ===
  {
    id: "gyeongju_bulguksa",
    cityCode: "GYEONGJU",
    nameKo: "불국사 & 석굴암",
    nameEn: "Bulguksa Temple & Seokguram Grotto",
    descKo: "신라 불교 예술의 최고봉인 유네스코 세계문화유산 사찰",
    descEn: "Masterpiece of Buddhist art and UNESCO World Heritage",
    price: 0,
    priceStatus: "FREE",
    tag: "유네스코 유산",
    emoji: "🛕",
    gradientBg: "from-amber-600/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_donggung",
    cityCode: "GYEONGJU",
    nameKo: "동궁과 월지 (안압지 야경)",
    nameEn: "Donggung Palace & Wolji Pond",
    descKo: "신라 왕족의 안압지 연못에 비치는 신비로운 야경 명소",
    descEn: "Breathtaking illuminated reflection night view over the Royal Pond",
    price: 3000,
    priceStatus: "PAID",
    tag: "야경/사적",
    emoji: "🌙",
    gradientBg: "from-indigo-600/15 to-purple-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_cheomseongdae",
    cityCode: "GYEONGJU",
    nameKo: "첨성대 & 대릉원 숲",
    nameEn: "Cheomseongdae Observatory & Daereungwon",
    descKo: "동양에서 가장 오래된 천문대와 신라 거대 왕릉 군락",
    descEn: "East Asia's oldest astronomical observatory and ancient royal tombs",
    price: 4000,
    priceStatus: "PAID",
    tag: "역사/유적",
    emoji: "🌌",
    gradientBg: "from-emerald-600/15 to-green-500/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_hwangnidan",
    cityCode: "GYEONGJU",
    nameKo: "황리단길 십원빵 & 한옥카페",
    nameEn: "Hwangnidan-gil Street",
    descKo: "경주 최고의 핫플레이스 한옥 카페와 십원빵 먹거리 거리",
    descEn: "Trendy Hanok street famous for 10-won cheese bread and cafes",
    price: 3500,
    priceStatus: "PAID",
    tag: "트렌드/미식",
    emoji: "🪙",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_national_museum",
    cityCode: "GYEONGJU",
    nameKo: "국립경주박물관 (성덕대왕신종)",
    nameEn: "Gyeongju National Museum",
    descKo: "신라 금관과 에밀레종의 울림을 전하는 박물관",
    descEn: "Houses Silla golden crowns and the Divine Bell of King Seongdeok",
    price: 0,
    priceStatus: "FREE",
    tag: "박물관",
    emoji: "🔔",
    gradientBg: "from-yellow-600/15 to-amber-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_woljeonggyo",
    cityCode: "GYEONGJU",
    nameKo: "월정교 야간 산책",
    nameEn: "Woljeonggyo Bridge Night Walk",
    descKo: "남천 위로 복원된 웅장하고 화려한 신라 왕경 누교",
    descEn: "Magnificently restored wooden bridge with brilliant night lights",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/교량",
    emoji: "🌉",
    gradientBg: "from-rose-500/15 to-red-500/15",
    isFeatured: true,
  },

  // === GANGNEUNG ===
  {
    id: "gangneung_anmok",
    cityCode: "GANGNEUNG",
    nameKo: "안목해변 커피거리",
    nameEn: "Anmok Beach Coffee Street",
    descKo: "동해 바다를 바라보며 커피 한 잔의 여유를 즐기는 해변",
    descEn: "Famous seaside strip packed with ocean-view cafes",
    price: 0,
    priceStatus: "FREE",
    tag: "카페/해변",
    emoji: "☕",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_haslla",
    cityCode: "GANGNEUNG",
    nameKo: "하슬라아트월드",
    nameEn: "Haslla Art World",
    descKo: "동해 바다가 시원하게 건너다뵈는 조각공원과 포토존 뮤지엄",
    descEn: "Oceanfront contemporary sculpture park and art museum",
    price: 17000,
    priceStatus: "PAID",
    tag: "미술관/포토존",
    emoji: "🎨",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_arte",
    cityCode: "GANGNEUNG",
    nameKo: "아르떼뮤지엄 강릉",
    nameEn: "Arte Museum Gangneung",
    descKo: "경포호 인근 백두대간과 자연의 빛을 담은 미디어아트",
    descEn: "Immersive nature-themed media art exhibition hall near Gyeongpo",
    price: 17000,
    priceStatus: "PAID",
    tag: "미디어아트",
    emoji: "✨",
    gradientBg: "from-indigo-600/15 to-sky-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_gyeongpo",
    cityCode: "GANGNEUNG",
    nameKo: "경포호 자전거 순환 산책",
    nameEn: "Gyeongpo Lake Bike Ride",
    descKo: "잔잔한 호수를 둘러싼 가로수길과 경포대 루프",
    descEn: "Scenic lakefront bicycle path and historical pavilion",
    price: 5000,
    priceStatus: "PAID",
    tag: "자연/액티비티",
    emoji: "🚲",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_ojukheon",
    cityCode: "GANGNEUNG",
    nameKo: "오죽헌 (신사임당 & 율곡 이이)",
    nameEn: "Ojukheon House",
    descKo: "오색 검은 대나무가 둘러싸인 한국에서 가장 오래된 목조건물 중 하나",
    descEn: "Birthplace of Shin Saimdang and Yulgok Yi I amidst black bamboo",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "🎋",
    gradientBg: "from-green-600/15 to-emerald-600/15",
    isFeatured: true,
  },
  {
    id: "gangneung_central_market",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 중앙시장 닭강정",
    nameEn: "Gangneung Central Market",
    descKo: "배 오징어순대와 닭강정 등 먹거리 천국 전통시장",
    descEn: "Traditional market famous for crispy fried chicken and stuffed squid",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🍗",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },

  // === SOKCHO ===
  {
    id: "sokcho_cablecar",
    cityCode: "SOKCHO",
    nameKo: "설악산 국립공원 케이블카",
    nameEn: "Seoraksan National Park Cable Car",
    descKo: "권금성 정상까지 케이블카로 오르며 감상하는 설악산 기암괴석",
    descEn: "Cable car ride up to Gwongeumseong Fortress in Seoraksan",
    price: 15000,
    priceStatus: "PAID",
    tag: "자연/액티비티",
    emoji: "⛰️",
    gradientBg: "from-emerald-600/15 to-teal-600/15",
    isFeatured: true,
  },
  {
    id: "sokcho_abai",
    cityCode: "SOKCHO",
    nameKo: "속초 아바이마을 갯배 체험",
    nameEn: "Abai Village Gaetbae Boat",
    descKo: "줄을 끌어 수로를 건너는 손맛 갯배 체험과 순대 마을",
    descEn: "Unique hand-pulled ferry boat experience to Abai Village",
    price: 1000,
    priceStatus: "PAID",
    tag: "체험",
    emoji: "⛵",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_sokchoeye",
    cityCode: "SOKCHO",
    nameKo: "속초아이 대관람차",
    nameEn: "Sokcho Eye Ferris Wheel",
    descKo: "속초 해수욕장 정중앙에서 동해바다를 내려다보는 초대형 관람차",
    descEn: "Giant Ferris wheel right on Sokcho Beach with sea views",
    price: 12000,
    priceStatus: "PAID",
    tag: "랜드마크",
    emoji: "🎡",
    gradientBg: "from-sky-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_yeonggeumjeong",
    cityCode: "SOKCHO",
    nameKo: "영금정 해돋이 정자",
    nameEn: "Yeonggeumjeong Pavilion",
    descKo: "바다 위 돌산 정자에서 듣는 거문고 소리 같은 파도 소리",
    descEn: "Seaside pavilion over ocean rocks with sunrise views",
    price: 0,
    priceStatus: "FREE",
    tag: "일출/자연",
    emoji: "🌅",
    gradientBg: "from-orange-500/15 to-rose-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_tourist_market",
    cityCode: "SOKCHO",
    nameKo: "속초 관광수산시장",
    nameEn: "Sokcho Tourist & Fishery Market",
    descKo: "만석닭강정, 씨앗호떡, 감자옹심이가 줄짓는 먹거리 시장",
    descEn: "Bustling market renowned for fried chicken and potato dumplings",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🦀",
    gradientBg: "from-amber-600/15 to-yellow-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_cheongchoho",
    cityCode: "SOKCHO",
    nameKo: "청초호 호수공원 엑스포타워",
    nameEn: "Cheongchoho Lake Park Tower",
    descKo: "호수와 바다가 조화를 이루는 청초호 산책로",
    descEn: "Lakeside park with observatory tower overlook",
    price: 2500,
    priceStatus: "PAID",
    tag: "산책/전망",
    emoji: "🏙️",
    gradientBg: "from-blue-600/15 to-indigo-600/15",
    isFeatured: true,
  },

  // === YEOSU ===
  {
    id: "yeosu_marine_cablecar",
    cityCode: "YEOSU",
    nameKo: "여수 해양케이블카 (크리스탈)",
    nameEn: "Yeosu Maritime Cable Car",
    descKo: "바다 위를 지나 섬과 육지를 연결하는 투명 바닥 케이블카",
    descEn: "Cable car connecting mainland to Dolsan with glass floor cabin",
    price: 22000,
    priceStatus: "PAID",
    tag: "액티비티/전망",
    emoji: "🚠",
    gradientBg: "from-blue-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_odongdo",
    cityCode: "YEOSU",
    nameKo: "오동도 동백열차 & 등대",
    nameEn: "Odongdo Island Camellia Train",
    descKo: "동백꽃 섬 오동도로 향하는 방파제 길과 숲 산책로",
    descEn: "Breakwater walk and camellia forest path on Odongdo",
    price: 1000,
    priceStatus: "PAID",
    tag: "자연/섬",
    emoji: "🌺",
    gradientBg: "from-rose-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_night_sea",
    cityCode: "YEOSU",
    nameKo: "여수 밤바다 낭만포차",
    nameEn: "Yeosu Romantic Pocha Street",
    descKo: "돌산대교 야경을 바다 건너 바라보는 분위기 있는 해변 포차",
    descEn: "Iconic oceanfront street food stalls under illuminated bridges",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/미식",
    emoji: "🌃",
    gradientBg: "from-purple-600/15 to-indigo-600/15",
    isFeatured: true,
  },
  {
    id: "yeosu_hyangiram",
    cityCode: "YEOSU",
    nameKo: "향일암 해돋이 절경",
    nameEn: "Hyangiram Hermitage",
    descKo: "해를 향하는 암자라는 뜻으로 기암절벽 해돋이로 이름난 암자",
    descEn: "Famous cliffside hermitage known for magnificent sunrises",
    price: 2000,
    priceStatus: "PAID",
    tag: "사찰/일출",
    emoji: "🌅",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_laon_railbike",
    cityCode: "YEOSU",
    nameKo: "여수 해양레일바이크",
    nameEn: "Yeosu Ocean Railbike",
    descKo: "전 구간 바다를 조망하며 시원한 터널을 달리는 해안 레일바이크",
    descEn: "Oceanfront railbike track passing scenic coastal tunnels",
    price: 13000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "🚲",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_yeosu_expo",
    cityCode: "YEOSU",
    nameKo: "여수 엑스포 빅오쇼 (Big-O)",
    nameEn: "Yeosu Expo Big-O Show",
    descKo: "화려한 분수쇼와 멀티미디어 해양 문화 분수 퍼포먼스",
    descEn: "Spectacular ocean fountain light show at Expo Park",
    price: 18000,
    priceStatus: "PAID",
    tag: "공연/멀티미디어",
    emoji: "🎆",
    gradientBg: "from-violet-600/15 to-purple-600/15",
    isFeatured: true,
  },
];

export const TOUR_COURSE_PRESETS: TourCoursePreset[] = [
  // === SEOUL (AREA_ROUTE) ===
  {
    id: "seoul_course_heritage",
    cityCode: "SEOUL",
    nameKo: "궁궐·북촌·인사동 코스",
    nameEn: "Palace, Bukchon & Insadong Course",
    descKo: "경복궁 수문장 교대의식부터 북촌 한옥 골목과 광화문광장 역사 도보 투어",
    descEn: "Traditional walk: Gyeongbokgung palace entry, hanok village & Insadong",
    spotIds: ["seoul_gyeongbokgung", "seoul_bukchon", "seoul_gwanghwamun"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_trend",
    cityCode: "SEOUL",
    nameKo: "성수·서울숲 문화 코스",
    nameEn: "Seongsu & Seoul Forest Culture Course",
    descKo: "MZ 핫플 성수동 팝업스토어 탐방과 울창한 서울숲 산책",
    descEn: "Hipster Seongsu pop-up stores & relaxing Seoul Forest walk",
    spotIds: ["seoul_seongsu"],
    estimatedHours: 3,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_night",
    cityCode: "SEOUL",
    nameKo: "홍대·연남 야간 코스",
    nameEn: "Hongdae & Yeonnam Night Course",
    descKo: "거리 버스킹과 연트럴파크 산책, 밤이 더 뜨거운 청춘 거리 투어",
    descEn: "Live street busking, Yeonnam park stroll & youth nightlife",
    spotIds: ["seoul_hongdae"],
    estimatedHours: 3,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_river",
    cityCode: "SEOUL",
    nameKo: "여의도·한강 저녁 코스",
    nameEn: "Yeouido & Riverfront Sunset Course",
    descKo: "한강 피크닉 라면 체험과 N서울타워 전망대에서 감상하는 서울 야경",
    descEn: "Riverfront picnic ramyeon & panoramic night lights from N Seoul Tower",
    spotIds: ["seoul_yeouido_hangang", "seoul_nseoultower"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },

  // === BUSAN (AREA_ROUTE) ===
  {
    id: "busan_course_haeundae_east",
    cityCode: "BUSAN",
    nameKo: "해운대·기장 해양 코스",
    nameEn: "Haeundae & Coastal Highlights",
    descKo: "해운대 해변, 블루라인 해변열차, 엑스더스카이 전망대와 해안 절벽 해동용궁사",
    descEn: "Haeundae Beach, Blueline coastal train, X the Sky observatory & Haedong Yonggungsa",
    spotIds: ["busan_haeundae", "busan_blueline", "busan_xthesky", "busan_haedong"],
    estimatedHours: 5,
    courseType: "AREA_ROUTE",
  },
  {
    id: "busan_course_nampo_culture",
    cityCode: "BUSAN",
    nameKo: "원도심 문화 & 미식 코스",
    nameEn: "Nampo Historic & Foodie Course",
    descKo: "알록달록 감천문화마을, 자갈치 수산시장, BIFF광장 먹거리와 부산타워 파노라마",
    descEn: "Colorful Gamcheon Village, Jagalchi fish market, BIFF street food & Busan Tower",
    spotIds: ["busan_gamcheon", "busan_jagalchi", "busan_biff_gukje", "busan_tower"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "busan_course_yeongdo_songdo",
    cityCode: "BUSAN",
    nameKo: "영도·송도 오션 힐링 코스",
    nameEn: "Yeongdo & Songdo Scenic Ocean Course",
    descKo: "절벽 위 흰여울문화마을과 태종대 해안절경, 송도 해상케이블카 오션 뷰",
    descEn: "Huinnyeoul cliffside village, Taejongdae ocean park & Songdo marine cable car",
    spotIds: ["busan_huinnyeoul", "busan_taejongdae", "busan_songdo_cablecar"],
    estimatedHours: 5,
    courseType: "AREA_ROUTE",
  },
  {
    id: "busan_course_night_trend",
    cityCode: "BUSAN",
    nameKo: "광안리 야경 & K-트렌드 코스",
    nameEn: "Gwangalli Night View & K-Trend Course",
    descKo: "전포 카페거리 감성 투어, 더베이101 마린시티 마천루 반영과 광안리 드론쇼",
    descEn: "Hip Jeonpo Cafe Street, The Bay 101 Marine City nightscapes & Gwangalli drone show",
    spotIds: ["busan_jeonpo_cafe", "busan_thebay101", "busan_gwangalli"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },

  // === JEJU (AREA_ROUTE) ===
  {
    id: "jeju_course_east",
    cityCode: "JEJU",
    nameKo: "동부 성산·우도 코스",
    nameEn: "Eastern Seongsan & Udo Island Course",
    descKo: "성산일출봉 등반과 우도 도항선 섬 투어로 즐기는 제주의 동쪽 바다",
    descEn: "Seongsan tuff cone climb & Udo island ferry scenic tour",
    spotIds: ["jeju_seongsan", "jeju_udo"],
    estimatedHours: 5,
    courseType: "AREA_ROUTE",
  },
  {
    id: "jeju_course_west",
    cityCode: "JEJU",
    nameKo: "서부 협재·애월 코스",
    nameEn: "Western Hyeopjae & Aewol Course",
    descKo: "투명한 에메랄드빛 협재 바다와 스누피가든 감성 야외 정원",
    descEn: "Clear turquoise Hyeopjae beach & Snoopy Garden Jeju",
    spotIds: ["jeju_hyeopjae", "jeju_snoopy"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "jeju_course_city",
    cityCode: "JEJU",
    nameKo: "제주시 도심·아트 코스",
    nameEn: "Jeju City & Media Art Course",
    descKo: "아르떼뮤지엄 빛의 미디어아트와 동문재래시장 야시장 미식 투어",
    descEn: "Arte Museum immersive media art & Dongmun night market food",
    spotIds: ["jeju_arte", "jeju_dongmun"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },

  // === INCHEON (CITY_HIGHLIGHT) ===
  {
    id: "incheon_course_highlight",
    cityCode: "INCHEON",
    nameKo: "인천 개항장 & 송도 미래도시 대표 코스",
    nameEn: "Incheon Open Port & Songdo Highlights",
    descKo: "차이나타운과 개항장 근대거리부터 송도 센트럴파크 수상택시까지",
    descEn: "Chinatown historic walk & Songdo futuristic Central Park water taxi",
    spotIds: ["incheon_chinatown", "incheon_songdo_central", "incheon_openport"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === SUWON (CITY_HIGHLIGHT) ===
  {
    id: "suwon_course_highlight",
    cityCode: "SUWON",
    nameKo: "수원화성 & 행리단길 대표 코스",
    nameEn: "Suwon Hwaseong & Haengnidan Highlights",
    descKo: "세계유산 수원화성 성곽 산책, 화성행궁 관람 및 행리단길 감성 카페",
    descEn: "Hwaseong Fortress walk, Haenggung Palace & Haengnidan cafe alley",
    spotIds: ["suwon_fortress", "suwon_haenggung", "suwon_haengnidan"],
    estimatedHours: 4,
    courseType: "CITY_HIGHLIGHT",
  },

  // === JEONJU (CITY_HIGHLIGHT) ===
  {
    id: "jeonju_course_highlight",
    cityCode: "JEONJU",
    nameKo: "전주 한옥마을 대표 코스",
    nameEn: "Jeonju Hanok Village Highlights",
    descKo: "경기전 어진 관람, 자만벽화마을과 전동성당, 모주 시음 슬로시티 투어",
    descEn: "Gyeonggijeon shrine, Jaman murals, Jeondong cathedral & Moju tasting",
    spotIds: ["jeonju_hanok_village", "jeonju_gyeonggijeon", "jeonju_jammanyi", "jeonju_traditional_wine"],
    estimatedHours: 4,
    courseType: "CITY_HIGHLIGHT",
  },

  // === GYEONGJU (CITY_HIGHLIGHT) ===
  {
    id: "gyeongju_course_highlight",
    cityCode: "GYEONGJU",
    nameKo: "신라 천년 역사 & 야경 대표 코스",
    nameEn: "Gyeongju Ancient Heritage & Night View Highlights",
    descKo: "불국사와 첨성대·대릉원 산책 후 동궁과 월지의 환상적인 야경 감상",
    descEn: "Bulguksa Temple, Cheomseongdae observatory & Donggung Palace night view",
    spotIds: ["gyeongju_bulguksa", "gyeongju_cheomseongdae", "gyeongju_donggung", "gyeongju_hwangnidan"],
    estimatedHours: 6,
    courseType: "CITY_HIGHLIGHT",
  },

  // === GANGNEUNG (CITY_HIGHLIGHT) ===
  {
    id: "gangneung_course_highlight",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 바다 & 커피 대표 코스",
    nameEn: "Gangneung Beach & Coffee Highlights",
    descKo: "안목해변 커피거리, 오죽헌 역사 탐방과 하슬라아트월드 미디어아트",
    descEn: "Anmok coffee street, Ojukheon house & Haslla Art World museum",
    spotIds: ["gangneung_anmok", "gangneung_ojukheon", "gangneung_haslla"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === SOKCHO (CITY_HIGHLIGHT) ===
  {
    id: "sokcho_course_highlight",
    cityCode: "SOKCHO",
    nameKo: "설악산 & 속초 바다 대표 코스",
    nameEn: "Seoraksan & Sokcho Sea Highlights",
    descKo: "설악산 케이블카 단풍·기암 조망과 아바이마을 갯배, 속초관광수산시장",
    descEn: "Seoraksan cable car, Abai village gaetbae boat & tourist market",
    spotIds: ["sokcho_cablecar", "sokcho_abai", "sokcho_tourist_market"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === YEOSU (CITY_HIGHLIGHT) ===
  {
    id: "yeosu_course_highlight",
    cityCode: "YEOSU",
    nameKo: "여수 해양 케이블카 & 밤바다 대표 코스",
    nameEn: "Yeosu Maritime Cable Car & Night Sea Highlights",
    descKo: "투명 해양케이블카 조망과 오동도 동백길, 낭만포차 밤바다 야경",
    descEn: "Maritime cable car over sea, Odongdo island walk & romantic pocha street",
    spotIds: ["yeosu_marine_cablecar", "yeosu_odongdo", "yeosu_night_sea"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },
];

/**
 * DB(Supabase) 또는 외부 API에서 불러온 최신 동적 관광지 목록을 카탈로그에 동기화합니다.
 */
export function registerCustomAttractionSpots(spots: (AttractionSpot & { imageUrl?: string; deepLink?: string })[]) {
  const existingMap = new Map(ATTRACTION_SPOTS_CATALOG.map((s, idx) => [s.id, idx]));
  spots.forEach((s) => {
    if (!s || !s.id || !s.cityCode) return;
    if (existingMap.has(s.id)) {
      const idx = existingMap.get(s.id)!;
      if (ATTRACTION_SPOTS_CATALOG[idx].cityCode === s.cityCode) {
        ATTRACTION_SPOTS_CATALOG[idx] = s;
      }
    } else {
      ATTRACTION_SPOTS_CATALOG.push(s);
      existingMap.set(s.id, ATTRACTION_SPOTS_CATALOG.length - 1);
    }
  });
}

