import { SupportedCity } from "../../../lib/trip-domain";

export type PriceStatus = "FREE" | "PAID" | "PARTIALLY_PAID" | "UNCONFIRMED";

export interface AttractionSpot {
  id: string;
  cityCode: SupportedCity;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  price: number;
  priceStatus: PriceStatus;
  tag: string;
  emoji: string;
  gradientBg: string;
  isFeatured: boolean;
  subwayInfo?: string;
  openingHours?: string;
  closedDays?: string;
  officialUrl?: string;
  imageUrl?: string;
  deepLink?: string;
}

/**
 * desc_en 문자열에서 || SUBWAY: ..., || HOURS: ..., || CLOSED: ..., || WEB: ...
 * 태그를 파싱하여 메타데이터와 순수 설명을 분리합니다.
 */
export function parseAttractionMetadata(rawDesc: string): {
  cleanDesc: string;
  subwayInfo?: string;
  openingHours?: string;
  closedDays?: string;
  officialUrl?: string;
} {
  if (!rawDesc) return { cleanDesc: "" };

  const subwayMatch = rawDesc.match(/\|\|\s*SUBWAY:\s*([^|]+)/i);
  const hoursMatch = rawDesc.match(/\|\|\s*HOURS:\s*([^|]+)/i);
  const closedMatch = rawDesc.match(/\|\|\s*CLOSED:\s*([^|]+)/i);
  const webMatch = rawDesc.match(/\|\|\s*WEB:\s*([^|]+)/i);

  // 태그 제거한 순수 설명
  const cleanDesc = rawDesc.split("||")[0].trim();

  return {
    cleanDesc,
    subwayInfo: subwayMatch ? subwayMatch[1].trim() : undefined,
    openingHours: hoursMatch ? hoursMatch[1].trim() : undefined,
    closedDays: closedMatch ? closedMatch[1].trim() : undefined,
    officialUrl: webMatch ? webMatch[1].trim() : undefined,
  };
}

export interface TourCoursePreset {
  id: string;
  cityCode: SupportedCity;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  spotIds: string[];
  estimatedHours: number;
  courseType: "AREA_ROUTE" | "CITY_HIGHLIGHT";
}

export const ATTRACTION_SPOTS_CATALOG: AttractionSpot[] = [
  // === SEOUL ===
  {
    id: "seoul_gyeongbokgung",
    cityCode: "SEOUL",
    nameKo: "경복궁 & 한복 대여 체험",
    nameEn: "Gyeongbokgung & Hanbok Rental",
    descKo: "조선 왕조의 으뜸 궁궐이자 한복 착용 시 입장료 무료",
    descEn: "Main royal palace of Joseon dynasty with free entry in Hanbok",
    price: 15000,
    priceStatus: "PAID",
    tag: "K-컬처",
    emoji: "🏯",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_nseoultower",
    cityCode: "SEOUL",
    nameKo: "N서울타워 전망대",
    nameEn: "N Seoul Tower Observatory",
    descKo: "서울 시내 전체를 360도로 한눈에 조망하는 대표 야경 랜드마크",
    descEn: "360-degree panoramic skyline view of Seoul",
    price: 21000,
    priceStatus: "PAID",
    tag: "전망/야경",
    emoji: "🗼",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_gwanghwamun",
    cityCode: "SEOUL",
    nameKo: "광화문 광장 & 청계천 산책",
    nameEn: "Gwanghwamun Square & Cheonggyecheon",
    descKo: "도심 속 탁 트인 역사 광장과 시원한 도심 개천 산책로",
    descEn: "Open historic square and relaxing urban stream walk",
    price: 0,
    priceStatus: "FREE",
    tag: "무료/휴식",
    emoji: "🏞️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_seoulsky",
    cityCode: "SEOUL",
    nameKo: "롯데월드 타워 서울스카이",
    nameEn: "Lotte World Tower Seoul Sky",
    descKo: "세계 5위 높이 초고층 타워에서 만나는 압도적 유리전망대",
    descEn: "Glass-floor observatory at the 5th tallest building in the world",
    price: 29000,
    priceStatus: "PAID",
    tag: "랜드마크",
    emoji: "🏙️",
    gradientBg: "from-sky-500/15 to-blue-600/15",
    isFeatured: true,
  },
  {
    id: "seoul_bukchon",
    cityCode: "SEOUL",
    nameKo: "북촌한옥마을 & 인사동 길",
    nameEn: "Bukchon Hanok Village & Insadong",
    descKo: "전통 한옥이 잘 보존된 600년 역사의 옛 골목길과 골동품 거리",
    descEn: "Traditional hanok alleys and cultural craft street",
    price: 0,
    priceStatus: "FREE",
    tag: "역사/문화",
    emoji: "🏘️",
    gradientBg: "from-amber-600/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "seoul_seongsu",
    cityCode: "SEOUL",
    nameKo: "성수동 팝업스토어 & 서울숲",
    nameEn: "Seongsu Pop-up Stores & Seoul Forest",
    descKo: "MZ 세대 핫플레이스 성수동 붉은벽돌 골목과 울창한 숲",
    descEn: "Trendy pop-up store district and lush city park",
    price: 0,
    priceStatus: "FREE",
    tag: "트렌드",
    emoji: "☕",
    gradientBg: "from-rose-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "seoul_hongdae",
    cityCode: "SEOUL",
    nameKo: "홍대 버스킹 거리 & 연남동 연트럴파크",
    nameEn: "Hongdae Busking & Yeonnam Park",
    descKo: "젊음과 버스킹 공연이 넘치는 문화의 거리와 선형 공원",
    descEn: "Youth culture street with live busking and park walk",
    price: 0,
    priceStatus: "FREE",
    tag: "야간/문화",
    emoji: "🎸",
    gradientBg: "from-purple-500/15 to-violet-500/15",
    isFeatured: false,
  },
  {
    id: "seoul_yeouido_hangang",
    cityCode: "SEOUL",
    nameKo: "여의도 한강공원 피크닉 & 라면",
    nameEn: "Yeouido Hangang Park Picnic",
    descKo: "한강변에서 즐기는 피크닉과 즉석 한강 라면 체험",
    descEn: "Riverfront picnic and instant K-ramyeon experience",
    price: 6000,
    priceStatus: "PAID",
    tag: "체험/휴식",
    emoji: "🍜",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
    isFeatured: false,
  },
  {
    id: "seoul_national_museum",
    cityCode: "SEOUL",
    nameKo: "국립중앙박물관 (사유의 방)",
    nameEn: "National Museum of Korea",
    descKo: "반가사유상이 모셔진 한국 최고의 국립 박물관",
    descEn: "Korea's flagship national museum featuring Room of Quiet Contemplation",
    price: 0,
    priceStatus: "FREE",
    tag: "박물관",
    emoji: "🏛️",
    gradientBg: "from-slate-500/15 to-zinc-500/15",
    isFeatured: false,
  },

  // === BUSAN ===
  {
    id: "busan_blueline",
    cityCode: "BUSAN",
    nameKo: "해운대 블루라인 해변열차",
    nameEn: "Haeundae Blueline Park Beach Train",
    descKo: "동해남부선 옛 철길을 활용한 수려한 해안 절경 코스 train",
    descEn: "Scenic coastal train ride along the Haeundae coastline",
    price: 16000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "🚃",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
  },
  {
    id: "busan_gamcheon",
    cityCode: "BUSAN",
    nameKo: "감천문화마을",
    nameEn: "Gamcheon Culture Village",
    descKo: "알록달록 산비탈 집들과 어린왕자 포토존이 매력적인 문화마을",
    descEn: "Colorful hillside village dubbed the Santorini of Busan",
    price: 0,
    priceStatus: "FREE",
    tag: "문화/포토존",
    emoji: "🎨",
    gradientBg: "from-amber-500/15 to-rose-500/15",
    isFeatured: true,
  },
  {
    id: "busan_tower",
    cityCode: "BUSAN",
    nameKo: "부산타워 & 용두산공원",
    nameEn: "Busan Tower & Yongdusan Park",
    descKo: "부산 항구와 원도심 풍경이 시원하게 펼쳐지는 전망 타워",
    descEn: "Panoramic view over Busan Port and downtown",
    price: 12000,
    priceStatus: "PAID",
    tag: "전망",
    emoji: "⚓",
    gradientBg: "from-indigo-500/15 to-blue-500/15",
    isFeatured: true,
  },
  {
    id: "busan_gwangalli",
    cityCode: "BUSAN",
    nameKo: "광안리 해수욕장 & 드론쇼",
    nameEn: "Gwangalli Beach & Drone Light Show",
    descKo: "광안대교 야경과 토요일 밤을 수놓는 환상적인 드론 라이트 쇼",
    descEn: "Gwangandaegyo bridge night view and Saturday drone show",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/해변",
    emoji: "🌉",
    gradientBg: "from-blue-600/15 to-purple-600/15",
    isFeatured: true,
  },
  {
    id: "busan_haedong",
    cityCode: "BUSAN",
    nameKo: "해동용궁사",
    nameEn: "Haedong Yonggungsa Temple",
    descKo: "파도가 철썩이는 깎아지른 바위 절벽 위에 세워진 해안 사찰",
    descEn: "Unique coastal Buddhist temple built on oceanfront cliffs",
    price: 0,
    priceStatus: "FREE",
    tag: "사찰/자연",
    emoji: "🛕",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
    isFeatured: true,
  },
  {
    id: "busan_jagalchi",
    cityCode: "BUSAN",
    nameKo: "자갈치시장 & BIFF 광장",
    nameEn: "Jagalchi Fish Market & BIFF Square",
    descKo: "부산 대표 수산시장과 씨앗호떡을 맛보는 활기찬 먹거리 거리",
    descEn: "Famous seafood market and iconic street food stalls",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🐟",
    gradientBg: "from-orange-500/15 to-amber-500/15",
    isFeatured: true,
  },

  // === JEJU ===
  {
    id: "jeju_seongsan",
    cityCode: "JEJU",
    nameKo: "성산일출봉 탐방",
    nameEn: "Seongsan Ilchulbong Tuff Cone",
    descKo: "유네스코 세계자연유산으로 지정된 해돋이 명소 화산구",
    descEn: "UNESCO World Natural Heritage volcanic tuff cone",
    price: 5000,
    priceStatus: "PAID",
    tag: "유네스코자연",
    emoji: "🌋",
    gradientBg: "from-emerald-600/15 to-green-600/15",
    isFeatured: true,
  },
  {
    id: "jeju_udo",
    cityCode: "JEJU",
    nameKo: "우도 도항선 & 전기차 투어",
    nameEn: "Udo Island Ferry & Electric Bike",
    descKo: "에메랄드빛 바다와 땅콩 아이스크림이 기다리는 섬 속의 섬",
    descEn: "Island off Jeju famous for turquoise waters and peanut ice cream",
    price: 10500,
    priceStatus: "PAID",
    tag: "섬투어/액티비티",
    emoji: "🏝️",
    gradientBg: "from-cyan-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "jeju_hyeopjae",
    cityCode: "JEJU",
    nameKo: "협재 해수욕장 & 비양도 전망",
    nameEn: "Hyeopjae Beach & Biyangdo",
    descKo: "투명한 모래사장에서 바라보는 비양도와 푸른 바다",
    descEn: "Pristine sandy beach looking out to Biyangdo Island",
    price: 0,
    priceStatus: "FREE",
    tag: "해변/휴식",
    emoji: "🏖️",
    gradientBg: "from-sky-500/15 to-blue-400/15",
    isFeatured: true,
  },
  {
    id: "jeju_snoopy",
    cityCode: "JEJU",
    nameKo: "스누피가든 체험",
    nameEn: "Snoopy Garden Jeju",
    descKo: "제주의 자연 오름과 스누피 테마가 어우러진 넓은 감성 정원",
    descEn: "Charming Peanuts-themed indoor & outdoor botanical garden",
    price: 18000,
    priceStatus: "PAID",
    tag: "테마파크",
    emoji: "🐶",
    gradientBg: "from-yellow-500/15 to-orange-400/15",
    isFeatured: true,
  },
  {
    id: "jeju_dongmun",
    cityCode: "JEJU",
    nameKo: "동문재래시장 야시장",
    nameEn: "Dongmun Traditional Night Market",
    descKo: "제주 특산물과 야시장 푸드트럭 먹거리가 가득한 대형 시장",
    descEn: "Vibrant traditional market famous for street food and citrus",
    price: 0,
    priceStatus: "FREE",
    tag: "야시장",
    emoji: "🍊",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "jeju_arte",
    cityCode: "JEJU",
    nameKo: "아르떼뮤지엄 제주",
    nameEn: "Arte Museum Jeju",
    descKo: "빛과 소리가 선사하는 몰입형 미디어아트 전시관",
    descEn: "Immersive media art exhibition hall presenting nature themes",
    price: 17000,
    priceStatus: "PAID",
    tag: "미디어아트",
    emoji: "🎨",
    gradientBg: "from-purple-600/15 to-pink-600/15",
    isFeatured: true,
  },

  // === INCHEON ===
  {
    id: "incheon_chinatown",
    cityCode: "INCHEON",
    nameKo: "인천 차이나타운 & 송월동 동화마을",
    nameEn: "Incheon Chinatown & Fairy Tale Village",
    descKo: "짜장면의 본고장이자 아기자기한 동화 벽화 거리",
    descEn: "Birthplace of Jajangmyeon and colorful fairytale street art",
    price: 0,
    priceStatus: "FREE",
    tag: "문화/음식",
    emoji: "🏮",
    gradientBg: "from-red-500/15 to-amber-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_songdo_central",
    cityCode: "INCHEON",
    nameKo: "송도 센트럴파크 수상택시",
    nameEn: "Songdo Central Park Water Taxi",
    descKo: "미래도시 빌딩 숲 사이 해수로에서 즐기는 보트 체험",
    descEn: "Scenic boat ride along seawater canal in futuristic Songdo",
    price: 5000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "⛵",
    gradientBg: "from-blue-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_wolmi_myland",
    cityCode: "INCHEON",
    nameKo: "월미도 마이랜드 디스코팡팡",
    nameEn: "Wolmido MyLand Theme Park",
    descKo: "바닷가 월미문화의거리와 유쾌한 놀이기구 체험",
    descEn: "Waterfront amusement rides and lively sea walkway",
    price: 6000,
    priceStatus: "PAID",
    tag: "놀이공원",
    emoji: "🎡",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_openport",
    cityCode: "INCHEON",
    nameKo: "개항장 근대역사거리",
    nameEn: "Open Port Modern History Street",
    descKo: "19세기 근대 건축물들이 잘 보존된 역사적인 가쿠라 거리",
    descEn: "Historic district with preserved 19th-century architecture",
    price: 0,
    priceStatus: "FREE",
    tag: "역사",
    emoji: "🏛️",
    gradientBg: "from-amber-600/15 to-stone-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_triple_street",
    cityCode: "INCHEON",
    nameKo: "송도 트리플스트리트",
    nameEn: "Songdo Triple Street",
    descKo: "쇼핑과 문화, 프리미엄 다이닝이 정돈된 복합 문화 공간",
    descEn: "Modern lifestyle and shopping complex in Songdo",
    price: 0,
    priceStatus: "FREE",
    tag: "쇼핑",
    emoji: "🛍️",
    gradientBg: "from-pink-500/15 to-rose-500/15",
    isFeatured: true,
  },
  {
    id: "incheon_incheon_bridge",
    cityCode: "INCHEON",
    nameKo: "인천대교 전망대 (오션스코프)",
    nameEn: "Incheon Bridge Observatory",
    descKo: "서해 바다와 웅장한 인천대교의 일몰을 바라보는 야경 명소",
    descEn: "Sunset and ocean views overlooking Incheon Grand Bridge",
    price: 0,
    priceStatus: "FREE",
    tag: "일몰/전망",
    emoji: "🌅",
    gradientBg: "from-orange-500/15 to-yellow-500/15",
    isFeatured: true,
  },

  // === SUWON ===
  {
    id: "suwon_fortress",
    cityCode: "SUWON",
    nameKo: "수원화성 성곽길 산책",
    nameEn: "Suwon Hwaseong Fortress Wall Walk",
    descKo: "정조 대왕의 효심과 조선 과학기술의 정수가 담긴 성곽길",
    descEn: "UNESCO World Heritage fortress wall offering scenic walks",
    price: 0,
    priceStatus: "FREE",
    tag: "유네스코 유산",
    emoji: "🏯",
    gradientBg: "from-emerald-600/15 to-teal-600/15",
    isFeatured: true,
  },
  {
    id: "suwon_haenggung",
    cityCode: "SUWON",
    nameKo: "화성행궁 관람",
    nameEn: "Hwaseong Haenggung Palace",
    descKo: "조선 시대 왕이 지방에 머물던 궁궐 중 가장 크고 웅장한 곳",
    descEn: "Largest temporary palace used by Joseon Dynasty Kings",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "👑",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
    isFeatured: true,
  },
  {
    id: "suwon_haengnidan",
    cityCode: "SUWON",
    nameKo: "행리단길 카페거리",
    nameEn: "Haengnidan-gil Cafe Street",
    descKo: "옛 한옥과 감성 카페, 소품샵들이 성벽 아래 밀집한 골목",
    descEn: "Charming alleyways packed with boutique cafes near fortress walls",
    price: 0,
    priceStatus: "FREE",
    tag: "카페/트렌드",
    emoji: "☕",
    gradientBg: "from-orange-500/15 to-amber-400/15",
    isFeatured: true,
  },
  {
    id: "suwon_flying_suwon",
    cityCode: "SUWON",
    nameKo: "플라잉수원 열기구 체험",
    nameEn: "Flying Suwon Hot Air Balloon",
    descKo: "150m 상공에서 수원화성의 야경을 조망하는 계류식 열기구",
    descEn: "Tethered helium balloon ride overlooking Suwon at night",
    price: 20000,
    priceStatus: "PAID",
    tag: "액티비티/야경",
    emoji: "🎈",
    gradientBg: "from-sky-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "suwon_starfield",
    cityCode: "SUWON",
    nameKo: "스타필드 수원 별마당 도서관",
    nameEn: "Starfield Suwon Byeolmadang Library",
    descKo: "웅장한 행성 구조물과 초대형 서가가 돋보이는 랜드마크 도서관",
    descEn: "Massive iconic multi-story open library inside Starfield mall",
    price: 0,
    priceStatus: "FREE",
    tag: "랜드마크",
    emoji: "📚",
    gradientBg: "from-blue-600/15 to-purple-600/15",
    isFeatured: true,
  },
  {
    id: "suwon_chicken_street",
    cityCode: "SUWON",
    nameKo: "수원 통닭거리",
    nameEn: "Suwon Chicken Street",
    descKo: "가마솥에서 튀겨내는 전통 통닭과 왕갈비통닭 명물 거리",
    descEn: "Famous street dedicated to traditional cauldron-fried chicken",
    price: 0,
    priceStatus: "FREE",
    tag: "미식",
    emoji: "🍗",
    gradientBg: "from-amber-600/15 to-orange-500/15",
    isFeatured: true,
  },

  // === JEONJU ===
  {
    id: "jeonju_hanok_village",
    cityCode: "JEONJU",
    nameKo: "전주 한옥마을 산책",
    nameEn: "Jeonju Hanok Village",
    descKo: "700여 채의 한옥이 모여있는 한국 대표 슬로시티 한옥마을",
    descEn: "Traditional Hanok Village with 700+ preserved Korean houses",
    price: 0,
    priceStatus: "FREE",
    tag: "한옥/문화",
    emoji: "🏠",
    gradientBg: "from-amber-600/15 to-stone-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_gyeonggijeon",
    cityCode: "JEONJU",
    nameKo: "경기전 (태조 이성계 어진)",
    nameEn: "Gyeonggijeon Shrine",
    descKo: "조선 태조 이성계의 초상화가 모셔진 역사 깊은 성지",
    descEn: "Historic shrine housing the official portrait of King Taejo",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "📜",
    gradientBg: "from-red-500/15 to-amber-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_jammanyi",
    cityCode: "JEONJU",
    nameKo: "자만벽화마을",
    nameEn: "Jaman Mural Village",
    descKo: "한옥마을 맞은편 언덕길을 따라 이어지는 귀여운 벽화 거리",
    descEn: "Hillside art village filled with anime & colorful murals",
    price: 0,
    priceStatus: "FREE",
    tag: "포토존",
    emoji: "🖼️",
    gradientBg: "from-pink-500/15 to-purple-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_jeondong",
    cityCode: "JEONJU",
    nameKo: "전동성당",
    nameEn: "Jeondong Cathedral",
    descKo: "호남 지역 최초의 로마네스크 양식 아름다운 성당",
    descEn: "Stunning 1914 Romanesque cathedral at entrance of Hanok Village",
    price: 0,
    priceStatus: "FREE",
    tag: "건축",
    emoji: "⛪",
    gradientBg: "from-slate-500/15 to-blue-500/15",
    isFeatured: true,
  },
  {
    id: "jeonju_traditional_wine",
    cityCode: "JEONJU",
    nameKo: "전주 모주 시음 & 한식 체험",
    nameEn: "Jeonju Moju Tasting & Food",
    descKo: "은은한 계피향 모주와 비빔밥 파전의 참맛 체험",
    descEn: "Tasting local traditional herbal rice wine (Moju) with Pajeon",
    price: 8000,
    priceStatus: "PAID",
    tag: "미식체험",
    emoji: "🍶",
    gradientBg: "from-amber-700/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "jeonju_deokjin",
    cityCode: "JEONJU",
    nameKo: "덕진공원 연꽃 자전거",
    nameEn: "Deokjin Park Lotus Pond",
    descKo: "여름철 연꽃이 장관을 이루는 도심 속 전통 호수 공원",
    descEn: "Traditional park centered around a historic lotus pond",
    price: 0,
    priceStatus: "FREE",
    tag: "자연/공원",
    emoji: "🪷",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },

  // === GYEONGJU ===
  {
    id: "gyeongju_bulguksa",
    cityCode: "GYEONGJU",
    nameKo: "불국사 & 석굴암",
    nameEn: "Bulguksa Temple & Seokguram Grotto",
    descKo: "신라 불교 예술의 최고봉인 유네스코 세계문화유산 사찰",
    descEn: "Masterpiece of Buddhist art and UNESCO World Heritage",
    price: 0,
    priceStatus: "FREE",
    tag: "유네스코 유산",
    emoji: "🛕",
    gradientBg: "from-amber-600/15 to-yellow-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_donggung",
    cityCode: "GYEONGJU",
    nameKo: "동궁과 월지 (안압지 야경)",
    nameEn: "Donggung Palace & Wolji Pond",
    descKo: "신라 왕족의 안압지 연못에 비치는 신비로운 야경 명소",
    descEn: "Breathtaking illuminated reflection night view over the Royal Pond",
    price: 3000,
    priceStatus: "PAID",
    tag: "야경/사적",
    emoji: "🌙",
    gradientBg: "from-indigo-600/15 to-purple-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_cheomseongdae",
    cityCode: "GYEONGJU",
    nameKo: "첨성대 & 대릉원 숲",
    nameEn: "Cheomseongdae Observatory & Daereungwon",
    descKo: "동양에서 가장 오래된 천문대와 신라 거대 왕릉 군락",
    descEn: "East Asia's oldest astronomical observatory and ancient royal tombs",
    price: 4000,
    priceStatus: "PAID",
    tag: "역사/유적",
    emoji: "🌌",
    gradientBg: "from-emerald-600/15 to-green-500/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_hwangnidan",
    cityCode: "GYEONGJU",
    nameKo: "황리단길 십원빵 & 한옥카페",
    nameEn: "Hwangnidan-gil Street",
    descKo: "경주 최고의 핫플레이스 한옥 카페와 십원빵 먹거리 거리",
    descEn: "Trendy Hanok street famous for 10-won cheese bread and cafes",
    price: 3500,
    priceStatus: "PAID",
    tag: "트렌드/미식",
    emoji: "🪙",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_national_museum",
    cityCode: "GYEONGJU",
    nameKo: "국립경주박물관 (성덕대왕신종)",
    nameEn: "Gyeongju National Museum",
    descKo: "신라 금관과 에밀레종의 울림을 전하는 박물관",
    descEn: "Houses Silla golden crowns and the Divine Bell of King Seongdeok",
    price: 0,
    priceStatus: "FREE",
    tag: "박물관",
    emoji: "🔔",
    gradientBg: "from-yellow-600/15 to-amber-600/15",
    isFeatured: true,
  },
  {
    id: "gyeongju_woljeonggyo",
    cityCode: "GYEONGJU",
    nameKo: "월정교 야간 산책",
    nameEn: "Woljeonggyo Bridge Night Walk",
    descKo: "남천 위로 복원된 웅장하고 화려한 신라 왕경 누교",
    descEn: "Magnificently restored wooden bridge with brilliant night lights",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/교량",
    emoji: "🌉",
    gradientBg: "from-rose-500/15 to-red-500/15",
    isFeatured: true,
  },

  // === GANGNEUNG ===
  {
    id: "gangneung_anmok",
    cityCode: "GANGNEUNG",
    nameKo: "안목해변 커피거리",
    nameEn: "Anmok Beach Coffee Street",
    descKo: "동해 바다를 바라보며 커피 한 잔의 여유를 즐기는 해변",
    descEn: "Famous seaside strip packed with ocean-view cafes",
    price: 0,
    priceStatus: "FREE",
    tag: "카페/해변",
    emoji: "☕",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_haslla",
    cityCode: "GANGNEUNG",
    nameKo: "하슬라아트월드",
    nameEn: "Haslla Art World",
    descKo: "동해 바다가 시원하게 건너다뵈는 조각공원과 포토존 뮤지엄",
    descEn: "Oceanfront contemporary sculpture park and art museum",
    price: 17000,
    priceStatus: "PAID",
    tag: "미술관/포토존",
    emoji: "🎨",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_arte",
    cityCode: "GANGNEUNG",
    nameKo: "아르떼뮤지엄 강릉",
    nameEn: "Arte Museum Gangneung",
    descKo: "경포호 인근 백두대간과 자연의 빛을 담은 미디어아트",
    descEn: "Immersive nature-themed media art exhibition hall near Gyeongpo",
    price: 17000,
    priceStatus: "PAID",
    tag: "미디어아트",
    emoji: "✨",
    gradientBg: "from-indigo-600/15 to-sky-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_gyeongpo",
    cityCode: "GANGNEUNG",
    nameKo: "경포호 자전거 순환 산책",
    nameEn: "Gyeongpo Lake Bike Ride",
    descKo: "잔잔한 호수를 둘러싼 가로수길과 경포대 루프",
    descEn: "Scenic lakefront bicycle path and historical pavilion",
    price: 5000,
    priceStatus: "PAID",
    tag: "자연/액티비티",
    emoji: "🚲",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "gangneung_ojukheon",
    cityCode: "GANGNEUNG",
    nameKo: "오죽헌 (신사임당 & 율곡 이이)",
    nameEn: "Ojukheon House",
    descKo: "오색 검은 대나무가 둘러싸인 한국에서 가장 오래된 목조건물 중 하나",
    descEn: "Birthplace of Shin Saimdang and Yulgok Yi I amidst black bamboo",
    price: 3000,
    priceStatus: "PAID",
    tag: "역사",
    emoji: "🎋",
    gradientBg: "from-green-600/15 to-emerald-600/15",
    isFeatured: true,
  },
  {
    id: "gangneung_central_market",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 중앙시장 닭강정",
    nameEn: "Gangneung Central Market",
    descKo: "배 오징어순대와 닭강정 등 먹거리 천국 전통시장",
    descEn: "Traditional market famous for crispy fried chicken and stuffed squid",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🍗",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },

  // === SOKCHO ===
  {
    id: "sokcho_cablecar",
    cityCode: "SOKCHO",
    nameKo: "설악산 국립공원 케이블카",
    nameEn: "Seoraksan National Park Cable Car",
    descKo: "권금성 정상까지 케이블카로 오르며 감상하는 설악산 기암괴석",
    descEn: "Cable car ride up to Gwongeumseong Fortress in Seoraksan",
    price: 15000,
    priceStatus: "PAID",
    tag: "자연/액티비티",
    emoji: "⛰️",
    gradientBg: "from-emerald-600/15 to-teal-600/15",
    isFeatured: true,
  },
  {
    id: "sokcho_abai",
    cityCode: "SOKCHO",
    nameKo: "속초 아바이마을 갯배 체험",
    nameEn: "Abai Village Gaetbae Boat",
    descKo: "줄을 끌어 수로를 건너는 손맛 갯배 체험과 순대 마을",
    descEn: "Unique hand-pulled ferry boat experience to Abai Village",
    price: 1000,
    priceStatus: "PAID",
    tag: "체험",
    emoji: "⛵",
    gradientBg: "from-blue-500/15 to-cyan-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_sokchoeye",
    cityCode: "SOKCHO",
    nameKo: "속초아이 대관람차",
    nameEn: "Sokcho Eye Ferris Wheel",
    descKo: "속초 해수욕장 정중앙에서 동해바다를 내려다보는 초대형 관람차",
    descEn: "Giant Ferris wheel right on Sokcho Beach with sea views",
    price: 12000,
    priceStatus: "PAID",
    tag: "랜드마크",
    emoji: "🎡",
    gradientBg: "from-sky-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_yeonggeumjeong",
    cityCode: "SOKCHO",
    nameKo: "영금정 해돋이 정자",
    nameEn: "Yeonggeumjeong Pavilion",
    descKo: "바다 위 돌산 정자에서 듣는 거문고 소리 같은 파도 소리",
    descEn: "Seaside pavilion over ocean rocks with sunrise views",
    price: 0,
    priceStatus: "FREE",
    tag: "일출/자연",
    emoji: "🌅",
    gradientBg: "from-orange-500/15 to-rose-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_tourist_market",
    cityCode: "SOKCHO",
    nameKo: "속초 관광수산시장",
    nameEn: "Sokcho Tourist & Fishery Market",
    descKo: "만석닭강정, 씨앗호떡, 감자옹심이가 줄짓는 먹거리 시장",
    descEn: "Bustling market renowned for fried chicken and potato dumplings",
    price: 0,
    priceStatus: "FREE",
    tag: "전통시장",
    emoji: "🦀",
    gradientBg: "from-amber-600/15 to-yellow-500/15",
    isFeatured: true,
  },
  {
    id: "sokcho_cheongchoho",
    cityCode: "SOKCHO",
    nameKo: "청초호 호수공원 엑스포타워",
    nameEn: "Cheongchoho Lake Park Tower",
    descKo: "호수와 바다가 조화를 이루는 청초호 산책로",
    descEn: "Lakeside park with observatory tower overlook",
    price: 2500,
    priceStatus: "PAID",
    tag: "산책/전망",
    emoji: "🏙️",
    gradientBg: "from-blue-600/15 to-indigo-600/15",
    isFeatured: true,
  },

  // === YEOSU ===
  {
    id: "yeosu_marine_cablecar",
    cityCode: "YEOSU",
    nameKo: "여수 해양케이블카 (크리스탈)",
    nameEn: "Yeosu Maritime Cable Car",
    descKo: "바다 위를 지나 섬과 육지를 연결하는 투명 바닥 케이블카",
    descEn: "Cable car connecting mainland to Dolsan with glass floor cabin",
    price: 22000,
    priceStatus: "PAID",
    tag: "액티비티/전망",
    emoji: "🚠",
    gradientBg: "from-blue-500/15 to-teal-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_odongdo",
    cityCode: "YEOSU",
    nameKo: "오동도 동백열차 & 등대",
    nameEn: "Odongdo Island Camellia Train",
    descKo: "동백꽃 섬 오동도로 향하는 방파제 길과 숲 산책로",
    descEn: "Breakwater walk and camellia forest path on Odongdo",
    price: 1000,
    priceStatus: "PAID",
    tag: "자연/섬",
    emoji: "🌺",
    gradientBg: "from-rose-500/15 to-pink-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_night_sea",
    cityCode: "YEOSU",
    nameKo: "여수 밤바다 낭만포차",
    nameEn: "Yeosu Romantic Pocha Street",
    descKo: "돌산대교 야경을 바다 건너 바라보는 분위기 있는 해변 포차",
    descEn: "Iconic oceanfront street food stalls under illuminated bridges",
    price: 0,
    priceStatus: "FREE",
    tag: "야경/미식",
    emoji: "🌃",
    gradientBg: "from-purple-600/15 to-indigo-600/15",
    isFeatured: true,
  },
  {
    id: "yeosu_hyangiram",
    cityCode: "YEOSU",
    nameKo: "향일암 해돋이 절경",
    nameEn: "Hyangiram Hermitage",
    descKo: "해를 향하는 암자라는 뜻으로 기암절벽 해돋이로 이름난 암자",
    descEn: "Famous cliffside hermitage known for magnificent sunrises",
    price: 2000,
    priceStatus: "PAID",
    tag: "사찰/일출",
    emoji: "🌅",
    gradientBg: "from-amber-500/15 to-orange-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_laon_railbike",
    cityCode: "YEOSU",
    nameKo: "여수 해양레일바이크",
    nameEn: "Yeosu Ocean Railbike",
    descKo: "전 구간 바다를 조망하며 시원한 터널을 달리는 해안 레일바이크",
    descEn: "Oceanfront railbike track passing scenic coastal tunnels",
    price: 13000,
    priceStatus: "PAID",
    tag: "액티비티",
    emoji: "🚲",
    gradientBg: "from-cyan-500/15 to-blue-500/15",
    isFeatured: true,
  },
  {
    id: "yeosu_yeosu_expo",
    cityCode: "YEOSU",
    nameKo: "여수 엑스포 빅오쇼 (Big-O)",
    nameEn: "Yeosu Expo Big-O Show",
    descKo: "화려한 분수쇼와 멀티미디어 해양 문화 분수 퍼포먼스",
    descEn: "Spectacular ocean fountain light show at Expo Park",
    price: 18000,
    priceStatus: "PAID",
    tag: "공연/멀티미디어",
    emoji: "🎆",
    gradientBg: "from-violet-600/15 to-purple-600/15",
    isFeatured: true,
  },
];

export const TOUR_COURSE_PRESETS: TourCoursePreset[] = [
  // === SEOUL (AREA_ROUTE) ===
  {
    id: "seoul_course_heritage",
    cityCode: "SEOUL",
    nameKo: "궁궐·북촌·인사동 코스",
    nameEn: "Palace, Bukchon & Insadong Course",
    descKo: "경복궁 한복 체험부터 북촌 한옥 골목과 인사동 문화거리 도보 투어",
    descEn: "Traditional walk: Gyeongbokgung palace entry, hanok village & Insadong",
    spotIds: ["seoul_gyeongbokgung", "seoul_bukchon", "seoul_gwanghwamun"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_trend",
    cityCode: "SEOUL",
    nameKo: "성수·서울숲 문화 코스",
    nameEn: "Seongsu & Seoul Forest Culture Course",
    descKo: "MZ 핫플 성수동 팝업스토어 탐방과 울창한 서울숲 산책",
    descEn: "Hipster Seongsu pop-up stores & relaxing Seoul Forest walk",
    spotIds: ["seoul_seongsu"],
    estimatedHours: 3,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_night",
    cityCode: "SEOUL",
    nameKo: "홍대·연남 야간 코스",
    nameEn: "Hongdae & Yeonnam Night Course",
    descKo: "거리 버스킹과 연트럴파크 산책, 밤이 더 뜨거운 청춘 거리 투어",
    descEn: "Live street busking, Yeonnam park stroll & youth nightlife",
    spotIds: ["seoul_hongdae"],
    estimatedHours: 3,
    courseType: "AREA_ROUTE",
  },
  {
    id: "seoul_course_river",
    cityCode: "SEOUL",
    nameKo: "여의도·한강 저녁 코스",
    nameEn: "Yeouido & Riverfront Sunset Course",
    descKo: "한강 피크닉 라면 체험과 N서울타워 전망대에서 감상하는 서울 야경",
    descEn: "Riverfront picnic ramyeon & panoramic night lights from N Seoul Tower",
    spotIds: ["seoul_yeouido_hangang", "seoul_nseoultower"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },

  // === BUSAN (AREA_ROUTE) ===
  {
    id: "busan_course_coast",
    cityCode: "BUSAN",
    nameKo: "해운대·청사포 해안 코스",
    nameEn: "Haeundae & Cheongsapo Coastal Course",
    descKo: "블루라인 해변열차를 타고 동해 바다절경과 용궁사를 탐방하는 해안 코스",
    descEn: "Blueline beach train ride & oceanfront Haedong Yonggungsa temple",
    spotIds: ["busan_blueline", "busan_haedong"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "busan_course_culture",
    cityCode: "BUSAN",
    nameKo: "감천·남포 문화 코스",
    nameEn: "Gamcheon & Nampo Culture Course",
    descKo: "알록달록 산비탈 감천마을과 자갈치 수산시장, 부산타워 전망대",
    descEn: "Colorful Gamcheon hillside village, Jagalchi market & Busan Tower",
    spotIds: ["busan_gamcheon", "busan_jagalchi", "busan_tower"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "busan_course_gwangalli",
    cityCode: "BUSAN",
    nameKo: "광안리 야간 코스",
    nameEn: "Gwangalli Night Beach Course",
    descKo: "광안대교 야경과 토요일 해변 드론 라이트 쇼 감상 코스",
    descEn: "Gwangandi bridge night lights & Saturday drone light show",
    spotIds: ["busan_gwangalli"],
    estimatedHours: 2,
    courseType: "AREA_ROUTE",
  },

  // === JEJU (AREA_ROUTE) ===
  {
    id: "jeju_course_east",
    cityCode: "JEJU",
    nameKo: "동부 성산·우도 코스",
    nameEn: "Eastern Seongsan & Udo Island Course",
    descKo: "성산일출봉 등반과 우도 도항선 섬 투어로 즐기는 제주의 동쪽 바다",
    descEn: "Seongsan tuff cone climb & Udo island ferry scenic tour",
    spotIds: ["jeju_seongsan", "jeju_udo"],
    estimatedHours: 5,
    courseType: "AREA_ROUTE",
  },
  {
    id: "jeju_course_west",
    cityCode: "JEJU",
    nameKo: "서부 협재·애월 코스",
    nameEn: "Western Hyeopjae & Aewol Course",
    descKo: "투명한 에메랄드빛 협재 바다와 스누피가든 감성 야외 정원",
    descEn: "Clear turquoise Hyeopjae beach & Snoopy Garden Jeju",
    spotIds: ["jeju_hyeopjae", "jeju_snoopy"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },
  {
    id: "jeju_course_city",
    cityCode: "JEJU",
    nameKo: "제주시 도심·아트 코스",
    nameEn: "Jeju City & Media Art Course",
    descKo: "아르떼뮤지엄 빛의 미디어아트와 동문재래시장 야시장 미식 투어",
    descEn: "Arte Museum immersive media art & Dongmun night market food",
    spotIds: ["jeju_arte", "jeju_dongmun"],
    estimatedHours: 4,
    courseType: "AREA_ROUTE",
  },

  // === INCHEON (CITY_HIGHLIGHT) ===
  {
    id: "incheon_course_highlight",
    cityCode: "INCHEON",
    nameKo: "인천 개항장 & 송도 미래도시 대표 코스",
    nameEn: "Incheon Open Port & Songdo Highlights",
    descKo: "차이나타운과 개항장 근대거리부터 송도 센트럴파크 수상택시까지",
    descEn: "Chinatown historic walk & Songdo futuristic Central Park water taxi",
    spotIds: ["incheon_chinatown", "incheon_songdo_central", "incheon_openport"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === SUWON (CITY_HIGHLIGHT) ===
  {
    id: "suwon_course_highlight",
    cityCode: "SUWON",
    nameKo: "수원화성 & 행리단길 대표 코스",
    nameEn: "Suwon Hwaseong & Haengnidan Highlights",
    descKo: "세계유산 수원화성 성곽 산책, 화성행궁 관람 및 행리단길 감성 카페",
    descEn: "Hwaseong Fortress walk, Haenggung Palace & Haengnidan cafe alley",
    spotIds: ["suwon_fortress", "suwon_haenggung", "suwon_haengnidan"],
    estimatedHours: 4,
    courseType: "CITY_HIGHLIGHT",
  },

  // === JEONJU (CITY_HIGHLIGHT) ===
  {
    id: "jeonju_course_highlight",
    cityCode: "JEONJU",
    nameKo: "전주 한옥마을 대표 코스",
    nameEn: "Jeonju Hanok Village Highlights",
    descKo: "경기전 어진 관람, 자만벽화마을과 전동성당, 모주 시음 슬로시티 투어",
    descEn: "Gyeonggijeon shrine, Jaman murals, Jeondong cathedral & Moju tasting",
    spotIds: ["jeonju_hanok_village", "jeonju_gyeonggijeon", "jeonju_jammanyi", "jeonju_traditional_wine"],
    estimatedHours: 4,
    courseType: "CITY_HIGHLIGHT",
  },

  // === GYEONGJU (CITY_HIGHLIGHT) ===
  {
    id: "gyeongju_course_highlight",
    cityCode: "GYEONGJU",
    nameKo: "신라 천년 역사 & 야경 대표 코스",
    nameEn: "Gyeongju Ancient Heritage & Night View Highlights",
    descKo: "불국사와 첨성대·대릉원 산책 후 동궁과 월지의 환상적인 야경 감상",
    descEn: "Bulguksa Temple, Cheomseongdae observatory & Donggung Palace night view",
    spotIds: ["gyeongju_bulguksa", "gyeongju_cheomseongdae", "gyeongju_donggung", "gyeongju_hwangnidan"],
    estimatedHours: 6,
    courseType: "CITY_HIGHLIGHT",
  },

  // === GANGNEUNG (CITY_HIGHLIGHT) ===
  {
    id: "gangneung_course_highlight",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 바다 & 커피 대표 코스",
    nameEn: "Gangneung Beach & Coffee Highlights",
    descKo: "안목해변 커피거리, 오죽헌 역사 탐방과 하슬라아트월드 미디어아트",
    descEn: "Anmok coffee street, Ojukheon house & Haslla Art World museum",
    spotIds: ["gangneung_anmok", "gangneung_ojukheon", "gangneung_haslla"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === SOKCHO (CITY_HIGHLIGHT) ===
  {
    id: "sokcho_course_highlight",
    cityCode: "SOKCHO",
    nameKo: "설악산 & 속초 바다 대표 코스",
    nameEn: "Seoraksan & Sokcho Sea Highlights",
    descKo: "설악산 케이블카 단풍·기암 조망과 아바이마을 갯배, 속초관광수산시장",
    descEn: "Seoraksan cable car, Abai village gaetbae boat & tourist market",
    spotIds: ["sokcho_cablecar", "sokcho_abai", "sokcho_tourist_market"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },

  // === YEOSU (CITY_HIGHLIGHT) ===
  {
    id: "yeosu_course_highlight",
    cityCode: "YEOSU",
    nameKo: "여수 해양 케이블카 & 밤바다 대표 코스",
    nameEn: "Yeosu Maritime Cable Car & Night Sea Highlights",
    descKo: "투명 해양케이블카 조망과 오동도 동백길, 낭만포차 밤바다 야경",
    descEn: "Maritime cable car over sea, Odongdo island walk & romantic pocha street",
    spotIds: ["yeosu_marine_cablecar", "yeosu_odongdo", "yeosu_night_sea"],
    estimatedHours: 5,
    courseType: "CITY_HIGHLIGHT",
  },
];

/**
 * DB(Supabase) 또는 외부 API에서 불러온 최신 동적 관광지 목록을 카탈로그에 동기화합니다.
 */
export function registerCustomAttractionSpots(spots: (AttractionSpot & { imageUrl?: string; deepLink?: string })[]) {
  const existingMap = new Map(ATTRACTION_SPOTS_CATALOG.map((s, idx) => [s.id, idx]));
  spots.forEach((s) => {
    if (existingMap.has(s.id)) {
      ATTRACTION_SPOTS_CATALOG[existingMap.get(s.id)!] = s;
    } else {
      ATTRACTION_SPOTS_CATALOG.push(s);
      existingMap.set(s.id, ATTRACTION_SPOTS_CATALOG.length - 1);
    }
  });
}

