import { SupportedCity } from "../../../lib/trip-domain";
import { FoodItemDefinition } from "../domain/types";

// =========================================================================
// 1. 🇰🇷 한국 대표 미식 (National K-Signature 24선)
// =========================================================================
export const NATIONAL_K_FOODS: FoodItemDefinition[] = [
  // --- [그룹 1: ★ 방한 외국인 최선호 4대 시그니처] ---
  {
    id: "nat_samgyeopsal",
    scope: "NATIONAL",
    nameKo: "삼겹살",
    nameEn: "Samgyeopsal (Grilled Pork Belly)",
    descKo: "신선한 돼지 삼겹살을 노릇하게 구워 쌈채소, 쌈장, 마늘과 곁들여 먹는 한국의 대표 구이 요리",
    descEn: "Thick slices of fresh pork belly grilled at the table, wrapped in lettuce leaves with savory ssamjang and garlic",
    categoryTag: "BBQ_FEAST",
    unitPriceKrw: 18000,
    priceMinKrw: 16000,
    priceMaxKrw: 22000,
    isMustEatTop3: true,
    emoji: "🥩",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/5360cac5-b787-4463-b04d-ac48429b5a67/it11",
  },
  {
    id: "nat_chimaek",
    scope: "NATIONAL",
    nameKo: "치킨",
    nameEn: "Korean Fried Chicken",
    descKo: "바삭하게 튀겨낸 후라이드치킨과 매콤달콤한 특제 양념치킨을 시원한 맥주와 함께 즐기는 국민 야식",
    descEn: "Crispy Korean double-fried chicken and sweet-spicy glazed chicken, traditionally enjoyed with cold draft beer",
    categoryTag: "MEAL",
    unitPriceKrw: 23000,
    priceMinKrw: 20000,
    priceMaxKrw: 27000,
    isMustEatTop3: true,
    emoji: "🍗",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=f9d253d5-e4f6-4e43-8235-1550d8e3773f",
  },
  {
    id: "nat_bulgogi",
    scope: "NATIONAL",
    nameKo: "불고기",
    nameEn: "Bulgogi (Marinated Beef BBQ)",
    descKo: "얇게 저민 소고기를 간장, 배, 양파를 넣은 달콤 짭조름한 특제 양념에 재워 구워낸 궁중 전통 요리",
    descEn: "Thinly sliced tender beef marinated in a sweet and savory soy, garlic, and pear sauce, grilled with fresh scallions and mushrooms",
    categoryTag: "MEAL",
    unitPriceKrw: 20000,
    priceMinKrw: 17000,
    priceMaxKrw: 25000,
    isMustEatTop3: true,
    emoji: "🥘",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/7b549ce5-ff43-45ff-a7ff-2f678f028441/it11",
  },
  {
    id: "nat_bibimbap",
    scope: "NATIONAL",
    nameKo: "비빔밥",
    nameEn: "Bibimbap (Mixed Rice Bowl with Vegetables)",
    descKo: "따뜻한 밥 위에 제철 나물, 볶은 고기, 계란을 얹어 고추장과 참기름으로 비벼 먹는 전통 음식",
    descEn: "Warm white rice topped with seasoned mountain vegetables, sauteed beef, egg, aromatic sesame oil, and spicy gochujang paste",
    categoryTag: "MEAL",
    unitPriceKrw: 11000,
    priceMinKrw: 9000,
    priceMaxKrw: 14000,
    isMustEatTop3: false,
    emoji: "🥗",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/12eaf037-1510-4b4d-a11c-e73860653812/it11",
  },

  // --- [그룹 2: 🥩 고기 요리 & 한상차림] ---
  {
    id: "nat_sogalbijjim",
    scope: "NATIONAL",
    nameKo: "갈비찜",
    nameEn: "Galbi-jjim (Braised Short Ribs)",
    descKo: "두툼한 갈비에 간장, 꿀, 밤, 대추, 버섯을 넣고 살이 부드럽게 떨어질 때까지 정성스레 졸여낸 한국 전통 찜 요리",
    descEn: "Tender, melt-in-the-mouth short ribs braised in sweet soy sauce with chestnuts, dates, and shiitake mushrooms",
    categoryTag: "MEAL",
    unitPriceKrw: 20000,
    priceMinKrw: 17000,
    priceMaxKrw: 26000,
    isMustEatTop3: false,
    emoji: "🥩",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/0af3cdf7-4080-4220-a377-1989070537f1/it11",
  },
  {
    id: "nat_dakgalbi",
    scope: "NATIONAL",
    nameKo: "닭갈비",
    nameEn: "Dak-galbi (Spicy Stir-fried Chicken)",
    descKo: "토막 친 닭고기를 매콤한 고추장 양념에 재운 뒤 양배추, 고구마, 떡과 함께 무쇠 철판에 볶아 먹는 요리",
    descEn: "Boneless chicken marinated in spicy chili sauce, stir-fried on a tabletop iron skillet with sweet cabbage, sweet potatoes, and rice cakes",
    categoryTag: "MEAL",
    unitPriceKrw: 16000,
    priceMinKrw: 14000,
    priceMaxKrw: 19000,
    isMustEatTop3: false,
    emoji: "🍳",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/40fb0d29-a845-47f4-9f9d-58a50780bcd8/it11",
  },
  {
    id: "nat_shabushabu",
    scope: "NATIONAL",
    nameKo: "샤브샤브",
    nameEn: "Korean Beef Shabu-shabu",
    descKo: "맑은 채소 육수에 얇게 썬 소고기와 신선한 버섯, 배추를 살짝 데쳐 먹은 뒤 칼국수와 죽으로 마무리하는 요리",
    descEn: "Thin tender beef slices gently cooked in hot vegetable broth with mushrooms, finished with noodles and comforting porridge",
    categoryTag: "MEAL",
    unitPriceKrw: 16000,
    priceMinKrw: 14000,
    priceMaxKrw: 20000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "http://tong.visitkorea.or.kr/cms/resource/52/2878052_image2_1.jpg",
  },
  {
    id: "nat_hanjeongsik",
    scope: "NATIONAL",
    nameKo: "한정식",
    nameEn: "Hanjeongsik (Full-Course Korean Table)",
    descKo: "한국 전통 상차림의 정수로 계절 나물, 구이, 탕, 찌개와 정갈한 찬들이 푸짐하게 차려지는 정식",
    descEn: "Exquisite Korean full-course meal feast featuring a harmonious spread of grilled dishes, soups, stews, and delicate side dishes",
    categoryTag: "MEAL",
    unitPriceKrw: 45000,
    priceMinKrw: 35000,
    priceMaxKrw: 65000,
    isMustEatTop3: false,
    emoji: "🍱",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/ee3b8a7f-8453-45e2-9968-ac214c6bb688/it11",
  },

  // --- [그룹 3: 🍚 밥 & 면 요리] ---
  {
    id: "nat_gimbap",
    scope: "NATIONAL",
    nameKo: "김밥",
    nameEn: "Gimbap (Korean Seaweed Rice Rolls)",
    descKo: "고소한 참기름 밥에 단무지, 시금치, 당근, 달걀, 햄을 넣고 바삭한 김으로 말아낸 대표적인 국민 간식이자 든든한 한 끼",
    descEn: "Steamed white rice seasoned with sesame oil and rolled in roasted seaweed with yellow radish, spinach, carrots, eggs, and ham",
    categoryTag: "STREET_SNACK",
    unitPriceKrw: 4500,
    priceMinKrw: 3500,
    priceMaxKrw: 6000,
    isMustEatTop3: false,
    emoji: "🍙",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b2fedcae-04b8-4fb4-ac2e-d97655d4ae72/it11",
  },
  {
    id: "nat_kimchi_bokkeumbap",
    scope: "NATIONAL",
    nameKo: "김치볶음밥",
    nameEn: "Kimchi Bokkeumbap (Kimchi Fried Rice)",
    descKo: "잘 익은 매콤한 김치와 밥, 햄 또는 참치를 센 불에 고소하게 볶아내 반숙 계란 후라이와 김가루를 얹은 소울푸드",
    descEn: "Stir-fried rice sizzling with tangy fermented kimchi, diced pork or tuna, topped with a runny fried egg and toasted seaweed flakes",
    categoryTag: "MEAL",
    unitPriceKrw: 9000,
    priceMinKrw: 8000,
    priceMaxKrw: 11000,
    isMustEatTop3: false,
    emoji: "🍳",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/a54c2b8c-b324-4cb7-bfab-e6c4ea8d56eb/it11",
  },
  {
    id: "nat_japchae",
    scope: "NATIONAL",
    nameKo: "잡채",
    nameEn: "Japchae (Stir-fried Glass Noodles & Vegetables)",
    descKo: "쫄깃한 당면에 신선한 시금치, 당근, 버섯, 소고기를 넣고 간장과 참기름에 고소하게 볶아낸 전통 잔치 음식",
    descEn: "Chewy sweet potato glass noodles stir-fried with colorful vegetables, mushrooms, and beef seasoned in soy sauce and sesame oil",
    categoryTag: "MEAL",
    unitPriceKrw: 12000,
    priceMinKrw: 9000,
    priceMaxKrw: 15000,
    isMustEatTop3: false,
    emoji: "🥢",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/864eb60c-76d2-45ce-beb4-886dc999cdf4/it11",
  },
  {
    id: "nat_naengmyeon",
    scope: "NATIONAL",
    nameKo: "냉면",
    nameEn: "Naengmyeon (Cold Noodles)",
    descKo: "시원한 동치미 살얼음 육수의 메밀 물냉면과 매콤새콤한 비빔장을 얹은 비빔냉면",
    descEn: "Chilled chewy buckwheat noodles served in refreshing icy broth or tossed with spicy sweet chili dressing",
    categoryTag: "MEAL",
    unitPriceKrw: 13000,
    priceMinKrw: 11000,
    priceMaxKrw: 16000,
    isMustEatTop3: false,
    emoji: "🍜",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=57333299-0645-4bb8-a093-ec5e233b43e5",
  },
  {
    id: "nat_jajangmyeon_mandu",
    scope: "NATIONAL",
    nameKo: "자장면",
    nameEn: "Jajangmyeon (Noodles in Black Bean Sauce)",
    descKo: "고소하고 달콤한 춘장 소스에 양파와 돼지고기를 볶아 갓 삶아낸 쫄깃한 면발에 비벼 먹는 국민 면 요리",
    descEn: "Chewy wheat noodles smothered in a rich, savory black bean sauce stir-fried with pork and sweet caramelized onions",
    categoryTag: "MEAL",
    unitPriceKrw: 8000,
    priceMinKrw: 7000,
    priceMaxKrw: 10000,
    isMustEatTop3: false,
    emoji: "🥢",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=8ae1266b-ff1c-489a-9aa5-7fecc6050796",
  },
  {
    id: "nat_haemul_pajeon",
    scope: "NATIONAL",
    nameKo: "해물파전 & 칼국수",
    nameEn: "Haemul Pajeon & Kalguksu (Seafood Pancake & Noodle Soup)",
    descKo: "싱싱한 오징어와 조갯살, 쪽파를 듬뿍 넣어 바삭하게 부친 해물파전과 시원하고 깊은 육수의 쫄깃한 손칼국수 세트",
    descEn: "Crispy savory seafood scallion pancake paired with a comforting bowl of fresh hand-cut noodle soup in rich broth",
    categoryTag: "BBQ_FEAST",
    unitPriceKrw: 19000,
    priceMinKrw: 16000,
    priceMaxKrw: 24000,
    isMustEatTop3: false,
    emoji: "🥞",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=ed7d07b1-ad52-45e2-a264-b617d6a78ff7",
  },

  // --- [그룹 4: 🥘 찌개 & 전골] ---
  {
    id: "nat_kimchi_jjigae",
    scope: "NATIONAL",
    nameKo: "김치찌개",
    nameEn: "Kimchi-jjigae (Spicy Kimchi Stew)",
    descKo: "잘 익은 숙성 김치와 두툼한 돼지고기, 두부를 듬뿍 넣고 얼큰하게 끓여낸 한국인의 소울푸드",
    descEn: "Hearty, spicy stew brewed with well-aged fermented kimchi, succulent tender pork chunks, and soft tofu cubes",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 9000,
    priceMaxKrw: 12000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=b2e49489-3ca7-47c5-9354-8370f40cbaf4",
  },
  {
    id: "nat_doenjang_jjigae",
    scope: "NATIONAL",
    nameKo: "된장찌개",
    nameEn: "Doenjang-jjigae (Soybean Paste Stew)",
    descKo: "구수한 재래식 된장 육수에 두부, 애호박, 양파, 버섯, 차돌박이 또는 바지락을 넣고 보글보글 끓여낸 한국인의 대표 찌개",
    descEn: "Comforting traditional stew brewed with rich fermented soybean paste, tender tofu cubes, zucchini, mushrooms, and savory beef or clams",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 8500,
    priceMaxKrw: 12000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/68813ba4-620b-4bdd-9817-7c29768af0c0/it11",
  },
  {
    id: "nat_sundubu",
    scope: "NATIONAL",
    nameKo: "순두부찌개",
    nameEn: "Sundubu-jjigae (Spicy Soft Tofu Stew)",
    descKo: "몽글몽글 부드러운 순두부와 신선한 조개, 새우, 계란을 넣고 칼칼하고 진하게 끓여낸 뚝배기 찌개",
    descEn: "Silken uncurdled soft tofu stew bubbling fiery red in an earthenware bowl with clams, shrimp, and an egg yolk",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 9000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2f195887-4706-448c-bd11-ef0393ce200f/it11",
  },
  {
    id: "nat_budae_jjigae",
    scope: "NATIONAL",
    nameKo: "부대찌개",
    nameEn: "Budae-jjigae (Sausage & Ham Army Stew)",
    descKo: "햄, 소시지, 김치, 베이크드 빈스, 치즈와 라면사리를 푸짐하게 끓여내는 퓨전 전통 찌개",
    descEn: "Hearty fusion hotpot simmered with savory ham, pork sausage, aged kimchi, baked beans, cheese, and chewy ramen noodles",
    categoryTag: "MEAL",
    unitPriceKrw: 12000,
    priceMinKrw: 10000,
    priceMaxKrw: 15000,
    isMustEatTop3: false,
    emoji: "🥘",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/bfd74860-7ebe-445a-bbea-a3283e707047/it11",
  },

  // --- [그룹 5: 🥣 탕 & 보양국] ---
  {
    id: "nat_samgyetang",
    scope: "NATIONAL",
    nameKo: "삼계탕",
    nameEn: "Samgyetang (Ginseng Chicken Soup)",
    descKo: "어린 닭의 뱃속에 찹쌀, 인삼, 대추, 마늘을 채워 푹 고아낸 대표적인 전통 보양식",
    descEn: "Whole tender young chicken stuffed with sweet sticky rice, ginseng root, jujubes, and garlic, simmered in rich medicinal broth",
    categoryTag: "MEAL",
    unitPriceKrw: 18000,
    priceMinKrw: 16000,
    priceMaxKrw: 22000,
    isMustEatTop3: false,
    emoji: "🥣",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/a1ac7b39-e0fb-4b2a-98bb-e29d133fa609/it11",
  },
  {
    id: "nat_gamjatang",
    scope: "NATIONAL",
    nameKo: "감자탕 (뼈해장국)",
    nameEn: "Gamjatang (Pork Bone Stew with Potatoes)",
    descKo: "돼지 등뼈와 우거지, 감자, 들깨가루를 듬뿍 넣고 오랜 시간 푹 고아내 깊고 구수한 맛을 내는 탕 요리",
    descEn: "Rich, deep broth stewed for hours with meaty pork spine bones, dried cabbage greens, whole potatoes, and perilla seeds",
    categoryTag: "MEAL",
    unitPriceKrw: 11000,
    priceMinKrw: 10000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🍖",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2c070992-9577-4377-b7a1-c5a8476c9d4b/it11",
  },
  {
    id: "nat_miyeok_guk",
    scope: "NATIONAL",
    nameKo: "미역국",
    nameEn: "Miyeok-guk (Seaweed Soup with Beef)",
    descKo: "참기름에 소고기와 바다 미역을 정성스레 볶은 후 오랜 시간 맑고 진하게 끓여낸 건강하고 따뜻한 생일 및 보양 탕 요리",
    descEn: "Hearty and comforting brown seaweed soup gently simmered with tender beef slices and toasted sesame oil, iconic for Korean birthdays and celebration",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 9000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🥣",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/5d260c22-cbc0-4173-a41c-77bf7744ddad/it11",
  },

  // --- [그룹 6: 🍢 K-길거리 & 분식·디저트] ---
  {
    id: "nat_tteokbokki_set",
    scope: "NATIONAL",
    nameKo: "떡튀순 (떡볶이, 튀김, 순대)",
    nameEn: "Tteok-Twi-Soon (Tteokbokki, Tempura & Blood Sausage)",
    descKo: "매콤달콤한 고추장 양념에 끓여낸 쫄깃한 쌀떡볶이와 바삭한 모둠튀김, 찰순대 분식 세트",
    descEn: "Chewy cylinder rice cakes simmered in sweet and spicy chili paste sauce, paired with crispy fritters and steamed sausage",
    categoryTag: "STREET_SNACK",
    unitPriceKrw: 12000,
    priceMinKrw: 9000,
    priceMaxKrw: 15000,
    isMustEatTop3: false,
    emoji: "🍢",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/263fff1d-a001-4f40-8369-b53ae49ac852/it11",
  },
  {
    id: "nat_street_toast",
    scope: "NATIONAL",
    nameKo: "길거리 토스트",
    nameEn: "Gilgeori Toast (Korean Street Egg Toast)",
    descKo: "버터에 구운 식빵 사이에 달걀 채소 패티와 햄을 넣고 설탕과 케첩을 뿌려 달콤 짭조름하게 즐기는 한국식 길거리 토스트",
    descEn: "Buttery toasted sandwich layered with an egg-vegetable patty, savory ham, ketchup, and sugar for a signature sweet-savory punch",
    categoryTag: "STREET_SNACK",
    unitPriceKrw: 5500,
    priceMinKrw: 4500,
    priceMaxKrw: 7000,
    isMustEatTop3: false,
    emoji: "🥪",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/911762eb-2164-485f-a429-cee65acc190f/it11",
  },
  {
    id: "nat_kkwabaegi_bungeoppang",
    scope: "NATIONAL",
    nameKo: "꽈배기",
    nameEn: "Kkwabaegi (Korean Twisted Donut)",
    descKo: "전통 시장에서 갓 튀겨내 설탕을 솔솔 묻힌 쫄깃하고 폭신한 추억의 찹쌀 꽈배기",
    descEn: "Chewy, fluffy twisted donut freshly deep-fried at traditional markets and lightly coated in sweet sugar",
    categoryTag: "DESSERT_CAFE",
    unitPriceKrw: 3500,
    priceMinKrw: 2500,
    priceMaxKrw: 5000,
    isMustEatTop3: false,
    emoji: "🥨",
    imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/6f75994d-b61a-425c-ae46-c1847f755a0d/it11",
  },
];

// =========================================================================
// 2. 🏙️ 10개 도시별 로컬 대표 미식 (City Specialties 각 10선 = 총 100선)
// =========================================================================
export const CITY_SPECIALTY_FOODS: Record<SupportedCity, FoodItemDefinition[]> = {
  // === 1. 서울 (SEOUL) ===
  SEOUL: [
    {
      id: "seoul_gwangjang_pancake",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "광장시장 녹두빈대떡",
      nameEn: "Gwangjang Market Bindaetteok (Mung Bean Pancake)",
      descKo: "맷돌로 거칠게 간 녹두 반죽에 숙주와 돼지고기를 넣고 무쇠 철판에 바삭하고 두툼하게 부쳐낸 광장시장 명물",
      descEn: "Crispy, savory stone-ground mung bean pancake pan-fried in oil with bean sprouts and pork at historic Gwangjang Market",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 9000,
      priceMinKrw: 7000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🥞",
      imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Korea_GwangjangMarket_Eats_01_%2813885110035%29.jpg/960px-Korea_GwangjangMarket_Eats_01_%2813885110035%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    },
    {
      id: "seoul_seolleongtang",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "종로 설렁탕",
      nameEn: "Jongno Seolleongtang (Ox Bone Soup)",
      descKo: "소 뼈와 양지를 가마솥에서 오랜 시간 뽀얗게 고아낸 진한 사골 육수에 소면과 밥, 깍두기를 곁들여 먹는 서울 전통 탕",
      descEn: "Rich, milky ox bone soup simmered for 15+ hours, served with tender beef slices, noodles, and crunchy radish kimchi",
      categoryTag: "MEAL",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 16000,
      isMustEatTop3: true,
      emoji: "🥣",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Seolleongtang.jpg",
    },
    {
      id: "seoul_sindang_tteokbokki",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "신당동 즉석떡볶이",
      nameEn: "Sindang-dong Tabletop Tteokbokki",
      descKo: "춘장과 고추장 황금비율 양념에 떡, 쫄면, 라면, 야끼만두, 계란을 즉석에서 끓여 먹는 신당동 떡볶이 골목 원조 메뉴",
      descEn: "Iconic table-cooked spicy rice cakes simmered in red pepper and black bean paste with ramen, dumplings, and eggs",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: true,
      emoji: "🥘",
      imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=3428735f-d5de-4d49-9d67-37e6168c242a",
    },
    {
      id: "seoul_mapo_galbi",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "마포 돼지갈비",
      nameEn: "Mapo Pork Galbi (Charcoal BBQ Ribs)",
      descKo: "달콤 짭조름한 비법 간장 양념에 재운 돼지갈비를 참숯불에 노릇하게 구워 먹는 마포 갈비 골목 전통의 맛",
      descEn: "Succulent pork ribs marinated in seasoned sweet soy glaze, charcoal-grilled to caramelized perfection in historic Mapo",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 17000,
      priceMinKrw: 15000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🥩",
      imageUrl: "http://tong.visitkorea.or.kr/cms/resource/25/2858125_image2_1.jpg",
    },
    {
      id: "seoul_dongdaemun_dakhanmari",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "동대문 닭한마리",
      nameEn: "Dongdaemun Dakhanmari (Whole Chicken Hotpot)",
      descKo: "양은 냄비에 통닭 한 마리를 맑은 육수에 끓여 알싸한 겨자 다대기 소스에 찍어 먹고 칼국수로 마무리하는 동대문 명물",
      descEn: "Whole tender chicken simmered at the table in clear broth, dipped in spicy vinegar-mustard sauce and finished with fresh knife-cut noodles",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 19000,
      isMustEatTop3: false,
      emoji: "🍲",
      imageUrl: "http://tong.visitkorea.or.kr/cms/resource/43/2869643_image2_1.jpg",
    },
    {
      id: "seoul_namdaemun_galchijorim",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "남대문 갈치조림",
      nameEn: "Namdaemun Galchi-jorim (Braised Cutlassfish)",
      descKo: "도톰한 갈치와 달큰하게 푹 익은 무를 매콤달콤한 고춧가루 양념에 졸여낸 남대문 시장 갈치 골목 대표 밥도둑",
      descEn: "Thick fresh cutlassfish steaks and tender radishes braised in a bubbling pot of fiery, savory red chili garlic sauce",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🐟",
      imageUrl: "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/7f241234-ee93-4ff5-a445-7429d95cdf6f/it11",
    },
    {
      id: "seoul_euljiro_golbaengi",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "을지로 골뱅이무침",
      nameEn: "Euljiro Golbaengi-muchim (Spicy Sea Snail Salad)",
      descKo: "큼직하고 쫄깃한 통골뱅이를 알싸한 파채와 고춧가루, 명태포와 함께 거칠게 버무려 맥주와 즐기는 힙지로 안주",
      descEn: "Plump sea snails tossed with fresh scallion threads, dried pollock strips, and spicy red pepper, served in retro Euljiro alleys",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🥗",
      imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Golbaengi-muchim_2.jpg/960px-Golbaengi-muchim_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    },
    {
      id: "seoul_sillim_sundaebokkeum",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "신림동 순대볶음",
      nameEn: "Sillim-dong Sundae-bokkeum (Stir-fried Blood Sausage)",
      descKo: "철판에 순대, 곱창, 쫄면, 깻잎, 양배추를 들깨가루와 매콤한 특제 양념과 함께 푸짐하게 볶아 먹는 신림동 순대타운 명물",
      descEn: "Chewy Korean glass noodle sausages and perilla leaves stir-fried on a hot iron griddle with cabbage and rich perilla seed seasonings at Sillim Sundae Town",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🥘",
      imageUrl: "https://tong.visitkorea.or.kr/cms/resource/36/3526736_image2_1.JPG",
    },
    {
      id: "seoul_majang_hanwoo",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "마장동 한우",
      nameEn: "Majang-dong Hanwoo (Premium Korean Beef BBQ)",
      descKo: "국내 최대 축산물 시장인 마장동에서 직송한 최고 등급(1++ 투뿔) 한우를 숯불에 구워 고소한 육즙과 부드러운 풍미를 즐기는 서울 대표 소고기 구이",
      descEn: "Top-grade 1++ Korean native beef (Hanwoo) charcoal-grilled to melt-in-your-mouth perfection, sourced directly from historic Majang Meat Market",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 45000,
      priceMinKrw: 35000,
      priceMaxKrw: 65000,
      isMustEatTop3: false,
      emoji: "🥩",
      imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=3c954d31-5be6-42c3-9694-b33c2919124b",
    },
    {
      id: "seoul_jangchung_jokbal",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "장충동 족발",
      nameEn: "Jangchung-dong Jokbal (Braised Pig's Trotters)",
      descKo: "각종 한약재와 비법 육수에 오랜 시간 푹 삶아내 쫄깃하고 부드러운 장충동 족발 골목의 원조 보양 요리",
      descEn: "Tender sliced pig's trotters slowly braised with herbs and soy sauce until gelatinous, soft, and richly savory",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 36000,
      isMustEatTop3: false,
      emoji: "🍖",
      imageUrl: "http://tong.visitkorea.or.kr/cms/resource/42/2794142_image2_1.jpg",
    },
  ],

  // === 2. 부산 (BUSAN) ===
  BUSAN: [
    {
      id: "busan_dwaeji_gukbap",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 돼지국밥",
      nameEn: "Busan Dwaeji-gukbap (Pork and Rice Soup)",
      descKo: "돼지 사골을 뽀얗게 우려낸 뜨끈한 육수에 푸짐한 수육과 부추 겉절이, 새우젓을 넣어 먹는 부산의 대표 향토음식",
      descEn: "Piping-hot, deep pork bone broth filled with sliced tender pork, seasoned with salted baby shrimp and fresh chives's pride: rich, comforting pork bone broth packed with tender pork slices and fresh seasoned garlic chives",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_milmyeon",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 밀면",
      nameEn: "Busan Milmyeon (Wheat Noodle Soup)",
      descKo: "쫄깃한 밀가루 면발에 한약재를 넣고 우린 살얼음 육수와 매콤달콤한 비빔 양념을 얹어 시원하게 즐기는 부산 여름 별미",
      descEn: "Busan signature cold wheat noodles served in icy herbal beef broth with cucumber, hard-boiled egg, and sweet chili sauce",
      categoryTag: "MEAL",
      unitPriceKrw: 9500,
      priceMinKrw: 8000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/88/3049888_image2_1.JPG",
    },
    {
      id: "busan_ssiat_hotteok",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "남포동 씨앗호떡",
      nameEn: "Nampodong Ssiat Hotteok (Seed Stuffed Sweet Pancake)",
      descKo: "마가린에 바삭하게 구운 찹쌀 반죽을 갈라 해바라기씨, 호박씨, 땅콩 등 고소한 견과류와 흑설탕을 듬뿍 채운 길거리 간식",
      descEn: "Golden griddled sweet pancake cut open and generously stuffed with crunchy sunflower seeds, pumpkin seeds, and brown sugar",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 2500,
      priceMinKrw: 2000,
      priceMaxKrw: 3500,
      isMustEatTop3: true,
      emoji: "🥞",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/94/2786894_image2_1.png",
    },
    {
      id: "busan_jagalchi_rawfish",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "자갈치 모둠 생선회",
      nameEn: "Jagalchi Raw Fish Platter (Sashimi)",
      descKo: "자갈치 시장에서 갓 건져 올린 광어, 우럭, 참돔을 싱싱하게 회 떠서 초고추장, 쌈장과 함께 즐기는 바다의 맛",
      descEn: "Ultra-fresh slices of local catch including flounder and sea bream, enjoyed with spicy red chili paste and sesame oil wrap",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 30000,
      priceMinKrw: 25000,
      priceMaxKrw: 40000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/13/2941313_image2_1.bmp",
    },
    {
      id: "busan_gijang_eel",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "기장 짚불 곰장어",
      nameEn: "Gijang Straw-Fire Grilled Hagfish",
      descKo: "볏짚에 불을 붙여 순간적인 고열로 구워내 겉은 바삭하고 속은 쫄깃하며 특유의 짚불 훈연 향이 배어있는 기장 명물",
      descEn: "Unique Busan delicacy cooked over blazing rice straw fire, locking in natural sea flavor with distinct smoky aroma",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 35000,
      isMustEatTop3: false,
      emoji: "🔥",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/83/4039583_image2_1.jpg",
    },
    {
      id: "busan_nakgop_sae",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 낙곱새",
      nameEn: "Busan Nakgopsae (Octopus, Intestine & Shrimp Stew)",
      descKo: "낙지, 대창(곱창), 새우를 매콤하고 얼큰한 비법 양념에 자작하게 끓여 밥 위에 얹어 김가루와 비벼 먹는 전골 요리",
      descEn: "Spicy pan-stew combining tender baby octopus, rich beef intestines, and plump shrimp, served over steamed rice with seaweed",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: false,
      emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_eomuk_mooltteok",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 어묵 & 물떡",
      nameEn: "Busan Fish Cake & Mooltteok (Rice Cake Skewers)",
      descKo: "진한 무와 멸치 육수 가마솥에 푹 익힌 두툼한 명품 부산 어묵 꼬치와 쫀득하게 간이 밴 가래떡 꼬치",
      descEn: "High-grade savory fish cakes and chewy cylindrical rice cakes slow-simmered on skewers in rich seasoned anchovy broth",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 4500,
      priceMinKrw: 3000,
      priceMaxKrw: 6500,
      isMustEatTop3: false,
      emoji: "🍢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_naengchae_jokbal",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "남포동 냉채족발",
      nameEn: "Nampodong Naengchae Jokbal (Chilled Jellyfish Trotters)",
      descKo: "얇게 썬 부드러운 족발에 오이, 해파리채를 곁들이고 코끝이 찡한 특제 겨자소스를 끼얹어 새콤달콤하게 즐기는 요리",
      descEn: "Chilled thinly-sliced braised pork trotters tossed with jellyfish, cucumber matchsticks, and refreshing pungent mustard dressing's trotters tossed with jellyfish, cucumber slices, and sinus-clearing mustard dressing",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2833858_image2_1.jpg",
    },
    {
      id: "busan_dongnae_pajeon",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "동래파전",
      nameEn: "Dongnae Pajeon (Traditional Green Onion Pancake)",
      descKo: "달콤하고 부드러운 동래 쪽파와 쇠고기, 신선한 해물을 찹쌀 반죽에 얹고 계란을 풀어 노릇하게 구워낸 부산 전통 파전",
      descEn: "Historic scallion pancake topped with fresh seafood, tender beef, and egg, fried soft and moist inside and golden crispy outside",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 20000,
      priceMinKrw: 16000,
      priceMaxKrw: 25000,
      isMustEatTop3: false,
      emoji: "🥞",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/65/2778665_image2_1.jpg",
    },
    {
      id: "busan_haenyeo_ramen",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "영도 해녀 김밥 & 해물라면",
      nameEn: "Yeongdo Haenyeo Gimbap & Seafood Ramyeon",
      descKo: "영도 절벽 앞 해녀들이 갓 채취한 신선한 성게알(우니)을 얹어 먹는 김밥과 꽃게, 홍합을 넣고 끓인 얼큰한 라면",
      descEn: "Cliffside seafood meal featuring seaweed rice rolls topped with fresh sea urchin roe and piping-hot ramen loaded with blue crab",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/69/2844169_image2_1.JPG",
    },
  ],

  // === 3. 제주 (JEJU) ===
  JEJU: [
    {
      id: "jeju_black_pork",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 흑돼지 구이",
      nameEn: "Jeju Black Pork BBQ",
      descKo: "청정 제주 한라산 자락에서 자란 토종 흑돼지를 두툼한 근고기로 썰어 멜젓(멸치젓)에 찍어 먹는 대표 구이",
      descEn: "Juicy thick steaks of native Jeju black pork charcoal-grilled and dipped in warm fermented anchovy sauce (meljeot)",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 25000,
      priceMinKrw: 22000,
      priceMaxKrw: 32000,
      isMustEatTop3: true,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_gogi_guksu",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 고기국수",
      nameEn: "Jeju Gogi-guksu (Pork Noodle Soup)",
      descKo: "돼지 뼈를 오랜 시간 뽀얗게 우려낸 담백하고 진한 육수에 중면 국수와 도톰한 수육 편육을 얹어 낸 제주의 향토음식",
      descEn: "Comforting bowl of yellow wheat noodles in rich pork bone broth crowned with tender slices of braised pork belly",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_galchi_jorim",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 은갈치조림",
      nameEn: "Jeju Galchi-jorim (Braised Silver Cutlassfish)",
      descKo: "제주 바다에서 갓 낚아 올린 싱싱한 은갈치를 감자, 무와 함께 매콤달콤한 고추장 양념에 자작하게 졸여낸 명품 요리",
      descEn: "Extra-long wild silver cutlassfish simmered gently with radishes and potatoes in fiery-sweet garlic chili sauce",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 32000,
      priceMinKrw: 28000,
      priceMaxKrw: 42000,
      isMustEatTop3: true,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_abalone_porridge",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 전복죽 & 해물뚝배기",
      nameEn: "Jeju Jeonbok-juk (Abalone Porridge & Clay Pot Stew)",
      descKo: "신선한 전복 내장을 넣어 진하고 녹진하게 끓인 전통 전복죽과 딱새우, 조개가 들어간 얼큰하고 시원한 해물뚝배기",
      descEn: "Rich, green-hued rice porridge simmered with wild abalone viscera, served alongside a sizzling clay pot of local seafood",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_ttaksaewoo_sashimi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 딱새우회 & 해산물 모둠",
      nameEn: "Jeju Ttaksaewoo Sashimi (Red-banded Lobster Platter)",
      descKo: "제주 청정 바다에서 갓 잡은 신선한 딱새우를 손질해 입에 넣으면 사르르 녹아내리는 달콤하고 차진 식감의 고급 생선회",
      descEn: "Pristine sweet red-banded spiny lobsters harvested around Jeju, noted for their tender, melt-in-mouth sweetness and chew's pristine waters",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 25000,
      priceMinKrw: 20000,
      priceMaxKrw: 32000,
      isMustEatTop3: false,
      emoji: "🦐",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_bomal_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 보말칼국수",
      nameEn: "Jeju Bomal Kalguksu (Sea Snail Noodle Soup)",
      descKo: "제주 갯바위에서 채취한 고둥(보말)의 내장까지 통째로 갈아 넣어 녹진하고 깊은 바다 향이 우러난 진국 칼국수",
      descEn: "Deep green, richly savory noodle soup made from wild Jeju sea snails ground with internal organs for intense sea umami",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_citrus_omegi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 오메기떡 & 한라봉 디저트",
      nameEn: "Jeju Omegi-tteok & Hallabong Dessert",
      descKo: "차조와 쑥 반죽 속에 달콤한 팥소를 채우고 통팥 고물을 묻힌 제주 전통 오메기떡과 상큼 달콤한 한라봉 주스",
      descEn: "Traditional Jeju mugwort rice cakes filled with sweet red beans rolled in azuki beans, served with refreshing Hallabong juice",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 6000,
      priceMinKrw: 4500,
      priceMaxKrw: 8000,
      isMustEatTop3: false,
      emoji: "🍊",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_dombe_gogi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 돔베고기",
      nameEn: "Jeju Dombe-gogi (Boiled Pork on Cutting Board)",
      descKo: "갓 삶아낸 두툼하고 촉촉한 돼지고기 수육을 나무 도마(돔베)에 썰어 굵은 소금과 멜젓, 쌈채소와 함께 즐기는 제주 향토 음식",
      descEn: "Juicy, freshly boiled tender pork belly sliced on a rustic wooden chopping board with sea salt and pungent fermented anchovy sauce",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_hanchi_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 한치물회",
      nameEn: "Jeju Hanchi Mulhoe (Chilled Squid Soup)",
      descKo: "갓 잡아 부드럽고 쫄깃한 한치 생선살을 오이, 미나리와 함께 살얼음 동동 띄운 된장·초고추장 육수에 말아 먹는 여름 별미",
      descEn: "Tender fresh squid slices served in refreshing ice-cold spicy broth seasoned with fermented soybean paste and vinegar",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_okdom_gui",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 옥돔구이",
      nameEn: "Jeju Okdom-gui (Grilled Red Tilefish)",
      descKo: "제주 특산 옥돔을 바닷바람에 반건조하여 기름에 노릇노릇 바삭하게 구워내 담백하고 고소한 맛이 일품인 생선구이",
      descEn: "Sea-breeze dried royal red tilefish grilled with a golden crisp exterior and moist, delicately sweet and clean white meat",
      categoryTag: "MEAL",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
  ],

  // === 4. 전주 (JEONJU) ===
  JEONJU: [
    {
      id: "jeonju_bibimbap",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 비빔밥",
      nameEn: "Jeonju Bibimbap (Royal Mixed Rice)",
      descKo: "사골 육수로 지은 밥에 황포묵, 육회, 콩나물, 계절 나물 등 오색 고명을 정갈하게 얹어 놋그릇에 담아내는 유네스코 미식",
      descEn: "World-renowned UNESCO traditional rice bowl cooked in rich beef bone broth, topped with seasonal namul, mung bean jelly, and seasoned beef's culinary crown jewel: beef broth rice served in heavy brass bowl with seasoned beef tartare and 10 herbs",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: true,
      emoji: "🥗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_kongnamul_gukbap",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 콩나물국밥",
      nameEn: "Jeonju Kongnamul-gukbap (Bean Sprout Soup)",
      descKo: "전주 8미 중 으뜸인 아삭한 콩나물과 오징어를 맑은 육수에 끓여 김가루와 수란(반숙란)을 곁들여 먹는 전주의 해장국",
      descEn: "Crisp local bean sprouts simmered in clean anchovy-squid broth, served boiling with soft-poached eggs and roasted seaweed",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_pi_sundae",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 피순대국밥",
      nameEn: "Jeonju Pi-sundae (Authentic Blood Sausage Soup)",
      descKo: "돼지 막창에 선지와 채소를 꽉 채워 쪄낸 부드럽고 녹진한 피순대를 초장에 찍어 먹고 얼큰한 뚝배기 국밥으로 즐기는 전주 명물",
      descEn: "Creamy traditional blood sausage hand-stuffed in natural casing, dipped in vinegared chili paste and enjoyed in boiling spicy stew",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 13000,
      isMustEatTop3: true,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_hanjeongsik_full",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 한정식",
      nameEn: "Jeonju Grand Hanjeongsik (Royal Course Feast)",
      descKo: "맛의 고장 전주의 진수를 느낄 수 있는 30여 가지의 산해진미, 갈비구이, 계절 찌개와 정갈한 찬들이 차려지는 명품 상차림",
      descEn: "Grand 30-dish royal feast representing the heritage of Jeonju with charcoal-grilled beef, seasonal stews, and delicate side dishes",
      categoryTag: "MEAL",
      unitPriceKrw: 40000,
      priceMinKrw: 30000,
      priceMaxKrw: 60000,
      isMustEatTop3: false,
      emoji: "🍱",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_gamaek",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 가맥 황태포",
      nameEn: "Jeonju Gamaek Hwangtae (Charcoal-Toasted Dried Pollock)",
      descKo: "동네 가게 맥줏집(가맥)에서 연탄불에 바삭하고 고소하게 구워낸 두툼한 황태포와 청양고추 간장마요 특제 소스",
      descEn: "Jeonju corner pub culture featuring thick dried pollock roasted over briquettes to airy perfection, paired with spicy mayo-soy dip",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: false,
      emoji: "🍺",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_tteokgalbi",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 한우 떡갈비",
      nameEn: "Jeonju Hanwoo Tteokgalbi (Minced Beef Patties)",
      descKo: "소갈빗살을 칼로 곱게 다져 달콤 짭조름한 양념을 버무린 뒤 참숯불에 떡처럼 도톰하게 빚어 구워낸 궁중 요리",
      descEn: "Tender minced beef ribs marinated in sweet garlic soy glaze, shaped into thick juicy patties and charcoal-grilled",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 16000,
      priceMinKrw: 13000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_moju_pajeon",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 모주 & 해물파전",
      nameEn: "Jeonju Moju & Haemul Pajeon (Herbal Wine & Scallion Pancake)",
      descKo: "막걸리에 계피, 대추, 생강 등 한약재를 넣고 달여 은은하게 달콤한 저알콜 모주와 겉바속촉 해물파전",
      descEn: "Naturally sweet low-alcohol herbal wine simmered with cinnamon and dates, paired with a crisp and savory seafood pancake",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 12000,
      priceMinKrw: 9000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍶",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_veteran_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 베테랑 들깨칼국수",
      nameEn: "Jeonju Veteran Kalguksu (Egg Drop Perilla Noodle Soup)",
      descKo: "달걀을 푼 구수하고 걸쭉한 국물에 들깨가루, 김가루, 고춧가루를 삼색으로 듬뿍 얹어 비벼 먹는 한옥마을 명물 칼국수",
      descEn: "Comforting thick egg-drop broth noodles generously dusted with toasted perilla seeds, nori flakes, and spicy red pepper",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_omogari_tang",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 오모가리탕",
      nameEn: "Jeonju Omogari-tang (Clay Pot Freshwater Fish Stew)",
      descKo: "전주천 변 뚝배기(오모가리)에 메기, 쏘가리와 시래기를 넣고 얼큰하고 구수하게 끓여낸 전통 매운탕",
      descEn: "Traditional spicy freshwater fish stew slow-simmered in thick earthenware pots with dried radish greens and garlic",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 30000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/97/3054097_image2_1.jpg",
    },
    {
      id: "jeonju_chocopie",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 수제 초코파이",
      nameEn: "Jeonju Artisanal Choco Pie",
      descKo: "달콤한 초콜릿 코팅과 부드러운 초코 시트 사이에 딸기잼과 하얀 마시멜로 크림, 호두가 씹히는 전주 전통 베이커리 빵",
      descEn: "Famous handmade pastry featuring soft chocolate biscuit filled with sweet strawberry jam, cream, and crunchy walnuts",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 3500,
      priceMinKrw: 2800,
      priceMaxKrw: 5000,
      isMustEatTop3: false,
      emoji: "🍫",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
  ],

  // === 5. 강릉 (GANGNEUNG) ===
  GANGNEUNG: [
    {
      id: "gangneung_chodang_sundubu",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 초당 순두부",
      nameEn: "Gangneung Chodang Sundubu (Sea-Water Soft Tofu)",
      descKo: "동해안 청정 바닷물을 간수로 사용하여 콩 본연의 고소하고 달큰한 풍미가 가득한 400년 전통의 부드러운 순두부",
      descEn: "Celebrated 400-year traditional soft tofu coagulated exclusively with pristine East Sea deep seawater for unmatched natural sweetness",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_jang_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 장칼국수",
      nameEn: "Gangneung Jang Kalguksu (Spicy Paste Noodles)",
      descKo: "구수한 된장과 칼칼한 고추장을 멸치 육수에 풀어 호박, 감자, 계란을 넣고 걸쭉하게 끓여낸 강릉의 소울 칼국수",
      descEn: "Thick hand-cut knife noodles simmered in rich, fiery red broth seasoned with fermented red pepper paste and soybean paste",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_anmok_coffee",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "안목해변 스페셜티 커피",
      nameEn: "Anmok Beach Specialty Drip Coffee",
      descKo: "한국의 커피 1번지 안목 커피거리 바다를 바라보며 마시는 대한민국 1세대 바리스타들의 명품 핸드드립 커피",
      descEn: "Freshly roasted artisanal specialty pour-over coffee savored along historic Anmok Coastal Beach Coffee Street's coffee capital overlooking the scenic blue ocean waves",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 8000,
      priceMinKrw: 6000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "☕",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/4075958_image2_1.jpg",
    },
    {
      id: "gangneung_ggomak_bibimbap",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 꼬막비빔밥",
      nameEn: "Gangneung Ggomak Bibimbap (Spicy Seasoned Cockles)",
      descKo: "통통하게 살이 오른 참꼬막을 고추, 쪽파, 참기름 특제 양념에 버무려 고소한 밥과 비벼 먹는 강릉 최고의 인기 미식",
      descEn: "Massive platter of tender, freshly shucked cockle clams tossed in savory soy, sesame oil, and hot green peppers served with seasoned rice",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🍱",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_gamja_ongsimi",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 감자옹심이",
      nameEn: "Gangneung Gamja Ongsimi (Chewy Potato Dumplings)",
      descKo: "강원도 감자를 갈아 빚은 쫀득한 새알심(옹심이)을 구수한 멸치 메밀 육수에 끓여낸 토속 음식",
      descEn: "Traditional Gangwon regional comfort soup featuring delightfully chewy, handcrafted potato starch dumplings in savory broth",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8500,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🥔",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_garlic_bread",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 육쪽마늘빵",
      nameEn: "Gangneung Cream Cheese Garlic Bread",
      descKo: "바삭한 바게트 빵 틈새에 알싸한 마늘 소스와 진하고 달콤한 크림치즈를 아낌없이 채워 구워낸 강릉 명물 베이커리",
      descEn: "Crusty six-segmented round bread drenched in aromatic roasted garlic butter and loaded with sweet cream cheese custard",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4500,
      priceMinKrw: 4000,
      priceMaxKrw: 6000,
      isMustEatTop3: false,
      emoji: "🥖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_ojingeo_sundae",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "주문진 오징어순대",
      nameEn: "Jumunjin Ojingeo Sundae (Stuffed Squid)",
      descKo: "통오징어 몸통 속에 찹쌀, 두부, 야채를 꽉 채워 쪄낸 후 달걀물을 입혀 철판에 노릇하게 부쳐낸 동해안 별미",
      descEn: "Fresh whole squid tube stuffed with sticky rice, tofu, and minced vegetables, sliced and pan-fried in golden egg wash",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: false,
      emoji: "🦑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/41/2839641_image2_1.jpg",
    },
    {
      id: "gangneung_mulhoe_set",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "사천진리 해변 모둠물회",
      nameEn: "Gangneung Mulhoe (Chilled Assorted Raw Fish Soup)",
      descKo: "동해 바다의 싱싱한 광어, 오징어, 해삼을 살얼음 띄운 매콤새콤한 과일 초고추장 육수에 말아 소면과 먹는 여름 요리",
      descEn: "Plentiful fresh raw fish and seafood served in an icy, sweet-and-sour red pepper broth garnished with fine somyeon noodles",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 22000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "gangneung_gaori_jjim",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 가오리 생선찜",
      nameEn: "Gangneung Gaori-jjim (Braised Stingray Fish)",
      descKo: "결대로 부드럽게 찢어지는 가오리 살과 포슬포슬한 감자, 무를 특제 매콤달콤 양념에 졸여낸 강릉 로컬 대표 찜 요리",
      descEn: "Succulent braised stingray with tender cartilege simmered in thick sweet-spicy chili glaze with soft potatoes and radishes",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 25000,
      priceMinKrw: 20000,
      priceMaxKrw: 32000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_sundubu_gelato",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "초당 순두부 젤라또",
      nameEn: "Chodang Sundubu Gelato Ice Cream",
      descKo: "초당 순두부의 고소하고 담백한 두유 맛을 이탈리안 전통 젤라또 제조법으로 담아낸 강릉만의 독창적인 수제 디저트",
      descEn: "Velvety artisanal Italian-style gelato crafted from authentic Chodang soft tofu, boasting a subtle and creamy soy flavor",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4500,
      priceMinKrw: 4000,
      priceMaxKrw: 6000,
      isMustEatTop3: false,
      emoji: "🍨",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/54/2930154_image2_1.JPG",
    },
  ],

  // === 6. 속초 (SOKCHO) ===
  SOKCHO: [
    {
      id: "sokcho_abai_sundae",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 아바이순대",
      nameEn: "Sokcho Abai Sundae (North Korean Style Sausage)",
      descKo: "돼지 대창 속에 찹쌀, 선지, 숙주, 배추를 꽉 채워 쪄낸 실향민들의 전통 순대로 매콤달콤한 명태회무침과 곁들여 먹는 요리",
      descEn: "Generously stuffed thick pork intestine sausage packed with sweet rice and vegetables, paired with sweet-and-sour seasoned pollack salad",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_dakgangjeong",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 만석 닭강정",
      nameEn: "Sokcho Dakgangjeong (Sweet & Crispy Fried Chicken)",
      descKo: "가마솥 고온에서 바삭하게 튀겨낸 닭고기를 조청과 고추로 버무려 식어도 바삭한 속초 중앙시장의 명물",
      descEn: "Famous crispy bite-sized fried chicken glazed with thick traditional grain syrup, chili peppers, and roasted almond flakes",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 20000,
      priceMinKrw: 18000,
      priceMaxKrw: 23000,
      isMustEatTop3: true,
      emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_bongpo_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 모둠 물회",
      nameEn: "Sokcho Bongpo Mulhoe (Cold Seafood Soup)",
      descKo: "성게, 해삼, 활어회, 전복을 과일 발효 초장에 시원한 살얼음과 비벼 소면과 함께 즐기는 속초의 1등 해산물 요리",
      descEn: "Loaded cold bowl of live sea urchin, abalone, sea cucumber, and fresh raw fish slices bathed in slushy tangy chili broth",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 19000,
      priceMinKrw: 17000,
      priceMaxKrw: 24000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/05/4032905_image2_1.jpg",
    },
    {
      id: "sokcho_red_crab_feast",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 동해안 홍게 찜",
      nameEn: "Sokcho Steamed Red Snow Crab",
      descKo: "속초 앞바다 심해에서 갓 잡은 신선한 붉은 대게(홍게)를 찜기에 쪄서 꽉 찬 달콤한 속살과 게딱지 볶음밥을 먹는 요리",
      descEn: "Fresh sweet East Sea red snow crabs steamed to order, served with fragrant crab shell fried rice seasoned with toasted nori and sesame oil",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 35000,
      priceMinKrw: 30000,
      priceMaxKrw: 50000,
      isMustEatTop3: false,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_hoe_naengmyeon",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 명태 회냉면",
      nameEn: "Sokcho Hoe-naengmyeon (Pollock Cold Noodles)",
      descKo: "쫄깃한 함흥식 고구마 전분 면발 위에 새콤달콤하게 숙성시킨 명태회를 듬뿍 얹어 비벼 먹는 속초 실향민의 전통 냉면",
      descEn: "Springy sweet potato starch noodles topped with chewy fermented spicy raw pollock fish and refreshing chilled broth",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 10000,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_seopguk",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 자연산 섭국",
      nameEn: "Sokcho Seopguk (Spicy Wild Mussel Soup)",
      descKo: "동해 깊은 바다 갯바위에서 딴 큼직한 자연산 홍합(섭)을 된장과 고추장 육수에 부추, 미나리와 얼큰하게 끓여낸 향토 해장국",
      descEn: "Robust spicy and comforting red broth soup cooked with giant wild East Sea mussels, fresh chives, and leeks",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_dongmyeong_sashimi",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "동명항 활어회",
      nameEn: "Dongmyeong Port Fresh Sashimi Platter",
      descKo: "속초 동명항 포차거리에서 갓 잡아 올린 도다리, 가자미, 오징어를 바닷바람을 맞으며 맛보는 자연산 활어회",
      descEn: "Just-caught East Sea seasonal wild sashimi sliced fresh at dockside markets, enjoyed with savory ssamjang dip by the sea",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 30000,
      priceMinKrw: 25000,
      priceMaxKrw: 42000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/55/3041255_image2_1.jpg",
    },
    {
      id: "sokcho_grilled_fish",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 숯불 생선구이",
      nameEn: "Sokcho Charcoal Grilled Fish Feast",
      descKo: "고등어, 꽁치, 조기, 메로, 양미리, 열기 등 다양한 동해안 생선을 참숯불에 즉석에서 직접 구워 먹는 속초 명물 한상",
      descEn: "Assorted seasonal East Sea fresh fish charcoal-grilled table-side over glowing embers until smoky and juicy",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 15000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_makguksu",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 동치미 막국수",
      nameEn: "Sokcho Dongchimi Makguksu (Buckwheat Noodles)",
      descKo: "항아리에서 숙성한 톡 쏘는 살얼음 동치미 무 육수를 순메밀 국수에 부어 들기름과 함께 담백하게 비벼 먹는 국수",
      descEn: "Rustic buckwheat noodles served with naturally fermented icy radish water kimchi broth, perilla oil, and sesame seeds",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/13/3449813_image2_1.jpg",
    },
    {
      id: "sokcho_sweet_pumpkin_sikhye",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 단호박 식혜",
      nameEn: "Sokcho Sweet Pumpkin Sikhye Beverage",
      descKo: "달콤하고 부드러운 단호박을 엿기름과 삭혀 살얼음 동동 띄워 시원하고 깔끔하게 마시는 전통 디저트 음료",
      descEn: "Refreshing golden-hued traditional fermented sweet pumpkin and malt beverage served ice-cold with soft rice grains",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4000,
      priceMinKrw: 3000,
      priceMaxKrw: 5500,
      isMustEatTop3: false,
      emoji: "🎃",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
  ],

  // === 7. 경주 (GYEONGJU) ===
  GYEONGJU: [
    {
      id: "gyeongju_hwangnambbang",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 황남빵 & 찰보리빵",
      nameEn: "Gyeongju Hwangnam-ppang & Barley Bread",
      descKo: "얇은 밀가루 피 속에 100% 국산 팥앙금을 가득 채워 구워낸 80년 전통의 경주 공인 전통 빵",
      descEn: "Historic Gyeongju regional pastries featuring thin crust stuffed with silky sweet red bean paste and soft chewy barley pancakes",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: true,
      emoji: "🥮",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/82/2877982_image2_1.jpg",
    },
    {
      id: "gyeongju_hanwoo_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 한우 물회",
      nameEn: "Gyeongju Hanwoo Beef Mulhoe (Chilled Raw Beef)",
      descKo: "신선한 최고급 경주 한우 육회를 살얼음 띄운 매콤달콤한 비법 육수에 소면, 오이와 함께 말아먹는 경주만의 독특한 별미",
      descEn: "Premium Korean native beef tartare served in an icy, sweet-and-tangy cold soup with thin cucumber slices and somyeon noodles",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_ssambap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "대릉원 쌈밥 정식",
      nameEn: "Daereungwon Ssambap (Leaf Wrap Feast)",
      descKo: "케일, 곰취, 당귀 등 10여 가지 신선한 쌈채소에 매콤한 제육볶음과 강된장, 다양한 궁중 찬을 싸 먹는 대릉원 앞 명물",
      descEn: "Abundant wellness table offering over ten varieties of fresh organic leafy wraps, savory bulgogi, and rich soybean paste dip",
      categoryTag: "MEAL",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🥬",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/98/4105798_image2_1.jpg",
    },
    {
      id: "gyeongju_maetdol_sundubu",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 맷돌 순두부찌개",
      nameEn: "Gyeongju Stone-Ground Sundubu Stew",
      descKo: "국산 콩을 전통 맷돌 방식으로 갈아 몽글몽글 끓여낸 구수한 순두부에 계란을 톡 깨 넣어 먹는 보문단지 전통 찌개",
      descEn: "Traditional stone-milled curded soft tofu soup boiled with baby shrimp, clams, and vegetables in deep earthenware",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "gyeongju_tteokgalbi_sotbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 한우 떡갈비 솥밥",
      nameEn: "Gyeongju Tteokgalbi & Hot Stone Rice",
      descKo: "경주 한우를 곱게 다져 달콤한 양념에 구워낸 육즙 가득한 떡갈비와 갓 지은 뜨끈한 은행 대추 영양 솥밥",
      descEn: "Juicy handcrafted Korean beef rib patties grilled over charcoal, accompanied by freshly steamed hot stone pot rice",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 14000,
      priceMaxKrw: 22000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_gyori_gimbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 교리김밥",
      nameEn: "Gyeongju Gyori Gimbap (Egg Ribbon Roll)",
      descKo: "가늘게 채 썬 부드러운 달걀지단을 김밥의 80% 이상 꽉 채워 고소하고 부드러운 식감이 일품인 교촌마을 원조 김밥",
      descEn: "Iconic traditional gimbap roll densely stuffed with hundreds of thinly shredded tender egg ribbons for a fluffy, savory bite",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 5500,
      priceMinKrw: 4500,
      priceMaxKrw: 7000,
      isMustEatTop3: false,
      emoji: "🍙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/11/4097011_image2_1.jpg",
    },
    {
      id: "gyeongju_10won_bread",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "황리단길 십원빵",
      nameEn: "Hwangridan-gil 10-Won Coin Cheese Bread",
      descKo: "경주 다보탑이 새겨진 옛 10원짜리 동전 모양 빵 반죽 속에 고소한 모짜렐라 치즈가 길게 늘어나는 인기 길거리 디저트",
      descEn: "Fun waffle pastry shaped like Korea's historic 10-won coin, filled with stretchy melted mozzarella cheese and sweet custard's historic 10-won coin, filled with stretchy melted mozzarella cheese and sweet custard",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 3500,
      priceMinKrw: 3000,
      priceMaxKrw: 4500,
      isMustEatTop3: false,
      emoji: "🪙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/21/2904221_image2_1.jpg",
    },
    {
      id: "gyeongju_mukbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 메밀 묵밥",
      nameEn: "Gyeongju Buckwheat Jelly Mukbap",
      descKo: "부드럽고 쌉싸름한 메밀묵 채에 멸치 육수와 볶은 김치, 김가루를 얹어 밥을 말아 시원하게 먹는 전통 묵 요리",
      descEn: "Wholesome bowl of sliced buckwheat jelly served in chilled savory broth with finely chopped kimchi and seaweed",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8000,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_charcoal_ribs",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 천년한우 갈비살 구이",
      nameEn: "Gyeongju Hanwoo Rib Eye Charcoal BBQ",
      descKo: "마블링이 빼어난 경주 명품 천년한우의 갈비살을 참숯불에 살짝 구워 천일염과 기름장에 찍어 먹는 최고급 구이",
      descEn: "Prime cuts of local Gyeongju Hanwoo beef rib fingers grilled table-side over hardwood charcoal with sea salt",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 29000,
      priceMinKrw: 24000,
      priceMaxKrw: 38000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_traditional_soup",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 가마솥 한우 곰탕",
      nameEn: "Gyeongju Cauldron Hanwoo Gomtang (Beef Soup)",
      descKo: "무쇠 가마솥에 한우 양지와 사골을 푹 고아내 맑고 깊은 감칠맛을 자랑하는 70년 전통의 경주식 해장 국밥",
      descEn: "Clear, deeply flavorful beef broth slow-boiled in massive traditional iron cauldrons with tender brisket cuts and spring onions",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
  ],

  // === 8. 수원 (SUWON) ===
  SUWON: [
    {
      id: "suwon_wanggalbi",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 왕갈비",
      nameEn: "Suwon Wang-galbi (King Charcoal Beef Ribs)",
      descKo: "정조대왕 시절부터 이어져 온 수원의 상징으로, 큼직한 소갈비에 소금과 마늘, 참기름으로 담백하게 간한 명품 숯불구이",
      descEn: "Giant royal bone-in beef short ribs seasoned delicately with sea salt, sesame, and garlic, charcoal-grilled over hot coals's legendary meat dishes: massive prime beef ribs seasoned lightly with salt, garlic, and sesame",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 38000,
      priceMinKrw: 32000,
      priceMaxKrw: 52000,
      isMustEatTop3: true,
      emoji: "🥩",
      imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=472e0548-f287-4407-b728-318b1bd6dd36",
    },
    {
      id: "suwon_chicken_street",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 왕갈비 통닭",
      nameEn: "Suwon Wang-galbi Fried Chicken",
      descKo: "달콤짭조름한 특제 왕갈비 양념 소스를 바삭하게 튀긴 치킨에 버무려 전국적 인기를 얻은 수원의 대표 명물 통닭",
      descEn: "Crispy fried chicken tossed in sweet, savory, and aromatic Wang-galbi barbecue sauce, a famous signature of Suwon",
      categoryTag: "MEAL",
      unitPriceKrw: 21000,
      priceMinKrw: 19000,
      priceMaxKrw: 24000,
      isMustEatTop3: true,
      emoji: "🍗",
      imageUrl: "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=9385c5d0-c078-4d8f-b0d8-1ae0d6b63ee5",
    },
    {
      id: "suwon_wang_galbitang",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 왕갈비탕",
      nameEn: "Suwon Wang-galbitang (Giant Beef Rib Soup)",
      descKo: "성인 팔뚝만 한 거대한 소갈비 뼈 2대를 맑은 육수에 푹 고아 파와 당면을 넣고 푸짐하게 끓여낸 든든한 보양탕",
      descEn: "Enormous beef ribs cooked in clear aromatic broth with glass noodles and scallions, served with hot dipping mustard sauce",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🥣",
      imageUrl: "/assets/suwon-wang-galbitang.jpg",
    },
    {
      id: "suwon_boyoung_mandu",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 군만두 & 쫄면",
      nameEn: "Suwon Fried Mandu & Jjolmyeon",
      descKo: "바삭하게 튀긴 육즙 가득한 수제 군만두를 양배추 가득한 새콤달콤 매운 쫄면에 싸 먹는 수원 행궁동의 대표 분식",
      descEn: "Deep-fried crispy handmade pork dumplings paired with chewy noodles tossed in shredded cabbage and fiery spicy-sour sauce",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 9000,
      priceMinKrw: 7500,
      priceMaxKrw: 11500,
      isMustEatTop3: false,
      emoji: "🥟",
      imageUrl: "/assets/suwon-mandu-jjolmyeon.jpg",
    },
    {
      id: "suwon_jidong_sundae",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 지동시장 순대곱창 볶음",
      nameEn: "Jidong Market Sundae & Tripe Stir-fry",
      descKo: "철판에 순대와 쫄깃한 돼지 곱창, 깻잎, 팽이버섯, 당면을 들깨가루와 매콤한 양념장에 볶아 먹는 100년 전통 지동시장 요리",
      descEn: "Sizzling tabletop skillet stir-fry of blood sausage, pork intestine, perilla leaves, and chewy glass noodles in spicy sauce",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🥘",
      imageUrl: "/assets/suwon-jidong-sundaebokkeum.jpg",
    },
    {
      id: "suwon_hwaseong_dessert",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "생선구이 백반",
      nameEn: "Grilled Fish Feast Baekban",
      descKo: "노릇노릇 바삭하게 구워낸 신선한 모둠 생선구이와 정갈한 반찬, 따뜻한 밥과 국이 함께 나오는 푸짐한 한식 밥상",
      descEn: "Crispy grilled whole seasonal fish served with warm steamed rice, hearty soup, and an array of traditional Korean side dishes",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: false,
      emoji: "🐟",
      imageUrl: "/assets/suwon-saengseongui-baekban.jpg",
    },
    {
      id: "suwon_haejang_guk",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 소갈비 선지 해장국",
      nameEn: "Suwon Beef Rib & Blood Hangover Soup",
      descKo: "부드러운 소갈비와 신선한 선지, 우거지, 콩나물을 된장 육수에 푹 끓여내 구수하고 속이 확 풀리는 40년 전통 해장국",
      descEn: "Savory hangover cure soup featuring tender beef ribs, fresh clotted ox blood, soybean paste broth, and dried cabbage greens",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9500,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_gwanggyo_craft",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 행궁 만두 & 칼국수",
      nameEn: "Suwon Hand-folded Mandu & Kalguksu",
      descKo: "얇고 쫀득한 피에 고기와 김치 소를 가득 채운 손만두와 시원한 해물 육수의 칼국수 한상",
      descEn: "Steamed thin-skinned dumplings stuffed with minced pork and vegetables, paired with hot knife-cut seafood noodle soup",
      categoryTag: "MEAL",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🍕",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/36/2835336_image2_1.jpg",
    },
    {
      id: "suwon_memil_makguksu",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 봉평 메밀 막국수",
      nameEn: "Suwon Buckwheat Makguksu & Boiled Pork",
      descKo: "순메밀 국수를 시원한 동치미 육수에 말아 담백하고 쫄깃하게 즐기는 북수원 명품 막국수와 수육",
      descEn: "Nutty buckwheat cold noodles in refreshing radish broth served alongside thin slices of warm boiled pork belly",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8500,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2844758_image2_1.jpg",
    },
    {
      id: "suwon_jangan_seolleongtang",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "장안문 도가니탕",
      nameEn: "Janganmun Doganitang (Ox Knee Cartilage Soup)",
      descKo: "소 무릎 도가니와 사골을 가마솥에 진하게 고아내 쫀득쫀득한 콜라겐 식감과 구수한 국물이 일품인 보양 탕",
      descEn: "Rich, collagen-filled soup made by simmering ox knee cartilage and marrow bones until deeply nourishing and tender",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 14000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/05/4054005_image2_1.jpg",
    },
  ],

  // === 9. 인천 (INCHEON) ===
  INCHEON: [
    {
      id: "incheon_chinatown_jajang",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "인천 차이나타운 자장면",
      nameEn: "Incheon Chinatown Original Jajangmyeon",
      descKo: "1883년 개항 이후 화교들에 의해 탄생한 한국 자장면의 발상지 인천 차이나타운의 정통 자장면과 바삭한 탕수육",
      descEn: "Birthplace of Korean-Chinese black bean noodles in Incheon historic Chinatown, served with crispy sweet and sour pork",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🥢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/76/2848776_image2_1.jpg",
    },
    {
      id: "incheon_sinpo_dakgangjeong",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "신포 닭강정",
      nameEn: "Sinpo Market Dakgangjeong (Spicy Glazed Chicken)",
      descKo: "무쇠 가마솥에 바삭하게 튀긴 닭을 청양고추와 물엿 베이스의 매콤하고 쫀득한 붉은 소스에 즉석에서 볶아내는 신포시장 명물",
      descEn: "Fiery, crispy fried chicken chunks glazed in a simmering cauldron of sticky sweet-spicy chili syrup with whole dried peppers",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 19000,
      priceMinKrw: 17000,
      priceMaxKrw: 22000,
      isMustEatTop3: true,
      emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/04/4064804_image2_1.jpg",
    },
    {
      id: "incheon_crab_soup",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "서해 꽃게탕 & 간장게장",
      nameEn: "Incheon Blue Crab Spicy Soup & Soy Crab",
      descKo: "살과 알이 꽉 찬 서해안 암꽃게를 단호박, 무, 된장 육수에 얼큰하게 끓여낸 꽃게탕과 짭조름한 밥도둑 간장게장",
      descEn: "Sweet fresh West Sea blue crabs stewed in fragrant spicy broth with squash, served with legendary soy-marinated raw crab",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 38000,
      isMustEatTop3: true,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/39/2900039_image2_1.jpg",
    },
    {
      id: "incheon_baendaengi",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "연안부두 밴댕이회무침",
      nameEn: "Incheon Baendaengi (Spicy Herring Salad)",
      descKo: "연안부두 밴댕이 골목에서 갓 잡은 기름진 밴댕이 살을 미나리, 오이와 매콤새콤하게 버무려 밥에 비벼 먹는 별미",
      descEn: "Plump local silver-striped round herring raw fillets tossed with water parsley, garlic, and vinegar chili paste over warm rice",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/97/2846797_image2_1.jpg",
    },
    {
      id: "incheon_clay_oven_dumpling",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "차이나타운 화덕만두 & 공갈빵",
      nameEn: "Chinatown Clay Oven Dumpling & Gonggalppang",
      descKo: "200도가 넘는 옹기 화덕 안쪽 벽에 붙여 구워내 겉은 바삭하고 속은 육즙 가득한 고기만두와 속이 텅 빈 바삭한 공갈빵",
      descEn: "Unique charcoal tandoor-style clay oven baked buns stuffed with juicy minced pork, and crispy hollow honey-glazed crackers",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 4000,
      priceMinKrw: 3000,
      priceMaxKrw: 5500,
      isMustEatTop3: false,
      emoji: "🥟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/92/3526892_image2_1.jpg",
    },
    {
      id: "incheon_multeombeong",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "용현동 아귀찜 (물텀벙)",
      nameEn: "Yonghyeon-dong Agwi-jjim (Spicy Braised Monkfish)",
      descKo: "담백하고 쫄깃한 아귀 살에 아삭한 콩나물, 미더덕을 넣고 매콤 칼칼한 고춧가루 양념에 볶아낸 용현동 물텀벙이 거리 요리",
      descEn: "Meaty monkfish braised with crisp bean sprouts and sea squirts in a fiery, thick chili starch sauce on historical food street",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 30000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "incheon_sinpo_jjolmyeon",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "신포동 쫄면",
      nameEn: "Sinpo-dong Original Jjolmyeon (Chewy Spicy Noodles)",
      descKo: "인천 국수 공장에서 탄생한 원조 쫄면으로, 굵고 탄력 넘치는 면발에 아삭한 콩나물, 양배추, 매콤새콤 특제 초고추장을 비벼 먹는 요리",
      descEn: "Invented in Incheon: extra-chewy thick wheat noodles tossed with crisp cabbage, bean sprouts, hard-boiled egg, and sweet chili sauce",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 8500,
      priceMinKrw: 7000,
      priceMaxKrw: 10500,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "incheon_samchi_street",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "동인천 삼치구이",
      nameEn: "Dongincheon Samchi-gui (Grilled King Mackerel)",
      descKo: "동인천 삼치골목에서 살이 통통하게 오른 삼치를 연탄 숯불에 노릇하게 구워 와사비 간장에 찍어 막걸리와 즐기는 요리",
      descEn: "Giant thick fillets of Pacific Spanish mackerel grilled crispy on the outside and moist inside over hot coals, served with wasabi soy",
      categoryTag: "MEAL",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 17000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/40/3013740_image2_1.jpg",
    },
    {
      id: "incheon_songdo_clam_noodles",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "영종도 바지락 해물칼국수",
      nameEn: "Yeongjongdo Seafood Clam Kalguksu",
      descKo: "서해 갯벌에서 캔 바지락과 가리비, 새우를 산더미처럼 넣고 끓여 맑고 시원한 감칠맛이 일품인 영종도 바닷가 국수",
      descEn: "Enormous steaming shared bowl of fresh knife-cut noodles swimming with abundant sweet manila clams and prawns in sea broth",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9500,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/06/2900006_image2_1.jpg",
    },
    {
      id: "incheon_wolmido_clam_bake",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "월미도 조개구이",
      nameEn: "Wolmido Oceanfront Grilled Shellfish BBQ",
      descKo: "가리비, 키조개, 백합, 치즈구이를 연탄불 위에 지글지글 구워 초고추장에 찍어 먹는 월미도 바닷가의 대표 미식",
      descEn: "Interactive seaside tabletop BBQ feast grilling fresh scallops, pen shells, clams, and melted cheese over hot briquettes",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 32000,
      priceMinKrw: 28000,
      priceMaxKrw: 42000,
      isMustEatTop3: false,
      emoji: "🦪",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/4066258_image2_1.jpg",
    },
  ],

  // === 10. 여수 (YEOSU) ===
  YEOSU: [
    {
      id: "yeosu_dolgejang",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 돌게장 백반",
      nameEn: "Yeosu Dolgejang (Soy Marinated Rock Crab)",
      descKo: "여수 바다의 단단한 돌게를 비법 간장과 청양고추로 숙성시켜 게딱지에 밥을 쓱쓱 비벼 먹는 여수 최고의 밥도둑 백반",
      descEn: "Small native wild rock crabs steeped in aged seasoned soy sauce, packed with rich savory roe to mix with steamed rice",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_nangman_samhap",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 해물삼합",
      nameEn: "Yeosu Seafood Samhap (Kimchi, Pork & Octopus)",
      descKo: "여수 돌산 갓김치와 생삼겹살, 살아있는 문어(낙지), 전복, 새우를 철판에 함께 지글지글 볶아 싸 먹는 낭만포차 시그니처",
      descEn: "Sizzling iron plate surf-and-turf uniting famous Dolsan mustard greens kimchi, pork belly slices, fresh octopus, and abalone",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 24000,
      priceMinKrw: 20000,
      priceMaxKrw: 30000,
      isMustEatTop3: true,
      emoji: "🐙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_seodaehoe",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 서대회무침",
      nameEn: "Yeosu Seodaehoe (Spicy Tongue Sole Salad)",
      descKo: "전통 막걸리 발효 식초로 서대 살을 무쳐 비린내가 전혀 없고 새콤달콤한 감칠맛이 폭발하는 여수 10미 중 으뜸 요리",
      descEn: "Delicate raw tongue sole fish fillets tossed in natural fermented rice vinegar chili paste with fresh seasonal greens",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: true,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_gatkimchi_samgyeop",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "돌산 갓김치 삼겹살 구이",
      nameEn: "Dolsan Gat-Kimchi & Pork Belly BBQ",
      descKo: "특유의 톡 쏘는 알싸함과 깊은 감칠맛을 지닌 여수 돌산 갓김치를 돼지 삼겹살 기름에 함께 구워 싸 먹는 별미",
      descEn: "Sizzling pork belly grilled alongside intensely aromatic, pungent fermented mustard leaf kimchi (Gat Kimchi)",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 19000,
      priceMinKrw: 16000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/51/612151_image2_1.jpg",
    },
    {
      id: "yeosu_hamo_yubikki",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 갯장어 샤브샤브 (하모 유비끼)",
      nameEn: "Yeosu Hamo Shabu-shabu (Sea Pike Eel)",
      descKo: "칼집을 촘촘히 낸 갯장어 살을 한약재 육수에 살짝 담그면 눈꽃처럼 하얗게 피어나는 여수의 명품 여름 보양식",
      descEn: "Finely scored fillet slices of sweet wild sea pike eel briefly dipped in hot herbal broth until blooming like white flowers",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 38000,
      priceMinKrw: 32000,
      priceMaxKrw: 50000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_saejogae_shabu",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 새조개 샤브샤브",
      nameEn: "Yeosu Saejogae Shabu-shabu (Bird Clam)",
      descKo: "새의 부리를 닮은 고급 겨울 조개로, 맑은 채소 육수에 살짝 데쳐 쫄깃하고 달콤한 조갯살을 맛보는 여수 겨울 미식",
      descEn: "Prized winter delicacy featuring sweet, plump bird clams lightly parboiled in fragrant broth with winter spinach and leeks",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 35000,
      priceMinKrw: 30000,
      priceMaxKrw: 48000,
      isMustEatTop3: false,
      emoji: "🦪",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_eel_soup",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 통장어탕 & 장어구이",
      nameEn: "Yeosu Whole Sea Eel Stew & Grilled Eel",
      descKo: "살이 통통한 바다장어(붕장어)를 통째로 넣고 우거지와 된장, 고춧가루로 얼큰하고 진하게 끓여낸 원기 회복 탕",
      descEn: "Thick, deeply nourishing sea eel soup simmered with dried greens and spicy soybean paste, served with char-grilled fillets",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_jeoneo_feast",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 전어구이 & 전어회",
      nameEn: "Yeosu Gizzard Shad Feast (Autumn Fish)",
      descKo: "가을철 기름이 바짝 오른 고소한 전어를 통째로 칼집 내어 천일염을 뿌려 구워낸 가을 여수의 대표 생선 요리",
      descEn: "Whole seasonal autumn gizzard shad grilled with coarse sea salt, eaten bones and all for maximum buttery nutty richness",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 24000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_gat_burger",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 갓버거 & 갓도넛",
      nameEn: "Yeosu Gat-Burger (Mustard Green Burger)",
      descKo: "여수 돌산 갓김치 특유의 알싸한 소스와 두툼한 수제 고기 패티가 조화로운 이순신광장의 명물 수제 버거",
      descEn: "Creative local burger combining juicy handcrafted beef patty with distinctive spicy-tart Dolsan mustard green relish",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 7500,
      priceMinKrw: 6000,
      priceMaxKrw: 9500,
      isMustEatTop3: false,
      emoji: "🍔",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_galchi_set",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 통갈치조림 & 갈치회",
      nameEn: "Yeosu Braised Cutlassfish & Sashimi Set",
      descKo: "남해안 청정 바다에서 잡은 싱싱한 은갈치를 특제 롱 냄비에 통째로 졸여낸 조림과 투명하고 쫄깃한 갈치회 한상",
      descEn: "Spectacular meter-long whole silver cutlassfish braised with abalones and octopus, served with pristine fresh cutlassfish sashimi",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
  ],
};

// =========================================================================
// 3. 통합 카탈로그 및 헬퍼 함수
// =========================================================================

export const ALL_FOOD_ITEMS: FoodItemDefinition[] = [
  ...NATIONAL_K_FOODS,
  ...Object.values(CITY_SPECIALTY_FOODS).flat(),
];

export const FOOD_CATALOG_BY_ID: Map<string, FoodItemDefinition> = new Map(
  ALL_FOOD_ITEMS.map((item) => [item.id, item])
);

export function getNationalFoods(): FoodItemDefinition[] {
  return NATIONAL_K_FOODS;
}

export function getCityFoods(city: SupportedCity): FoodItemDefinition[] {
  return CITY_SPECIALTY_FOODS[city] || [];
}

export function getFoodById(id: string): FoodItemDefinition | undefined {
  return FOOD_CATALOG_BY_ID.get(id);
}
