import { SupportedCity } from "../../../lib/trip-domain";
import { FoodItemDefinition } from "../domain/types";

// =========================================================================
// 1. 🇰🇷 한국 대표 미식 (National K-Signature 20선)
// =========================================================================
export const NATIONAL_K_FOODS: FoodItemDefinition[] = [
  {
    id: "nat_samgyeopsal",
    scope: "NATIONAL",
    nameKo: "K-BBQ 삼겹살 / 목살",
    nameEn: "K-BBQ Pork Belly & Neck",
    descKo: "지글지글 구운 삼겹살을 쌈장, 마늘, 쌈채소와 함께 즐기는 한국인의 소울푸드",
    descEn: "Sizzling grilled pork belly wrapped in fresh lettuce with garlic and savory ssamjang dip",
    categoryTag: "BBQ_FEAST",
    unitPriceKrw: 18000,
    priceMinKrw: 16000,
    priceMaxKrw: 22000,
    isMustEatTop3: true,
    emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
  },
  {
    id: "nat_chimaek",
    scope: "NATIONAL",
    nameKo: "K-치맥 (양념반 후라이드반 & 생맥주)",
    nameEn: "K-Chimaek (Crispy & Yangnyeom Fried Chicken + Draft Beer)",
    descKo: "바삭한 튀김옷과 매콤달콤 양념치킨에 시원한 생맥주를 곁들이는 완벽한 야식",
    descEn: "Crispy fried and sweet-spicy glazed chicken paired with a cold draft beer",
    categoryTag: "MEAL",
    unitPriceKrw: 23000,
    priceMinKrw: 20000,
    priceMaxKrw: 27000,
    isMustEatTop3: true,
    emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/84/4071284_image2_1.jpg",
  },
  {
    id: "nat_tteokbokki_set",
    scope: "NATIONAL",
    nameKo: "분식 세트 (매콤 떡볶이 + 튀김 + 순대)",
    nameEn: "K-Street Snack Platter (Spicy Tteokbokki + Tempura + Sundae)",
    descKo: "쫄깃한 쌀떡과 매콤달콤한 고추장 소스, 갓 튀긴 바삭한 모둠튀김과 찰순대 세트",
    descEn: "Chewy rice cakes in sweet-spicy chili sauce paired with crispy fritters and steamed blood sausage",
    categoryTag: "STREET_SNACK",
    unitPriceKrw: 12000,
    priceMinKrw: 9000,
    priceMaxKrw: 15000,
    isMustEatTop3: true,
    emoji: "🍢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/43/2831643_image2_1.jpg",
  },
  {
    id: "nat_bibimbap",
    scope: "NATIONAL",
    nameKo: "전통 비빔밥 & 된장찌개 정식",
    nameEn: "Traditional Bibimbap & Doenjang Jjigae Set",
    descKo: "다양한 제철 나물과 고소한 참기름, 고추장을 밥과 쓱쓱 비벼 먹는 건강한 한 끼",
    descEn: "Steamed rice bowl topped with fresh seasoned vegetables, fried egg, chili paste, and sesame oil",
    categoryTag: "MEAL",
    unitPriceKrw: 11000,
    priceMinKrw: 9000,
    priceMaxKrw: 14000,
    isMustEatTop3: false,
    emoji: "🥗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/86/2837886_image2_1.jpg",
  },
  {
    id: "nat_kimchi_jjigae",
    scope: "NATIONAL",
    nameKo: "돼지고기 듬뿍 김치찌개 백반 & 라면사리",
    nameEn: "Pork Kimchi Stew Set with Ramen Noodles",
    descKo: "잘 익은 묵은지와 두툼한 돼지고기를 푹 끓여낸 얼큰하고 시원한 밥도둑 찌개",
    descEn: "Hearty, spicy stew brewed with aged kimchi, tender pork slices, tofu, and ramen noodles",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 9000,
    priceMaxKrw: 12000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/88/2796888_image2_1.JPG",
  },
  {
    id: "nat_samgyetang",
    scope: "NATIONAL",
    nameKo: "영양 삼계탕 (한마리 & 찹쌀 인삼)",
    nameEn: "Ginseng Chicken Soup (Whole Young Chicken with Sticky Rice)",
    descKo: "어린 닭에 찹쌀, 인삼, 대추, 마늘을 채워 진하게 고아낸 전통 보양식",
    descEn: "Traditional health-boosting soup made with a whole young chicken stuffed with glutinous rice and ginseng",
    categoryTag: "MEAL",
    unitPriceKrw: 18000,
    priceMinKrw: 16000,
    priceMaxKrw: 22000,
    isMustEatTop3: false,
    emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/24/2847724_image2_1.JPG",
  },
  {
    id: "nat_bulgogi",
    scope: "NATIONAL",
    nameKo: "한우 불고기 전골 & 당면사리",
    nameEn: "Beef Bulgogi Hotpot with Glass Noodles",
    descKo: "달콤 짭조름한 특제 간장 양념에 얇게 썬 소고기와 버섯, 당면을 보글보글 끓인 요리",
    descEn: "Tender beef slices marinated in sweet soy sauce stewed with mushrooms, vegetables, and glass noodles",
    categoryTag: "MEAL",
    unitPriceKrw: 20000,
    priceMinKrw: 17000,
    priceMaxKrw: 25000,
    isMustEatTop3: false,
    emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/2903763_image2_1.png",
  },
  {
    id: "nat_shabushabu",
    scope: "NATIONAL",
    nameKo: "소고기 버섯 샤브샤브 & 칼국수 / 죽",
    nameEn: "Beef & Mushroom Shabu-shabu with Kalguksu & Porridge",
    descKo: "신선한 야채와 얇게 썬 소고기를 담백한 육수에 살짝 데쳐 먹은 후 칼국수와 죽으로 마무리",
    descEn: "Thinly sliced beef and fresh seasonal vegetables simmered in hot broth, finished with noodles and porridge",
    categoryTag: "MEAL",
    unitPriceKrw: 16000,
    priceMinKrw: 14000,
    priceMaxKrw: 20000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "/assets/food/shabushabu.jpg",
  },
  {
    id: "nat_dakgalbi",
    scope: "NATIONAL",
    nameKo: "춘천식 매콤 닭갈비 & 치즈 볶음밥",
    nameEn: "Chuncheon-style Spicy Stir-fried Chicken & Cheese Fried Rice",
    descKo: "매콤한 양념 닭고기에 양배추, 고구마, 떡을 철판에 볶아 먹고 고소한 치즈 볶음밥으로 완성",
    descEn: "Pan-fried chicken chunks marinated in spicy sauce with sweet potatoes, rice cakes, and melted cheese rice",
    categoryTag: "MEAL",
    unitPriceKrw: 16000,
    priceMinKrw: 14000,
    priceMaxKrw: 19000,
    isMustEatTop3: false,
    emoji: "🍳",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/53/2841653_image2_1.jpg",
  },
  {
    id: "nat_haemul_pajeon",
    scope: "NATIONAL",
    nameKo: "해물파전 & 전통 막걸리 한 병",
    nameEn: "Seafood Scallion Pancake & Traditional Rice Makgeolli",
    descKo: "오징어와 새우 등 해산물과 쪽파를 노릇노릇 부쳐낸 바삭한 전과 달콤 톡 쏘는 막걸리",
    descEn: "Crispy pancake packed with fresh squid, prawns, and scallions served alongside refreshing cloudy rice wine",
    categoryTag: "BBQ_FEAST",
    unitPriceKrw: 19000,
    priceMinKrw: 16000,
    priceMaxKrw: 24000,
    isMustEatTop3: false,
    emoji: "🥞",
    imageUrl: "/assets/food/pajeon.jpg",
  },
  {
    id: "nat_sundubu",
    scope: "NATIONAL",
    nameKo: "해물 순두부찌개 정식 & 솥밥",
    nameEn: "Spicy Soft Tofu Stew with Hot Stone Rice",
    descKo: "부드러운 순두부와 조개, 새우, 계란이 어우러져 칼칼하고 부드러운 국물 요리",
    descEn: "Silken soft tofu bubbling in spicy seafood broth with clams, shrimp, egg, and fresh stone pot rice",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 9000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/70/2873170_image2_1.jpg",
  },
  {
    id: "nat_gamjatang",
    scope: "NATIONAL",
    nameKo: "뚝배기 뼈다귀 해장국 / 감자탕",
    nameEn: "Pork Backbone Soup (Gamjatang)",
    descKo: "살코기가 푸짐한 돼지 등뼈와 우거지, 들깨가루를 듬뿍 넣어 푹 고아낸 진한 국물",
    descEn: "Hearty pork backbone soup simmered with dried radish greens, crushed perilla seeds, and rich savory broth",
    categoryTag: "MEAL",
    unitPriceKrw: 11000,
    priceMinKrw: 10000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/68/2846968_image2_1.jpg",
  },
  {
    id: "nat_budae_jjigae",
    scope: "NATIONAL",
    nameKo: "얼큰 부대찌개 (스팸+소시지+라면사리)",
    nameEn: "Budae Jjigae (Korean Army Base Stew)",
    descKo: "햄, 소시지, 치즈, 떡, 김치와 라면사리를 푸짐하게 끓여낸 중독성 강한 찌개",
    descEn: "Savory fusion stew made with ham, sausages, baked beans, kimchi, melted cheese, and ramen noodles",
    categoryTag: "MEAL",
    unitPriceKrw: 12000,
    priceMinKrw: 10000,
    priceMaxKrw: 15000,
    isMustEatTop3: false,
    emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/37/2877237_image2_1.jpg",
  },
  {
    id: "nat_naengmyeon",
    scope: "NATIONAL",
    nameKo: "시원한 물냉면 / 비빔냉면 & 찐만두",
    nameEn: "Cold Buckwheat Naengmyeon & Steamed Dumplings",
    descKo: "살얼음 동동 띄운 시원한 동치미 육수 냉면 또는 매콤달콤 비빔냉면에 만두 곁들임",
    descEn: "Chilled chewy buckwheat noodles in icy beef-radish broth or spicy sauce, served with juicy dumplings",
    categoryTag: "MEAL",
    unitPriceKrw: 13000,
    priceMinKrw: 11000,
    priceMaxKrw: 16000,
    isMustEatTop3: false,
    emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/70/2873170_image2_1.jpg",
  },
  {
    id: "nat_street_toast",
    scope: "NATIONAL",
    nameKo: "K-길거리 토스트 & 바나나우유 (간편 조식)",
    nameEn: "K-Street Egg Toast & Banana Milk (Quick Breakfast)",
    descKo: "버터에 구운 빵에 달걀 야채 패티, 햄, 설탕, 케첩을 얹은 달콤 고소한 한국식 아침 토스트",
    descEn: "Buttery griddled toast sandwich with egg cabbage omelette, ham, sugar sprinkle, and sweet ketchup",
    categoryTag: "STREET_SNACK",
    unitPriceKrw: 5500,
    priceMinKrw: 4500,
    priceMaxKrw: 7000,
    isMustEatTop3: false,
    emoji: "🥪",
    imageUrl: "/assets/food/toast.jpg",
  },
  {
    id: "nat_kkwabaegi_bungeoppang",
    scope: "NATIONAL",
    nameKo: "전통시장 찹쌀 꽈배기 & 바삭 붕어빵",
    nameEn: "Market Twisted Doughnuts (Kkbaegi) & Bungeoppang",
    descKo: "설탕 묻힌 쫄깃한 찹쌀 꽈배기와 달콤한 팥/슈크림이 가득 찬 황금빛 붕어빵",
    descEn: "Warm, chewy sugar-dusted twisted donuts and fish-shaped crispy pastries filled with sweet red bean or custard",
    categoryTag: "DESSERT_CAFE",
    unitPriceKrw: 4000,
    priceMinKrw: 3000,
    priceMaxKrw: 6000,
    isMustEatTop3: false,
    emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/08/3421808_image2_1.jpg",
  },
  {
    id: "nat_bingsu",
    scope: "NATIONAL",
    nameKo: "인절미 눈꽃 팥빙수 & 연유",
    nameEn: "Injeolmi Snowflake Milk Bingsu with Condensed Milk",
    descKo: "부드러운 우유 눈꽃 얼음 위에 고소한 콩가루, 쫄깃한 떡, 달콤한 팥과 연유를 듬뿍 올린 빙수",
    descEn: "Fluffy shaved milk ice topped with nutty roasted bean powder, chewy rice cakes, and sweet condensed milk",
    categoryTag: "DESSERT_CAFE",
    unitPriceKrw: 13000,
    priceMinKrw: 11000,
    priceMaxKrw: 16000,
    isMustEatTop3: false,
    emoji: "🍧",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/74/2901174_image2_1.jpg",
  },
  {
    id: "nat_sogalbijjim",
    scope: "NATIONAL",
    nameKo: "뚝배기 소갈비찜 정식 & 공깃밥",
    nameEn: "Braised Beef Short Ribs (Sogalbi Jjim) Set",
    descKo: "부드럽게 익힌 소갈비와 밤, 당근, 버섯에 달콤 짭조름한 특제 양념이 깊게 밴 전통 일품요리",
    descEn: "Melt-in-your-mouth braised beef short ribs simmered in rich sweet soy glaze with chestnuts and carrots",
    categoryTag: "MEAL",
    unitPriceKrw: 20000,
    priceMinKrw: 17000,
    priceMaxKrw: 26000,
    isMustEatTop3: false,
    emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/60/3567160_image2_1.jpg",
  },
  {
    id: "nat_jajangmyeon_mandu",
    scope: "NATIONAL",
    nameKo: "원조 자장면 & 바삭 군만두 세트",
    nameEn: "Classic Jajangmyeon (Black Bean Noodles) & Fried Dumplings",
    descKo: "고소한 춘장 소스에 볶은 돼지고기 양파 소스를 쫄깃한 면에 비벼 먹고 바삭한 군만두 곁들임",
    descEn: "Chewy noodles tossed in rich roasted black bean sauce with diced pork, served with golden crispy dumplings",
    categoryTag: "MEAL",
    unitPriceKrw: 10000,
    priceMinKrw: 8000,
    priceMaxKrw: 13000,
    isMustEatTop3: false,
    emoji: "🥢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/82/2877982_image2_1.jpg",
  },
  {
    id: "nat_hanjeongsik",
    scope: "NATIONAL",
    nameKo: "정갈한 수라 한정식 코스 (프리미엄)",
    nameEn: "Royal Court Hanjeongsik (Multi-course Feast)",
    descKo: "신선한 전채 요리부터 구이, 탕, 계절 반찬 10여 가지가 정갈하게 차려지는 정통 한국 코스",
    descEn: "Elaborate multi-course Korean banquet featuring royal appetizers, grilled meats, savory stews, and side dishes",
    categoryTag: "MEAL",
    unitPriceKrw: 45000,
    priceMinKrw: 35000,
    priceMaxKrw: 65000,
    isMustEatTop3: false,
    emoji: "🍱",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/90/2871590_image2_1.jpg",
  },
];

// =========================================================================
// 2. 🏙️ 10개 도시별 로컬 대표 미식 (City Specialties 각 10선 = 총 100선)
// =========================================================================
export const CITY_SPECIALTY_FOODS: Record<SupportedCity, FoodItemDefinition[]> = {
  // === 1. 서울 (SEOUL) ===
  SEOUL: [
    {
      id: "seoul_gwangjang_pancake",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "광장시장 맷돌 녹두빈대떡 & 마약김밥",
      nameEn: "Gwangjang Market Mung Bean Pancake & Mayak Gimbap",
      descKo: "기름에 바삭하게 부쳐낸 고소한 맷돌 빈대떡과 중독성 강한 겨자소스 꼬마김밥",
      descEn: "Crispy griddled mung bean pancake paired with mini bite-sized seaweed rice rolls with tangy mustard dip",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 9000,
      priceMinKrw: 7000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🥞",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/81/2668981_image2_1.jpg",
    },
    {
      id: "seoul_seolleongtang",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "종로 전통 가마솥 설렁탕 & 깍두기",
      nameEn: "Jongno Traditional Ox Bone Seolleongtang & Radish Kimchi",
      descKo: "사골을 오랜 시간 뽀얗게 우려낸 담백한 국물에 소면과 얇게 썬 양지, 잘 익은 깍두기",
      descEn: "Milky white ox bone soup simmered for 15 hours, served with tender beef slices, noodles, and crunchy kimchi",
      categoryTag: "MEAL",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 16000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/36/3094136_image2_1.jpg",
    },
    {
      id: "seoul_sindang_tteokbokki",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "신당동 원조 즉석떡볶이 타운 풀세트",
      nameEn: "Sindang-dong Tabletop Cooked Tteokbokki Full Set",
      descKo: "춘장과 고추장의 황금비율 소스에 라면, 쫄면, 야끼만두, 계란을 즉석에서 보글보글 끓여 먹는 요리",
      descEn: "Iconic table-cooked spicy rice cakes with ramen, glass noodles, fried dumplings, and eggs in savory-spicy broth",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: true,
      emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/74/3083874_image2_1.JPG",
    },
    {
      id: "seoul_mapo_galbi",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "마포 참숯 돼지갈비 구이",
      nameEn: "Mapo Charcoal-grilled Seasoned Pork Galbi",
      descKo: "특제 양념에 숙성한 달콤 짭조름한 돼지갈비를 참숯불에 노릇하게 구워 먹는 서울 명물",
      descEn: "Tender pork spare ribs marinated in sweet and savory soy glaze grilled over glowing natural charcoal",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 17000,
      priceMinKrw: 15000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/31/2900431_image2_1.jpg",
    },
    {
      id: "seoul_dongdaemun_dakhanmari",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "동대문 닭한마리 칼국수 & 다대기 소스",
      nameEn: "Dongdaemun Whole Chicken Hotpot with Kalguksu",
      descKo: "양은 냄비에 닭 한 마리를 통째로 넣고 맑은 육수에 끓여 매콤 겨자 소스에 찍어 먹는 별미",
      descEn: "Whole tender chicken boiled in rich clear chicken broth, dipped in spicy mustard chive sauce, finished with noodles",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 19000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/43/4041943_image2_1.jpg",
    },
    {
      id: "seoul_namdaemun_galchijorim",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "남대문 시장 매콤 갈치조림 골목 한상",
      nameEn: "Namdaemun Market Spicy Braised Cutlassfish Alley Set",
      descKo: "양은 냄비에 두툼한 갈치와 푹 익은 무를 매콤달콤하게 졸여낸 밥도둑 시장 전통 요리",
      descEn: "Fiery braised beltfish and sweet radishes simmered down in spicy red chili garlic sauce in iconic market alley",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/35/3082835_image2_1.png",
    },
    {
      id: "seoul_euljiro_golbaengi",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "을지로 노가리 골목 새콤달콤 골뱅이무침",
      nameEn: "Euljiro Hipjiro Spicy Sea Snail Salad with Scallions",
      descKo: "푸짐한 통골뱅이와 파채, 고춧가루, 어포를 매콤새콤하게 버무려 맥주와 함께 즐기는 힙지로 안주",
      descEn: "Plump sea snails tossed with fresh scallion threads, chili powder, and fish jerky in historic retro alleyway",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🥗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/41/4020541_image2_1.jpeg",
    },
    {
      id: "seoul_bukchon_sujebi",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "북촌 삼청동 항아리 손수제비 & 감자전",
      nameEn: "Samcheong-dong Hand-pulled Dough Sujebi & Potato Pancake",
      descKo: "바지락과 멸치로 우려낸 시원한 국물에 얇게 뜯어 넣은 쫄깃한 반죽과 쫀득한 감자전",
      descEn: "Hand-torn chewy dough flakes in savory clam broth served inside an earthenware jar with crisp potato pancake",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/84/3446384_image2_1.JPG",
    },
    {
      id: "seoul_itaewon_fusion",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "이태원 K-갈비 타코 & 수제 크래프트 비어",
      nameEn: "Itaewon K-Galbi Taco & Craft Beer",
      descKo: "한국식 숯불 양념 갈비와 김치 살사를 또띠아에 얹어 다국적 분위기에서 즐기는 퓨전 다이닝",
      descEn: "Korean marinated short rib BBQ and kimchi salsa inside warm tortillas served with Seoul local craft beer",
      categoryTag: "MEAL",
      unitPriceKrw: 16000,
      priceMinKrw: 13000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🌮",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/59/4017659_image2_1.jpg",
    },
    {
      id: "seoul_jangchung_jokbal",
      scope: "CITY_LOCAL",
      cityCode: "SEOUL",
      nameKo: "장충동 원조 한방 족발 & 보쌈 세트",
      nameEn: "Jangchung-dong Glazed Braised Pork Trotters & Bossam",
      descKo: "한약재와 비법 육수에 푹 삶아 쫄깃하고 부드러운 껍질과 촉촉한 살코기의 원조 족발",
      descEn: "Tender, savory braised pork trotters infused with herbal spices, wrapped with spicy salted kimchi and crisp lettuce",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 36000,
      isMustEatTop3: false,
      emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/72/3589072_image2_1.jpg",
    },
  ],

  // === 2. 부산 (BUSAN) ===
  BUSAN: [
    {
      id: "busan_dwaeji_gukbap",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 원조 돼지국밥 & 맛보기 순대",
      nameEn: "Original Busan Dwaeji Gukbap (Pork Soup) & Sundae",
      descKo: "진하게 우려낸 돼지 사골 육수에 부드러운 수육과 부추무침, 다대기를 풀어 든든하게 먹는 부산 1위",
      descEn: "Busan's pride: rich, comforting pork bone broth packed with tender pork slices and fresh seasoned garlic chives",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_milmyeon",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "시원한 살얼음 부산 밀면 & 만두",
      nameEn: "Busan Chilled Wheat Milmyeon & Steamed Dumplings",
      descKo: "한약재와 소뼈로 우려낸 살얼음 육수에 쫄깃한 밀가루 면과 매콤한 양념장을 비벼 먹는 여름 별미",
      descEn: "Refreshing chilled wheat flour noodles in aromatic herbal beef broth topped with boiled egg and sweet spicy sauce",
      categoryTag: "MEAL",
      unitPriceKrw: 9500,
      priceMinKrw: 8000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/88/3049888_image2_1.JPG",
    },
    {
      id: "busan_ssiat_hotteok",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "남포동 BIFF거리 원조 씨앗호떡",
      nameEn: "Nampo-dong BIFF Square Sweet Seed-stuffed Hotteok",
      descKo: "마가린에 튀기듯 구운 찹쌀 반죽을 갈라 흑설탕과 고소한 해바라기씨, 견과류를 가득 채운 간식",
      descEn: "Golden griddled sweet pancake pocket bursting with caramelized brown sugar, sunflower seeds, and crushed nuts",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 2500,
      priceMinKrw: 2000,
      priceMaxKrw: 3500,
      isMustEatTop3: true,
      emoji: "🥞",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/94/2786894_image2_1.png",
    },
    {
      id: "busan_jagalchi_rawfish",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "자갈치시장 제철 활어회 & 칼칼 매운탕",
      nameEn: "Jagalchi Fish Market Fresh Sashimi & Spicy Fish Stew",
      descKo: "부산 바다에서 갓 건져 올린 광어, 우럭 제철 활어회와 얼큰하게 끓인 서더리 매운탕",
      descEn: "Ultra-fresh Korean style sliced raw seasonal fish served with chili garlic paste and bubbling spicy fish head stew",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 30000,
      priceMinKrw: 25000,
      priceMaxKrw: 40000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/13/2941313_image2_1.bmp",
    },
    {
      id: "busan_gijang_eel",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "기장 짚불 곰장어 소금구이",
      nameEn: "Gijang Straw-fired Sea Hagfish (Eel) BBQ",
      descKo: "볏짚에 불을 붙여 순간 화력으로 훈연 구워낸 고소하고 쫄깃한 식감의 기장 명물 곰장어",
      descEn: "Distinctive Korean delicacy: chewy ocean hagfish flash-roasted inside burning straw rice stalks for smoky aroma",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 35000,
      isMustEatTop3: false,
      emoji: "🔥",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/83/4039583_image2_1.jpg",
    },
    {
      id: "busan_nakgop_sae",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 명물 낙곱새 전골 & 우동사리",
      nameEn: "Busan Nak-Gop-Sae (Octopus, Intestine, Shrimp Hotpot)",
      descKo: "쫄깃한 낙지, 고소한 대창, 탱글한 새우를 매콤한 양념에 자작하게 끓여 밥 위에 비벼 먹는 요리",
      descEn: "Tri-ingredient spicy hotpot combining tender octopus, beef intestines, and fresh shrimp scooped over rice bowl",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: false,
      emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_eomuk_mooltteok",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부산 포장마차 삼진어묵 & 가래떡 물떡 꼬치",
      nameEn: "Busan Authentic Fishcake & Soft Rice Cake Mooltteok Skewers",
      descKo: "시원한 게 꽃게 육수에 푹 담가 부드럽게 익힌 어묵 꼬치와 쫀득한 가래떡 물떡",
      descEn: "Skewered premium Busan fish cakes and cylindrical rice cakes soaked in hot crab-infused kelp broth",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 4500,
      priceMinKrw: 3000,
      priceMaxKrw: 6500,
      isMustEatTop3: false,
      emoji: "🍢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/80/2759680_image2_1.jpg",
    },
    {
      id: "busan_naengchae_jokbal",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "부평 깡통시장 톡 쏘는 냉채족발",
      nameEn: "Bupyeong Kkangtong Market Chilled Jellyfish Mustard Jokbal",
      descKo: "얇게 썬 족발에 해파리, 오이와 톡 쏘는 새콤달콤 겨자 소스를 버무려 상큼하게 즐기는 냉채 요리",
      descEn: "Chilled thinly sliced pig's trotters tossed with jellyfish, cucumber slices, and sinus-clearing mustard dressing",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2833858_image2_1.jpg",
    },
    {
      id: "busan_dongnae_pajeon",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "동래 전통 해물파전 & 산성 막걸리",
      nameEn: "Dongnae Royal Seafood Scallion Pancake & Mountain Wine",
      descKo: "달콤한 조선 쪽파와 풍성한 해물, 찹쌀 반죽에 달걀을 얹어 촉촉하고 부드럽게 구운 부산 향토음식",
      descEn: "Thick, moist traditional pancake layering sweet whole green scallions, diced clams and squid, topped with whipped egg",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 20000,
      priceMinKrw: 16000,
      priceMaxKrw: 25000,
      isMustEatTop3: false,
      emoji: "🥞",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/65/2778665_image2_1.jpg",
    },
    {
      id: "busan_haenyeo_ramen",
      scope: "CITY_LOCAL",
      cityCode: "BUSAN",
      nameKo: "영도 흰여울 해녀촌 전복 해물라면",
      nameEn: "Yeongdo Coastal Haenyeo Fresh Abalone Seafood Ramen",
      descKo: "바다를 바라보며 해녀가 직접 채취한 싱싱한 전복, 홍합, 게를 듬뿍 넣고 끓여낸 얼큰한 해물라면",
      descEn: "Spicy Korean ramen bubbling with freshly caught abalone, mussels, and wild crabs right by the ocean cliff",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/69/2844169_image2_1.JPG",
    },
  ],

  // === 3. 제주 (JEJU) ===
  JEJU: [
    {
      id: "jeju_black_pork",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 흑돼지 참숯 근고기 구이 & 멜젓",
      nameEn: "Jeju Island Black Pork Thick Cut BBQ with Meljeot Dip",
      descKo: "두툼하게 썰어낸 제주 토종 흑돼지를 참숯에 구워 보글보글 끓인 멸치젓갈(멜젓)에 콕 찍어 먹는 명물",
      descEn: "Thick charcoal-grilled premium black pork steaks dipped in bubbling fermented anchovy sauce (Meljeot)",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 25000,
      priceMinKrw: 22000,
      priceMaxKrw: 32000,
      isMustEatTop3: true,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_gogi_guksu",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 진한 사골 고기국수 & 돔베고기",
      nameEn: "Jeju Savory Pork Broth Gogi Guksu with Dombe Slices",
      descKo: "돼지 사골을 푹 우려낸 뽀얗고 구수한 육수에 도톰한 중면과 부드러운 수육 고명을 얹은 국수",
      descEn: "Rich, creamy pork bone noodle soup topped with boiled pork belly slices and scallions, unique to Jeju",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_galchi_jorim",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 은갈치 통갈치조림 & 구이 정식",
      nameEn: "Jeju Silver Cutlassfish Long Braised Stew & Grilled Set",
      descKo: "제주 청정 바다의 은빛 갈치를 매콤 칼칼한 양념과 무, 감자와 함께 1미터 철판에 졸여 먹는 밥도둑",
      descEn: "Spectacular whole silver cutlassfish braised with sweet potatoes and spicy chili glaze in a long iron pan",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 32000,
      priceMinKrw: 28000,
      priceMaxKrw: 42000,
      isMustEatTop3: true,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_abalone_porridge",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 자연산 활전복죽 & 해물뚝배기",
      nameEn: "Jeju Green Abalone Porridge & Seafood Claypot Soup",
      descKo: "전복 내장(게우)을 듬뿍 넣어 녹진하고 고소한 전복죽과 딱새우, 조개가 들어간 시원한 뚝배기",
      descEn: "Velvety rice porridge colored green with rich abalone entrails, served with aromatic seafood claypot stew",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_ttaksaewoo_sashimi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 달콤한 딱새우회 & 모둠해산물",
      nameEn: "Jeju Sweet Red Banded Lobster (Ttaksaewoo) Sashimi",
      descKo: "껍질을 손질해 입에 넣으면 사르르 녹아내리는 달콤하고 탱글탱글한 제주산 딱새우 생선회",
      descEn: "Sweet, melt-in-the-mouth raw red-banded spiny lobsters caught locally around Jeju's pristine waters",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 25000,
      priceMinKrw: 20000,
      priceMaxKrw: 32000,
      isMustEatTop3: false,
      emoji: "🦐",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_bomal_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 바다 향 가득 보말칼국수 & 보말전",
      nameEn: "Jeju Sea Snail Bomal Kalguksu & Savory Pancake",
      descKo: "제주 갯바위에서 채취한 고둥(보말)을 갈아 넣어 짙은 초록빛 국물이 일품인 깊은 맛의 칼국수",
      descEn: "Hearty handmade knife-cut noodle soup enriched with dark green broth made from nutrient-rich ocean sea snails",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_citrus_omegi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 한라봉 감귤 디저트 & 오메기떡",
      nameEn: "Jeju Hallabong Tangerine Sorbet & Omegi Rice Cake",
      descKo: "달콤 상큼한 한라봉 아이스크림과 쑥떡 속에 팥 앙금을 넣고 겉에 통팥을 묻힌 제주 전통 떡",
      descEn: "Refreshing citrus gelato made from Jeju Hallabong tangerines paired with traditional red bean Omegi mochi",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 6000,
      priceMinKrw: 4500,
      priceMaxKrw: 8000,
      isMustEatTop3: false,
      emoji: "🍊",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_dombe_gogi",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 도마 수육 (돔베고기) & 쌈채소",
      nameEn: "Jeju Dombe Gogi (Boiled Pork Served on Wooden Board)",
      descKo: "갓 삶은 따뜻한 돼지고기 수육을 도마(돔베)에 썰어 굵은 소금과 갈치속젓에 싸 먹는 요리",
      descEn: "Succulent freshly sliced boiled pork belly served directly on a rustic wooden cutting board with coarse salt",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_hanchi_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 살얼음 한치물회 & 된장 물회",
      nameEn: "Jeju Chilled Squid Mulhoe with Fermented Bean Broth",
      descKo: "달콤 쫄깃한 싱싱한 한치회에 오이, 미나리, 고추장과 된장 베이스의 새콤한 얼음 육수를 부어 먹는 냉국",
      descEn: "Slivers of sweet fresh squid floating in icy, tangy red chili and fermented soybean broth with crisp cucumbers",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
    {
      id: "jeju_okdom_gui",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "제주 노릇한 옥돔구이 백반 정식",
      nameEn: "Jeju Pan-fried Red Tilefish (Okdom) Meal Set",
      descKo: "제주 특산 옥돔을 해풍에 꾸덕하게 말려 참기름에 고소하게 구워낸 임금님 진상품 생선구이",
      descEn: "Prized local Red Tilefish, sea-breeze dried and pan-seared until skin is crispy and meat is tender and sweet",
      categoryTag: "MEAL",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/33/2870533_image2_1.jpg",
    },
  ],

  // === 4. 전주 (JEONJU) ===
  JEONJU: [
    {
      id: "jeonju_bibimbap",
      scope: "CITY_LOCAL",
      cityCode: "JEJU",
      nameKo: "전주 전통 놋그릇 육회비빔밥 & 콩나물국",
      nameEn: "Authentic Jeonju Yukhoe (Beef Tartare) Bibimbap Set",
      descKo: "따뜻한 놋그릇에 사골로 지은 밥, 황포묵, 신선한 육회와 10가지 나물이 어우러진 비빔밥의 본고장 요리",
      descEn: "Korea's culinary crown jewel: beef broth rice served in heavy brass bowl with seasoned beef tartare and 10 herbs",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: true,
      emoji: "🥗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_kongnamul_gukbap",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 남부시장 콩나물국밥 & 수란",
      nameEn: "Jeonju Nambu Market Bean Sprout Gukbap & Poached Egg",
      descKo: "아삭한 전주 콩나물과 오징어 사리, 청양고추로 우려낸 개운한 국물에 고소한 수란을 곁들이는 해장국",
      descEn: "Refreshing soul food: crunchy bean sprouts simmered in savory broth with diced squid and poached egg with seaweed",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_pi_sundae",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 남부시장 원조 피순대국밥 & 모둠수육",
      nameEn: "Jeonju Authentic Blood Sundae Stew & Steamed Pork",
      descKo: "선지와 채소로 속을 꽉 채워 크리미하고 진한 맛의 전주식 전통 피순대와 얼큰한 국밥",
      descEn: "Rich, creamy blood sausage packed with vegetables and pork, served in spicy bubbling broth with 초고추장 dip",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 13000,
      isMustEatTop3: true,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_hanjeongsik_full",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 30첩 반상 명품 한정식 풀코스",
      nameEn: "Jeonju 30-dish Masterclass Grand Hanjeongsik",
      descKo: "맛의 고장 전주의 진수를 보여주는 떡갈비, 신선로, 홍어삼합, 게장 등 상다리 부러지는 진수성찬",
      descEn: "The absolute pinnacle of Korean dining: over 30 traditional side dishes, grilled short ribs, and royal hotpot",
      categoryTag: "MEAL",
      unitPriceKrw: 40000,
      priceMinKrw: 30000,
      priceMaxKrw: 60000,
      isMustEatTop3: false,
      emoji: "🍱",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_gamaek",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 가맥거리 황태포 & 마약 간장마요 소스",
      nameEn: "Jeonju Gamaek (Corner Store Pub) Crispy Dried Pollock",
      descKo: "연탄불에 바삭하게 구운 두툼한 황태포를 청양고추 간장마요 비법 소스에 찍어 차가운 맥주와 먹는 문화",
      descEn: "Unique local culture: charcoal-toasted crispy whole dried pollock dipped in addictive spicy mayo soy sauce with cold beer",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: false,
      emoji: "🍺",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_tteokgalbi",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 수제 떡갈비 솥밥 정식",
      nameEn: "Handcrafted Grilled Beef-Pork Tteokgalbi & Pot Rice",
      descKo: "갈빗살을 곱게 다져 달콤한 양념에 치댄 후 숯불에 구워낸 육즙 가득한 떡갈비와 갓 지은 솥밥",
      descEn: "Succulent minced rib meat patty glazed with sweet soy marinade, chargrilled and served with steaming stone rice",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 16000,
      priceMinKrw: 13000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_moju_pajeon",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 모주 (한방 전통주) & 해물파전",
      nameEn: "Jeonju Warm Herbal Moju Wine & Crispy Scallion Pancake",
      descKo: "막걸리에 계피, 생강, 대추, 감초를 넣고 알코올이 거의 없게 달여낸 향긋하고 달콤한 건강 음료",
      descEn: "Gentle low-alcohol spiced wine brewed with cinnamon, ginger, and dates, paired with golden seafood pancake",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 12000,
      priceMinKrw: 9000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍶",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_veteran_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 한옥마을 들깨 칼국수 & 고기만두",
      nameEn: "Jeonju Perilla Seed Egg Drop Kalguksu & Dumplings",
      descKo: "계란을 푼 구수한 국물에 들깨가루와 김가루, 고춧가루를 듬뿍 올려 비벼 먹는 독특한 전주 명물 국수",
      descEn: "Iconic silky noodle soup featuring whipped eggs, heavily topped with aromatic ground perilla seeds, seaweed, and chili",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
    {
      id: "jeonju_omogari_tang",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주천 오모가리탕 (뚝배기 민물매운탕)",
      nameEn: "Omogari Earthenware Freshwater Fish Spicy Stew",
      descKo: "뚝배기(오모가리)에 시래기와 메기, 쏘가리를 넣고 얼큰 칼칼하게 끓여낸 전주 전통 향토 보양식",
      descEn: "Deep, earthy freshwater catfish stew slowly simmered with dried turnip greens in heavy heat-retaining clay pots",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 30000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/97/3054097_image2_1.jpg",
    },
    {
      id: "jeonju_chocopie",
      scope: "CITY_LOCAL",
      cityCode: "JEONJU",
      nameKo: "전주 풍년제과 수제 초코파이 & 카페",
      nameEn: "Jeonju Artisanal Bakery Handmade Choco Pie & Coffee",
      descKo: "달콤한 초콜릿 코팅 속에 호두와 딸기잼, 크림이 샌드된 전주 한옥마을 필수 기념품 디저트",
      descEn: "Famous handcrafted thick cocoa biscuit filled with fluffy marshmallow cream, strawberry jam, and crushed walnuts",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 3500,
      priceMinKrw: 2800,
      priceMaxKrw: 5000,
      isMustEatTop3: false,
      emoji: "🍫",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
    },
  ],

  // === 5. 강릉 (GANGNEUNG) ===
  GANGNEUNG: [
    {
      id: "gangneung_chodang_sundubu",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 초당 순두부 백반 & 모두부",
      nameEn: "Gangneung Chodang Sea-Water Soft Tofu Meal & Warm Cake",
      descKo: "동해안 깨끗한 바닷물을 간수로 사용하여 몽글몽글하고 담백 고소함이 극대화된 400년 전통 두부",
      descEn: "Pure culinary heritage: velvety soft curd tofu curdled with natural East Sea brine for unmatched clean flavor",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9000,
      priceMaxKrw: 14000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_jang_kalguksu",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 칼칼한 장칼국수 & 겉절이",
      nameEn: "Gangneung Spicy Gochujang Jang Kalguksu Noodles",
      descKo: "고추장과 된장을 풀어낸 걸쭉하고 얼큰한 육수에 호박, 버섯, 계란을 풀고 굵은 면을 넣은 강원도 소울푸드",
      descEn: "Thick, rustic knife-cut noodles swimming in a deeply savory, warming chili-soybean paste broth with zucchini",
      categoryTag: "MEAL",
      unitPriceKrw: 9000,
      priceMinKrw: 8000,
      priceMaxKrw: 11000,
      isMustEatTop3: true,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_anmok_coffee",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "안목해변 커피거리 스페셜티 핸드드립 & 디저트",
      nameEn: "Anmok Beach Coffee Street Specialty Drip & Ocean Dessert",
      descKo: "푸른 동해 바다 뷰를 감상하며 대한민국 커피 1번지 강릉의 수준 높은 로스팅 핸드드립 커피 즐기기",
      descEn: "Fresh single-origin pour-over coffee roasted in Korea's coffee capital overlooking the scenic blue ocean waves",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 8000,
      priceMinKrw: 6000,
      priceMaxKrw: 12000,
      isMustEatTop3: true,
      emoji: "☕",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/4075958_image2_1.jpg",
    },
    {
      id: "gangneung_ggomak_bibimbap",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 엄지네 꼬막비빔밥 & 꼬막무침",
      nameEn: "Gangneung Spicy Seasoned Cockles & Rice Platter",
      descKo: "통통하게 살이 오른 꼬막을 청양고추와 특제 간장 양념에 버무려 고소한 밥과 비벼 먹는 줄 서는 맛집",
      descEn: "Massive round platter of tender sea cockles tossed in savory garlic chives and fragrant sesame oil mixed with rice",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🍱",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_gamja_ongsimi",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 쫀득한 감자옹심이 칼국수",
      nameEn: "Chewy Potato Ongsimi (Potato Dumplings) Soup",
      descKo: "강원도 감자를 갈아 앙금을 짜내어 동글동글 빚은 극강의 쫀득한 식감과 구수한 멸치 육수",
      descEn: "Unique chewy potato dough balls boiled in clear anchovy vegetable broth, an authentic mountain tradition",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8500,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🥔",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_garlic_bread",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 중앙시장 팡파미유 육쪽마늘빵",
      nameEn: "Gangneung 6-Segment Cream Cheese Garlic Bread",
      descKo: "달콤한 마늘 버터 소스에 듬뿍 적셔 크림치즈를 가득 채운 바삭 촉촉한 강릉 명물 베이커리",
      descEn: "Famous pull-apart bread infused with rich sweet garlic butter and overflowing with smooth cream cheese",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4500,
      priceMinKrw: 4000,
      priceMaxKrw: 6000,
      isMustEatTop3: false,
      emoji: "🥖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_ojingeo_sundae",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "주문진 수산시장 통오징어순대 계란전",
      nameEn: "Jumunjin Stuffed Squid Sundae Pan-fried with Egg",
      descKo: "신선한 통오징어 속에 찹쌀, 채소, 당면을 채워 찐 후 계란물을 묻혀 노릇하게 부친 별미",
      descEn: "Fresh whole squid tube stuffed with sticky rice, minced tentacles and vegetables, sliced and egg-battered",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: false,
      emoji: "🦑",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/41/2839641_image2_1.jpg",
    },
    {
      id: "gangneung_mulhoe_set",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "사천진리 해변 모둠 물회 & 소면사리",
      nameEn: "Sacheon Beach Chilled Assorted Seafood Mulhoe",
      descKo: "광어, 오징어, 해삼, 멍게에 매콤달콤 살얼음 과일 육수를 붓고 소면을 말아먹는 시원한 바다 맛",
      descEn: "Refreshing cold bowl loaded with fresh white fish sashimi, sea cucumbers, and thin noodles in icy spicy broth",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 22000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "gangneung_gaori_jjim",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "강릉 이모네 생선찜 (매콤 가오리찜)",
      nameEn: "Braised Stingray Gaori Jjim in Sweet Spicy Glaze",
      descKo: "부드럽게 뼈째 발라지는 살코기 가오리와 두툼한 감자, 무에 중독성 있는 매콤달콤 양념을 얹은 생선찜",
      descEn: "Tender stingray wings that pull apart in succulent ribbons, slow-braised with sweet potatoes in spicy red glaze",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 25000,
      priceMinKrw: 20000,
      priceMaxKrw: 32000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/61/4039261_image2_1.jpg",
    },
    {
      id: "gangneung_sundubu_gelato",
      scope: "CITY_LOCAL",
      cityCode: "GANGNEUNG",
      nameKo: "초당 순두부 젤라또 & 흑임자 젤라또",
      nameEn: "Chodang Soft Tofu Gelato & Black Sesame Ice Cream",
      descKo: "초당 순두부의 고소하고 은은한 단맛을 이탈리아 젤라또 기법으로 완성한 강릉 시그니처 아이스크림",
      descEn: "Surprisingly addictive artisanal gelato made using freshly curdled Chodang tofu and roasted black sesame",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4500,
      priceMinKrw: 4000,
      priceMaxKrw: 6000,
      isMustEatTop3: false,
      emoji: "🍨",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/54/2930154_image2_1.JPG",
    },
  ],

  // === 6. 속초 (SOKCHO) ===
  SOKCHO: [
    {
      id: "sokcho_abai_sundae",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 아바이마을 아바이순대 & 명태회무침",
      nameEn: "Abai Village North Korean Style Sundae with Pollock Salad",
      descKo: "함경도 실향민들이 정착해 돼지 대창 속에 선지와 찹쌀을 채워 만든 묵직하고 고소한 전통 순대",
      descEn: "Substantial North Korean heritage blood sausage made with thick pork casing, paired with sweet spicy pollock",
      categoryTag: "MEAL",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🍖",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_dakgangjeong",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 중앙시장 만석 닭강정 (순살/뼈)",
      nameEn: "Sokcho Jungang Market Manseok Sweet Crispy Dakgangjeong",
      descKo: "식어도 바삭함을 잃지 않는 비법 조청 소스와 고소한 아몬드를 솔솔 뿌린 전국 1위 닭강정",
      descEn: "Legendary bite-sized crunchy glazed fried chicken coated in glossy sweet chili syrup and slivered almonds",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 20000,
      priceMinKrw: 18000,
      priceMaxKrw: 23000,
      isMustEatTop3: true,
      emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_bongpo_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "봉포머구리집 명품 모둠 물회 & 국수",
      nameEn: "Bongpo Meoguri House Master Assorted Mulhoe",
      descKo: "해녀 머구리가 직접 잠수해 채취한 전복, 해삼, 멍게, 문어, 활어회가 가득 담긴 새콤 시원한 물회",
      descEn: "Towering bowl of pristine cold broth packed with fresh diver-caught abalone, octopus, sashimi, and noodles",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 19000,
      priceMinKrw: 17000,
      priceMaxKrw: 24000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/05/4032905_image2_1.jpg",
    },
    {
      id: "sokcho_red_crab_feast",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 동해안 살 가득 홍게 & 게딱지 볶음밥",
      nameEn: "Sokcho Steamed Red Snow Crab with Shell Fried Rice",
      descKo: "속초항에서 당일 입항한 신선한 홍게를 즉석에서 쪄내 달콤한 게살과 녹진한 게딱지 내장 볶음밥",
      descEn: "Steamed sweet red snow crab legs with savory fried rice packed into the crab shell with toasted seaweed",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 35000,
      priceMinKrw: 30000,
      priceMaxKrw: 50000,
      isMustEatTop3: false,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_hoe_naengmyeon",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 원조 명태 회냉면 & 온육수",
      nameEn: "Sokcho Hamheung Style Cold Noodles with Raw Pollock",
      descKo: "새콤달콤 매콤하게 숙성한 명태회를 고명으로 얹어 고소한 온육수와 함께 비벼 먹는 함흥식 냉면",
      descEn: "Springy potato starch noodles mixed with chewy marinated raw pollock fish and warm seasoned beef broth",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 10000,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_seopguk",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 자연산 홍합 섭국 & 부추",
      nameEn: "Wild Natural Mussel Seopguk Spicy Soup",
      descKo: "동해안 깊은 바다 자연산 큰 홍합(섭)을 듬뿍 넣고 된장과 고추장으로 칼칼하고 시원하게 끓인 국",
      descEn: "Deep, robust spicy coastal stew made with giant wild mussels, garlic chives, and aged chili paste",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 16000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_dongmyeong_sashimi",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "동명항 활어포차 갓 잡은 자연산 회",
      nameEn: "Dongmyeong Port Dockside Fresh Caught Fish Sashimi",
      descKo: "동명항 난전에서 어선이 들어오자마자 썰어내는 자연산 가자미, 놀래미, 해산물 세트",
      descEn: "Authentic dockside dining: naturally caught flounder and rockfish sliced fresh straight off the fishing boats",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 30000,
      priceMinKrw: 25000,
      priceMaxKrw: 42000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/55/3041255_image2_1.jpg",
    },
    {
      id: "sokcho_grilled_fish",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 88 숯불 모둠 생선구이 정식",
      nameEn: "Sokcho 88 Charcoal Grilled Assorted Fish Platter",
      descKo: "고등어, 꽁치, 조기, 삼치, 오징어를 테이블 위 숯불에서 직접 바삭하게 구워주는 40년 전통 구이",
      descEn: "Feast of 6+ fish varieties (mackerel, saury, yellow corvina) grilled over live table charcoal right in front of you",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 15000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
    {
      id: "sokcho_makguksu",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "영랑호 동치미 메밀 막국수 & 수육",
      nameEn: "Yeongrang Lake Dongchimi Buckwheat Makguksu",
      descKo: "메밀 함량이 높은 구수한 국수에 살얼음 톡 쏘는 항아리 동치미 국물을 세 국자 부어 먹는 막국수",
      descEn: "Rustic buckwheat noodles served dry so diners can ladle their own fizzy, ice-cold winter radish water",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 9000,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/13/3449813_image2_1.jpg",
    },
    {
      id: "sokcho_sweet_pumpkin_sikhye",
      scope: "CITY_LOCAL",
      cityCode: "SOKCHO",
      nameKo: "속초 중앙시장 살얼음 단호박 식혜 & 강정",
      nameEn: "Icy Sweet Pumpkin Sikhye & Traditional Nut Brittles",
      descKo: "달콤하고 부드러운 단호박을 넣고 전통 방식으로 삭힌 노란빛의 시원한 천연 소화 디저트 음료",
      descEn: "Frosty, golden traditional fermented rice punch flavored with sweet pumpkin, an essential market treat",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 4000,
      priceMinKrw: 3000,
      priceMaxKrw: 5500,
      isMustEatTop3: false,
      emoji: "🎃",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2845558_image2_1.jpg",
    },
  ],

  // === 7. 경주 (GYEONGJU) ===
  GYEONGJU: [
    {
      id: "gyeongju_hwangnambbang",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "원조 황남빵 & 찰보리빵 세트",
      nameEn: "Original Hwangnam-ppang (Red Bean Pastry) & Barley Bread",
      descKo: "얇은 밀가루 피 속에 부드럽고 달지 않은 100% 국산 팥 앙금이 꽉 들어찬 1939년 시작된 경주 1위",
      descEn: "Historic thin-crust golden pastry stuffed to bursting with smooth, delicate red bean paste since 1939",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: true,
      emoji: "🥮",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/82/2877982_image2_1.jpg",
    },
    {
      id: "gyeongju_hanwoo_mulhoe",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 보문단지 한우 물회 & 소면",
      nameEn: "Gyeongju Premium Hanwoo Raw Beef Chilled Mulhoe",
      descKo: "신선한 최고급 경주 한우 우둔살 육회에 살얼음 동동 띄운 매콤달콤 육수를 부어 소면과 함께 비벼 먹는 요리",
      descEn: "A Gyeongju revelation: ribbons of fresh Korean Hanwoo beef sashimi served in tangy frozen chili broth with noodles",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_ssambap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "대릉원 유기농 쌈밥 정식 (제육/불고기)",
      nameEn: "Daereungwon Royal Leaf Wrap Ssambap Organic Feast",
      descKo: "10여 가지 신선한 제철 쌈채소와 강된장, 숯불 제육볶음, 생선구이가 차려지는 왕실 쌈밥",
      descEn: "Feast of 10+ fresh crisp garden leaves wrapped around fragrant rice, savory soybean paste dip, and spicy pork",
      categoryTag: "MEAL",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🥬",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/98/4105798_image2_1.jpg",
    },
    {
      id: "gyeongju_maetdol_sundubu",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "보문단지 맷돌 몽글 순두부찌개",
      nameEn: "Bomun Traditional Millstone Ground Soft Tofu Stew",
      descKo: "국산 콩을 옛 맷돌 방식으로 갈아 만든 부드럽고 담백한 순두부에 날달걀을 톡 깨뜨려 먹는 찌개",
      descEn: "Nutty soft tofu ground in old-fashioned stone mills simmered in gentle red broth with raw egg garnish",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "gyeongju_tteokgalbi_sotbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 한우 떡갈비 솥밥 정식",
      nameEn: "Gyeongju Hanwoo Beef Tteokgalbi & Hot Stone Rice",
      descKo: "경주 특산 한우로 빚어 육즙이 살아있는 떡갈비와 단호박, 은행을 올린 건강한 돌솥밥",
      descEn: "Savory chargrilled Korean beef patty served beside steaming stone bowl rice topped with sweet pumpkin",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 14000,
      priceMaxKrw: 22000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_gyori_gimbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "교촌마을 원조 교리김밥 (계란지단 가득)",
      nameEn: "Gyodong Historic Village Ribboned Egg Gyori Gimbap",
      descKo: "밥보다 얇게 채 썬 고소한 계란지단이 터질 듯 가득 차 부드러운 식감이 일품인 줄 서는 명물 김밥",
      descEn: "Nationally renowned seaweed rice roll packed with an astonishing mountain of finely shredded fluffy egg crepes",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 5500,
      priceMinKrw: 4500,
      priceMaxKrw: 7000,
      isMustEatTop3: false,
      emoji: "🍙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/11/4097011_image2_1.jpg",
    },
    {
      id: "gyeongju_10won_bread",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "황리단길 모짜렐라 치즈 십원빵",
      nameEn: "Hwangridan-gil 10-Won Coin Melted Mozzarella Bread",
      descKo: "다보탑이 새겨진 10원 동전 모양 반죽 속에 통 모짜렐라 치즈가 쭈욱 늘어나는 황리단길 대표 디저트",
      descEn: "Iconic coin-shaped waffle bread stamped with Dabotap Pagoda, bursting with gooey stringy mozzarella cheese",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 3500,
      priceMinKrw: 3000,
      priceMaxKrw: 4500,
      isMustEatTop3: false,
      emoji: "🪙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/21/2904221_image2_1.jpg",
    },
    {
      id: "gyeongju_mukbap",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 시원한 메밀묵채 & 묵밥",
      nameEn: "Chilled Acorn & Buckwheat Jelly Mukbap Bowl",
      descKo: "탱글한 도토리묵과 메밀묵에 볶은 김치, 김가루를 얹고 시원한 멸치 육수를 부어 밥을 말아먹는 전통 요리",
      descEn: "Refreshing savory jelly strips served in cold kelp broth with chopped kimchi and warm rice",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8000,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_charcoal_ribs",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 천년한우 갈비살 참숯구이",
      nameEn: "Gyeongju Local Hanwoo Prime Rib Charcoal BBQ",
      descKo: "경주의 청정 자연에서 자란 천년한우의 마블링 좋은 갈비살을 소금에 콕 찍어 먹는 고급 구이",
      descEn: "Exceptional local Korean beef short rib cuts grilled quickly over white charcoal for melt-in-mouth richness",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 29000,
      priceMinKrw: 24000,
      priceMaxKrw: 38000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
    {
      id: "gyeongju_traditional_soup",
      scope: "CITY_LOCAL",
      cityCode: "GYEONGJU",
      nameKo: "경주 전통 가마솥 한우 곰탕 / 육개장",
      nameEn: "Gyeongju Traditional Cauldron Beef Soup Set",
      descKo: "토란대와 고사리, 대파, 한우 양지를 넣고 칼칼하고 진하게 끓여낸 신라 천년의 깊은 맛",
      descEn: "Slow-simmered beef brisket soup with wild bracken ferns and leeks, offering robust depth and heritage comfort",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/29/2838729_image2_1.jpg",
    },
  ],

  // === 8. 수원 (SUWON) ===
  SUWON: [
    {
      id: "suwon_wanggalbi",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "전통 수원 왕갈비 구이 (양념 / 생갈비)",
      nameEn: "Authentic Suwon Giant Wang-Galbi Charcoal BBQ",
      descKo: "소금, 설탕, 마늘, 참기름으로 잰 비법 소금 양념에 15cm 이상의 큼직한 갈빗대를 숯불에 굽는 전국 3대 갈비",
      descEn: "One of Korea's legendary meat dishes: massive prime beef ribs seasoned lightly with salt, garlic, and sesame",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 38000,
      priceMinKrw: 32000,
      priceMaxKrw: 52000,
      isMustEatTop3: true,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/21/3048121_image2_1.JPG",
    },
    {
      id: "suwon_chicken_street",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 남문 통닭거리 원조 가마솥 통닭",
      nameEn: "Suwon Chicken Street Crispy Whole Cauldron Fried Chicken",
      descKo: "무쇠 가마솥의 센 화력으로 통째로 튀겨내 껍질은 과자처럼 바삭하고 속살은 육즙이 터지는 명물 통닭",
      descEn: "Fried whole in heavy cast-iron cauldrons for intensely crackling paper-thin skin and tender steaming meat",
      categoryTag: "MEAL",
      unitPriceKrw: 19000,
      priceMinKrw: 16000,
      priceMaxKrw: 23000,
      isMustEatTop3: true,
      emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_wang_galbitang",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 진미 왕갈비탕 & 함흥냉면",
      nameEn: "Suwon Rich King Beef Rib Soup (Wang-Galbitang)",
      descKo: "손바닥만 한 대형 왕갈비 2대가 통째로 들어간 맑고 깊은 육수의 든든한 보양 갈비탕",
      descEn: "Deep, clear beef bone broth housing two massive tender short ribs that slide effortlessly off the bone",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 13000,
      priceMaxKrw: 18000,
      isMustEatTop3: true,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_boyoung_mandu",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 행궁동 보영만두 (매콤 쫄면 & 군만두)",
      nameEn: "Haenggung-dong Boyoung Crunchy Dumplings & Spicy Jjolmyeon",
      descKo: "겉은 바삭하고 육즙이 터지는 수제 군만두를 매콤 알싸한 양배추 쫄면에 싸 먹는 수원 청춘들의 성지",
      descEn: "Super-crispy fried pork dumplings dipped into fiery chewy noodles tossed with finely shredded cabbage",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 9000,
      priceMinKrw: 7500,
      priceMaxKrw: 11500,
      isMustEatTop3: false,
      emoji: "🥟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_jidong_sundae",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 지동시장 순대곱창 철판볶음",
      nameEn: "Jidong Market Sizzling Sundae & Pork Intestine Stir-fry",
      descKo: "철판에 찰순대, 곱창, 깻잎, 팽이버섯, 당면을 들깨가루와 매콤 양념장에 볶아 먹는 시장 명물",
      descEn: "Generous sizzling tabletop stir-fry of blood sausage and pork intestines seasoned with fragrant perilla leaves",
      categoryTag: "MEAL",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🥘",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_hwaseong_dessert",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 화성 행궁 성곽 뷰 개성주악 & 차",
      nameEn: "Suwon Hwaseong Fortress Gaeseong Juak Traditional Sweet",
      descKo: "찹쌀과 막걸리로 반죽해 조청을 입힌 쫀득하고 즙이 터지는 전통 한과와 고즈넉한 성곽 뷰 카페",
      descEn: "Sticky rice and wine doughnut drenched in ginger rice syrup, savored alongside fortress stone wall views",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 7000,
      priceMinKrw: 5000,
      priceMaxKrw: 9500,
      isMustEatTop3: false,
      emoji: "🍯",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_haejang_guk",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "수원 우만동 40년 전통 선지 소갈비 해장국",
      nameEn: "Uman-dong 40-Year Beef Rib & Ox Blood Hangover Soup",
      descKo: "소갈비 살코기와 신선한 선지, 우거지가 푸짐하게 어우러진 깊고 칼칼한 국밥",
      descEn: "Deep, soothing hangover cure stew bubbling with rich beef rib cuts, tender dried greens, and mineral ox blood",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9500,
      priceMaxKrw: 13000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/42/2848342_image2_1.png",
    },
    {
      id: "suwon_gwanggyo_craft",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "광교 호수공원 뷰 화덕피자 & 수제맥주",
      nameEn: "Gwanggyo Lake Park Wood-fired Pizza & Craft Beer",
      descKo: "야경이 아름다운 광교 호수공원을 바라보며 즐기는 정통 참나무 화덕 나폴리 피자와 크래프트 맥주",
      descEn: "Neapolitan blistered crust pizza and chilled artisanal craft beers overlooking the dazzling lake promenade",
      categoryTag: "MEAL",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🍕",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/36/2835336_image2_1.jpg",
    },
    {
      id: "suwon_memil_makguksu",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "북수원 시원한 봉평 메밀 막국수 & 수육",
      nameEn: "North Suwon Chilled Buckwheat Makguksu & Boiled Pork",
      descKo: "메밀 향이 진한 면발에 매콤새콤 양념장과 시원한 육수를 자작하게 부어 먹는 깔끔한 한 끼",
      descEn: "Nutty buckwheat cold noodles served with a splash of chilled broth and thinly sliced savory boiled pork",
      categoryTag: "MEAL",
      unitPriceKrw: 10000,
      priceMinKrw: 8500,
      priceMaxKrw: 12000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/2844758_image2_1.jpg",
    },
    {
      id: "suwon_jangan_seolleongtang",
      scope: "CITY_LOCAL",
      cityCode: "SUWON",
      nameKo: "장안문 가마솥 도가니탕 & 수육",
      nameEn: "Janganmun Fortress Ox Knee Cartilage Doganitang",
      descKo: "콜라겐이 풍부한 소 도가니를 진하게 고아 쫀득한 식감과 보양 효과가 뛰어난 보양탕",
      descEn: "Nourishing, collagen-rich ox knee cartilage soup brewed in huge iron cauldrons near the ancient fortress gate",
      categoryTag: "MEAL",
      unitPriceKrw: 17000,
      priceMinKrw: 14000,
      priceMaxKrw: 21000,
      isMustEatTop3: false,
      emoji: "🥣",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/05/4054005_image2_1.jpg",
    },
  ],

  // === 9. 인천 (INCHEON) ===
  INCHEON: [
    {
      id: "incheon_chinatown_jajang",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "인천 차이나타운 100년 원조 공화춘 백짜장 & 탕수육",
      nameEn: "Incheon Chinatown Historic Gonghwachun White Jajang & Tangsuyuk",
      descKo: "1883년 개항과 함께 탄생한 자장면의 발상지 인천 차이나타운의 원조 짜장면과 바삭한 찹쌀 탕수육",
      descEn: "Birthplace of Korean-Chinese cuisine: authentic white bean sauce noodles paired with crispy sweet & sour pork",
      categoryTag: "MEAL",
      unitPriceKrw: 15000,
      priceMinKrw: 12000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🥢",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/76/2848776_image2_1.jpg",
    },
    {
      id: "incheon_sinpo_dakgangjeong",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "신포국제시장 원조 매콤 닭강정",
      nameEn: "Sinpo International Market Original Fiery Dakgangjeong",
      descKo: "가마솥에서 센 불로 청양고추와 물엿소스를 버무려 겉은 바삭하고 속은 촉촉한 전국 최고 명물 닭강정",
      descEn: "Intensely crunchy fried chicken tossed in hot wok with dried chili peppers and thick savory-sweet glaze",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 19000,
      priceMinKrw: 17000,
      priceMaxKrw: 22000,
      isMustEatTop3: true,
      emoji: "🍗",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/04/4064804_image2_1.jpg",
    },
    {
      id: "incheon_crab_soup",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "서해 연평도 암꽃게탕 & 게장 백반",
      nameEn: "Yeonpyeong Island Blue Crab Spicy Stew & Soy Crab Meal",
      descKo: "알과 살이 꽉 찬 서해안 꽃게와 단호박, 콩나물을 넣고 얼큰 시원하게 끓여낸 바다의 맛",
      descEn: "Sweet, meat-packed local yellow sea blue crabs simmered in bubbling spicy stew with sweet pumpkin and bean sprouts",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 28000,
      priceMinKrw: 24000,
      priceMaxKrw: 38000,
      isMustEatTop3: true,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/39/2900039_image2_1.jpg",
    },
    {
      id: "incheon_baendaengi",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "연안부두 밴댕이회무침 비빔밥 골목",
      nameEn: "Yeonan Pier Spicy Baendaengi (Herring) Sashimi Rice",
      descKo: "고소한 강화도 밴댕이회를 미나리, 상추와 매콤새콤하게 무쳐 따뜻한 밥에 쓱쓱 비벼 먹는 별미",
      descEn: "Small, flavorful coastal herrings tossed with fragrant wild dropwort and spicy chili vinegar sauce over warm rice",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 12000,
      priceMinKrw: 10000,
      priceMaxKrw: 15000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/97/2846797_image2_1.jpg",
    },
    {
      id: "incheon_clay_oven_dumpling",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "차이나타운 옹기 화덕만두 & 공갈빵",
      nameEn: "Chinatown Tandoor Clay Oven Stuffed Dumpling & Gonggalppang",
      descKo: "200도 화덕 벽에 붙여 구워내 기름기 없이 바삭한 만두피 속에 육즙 가득한 고기와 부추",
      descEn: "Handmade buns baked inside roaring clay tandoor walls, bursting with juicy spiced meat, alongside crisp hollow pastry",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 4000,
      priceMinKrw: 3000,
      priceMaxKrw: 5500,
      isMustEatTop3: false,
      emoji: "🥟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/92/3526892_image2_1.jpg",
    },
    {
      id: "incheon_multeombeong",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "용현동 물텀벙이 거리 원조 아귀찜",
      nameEn: "Yonghyeon-dong Multeombeong Spicy Braised Monkfish",
      descKo: "살코기가 부드러운 아귀에 아삭한 콩나물과 미더덕, 매콤한 양념장을 듬뿍 넣어 볶아낸 인천 토속 요리",
      descEn: "Plump, tender monkfish braised with crunchy bean sprouts and sea squirts in a thick, savory-spicy red sauce",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 30000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "incheon_sinpo_jjolmyeon",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "신포동 발상 원조 매콤 쫄면 & 야채만두",
      nameEn: "Sinpo Original Chewy Jjolmyeon & Fresh Dumplings",
      descKo: "인천 국수공장에서 우연히 탄생한 탱글탱글한 면발에 새콤달콤 고추장 양념과 채소를 듬뿍 비빈 분식",
      descEn: "Birthplace of Jjolmyeon: extra-springy wheat noodles tossed with spicy vinegar paste, shredded cabbage, and boiled egg",
      categoryTag: "STREET_SNACK",
      unitPriceKrw: 8500,
      priceMinKrw: 7000,
      priceMaxKrw: 10500,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/79/2912779_image2_1.jpg",
    },
    {
      id: "incheon_samchi_street",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "동인천 삼치골목 통삼치 소금구이 & 계란말이",
      nameEn: "Dongincheon King Mackerel (Samchi) Charcoal Grill Set",
      descKo: "신선한 대형 삼치를 통째로 노릇노릇 구워 담백하고 부드러운 살코기를 양념간장에 찍어 먹는 선술집 안주",
      descEn: "Giant whole King Mackerel broiled golden brown, famous in the university alleyway alongside fluffy rolled omelet",
      categoryTag: "MEAL",
      unitPriceKrw: 13000,
      priceMinKrw: 11000,
      priceMaxKrw: 17000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/40/3013740_image2_1.jpg",
    },
    {
      id: "incheon_songdo_clam_noodles",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "송도 영종도 바지락 해물 손칼국수",
      nameEn: "Songdo Yellow Sea Clam Seafood Kalguksu Bowl",
      descKo: "살아있는 바지락 조개를 아낌없이 넣어 국물이 맑고 개운한 인천 서해안의 대표 손칼국수",
      descEn: "Huge steaming basin of handmade noodles swimming in briny broth filled with sweet Yellow Sea Manila clams",
      categoryTag: "MEAL",
      unitPriceKrw: 11000,
      priceMinKrw: 9500,
      priceMaxKrw: 14000,
      isMustEatTop3: false,
      emoji: "🍜",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/06/2900006_image2_1.jpg",
    },
    {
      id: "incheon_wolmido_clam_bake",
      scope: "CITY_LOCAL",
      cityCode: "INCHEON",
      nameKo: "월미도 바다뷰 조개구이 무한 세트",
      nameEn: "Wolmido Oceanfront Sizzling Shellfish BBQ Feast",
      descKo: "가리비, 키조개 치즈구이, 백합을 연탄불에 올려 바닷바람 맞으며 푸짐하게 구워 먹는 월미도 명물",
      descEn: "Seaside table grill loaded with fresh scallops, buttered giant pen shells, and clams roasted over live fire",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 32000,
      priceMinKrw: 28000,
      priceMaxKrw: 42000,
      isMustEatTop3: false,
      emoji: "🦪",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/58/4066258_image2_1.jpg",
    },
  ],

  // === 10. 여수 (YEOSU) ===
  YEOSU: [
    {
      id: "yeosu_dolgejang",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 원조 돌게장 백반 (간장게장 + 양념게장 무한리필)",
      nameEn: "Yeosu All-You-Can-Eat Small Rock Crab Gejang Set",
      descKo: "달콤 짭조름한 비법 간장게장과 매콤한 양념게장의 게딱지에 밥을 쓱쓱 비벼 먹는 여수 최고의 밥도둑",
      descEn: "Legendary rice thief: sweet savory soy-marinated small rock crabs bursting with orange roe and spicy glazed crabs",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: true,
      emoji: "🦀",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_nangman_samhap",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 낭만포차 해물삼합 (돌산갓김치 + 차돌 + 문어/새우)",
      nameEn: "Yeosu Romantic Pocha Seafood Samhap (Octopus + Beef + Gat Kimchi)",
      descKo: "여수 밤바다 포차에서 돌산 갓김치, 우삼겹, 생문어, 전복, 새우를 철판에 볶아 한 쌈에 싸 먹는 요리",
      descEn: "Celebrated harbor night dish: lively octopus, tender beef brisket, and spicy mustard leaf kimchi sizzled together",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 24000,
      priceMinKrw: 20000,
      priceMaxKrw: 30000,
      isMustEatTop3: true,
      emoji: "🐙",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_seodaehoe",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 막걸리식초 새콤달콤 서대회무침",
      nameEn: "Yeosu Fermented Rice Vinegar Tongue Sole Sashimi Salad",
      descKo: "전통 막걸리 식초로 버무려 비린내 없이 새콤달콤하고 감칠맛 넘치는 여수 10미 서대 생선회",
      descEn: "Thin delicate slices of wild sole sashimi tossed with crisp cucumbers and aged artisanal makgeolli vinegar",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 14000,
      priceMinKrw: 12000,
      priceMaxKrw: 17000,
      isMustEatTop3: true,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_gatkimchi_samgyeop",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "돌산 갓김치 솥뚜껑 삼겹살 구이",
      nameEn: "Dolsan Mustard Leaf Gat Kimchi & Pork Belly BBQ",
      descKo: "알싸한 톡 쏘는 여수 돌산 갓김치를 돼지기름에 함께 구워 삼겹살에 돌돌 말아 먹는 황홀한 조화",
      descEn: "Crisp grilled pork belly wrapped with pungent, caramelized local Dolsan mustard leaf kimchi on cast-iron cauldron lid",
      categoryTag: "BBQ_FEAST",
      unitPriceKrw: 19000,
      priceMinKrw: 16000,
      priceMaxKrw: 23000,
      isMustEatTop3: false,
      emoji: "🥩",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/51/612151_image2_1.jpg",
    },
    {
      id: "yeosu_hamo_yubikki",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 여름 하모 유비끼 (갯장어 샤브샤브)",
      nameEn: "Yeosu Summer Hamo (Sea Pike Eel) Delicate Shabu-shabu",
      descKo: "칼집을 촘촘히 낸 싱싱한 갯장어를 뜨거운 한방 육수에 살짝 담가 눈꽃처럼 피어날 때 양파 쌈에 싸 먹는 최고급 보양식",
      descEn: "Aristocratic summer delicacy: fine-scored conger pike eel dipped in herb broth until it blooms like a white flower",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 38000,
      priceMinKrw: 32000,
      priceMaxKrw: 50000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_saejogae_shabu",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 겨울 명품 새조개 샤브샤브",
      nameEn: "Yeosu Winter Royal Bird Clam (Saejogae) Shabu-shabu",
      descKo: "새의 부리를 닮은 달콤하고 쫄깃한 명품 새조개를 시금치, 팽이버섯과 함께 맑은 육수에 데쳐 먹는 겨울 별미",
      descEn: "Sweet, crunchy bird clams harvested from deep seabed, flash-boiled with winter spinach in soothing broth",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 35000,
      priceMinKrw: 30000,
      priceMaxKrw: 48000,
      isMustEatTop3: false,
      emoji: "🦪",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_eel_soup",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 통장어탕 & 바다장어 구이 백반",
      nameEn: "Yeosu Whole Sea Eel Spicy Stew & Grilled Set",
      descKo: "큼직한 붕장어를 통째로 썰어 넣고 된장과 시래기, 숙주와 함께 얼큰하고 구수하게 끓여낸 든든한 장어탕",
      descEn: "Hearty, rich sea eel stew simmered with dried greens and whole chunks of tender eel meat",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 16000,
      priceMinKrw: 14000,
      priceMaxKrw: 20000,
      isMustEatTop3: false,
      emoji: "🍲",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_jeoneo_feast",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 가을 고소한 전어구이 & 전어회",
      nameEn: "Yeosu Autumn Gizzard Shad Whole Grilled & Sashimi",
      descKo: "집 나간 며느리도 돌아온다는 가을 바다 전어의 기름진 고소함을 통째로 뼈째 씹어 먹는 계절 요리",
      descEn: "Nutty, buttery autumn gizzard shad salted and broiled whole over flames, savored with spicy garlic paste",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 18000,
      priceMinKrw: 15000,
      priceMaxKrw: 24000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_gat_burger",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 이순신광장 수제 갓버거 & 갓도넛",
      nameEn: "Yeosu Yi Sun-sin Square Handcrafted Gat-Burger & Doughnut",
      descKo: "육즙 가득한 소고기 패티에 알싸한 돌산 갓김치 피클 소스를 더해 느끼함을 잡은 여수 명물 수제버거",
      descEn: "Unique fusion: gourmet beef burger dressed with tangy-spicy local mustard pickle relish sauce",
      categoryTag: "DESSERT_CAFE",
      unitPriceKrw: 7500,
      priceMinKrw: 6000,
      priceMaxKrw: 9500,
      isMustEatTop3: false,
      emoji: "🍔",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
    {
      id: "yeosu_galchi_set",
      scope: "CITY_LOCAL",
      cityCode: "YEOSU",
      nameKo: "여수 청정 통갈치조림 & 갈치회 한상",
      nameEn: "Yeosu Braised Cutlassfish Stew & Tender Raw Slices",
      descKo: "여수 앞바다에서 잡은 싱싱한 갈치를 칼칼한 양념에 졸여 흰 쌀밥에 얹어 먹는 남도 백반의 정수",
      descEn: "Silver ribbonfish simmered in thick spicy garlic broth with radishes, served with southern style side dishes",
      categoryTag: "SEAFOOD",
      unitPriceKrw: 22000,
      priceMinKrw: 18000,
      priceMaxKrw: 28000,
      isMustEatTop3: false,
      emoji: "🐟",
    imageUrl: "https://tong.visitkorea.or.kr/cms/resource/50/2931150_image2_1.jpg",
    },
  ],
};

// =========================================================================
// 3. 통합 카탈로그 및 헬퍼 함수
// =========================================================================

export const ALL_FOOD_ITEMS: FoodItemDefinition[] = [
  ...NATIONAL_K_FOODS,
  ...Object.values(CITY_SPECIALTY_FOODS).flat(),
];

export const FOOD_CATALOG_BY_ID: Map<string, FoodItemDefinition> = new Map(
  ALL_FOOD_ITEMS.map((item) => [item.id, item])
);

export function getNationalFoods(): FoodItemDefinition[] {
  return NATIONAL_K_FOODS;
}

export function getCityFoods(city: SupportedCity): FoodItemDefinition[] {
  return CITY_SPECIALTY_FOODS[city] || [];
}

export function getFoodById(id: string): FoodItemDefinition | undefined {
  return FOOD_CATALOG_BY_ID.get(id);
}
