import { SupportedCity } from "../../../lib/trip-domain";
import { FoodItemDefinition } from "../domain/types";

// =========================================================================
// 1.  한국 대표 음식 (National K-Signature 24선)
// =========================================================================
export const NATIONAL_K_FOODS: FoodItemDefinition[] = [
  {
    "id": "nat_samgyeopsal",
    "scope": "NATIONAL",
    "nameKo": "삼겹살",
    "nameEn": "Samgyeopsal",
    "descKo": "노릇하게 구운 도톰한 삼겹살을 쌈채소, 마늘, 쌈장과 곁들여 고소한 육즙을 즐기는 한국 대표 음식",
    "descEn": "Thick slices of fresh pork belly grilled at the table, wrapped in lettuce leaves with savory ssamjang and garlic",
    "categoryTag": "BBQ_FEAST",
    "unitPriceKrw": 36000,
    "priceMinKrw": 32000,
    "priceMaxKrw": 44000,
    "isMustEatTop3": true,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/5360cac5-b787-4463-b04d-ac48429b5a67/it11",
    "targetScope": "BOTH",
    "sortOrder": 1,
    "isActive": true
  },
  {
    "id": "nat_chimaek",
    "scope": "NATIONAL",
    "nameKo": "치킨",
    "nameEn": "Korean Fried Chicken",
    "descKo": "바삭하게 튀겨낸 치킨에 매콤달콤한 양념이나 간장 소스를 곁들여 시원한 맥주와 즐기는 한국의 대표 야식 메뉴",
    "descEn": "Crispy Korean fried chicken, cold draft beer, and instant boiling Han River ramyeon combo",
    "categoryTag": "MEAL",
    "unitPriceKrw": 23000,
    "priceMinKrw": 20000,
    "priceMaxKrw": 32000,
    "isMustEatTop3": true,
    "emoji": "",
    "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=f9d253d5-e4f6-4e43-8235-1550d8e3773f",
    "targetScope": "BOTH",
    "sortOrder": 2,
    "isActive": true
  },
  {
    "id": "nat_bulgogi",
    "scope": "NATIONAL",
    "nameKo": "불고기",
    "nameEn": "Bulgogi",
    "descKo": "얇게 썬 소고기를 달콤 짭조름한 간장 양념에 재워 채소와 함께 볶거나 전골로 즐기는 부드러운 전통 요리",
    "descEn": "Traditional Seoul-style bulgogi hot pot simmering tender marinated beef with savory broth, seasonal vegetables and glass noodles",
    "categoryTag": "MEAL",
    "unitPriceKrw": 18000,
    "priceMinKrw": 32000,
    "priceMaxKrw": 48000,
    "isMustEatTop3": true,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b5e503f9-548b-4998-a9de-e9f488eaef48/it11",
    "targetScope": "BOTH",
    "sortOrder": 3,
    "isActive": true
  },
  {
    "id": "nat_bibimbap",
    "scope": "NATIONAL",
    "nameKo": "비빔밥",
    "nameEn": "Bibimbap",
    "descKo": "따뜻한 밥 위에 다채로운 나물과 고기, 고추장, 참기름을 얹어 골고루 비벼 먹는 건강하고 정갈한 한 그릇 요리",
    "descEn": "Authentic Jeonju bibimbap served in heavy brassware bowls with fresh beef tartare and savory handmade tteokgalbi for two",
    "categoryTag": "MEAL",
    "unitPriceKrw": 11000,
    "priceMinKrw": 26000,
    "priceMaxKrw": 36000,
    "isMustEatTop3": true,
    "emoji": "🥘",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/21de8fbf-06b0-4d45-b0f9-49fa7892d8b3/it11",
    "targetScope": "BOTH",
    "sortOrder": 4,
    "isActive": true
  },
  {
    "id": "nat_sogalbijjim",
    "scope": "NATIONAL",
    "nameKo": "갈비찜",
    "nameEn": "Galbi-jjim",
    "descKo": "두툼한 소갈비를 달콤 짭조름한 간장 양념과 채소를 넣고 푹 쪄내 뼈에서 살이 부드럽게 발라지는 고급 전통 요리",
    "descEn": "Tender, melt-in-the-mouth short ribs braised in sweet soy sauce with chestnuts, dates, and shiitake mushrooms",
    "categoryTag": "MEAL",
    "unitPriceKrw": 28000,
    "priceMinKrw": 17000,
    "priceMaxKrw": 26000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/0af3cdf7-4080-4220-a377-1989070537f1/it11",
    "targetScope": "BOTH",
    "sortOrder": 5,
    "isActive": true
  },
  {
    "id": "nat_dakgalbi",
    "scope": "NATIONAL",
    "nameKo": "닭갈비",
    "nameEn": "Dak-galbi",
    "descKo": "부드러운 닭고기를 매콤달콤한 양념에 양배추, 떡과 함께 철판에서 볶아 먹고 볶음밥으로 마무리하는 인기 요리",
    "descEn": "Boneless chicken marinated in spicy chili sauce, stir-fried on a tabletop iron skillet with sweet cabbage, sweet potatoes, and rice cakes",
    "categoryTag": "MEAL",
    "unitPriceKrw": 16000,
    "priceMinKrw": 14000,
    "priceMaxKrw": 19000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/40fb0d29-a845-47f4-9f9d-58a50780bcd8/it11",
    "targetScope": "BOTH",
    "sortOrder": 6,
    "isActive": true
  },
  {
    "id": "nat_shabushabu",
    "scope": "NATIONAL",
    "nameKo": "샤브샤브",
    "nameEn": "Korean Beef Shabu-shabu",
    "descKo": "맑은 채소 육수에 얇게 썬 소고기와 신선한 버섯, 배추를 살짝 데쳐 먹은 뒤 칼국수와 죽으로 마무리하는 요리",
    "descEn": "Thin tender beef slices gently cooked in hot vegetable broth with mushrooms, finished with noodles and comforting porridge",
    "categoryTag": "MEAL",
    "unitPriceKrw": 16000,
    "priceMinKrw": 14000,
    "priceMaxKrw": 20000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/52/2878052_image2_1.jpg",
    "targetScope": "BOTH",
    "sortOrder": 7,
    "isActive": true
  },
  {
    "id": "nat_hanjeongsik",
    "scope": "NATIONAL",
    "nameKo": "한정식",
    "nameEn": "Hanjeongsik (Full-Course Korean Table)",
    "descKo": "한국 전통 상차림의 정수로 계절 나물, 구이, 탕, 찌개와 정갈한 찬들이 푸짐하게 차려지는 정식",
    "descEn": "Exquisite Korean full-course meal feast featuring a harmonious spread of grilled dishes, soups, stews, and delicate side dishes",
    "categoryTag": "MEAL",
    "unitPriceKrw": 45000,
    "priceMinKrw": 35000,
    "priceMaxKrw": 65000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/ee3b8a7f-8453-45e2-9968-ac214c6bb688/it11",
    "targetScope": "BOTH",
    "sortOrder": 8,
    "isActive": true
  },
  {
    "id": "nat_gimbap",
    "scope": "NATIONAL",
    "nameKo": "김밥",
    "nameEn": "Gimbap (Korean Seaweed Rice Rolls)",
    "descKo": "참기름을 바른 밥에 여러 가지 채소와 계란, 햄을 넣고 김으로 말아 한 입 크기로 썰어 먹는 든든한 국민 음식",
    "descEn": "Steamed white rice seasoned with sesame oil and rolled in roasted seaweed with yellow radish, spinach, carrots, eggs, and ham",
    "categoryTag": "STREET_SNACK",
    "unitPriceKrw": 4500,
    "priceMinKrw": 3500,
    "priceMaxKrw": 6000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b2fedcae-04b8-4fb4-ac2e-d97655d4ae72/it11",
    "targetScope": "BOTH",
    "sortOrder": 9,
    "isActive": true
  },
  {
    "id": "nat_kimchi_bokkeumbap",
    "scope": "NATIONAL",
    "nameKo": "김치볶음밥",
    "nameEn": "Kimchi Bokkeumbap (Kimchi Fried Rice)",
    "descKo": "잘 익은 매콤한 김치와 밥, 햄 또는 참치를 센 불에 고소하게 볶아내 반숙 계란 후라이와 김가루를 얹은 소울푸드",
    "descEn": "Stir-fried rice sizzling with tangy fermented kimchi, diced pork or tuna, topped with a runny fried egg and toasted seaweed flakes",
    "categoryTag": "MEAL",
    "unitPriceKrw": 9000,
    "priceMinKrw": 8000,
    "priceMaxKrw": 11000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/a54c2b8c-b324-4cb7-bfab-e6c4ea8d56eb/it11",
    "targetScope": "BOTH",
    "sortOrder": 10,
    "isActive": true
  },
  {
    "id": "nat_japchae",
    "scope": "NATIONAL",
    "nameKo": "잡채",
    "nameEn": "Japchae (Stir-fried Glass Noodles & Vegetables)",
    "descKo": "쫄깃한 당면에 신선한 시금치, 당근, 버섯, 소고기를 넣고 간장과 참기름에 고소하게 볶아낸 전통 잔치 음식",
    "descEn": "Chewy sweet potato glass noodles stir-fried with colorful vegetables, mushrooms, and beef seasoned in soy sauce and sesame oil",
    "categoryTag": "MEAL",
    "unitPriceKrw": 12000,
    "priceMinKrw": 9000,
    "priceMaxKrw": 15000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/864eb60c-76d2-45ce-beb4-886dc999cdf4/it11",
    "targetScope": "BOTH",
    "sortOrder": 11,
    "isActive": true
  },
  {
    "id": "nat_naengmyeon",
    "scope": "NATIONAL",
    "nameKo": "냉면",
    "nameEn": "Naengmyeon (Korean Cold Buckwheat Noodles)",
    "descKo": "살얼음 동동 뜬 시원한 육수나 매콤한 비빔 양념에 쫄깃한 메밀면을 말아 먹는 한국의 대표 여름 별미 국수",
    "descEn": "Chilled chewy buckwheat noodles served in refreshing icy broth or tossed with spicy sweet chili dressing",
    "categoryTag": "MEAL",
    "unitPriceKrw": 12000,
    "priceMinKrw": 11000,
    "priceMaxKrw": 16000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=57333299-0645-4bb8-a093-ec5e233b43e5",
    "targetScope": "BOTH",
    "sortOrder": 12,
    "isActive": true
  },
  {
    "id": "nat_jajangmyeon_mandu",
    "scope": "NATIONAL",
    "nameKo": "자장면",
    "nameEn": "Jajangmyeon (Noodles in Black Bean Sauce)",
    "descKo": "고소하고 달콤한 춘장 소스에 양파와 돼지고기를 볶아 갓 삶아낸 쫄깃한 면발에 비벼 먹는 국민 면 요리",
    "descEn": "Chewy wheat noodles smothered in a rich, savory black bean sauce stir-fried with pork and sweet caramelized onions",
    "categoryTag": "MEAL",
    "unitPriceKrw": 8000,
    "priceMinKrw": 7000,
    "priceMaxKrw": 10000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=8ae1266b-ff1c-489a-9aa5-7fecc6050796",
    "targetScope": "BOTH",
    "sortOrder": 13,
    "isActive": true
  },
  {
    "id": "nat_haemul_pajeon",
    "scope": "NATIONAL",
    "nameKo": "해물파전 & 칼국수",
    "nameEn": "Haemul Pajeon & Kalguksu (Seafood Pancake & Noodle Soup)",
    "descKo": "싱싱한 오징어와 조갯살, 쪽파를 듬뿍 넣어 바삭하게 부친 해물파전과 시원하고 깊은 육수의 쫄깃한 손칼국수 세트",
    "descEn": "Crispy savory seafood scallion pancake paired with a comforting bowl of fresh hand-cut noodle soup in rich broth",
    "categoryTag": "BBQ_FEAST",
    "unitPriceKrw": 19000,
    "priceMinKrw": 16000,
    "priceMaxKrw": 24000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=ed7d07b1-ad52-45e2-a264-b617d6a78ff7",
    "targetScope": "BOTH",
    "sortOrder": 14,
    "isActive": true
  },
  {
    "id": "nat_kimchi_jjigae",
    "scope": "NATIONAL",
    "nameKo": "김치찌개",
    "nameEn": "Kimchi-jjigae (Spicy Kimchi Stew)",
    "descKo": "잘 익은 숙성 김치와 두툼한 돼지고기, 두부를 듬뿍 넣고 얼큰하게 끓여낸 한국인의 소울푸드",
    "descEn": "Hearty, spicy stew brewed with well-aged fermented kimchi, succulent tender pork chunks, and soft tofu cubes",
    "categoryTag": "MEAL",
    "unitPriceKrw": 10000,
    "priceMinKrw": 9000,
    "priceMaxKrw": 12000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=b2e49489-3ca7-47c5-9354-8370f40cbaf4",
    "targetScope": "BOTH",
    "sortOrder": 15,
    "isActive": true
  },
  {
    "id": "nat_doenjang_jjigae",
    "scope": "NATIONAL",
    "nameKo": "된장찌개",
    "nameEn": "Doenjang-jjigae (Soybean Paste Stew)",
    "descKo": "구수한 재래식 된장 육수에 두부, 애호박, 양파, 버섯, 차돌박이 또는 바지락을 넣고 보글보글 끓여낸 한국인의 대표 찌개",
    "descEn": "Comforting traditional stew brewed with rich fermented soybean paste, tender tofu cubes, zucchini, mushrooms, and savory beef or clams",
    "categoryTag": "MEAL",
    "unitPriceKrw": 10000,
    "priceMinKrw": 8500,
    "priceMaxKrw": 12000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/68813ba4-620b-4bdd-9817-7c29768af0c0/it11",
    "targetScope": "BOTH",
    "sortOrder": 16,
    "isActive": true
  },
  {
    "id": "nat_sundubu",
    "scope": "NATIONAL",
    "nameKo": "순두부찌개",
    "nameEn": "Sundubu-jjigae (Spicy Soft Tofu Stew)",
    "descKo": "몽글몽글 부드러운 순두부와 신선한 조개, 새우, 계란을 넣고 칼칼하고 진하게 끓여낸 뚝배기 찌개",
    "descEn": "Silken uncurdled soft tofu stew bubbling fiery red in an earthenware bowl with clams, shrimp, and an egg yolk",
    "categoryTag": "MEAL",
    "unitPriceKrw": 10000,
    "priceMinKrw": 9000,
    "priceMaxKrw": 13000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2f195887-4706-448c-bd11-ef0393ce200f/it11",
    "targetScope": "BOTH",
    "sortOrder": 17,
    "isActive": true
  },
  {
    "id": "nat_budae_jjigae",
    "scope": "NATIONAL",
    "nameKo": "부대찌개",
    "nameEn": "Budae-jjigae (Sausage & Ham Army Stew)",
    "descKo": "햄, 소시지, 김치, 베이크드 빈스, 치즈와 라면사리를 푸짐하게 끓여내는 퓨전 전통 찌개",
    "descEn": "Hearty fusion hotpot simmered with savory ham, pork sausage, aged kimchi, baked beans, cheese, and chewy ramen noodles",
    "categoryTag": "MEAL",
    "unitPriceKrw": 12000,
    "priceMinKrw": 10000,
    "priceMaxKrw": 15000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/bfd74860-7ebe-445a-bbea-a3283e707047/it11",
    "targetScope": "BOTH",
    "sortOrder": 18,
    "isActive": true
  },
  {
    "id": "nat_samgyetang",
    "scope": "NATIONAL",
    "nameKo": "삼계탕",
    "nameEn": "Samgyetang (Ginseng Chicken Soup)",
    "descKo": "어린 닭의 뱃속에 찹쌀, 인삼, 대추, 마늘을 채워 푹 고아낸 대표적인 전통 보양식",
    "descEn": "Whole tender young chicken stuffed with sweet sticky rice, ginseng root, jujubes, and garlic, simmered in rich medicinal broth",
    "categoryTag": "MEAL",
    "unitPriceKrw": 18000,
    "priceMinKrw": 16000,
    "priceMaxKrw": 22000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/a1ac7b39-e0fb-4b2a-98bb-e29d133fa609/it11",
    "targetScope": "BOTH",
    "sortOrder": 19,
    "isActive": true
  },
  {
    "id": "nat_gamjatang",
    "scope": "NATIONAL",
    "nameKo": "감자탕 (뼈해장국)",
    "nameEn": "Gamjatang (Pork Bone Stew with Potatoes)",
    "descKo": "돼지 등뼈와 우거지, 감자, 들깨가루를 듬뿍 넣고 오랜 시간 푹 고아내 깊고 구수한 맛을 내는 탕 요리",
    "descEn": "Rich, deep broth stewed for hours with meaty pork spine bones, dried cabbage greens, whole potatoes, and perilla seeds",
    "categoryTag": "MEAL",
    "unitPriceKrw": 11000,
    "priceMinKrw": 10000,
    "priceMaxKrw": 13000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2c070992-9577-4377-b7a1-c5a8476c9d4b/it11",
    "targetScope": "BOTH",
    "sortOrder": 20,
    "isActive": true
  },
  {
    "id": "nat_miyeok_guk",
    "scope": "NATIONAL",
    "nameKo": "미역국",
    "nameEn": "Miyeok-guk (Seaweed Soup with Beef)",
    "descKo": "참기름에 소고기와 바다 미역을 정성스레 볶은 후 오랜 시간 맑고 진하게 끓여낸 건강하고 따뜻한 생일 및 보양 탕 요리",
    "descEn": "Hearty and comforting brown seaweed soup gently simmered with tender beef slices and toasted sesame oil, iconic for Korean birthdays and celebration",
    "categoryTag": "MEAL",
    "unitPriceKrw": 10000,
    "priceMinKrw": 9000,
    "priceMaxKrw": 13000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/5d260c22-cbc0-4173-a41c-77bf7744ddad/it11",
    "targetScope": "BOTH",
    "sortOrder": 21,
    "isActive": true
  },
  {
    "id": "nat_tteokbokki_set",
    "scope": "NATIONAL",
    "nameKo": "떡튀순 (떡볶이, 튀김, 순대)",
    "nameEn": "Tteok-Twi-Soon (Tteokbokki, Tempura & Blood Sausage)",
    "descKo": "매콤달콤한 고추장 양념에 끓여낸 쫄깃한 쌀떡볶이와 바삭한 모둠튀김, 찰순대 분식 세트",
    "descEn": "Chewy cylinder rice cakes simmered in sweet and spicy chili paste sauce, paired with crispy fritters and steamed sausage",
    "categoryTag": "STREET_SNACK",
    "unitPriceKrw": 12000,
    "priceMinKrw": 9000,
    "priceMaxKrw": 15000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/263fff1d-a001-4f40-8369-b53ae49ac852/it11",
    "targetScope": "BOTH",
    "sortOrder": 22,
    "isActive": true
  },
  {
    "id": "nat_street_toast",
    "scope": "NATIONAL",
    "nameKo": "길거리 토스트",
    "nameEn": "Gilgeori Toast (Korean Street Egg Toast)",
    "descKo": "버터에 구운 식빵 사이에 달걀 채소 패티와 햄을 넣고 설탕과 케첩을 뿌려 달콤 짭조름하게 즐기는 한국식 길거리 토스트",
    "descEn": "Buttery toasted sandwich layered with an egg-vegetable patty, savory ham, ketchup, and sugar for a signature sweet-savory punch",
    "categoryTag": "STREET_SNACK",
    "unitPriceKrw": 5500,
    "priceMinKrw": 4500,
    "priceMaxKrw": 7000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/911762eb-2164-485f-a429-cee65acc190f/it11",
    "targetScope": "BOTH",
    "sortOrder": 23,
    "isActive": true
  },
  {
    "id": "nat_kkwabaegi_bungeoppang",
    "scope": "NATIONAL",
    "nameKo": "꽈배기",
    "nameEn": "Kkwabaegi (Korean Twisted Donut)",
    "descKo": "전통 시장에서 갓 튀겨내 설탕을 솔솔 묻힌 쫄깃하고 폭신한 추억의 찹쌀 꽈배기",
    "descEn": "Chewy, fluffy twisted donut freshly deep-fried at traditional markets and lightly coated in sweet sugar",
    "categoryTag": "DESSERT_CAFE",
    "unitPriceKrw": 3500,
    "priceMinKrw": 2500,
    "priceMaxKrw": 5000,
    "isMustEatTop3": false,
    "emoji": "",
    "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/6f75994d-b61a-425c-ae46-c1847f755a0d/it11",
    "targetScope": "BOTH",
    "sortOrder": 24,
    "isActive": true
  }
];

// =========================================================================
// 2.  10대 도시별 대표 로컬 음식 카탈로그
// =========================================================================
export const CITY_SPECIALTY_FOODS: Record<SupportedCity, FoodItemDefinition[]> = {
  "SEOUL": [
    {
      "id": "seoul_gwangjang_pancake",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "광장시장 녹두빈대떡",
      "nameEn": "Gwangjang Market Bindaetteok (Mung Bean Pancake)",
      "descKo": "맷돌로 거칠게 간 녹두 반죽에 숙주와 돼지고기를 넣고 무쇠 철판에 바삭하고 두툼하게 부쳐낸 광장시장 명물",
      "descEn": "Crispy, savory stone-ground mung bean pancake pan-fried in oil with bean sprouts and pork at historic Gwangjang Market",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 6000,
      "priceMinKrw": 7000,
      "priceMaxKrw": 12000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/ddbf212e-256d-4d37-880c-8643c611da55/it11",
      "targetScope": "BOTH",
      "sortOrder": 25,
      "isActive": true
    },
    {
      "id": "seoul_seolleongtang",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "설렁탕",
      "nameEn": "Seolleongtang (Ox Bone Soup)",
      "descKo": "소 뼈와 양지를 가마솥에서 오랜 시간 뽀얗게 고아낸 진한 사골 육수에 소면과 밥, 깍두기를 곁들여 먹는 탕",
      "descEn": "Rich, milky ox bone soup simmered for 15+ hours, served with tender beef slices, noodles, and crunchy radish kimchi",
      "categoryTag": "MEAL",
      "unitPriceKrw": 13000,
      "priceMinKrw": 11000,
      "priceMaxKrw": 16000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Seolleongtang.jpg",
      "targetScope": "BOTH",
      "sortOrder": 26,
      "isActive": true
    },
    {
      "id": "food_724803",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "광장시장 육회",
      "nameEn": "Gwangjang Market Korean Beef Tartare (Yukhoe)",
      "descKo": "신선한 소고기 우둔살을 얇게 썰어 참기름과 마늘 양념에 버무린 뒤 달콤한 배, 달걀노른자를 곁들여 먹는 고급 요리",
      "descEn": "신선한 소고기 우둔살을 얇게 썰어 참기름과 마늘 양념에 버무린 뒤 달콤한 배, 달걀노른자를 곁들여 먹는 고급 요리",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 23000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 18000,
      "targetScope": "BOTH",
      "sortOrder": 26,
      "isMustEatTop3": false,
      "imageUrl": "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20240416_73%2F1713260931839RK78G_JPEG%2F%25C0%25B0%25C8%25B82.jpg",
      "isActive": true
    },
    {
      "id": "seoul_sindang_tteokbokki",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "신당동 즉석떡볶이",
      "nameEn": "Sindang-dong Tabletop Tteokbokki",
      "descKo": "춘장과 고추장 황금비율 양념에 떡, 쫄면, 라면, 야끼만두, 계란을 즉석에서 끓여 먹는 신당동 떡볶이 골목 원조 메뉴",
      "descEn": "Iconic table-cooked spicy rice cakes simmered in red pepper and black bean paste with ramen, dumplings, and eggs",
      "categoryTag": "MEAL",
      "unitPriceKrw": 11000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 14000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=3428735f-d5de-4d49-9d67-37e6168c242a",
      "targetScope": "BOTH",
      "sortOrder": 27,
      "isActive": true
    },
    {
      "id": "seoul_mapo_galbi",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "마포 돼지갈비",
      "nameEn": "Mapo Pork Galbi (Charcoal BBQ Ribs)",
      "descKo": "달콤 짭조름한 비법 간장 양념에 재운 돼지갈비를 참숯불에 노릇하게 구워 먹는 마포 갈비 골목 전통의 맛",
      "descEn": "Succulent pork ribs marinated in seasoned sweet soy glaze, charcoal-grilled to caramelized perfection in historic Mapo",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 17000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 21000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/25/2858125_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 28,
      "isActive": true
    },
    {
      "id": "seoul_dongdaemun_dakhanmari",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "동대문 닭한마리",
      "nameEn": "Dongdaemun Dakhanmari (Whole Chicken Hotpot)",
      "descKo": "양은 냄비에 통닭 한 마리를 맑은 육수에 끓여 알싸한 겨자 다대기 소스에 찍어 먹고 칼국수로 마무리하는 동대문 명물",
      "descEn": "Whole tender chicken simmered at the table in clear broth, dipped in spicy vinegar-mustard sauce and finished with fresh knife-cut noodles",
      "categoryTag": "MEAL",
      "unitPriceKrw": 15000,
      "priceMinKrw": 13000,
      "priceMaxKrw": 19000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/43/2869643_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 29,
      "isActive": true
    },
    {
      "id": "seoul_namdaemun_galchijorim",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "남대문 갈치조림",
      "nameEn": "Namdaemun Galchi-jorim (Braised Cutlassfish)",
      "descKo": "도톰한 갈치와 달큰하게 푹 익은 무를 매콤달콤한 고춧가루 양념에 졸여낸 남대문 시장 갈치 골목 대표 밥도둑",
      "descEn": "Thick fresh cutlassfish steaks and tender radishes braised in a bubbling pot of fiery, savory red chili garlic sauce",
      "categoryTag": "MEAL",
      "unitPriceKrw": 12000,
      "priceMinKrw": 10000,
      "priceMaxKrw": 15000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/7f241234-ee93-4ff5-a445-7429d95cdf6f/it11",
      "targetScope": "BOTH",
      "sortOrder": 30,
      "isActive": true
    },
    {
      "id": "seoul_euljiro_golbaengi",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "을지로 골뱅이무침",
      "nameEn": "Euljiro Golbaengi-muchim (Spicy Sea Snail Salad)",
      "descKo": "큼직하고 쫄깃한 통골뱅이를 알싸한 파채와 고춧가루, 명태포와 함께 거칠게 버무려 맥주와 즐기는 힙지로 안주",
      "descEn": "Plump sea snails tossed with fresh scallion threads, dried pollock strips, and spicy red pepper, served in retro Euljiro alleys",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 18000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 23000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Golbaengi-muchim_2.jpg/960px-Golbaengi-muchim_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "targetScope": "BOTH",
      "sortOrder": 31,
      "isActive": true
    },
    {
      "id": "seoul_sillim_sundaebokkeum",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "신림동 순대볶음",
      "nameEn": "Sillim-dong Sundae-bokkeum (Stir-fried Blood Sausage)",
      "descKo": "철판에 순대, 곱창, 쫄면, 깻잎, 양배추를 들깨가루와 매콤한 특제 양념과 함께 푸짐하게 볶아 먹는 신림동 순대타운 명물",
      "descEn": "Chewy Korean glass noodle sausages and perilla leaves stir-fried on a hot iron griddle with cabbage and rich perilla seed seasonings at Sillim Sundae Town",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 11000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 14000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/36/3526736_image2_1.JPG",
      "targetScope": "BOTH",
      "sortOrder": 32,
      "isActive": true
    },
    {
      "id": "seoul_majang_hanwoo",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "마장동 한우",
      "nameEn": "Majang-dong Hanwoo (Premium Korean Beef BBQ)",
      "descKo": "국내 최대 축산물 시장인 마장동에서 직송한 최고 등급(1++ 투뿔) 한우를 숯불에 구워 고소한 육즙과 부드러운 풍미를 즐기는 서울 대표 소고기 구이",
      "descEn": "Top-grade 1++ Korean native beef (Hanwoo) charcoal-grilled to melt-in-your-mouth perfection, sourced directly from historic Majang Meat Market",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 45000,
      "priceMinKrw": 35000,
      "priceMaxKrw": 65000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/752556b2-4452-4b16-ab71-5bf4ec2706c2/it11",
      "targetScope": "BOTH",
      "sortOrder": 33,
      "isActive": true
    },
    {
      "id": "seoul_jangchung_jokbal",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "장충동 족발",
      "nameEn": "Jangchung-dong Jokbal (Braised Pig's Trotters)",
      "descKo": "각종 한약재와 비법 육수에 오랜 시간 푹 삶아내 쫄깃하고 부드러운 장충동 족발 골목의 원조 보양 요리",
      "descEn": "Tender sliced pig's trotters slowly braised with herbs and soy sauce until gelatinous, soft, and richly savory",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 28000,
      "priceMinKrw": 24000,
      "priceMaxKrw": 36000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/42/2794142_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 34,
      "isActive": true
    },
    {
      "id": "insadong_traditional_tea",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "인사동 전통 찻집 & 한과 세트",
      "nameEn": "Insadong Traditional Tea & Snack Set",
      "descKo": "인사동 쌈지길 고즈넉한 한옥 찻집에서 즐기는 전통 차와 유과·약과 한과 세트",
      "descEn": "Traditional iced Omija berry tea paired with handcrafted Korean sweet honey cookies in Insadong Hanok tea house",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 15000,
      "priceMinKrw": 14000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": true,
      "emoji": "🍵",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/13090ab1-108d-45de-88fb-20ca1010aecd/it11",
      "targetScope": "BOTH",
      "sortOrder": 36,
      "isActive": true
    },
    {
      "id": "myeongdong_street_snack",
      "scope": "CITY_LOCAL",
      "cityCode": "SEOUL",
      "nameKo": "명동 스트리트 푸드 콤보",
      "nameEn": "Myeongdong Street Food Tasting Combo",
      "descKo": "랍스터구이, 닭꼬치, 회오리감 등 화려하고 이색적인 간식 노점들이 즐비해 골라 먹는 재미가 가득한 서울의 대표 길거리 미식 코스",
      "descEn": "Tasting combo featuring sweet honey hotteok, egg street toast, strawberry tanghulu, and fish cake skewers in vibrant Myeongdong",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 10000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": true,
      "emoji": "🍢",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2186c273-3d14-4c32-81f0-e539c7182261/it11",
      "targetScope": "BOTH",
      "sortOrder": 38,
      "isActive": true
    }
  ],
  "BUSAN": [
    {
      "id": "busan_dwaeji_gukbap",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "돼지국밥",
      "nameEn": "Busan Pork Soup (Dwaeji-gukbap)",
      "descKo": "진하게 우려낸 돼지 사골 육수에 부드러운 수육과 밥을 말아 부추무침, 새우젓을 곁들여 먹는 든든한 부산 대표 소울푸드",
      "descEn": "Piping-hot, rich pork bone broth packed with tender meat alongside savory boiled pork belly slices platter for two",
      "categoryTag": "MEAL",
      "unitPriceKrw": 11000,
      "priceMinKrw": 20000,
      "priceMaxKrw": 28000,
      "isMustEatTop3": true,
      "emoji": "🍲",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/d524e369-9b2f-4ff2-91a8-258f4d57ccdd/it11",
      "targetScope": "BOTH",
      "sortOrder": 41,
      "isActive": true
    },
    {
      "id": "jagalchi_raw_fish",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "자갈치 회센터 제철 활어회",
      "nameEn": "Jagalchi Market Fresh Sashimi Platter",
      "descKo": "자갈치 수산시장에서 갓 잡은 싱싱한 제철 활어를 얇게 썰어 초고추장, 쌈채소, 매운탕과 함께 즐기는 부산 대표 바다 미식",
      "descEn": "Ocean-fresh seasonal sashimi platter featuring wild flatfish and rockfish paired with piping-hot spicy fish stew for two at Jagalchi Market",
      "categoryTag": "MEAL",
      "unitPriceKrw": 50000,
      "priceMinKrw": 50000,
      "priceMaxKrw": 75000,
      "isMustEatTop3": true,
      "emoji": "🐟",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/47181571-c482-4ea5-9450-1b777937b340/it11",
      "targetScope": "BOTH",
      "sortOrder": 42,
      "isActive": true
    },
    {
      "id": "busan_nampo_street_snack",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "남포동 씨앗호떡",
      "nameEn": "Busan Ssiat Hotteok (Seed-Stuffed Sweet Pancake)",
      "descKo": "마가린에 노릇하게 튀겨낸 쫄깃한 찹쌀 반죽 속에 흑설탕과 해바라기씨, 호박씨 등 고소한 견과류를 가득 채운 부산의 명물 길거리 디저트",
      "descEn": "Crispy sweet pancakes stuffed with crunchy seeds and nuts alongside chewy Busan skewered rice cakes in savory fish cake broth",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 2000,
      "priceMinKrw": 6000,
      "priceMaxKrw": 12000,
      "isMustEatTop3": true,
      "emoji": "🥞",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/2ffe1acd-81bc-47ba-890d-00959840a780/it11",
      "targetScope": "BOTH",
      "sortOrder": 43,
      "isActive": true
    },
    {
      "id": "busan_milmyeon",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "부산 밀면",
      "nameEn": "Busan Milmyeon (Wheat Noodle Soup)",
      "descKo": "살얼음 동동 뜬 시원한 한약재 사골 육수에 밀가루로 뽑은 쫄깃한 면과 매콤한 양념장을 얹어 먹는 부산의 대표 여름 별미 국수",
      "descEn": "Busan signature cold wheat noodles served in icy herbal beef broth with cucumber, hard-boiled egg, and sweet chili sauce",
      "categoryTag": "MEAL",
      "unitPriceKrw": 9500,
      "priceMinKrw": 8000,
      "priceMaxKrw": 12000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/de36985f-2083-410e-9c1c-366d26dfe53a/it11",
      "targetScope": "BOTH",
      "sortOrder": 44,
      "isActive": true
    },
    {
      "id": "busan_naengchae_jokbal",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "부산 냉채족발",
      "nameEn": "Busan Naengchae Jokbal (Chilled Braised Pig's Feet Salad)",
      "descKo": "얇게 썬 쫄깃한 족발에 아삭한 오이, 해파리, 톡 쏘는 알싸한 겨자 소스를 버무려 새콤하고 시원하게 즐기는 부산 부평동의 명물 요리",
      "descEn": "Chilled thinly-sliced braised pork trotters tossed with jellyfish, cucumber matchsticks, and refreshing pungent mustard dressing's trotters tossed with jellyfish, cucumber slices, and sinus-clearing mustard dressing",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 35000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 23000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/6e529c81-048b-46ba-879c-847df92413b4/it11",
      "targetScope": "BOTH",
      "sortOrder": 50,
      "isActive": true
    },
    {
      "id": "busan_dongnae_pajeon",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "동래파전",
      "nameEn": "Dongnae Pajeon (Traditional Green Onion Pancake)",
      "descKo": "달큰한 쪽파에 신선한 해물과 소고기를 얹고 찹쌀 반죽과 달걀을 풀어 촉촉하고 부드럽게 지져낸 부산 동래의 유서 깊은 향토 전 요리",
      "descEn": "Historic scallion pancake topped with fresh seafood, tender beef, and egg, fried soft and moist inside and golden crispy outside",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 20000,
      "priceMinKrw": 16000,
      "priceMaxKrw": 25000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/82b55b4e-d58d-4877-8887-2df8ab454a8a/it11",
      "targetScope": "BOTH",
      "sortOrder": 51,
      "isActive": true
    },
    {
      "id": "busan_seafood_night",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "광안리 조개구이",
      "nameEn": "Gwangalli Ocean View Seafood Platter",
      "descKo": "광안대교 야경을 바라보며 가리비, 키조개 등 신선한 조개를 치즈, 버터와 함께 불판에 구워 먹는 부산의 대표 밤바다 미식",
      "descEn": "Fresh coastal grilled clams and seasonal seafood platter overlooking nighttime Gwangalli Bridge",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 40000,
      "priceMinKrw": 50000,
      "priceMaxKrw": 80000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20251209_93%2F1765272473278C8yG9_JPEG%2FGJF02076.jpg",
      "targetScope": "BOTH",
      "sortOrder": 53,
      "isActive": true
    },
    {
      "id": "busan_street_snack",
      "scope": "CITY_LOCAL",
      "cityCode": "BUSAN",
      "nameKo": "부산 물떡 어묵",
      "nameEn": "Busan Eomuk & Mul-tteok (Fish Cake & Rice Cake Skewers)",
      "descKo": "깊은 감칠맛의 따끈한 해물 육수에 푹 익힌 쫄깃한 가래떡과 도톰한 부산 어묵을 간장에 찍어 먹는 부산의 대표 길거 간식",
      "descEn": "Busan's iconic sweet seed hotteok paired with chewy rice cake skewers in piping-hot fish cake broth",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 4000,
      "priceMinKrw": 6000,
      "priceMaxKrw": 10000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/6fd5b254-89ca-4842-bb89-c4a26b4c34a7/it11",
      "targetScope": "BOTH",
      "sortOrder": 54,
      "isActive": true
    }
  ],
  "JEJU": [
    {
      "id": "jeju_black_pork",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 흑돼지 구이",
      "nameEn": "Jeju Black Pork BBQ",
      "descKo": "도톰하고 쫄깃한 육질의 제주 흑돼지를 참숯에 구워 보글보글 끓인 짭조름한 멜젓(멸치젓)에 찍어 먹는 제주의 대표 명품 구이",
      "descEn": "Authentic Jeju black pork thick-cut belly charcoal-grilled and served with warm fermented anchovy meljeot dipping sauce feast for two",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 25000,
      "priceMinKrw": 56000,
      "priceMaxKrw": 75000,
      "isMustEatTop3": true,
      "emoji": "🥩",
      "imageUrl": "https://aqfvmuytaukrkdmememh.supabase.co/storage/v1/object/public/admin_data/foods/jeju-black-pork.jpg",
      "targetScope": "BOTH",
      "sortOrder": 55,
      "isActive": true
    },
    {
      "id": "jeju_seafood_ramyeon",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 해물라면",
      "nameEn": "Jeju Coastal Seafood Ramyeon",
      "descKo": "얼큰하고 시원한 라면 국물에 통째로 들어간 쫄깃한 문어와 싱싱한 해산물을 가득 얹어 바다 향을 진하게 즐기는 해변 요리",
      "descEn": "Whole baby octopus, fresh abalone, crab and mussels simmered in spicy broth paired with sweet Jeju red band shrimp sashimi",
      "categoryTag": "MEAL",
      "unitPriceKrw": 16000,
      "priceMinKrw": 22000,
      "priceMaxKrw": 32000,
      "isMustEatTop3": true,
      "emoji": "🍜",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/98/2905298_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 56,
      "isActive": true
    },
    {
      "id": "jeju_gogi_guksu",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 고기국수",
      "nameEn": "Jeju Gogi-guksu (Pork Noodle Soup)",
      "descKo": "진하게 우려낸 돼지 사골 육수에 도톰한 중면을 말아 부드러운 돔베고기(수육)를 듬뿍 얹어 먹는 든든한 제주 전통 면 요리",
      "descEn": "Comforting bowl of yellow wheat noodles in rich pork bone broth crowned with tender slices of braised pork belly",
      "categoryTag": "MEAL",
      "unitPriceKrw": 10000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 12000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b03baf34-39e0-4833-8025-daa4f75fd206/it11",
      "targetScope": "BOTH",
      "sortOrder": 58,
      "isActive": true
    },
    {
      "id": "jeju_galchi_jorim",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 갈치구이",
      "nameEn": "Jeju Grilled Cutlassfish (Galchi-gui)",
      "descKo": "제주 청정 바다에서 잡은 은갈치를 통째로 노릇하게 구워내 담백하고 부드러운 하얀 속살과 고소한 풍미를 즐기는 명품 해산물 요리",
      "descEn": "Extra-long wild silver cutlassfish simmered gently with radishes and potatoes in fiery-sweet garlic chili sauce",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 32000,
      "priceMinKrw": 28000,
      "priceMaxKrw": 42000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b88e1cd5-efaf-41ce-91c6-d0fb3f3b25b2/it11",
      "targetScope": "BOTH",
      "sortOrder": 59,
      "isActive": true
    },
    {
      "id": "jeju_abalone_porridge",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 전복 돌솥밥",
      "nameEn": "Jeju Jeonbok Dolsot-bap (Abalone Hot Pot Rice)",
      "descKo": "녹진한 전복 내장으로 지은 뜨거운 돌솥밥 위에 얇게 썬 전복과 단호박을 얹어 버터, 양념장에 비벼 먹고 누룽지로 마무리하는 제주 보양식",
      "descEn": "Rich, green-hued rice porridge simmered with wild abalone viscera, served alongside a sizzling clay pot of local seafood",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 16000,
      "priceMinKrw": 14000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/d0ee275c-c3ec-4fe5-8912-527faa0dc06d/it11",
      "targetScope": "BOTH",
      "sortOrder": 60,
      "isActive": true
    },
    {
      "id": "jeju_ttaksaewoo_sashimi",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 딱새우회",
      "nameEn": "Jeju Ttaksaewoo Sashimi (Red-banded Lobster Platter)",
      "descKo": "먹기 좋게 손질된 투명한 딱새우를 초장이나 간장에 찍어 한 입 베어 물면 특유의 탱글한 식감과 달큰한 감칠맛이 입안 가득 퍼지는 제주 별미 회",
      "descEn": "Pristine sweet red-banded spiny lobsters harvested around Jeju, noted for their tender, melt-in-mouth sweetness and chew's pristine waters",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 25000,
      "priceMinKrw": 20000,
      "priceMaxKrw": 32000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4f/%EB%94%B1%EC%83%88%EC%9A%B0.jpg",
      "targetScope": "BOTH",
      "sortOrder": 61,
      "isActive": true
    },
    {
      "id": "jeju_bomal_kalguksu",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 보말칼국수",
      "nameEn": "Jeju Bomal Kalguksu (Sea Snail Noodle Soup)",
      "descKo": "제주 바다 바위틈에서 채취한 바다고둥(보말)과 미역을 넣고 진하게 우려낸 짙은 초록빛 국물에 쫄깃한 칼국수 면을 말아 먹는 구수한 향토 국수",
      "descEn": "Deep green, richly savory noodle soup made from wild Jeju sea snails ground with internal organs for intense sea umami",
      "categoryTag": "MEAL",
      "unitPriceKrw": 12000,
      "priceMinKrw": 10000,
      "priceMaxKrw": 14000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/314a0e42-e50c-405d-9cbc-b6aee390ff9c/it11",
      "targetScope": "BOTH",
      "sortOrder": 62,
      "isActive": true
    },
    {
      "id": "jeju_citrus_omegi",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 해물 뚝배기",
      "nameEn": "Jeju Haemul Ddukbaegi (Seafood Hot Pot Stew)",
      "descKo": "살아있는 전복, 딱새우, 게, 조개 등 싱싱한 해산물을 뚝배기에 넣고 된장 베이스로 칼칼하고 시원하게 끓여낸 제주 대표 해장 찌개",
      "descEn": "Traditional Jeju mugwort rice cakes filled with sweet red beans rolled in azuki beans, served with refreshing Hallabong juice",
      "categoryTag": "MEAL",
      "unitPriceKrw": 16000,
      "priceMinKrw": 4500,
      "priceMaxKrw": 8000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/1eff7de2-aeb3-4331-a97e-17c7e9599266/it11",
      "targetScope": "BOTH",
      "sortOrder": 63,
      "isActive": true
    },
    {
      "id": "jeju_dombe_gogi",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 돔베고기",
      "nameEn": "Jeju Dombe-gogi (Boiled Pork on Cutting Board)",
      "descKo": "갓 삶아낸 두툼하고 촉촉한 돼지고기 수육을 나무 도마(돔베)에 썰어 굵은 소금과 멜젓, 쌈채소와 함께 즐기는 제주 향토 음식",
      "descEn": "Juicy, freshly boiled tender pork belly sliced on a rustic wooden chopping board with sea salt and pungent fermented anchovy sauce",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 22000,
      "priceMinKrw": 18000,
      "priceMaxKrw": 28000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/67/2836967_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 64,
      "isActive": true
    },
    {
      "id": "jeju_hanchi_mulhoe",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 물회",
      "nameEn": "Jeju Mulhoe (Cold Raw Fish Soup)",
      "descKo": "신선한 제철 회와 채소에 된장과 고추장을 푼 살얼음 육수를 붓고 밥이나 면을 말아 시원하고 새콤달콤하게 즐기는 제주의 대표 여름 바다 별미",
      "descEn": "Tender fresh squid slices served in refreshing ice-cold spicy broth seasoned with fermented soybean paste and vinegar",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 16000,
      "priceMinKrw": 14000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/89340c01-6459-49ea-a74f-32ce7b03e4a2/it11",
      "targetScope": "BOTH",
      "sortOrder": 65,
      "isActive": true
    },
    {
      "id": "jeju_okdom_gui",
      "scope": "CITY_LOCAL",
      "cityCode": "JEJU",
      "nameKo": "제주 옥돔구이",
      "nameEn": "Jeju Okdom-gui (Grilled Red Tilefish)",
      "descKo": "해풍에 꾸덕꾸덕하게 말린 제주산 옥돔을 노릇하게 구워내 담백하면서도 쫄깃한 흰 살과 깊은 감칠맛을 즐기는 제주의 대표 고급 생선구이",
      "descEn": "Sea-breeze dried royal red tilefish grilled with a golden crisp exterior and moist, delicately sweet and clean white meat",
      "categoryTag": "MEAL",
      "unitPriceKrw": 30000,
      "priceMinKrw": 18000,
      "priceMaxKrw": 28000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Korean_cuisine-Jeju_Island-Okdom_gui-Grilled_Tilefish-01.jpg",
      "targetScope": "BOTH",
      "sortOrder": 66,
      "isActive": true
    }
  ],
  "JEONJU": [
    {
      "id": "jeonju_bibimbap",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 비빔밥",
      "nameEn": "Jeonju Bibimbap (Royal Mixed Rice)",
      "descKo": "사골 육수로 지은 밥에 황포묵, 육회, 콩나물, 계절 나물 등 오색 고명을 정갈하게 얹어 놋그릇에 담아내는 유네스코 음식 창의도시 전주의 대표 요리",
      "descEn": "World-renowned UNESCO traditional rice bowl cooked in rich beef bone broth, topped with seasonal namul, mung bean jelly, and seasoned beef's culinary crown jewel: beef broth rice served in heavy brass bowl with seasoned beef tartare and 10 herbs",
      "categoryTag": "MEAL",
      "unitPriceKrw": 14000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 17000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/63/1023863_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 69,
      "isActive": true
    },
    {
      "id": "jeonju_kongnamul_gukbap",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 콩나물국밥",
      "nameEn": "Jeonju Kongnamul-gukbap (Bean Sprout Soup)",
      "descKo": "전주 8미 중 으뜸인 아삭한 콩나물과 오징어를 맑은 육수에 끓여 김가루와 수란(반숙란)을 곁들여 먹는 전주의 해장국",
      "descEn": "Crisp local bean sprouts simmered in clean anchovy-squid broth, served boiling with soft-poached eggs and roasted seaweed",
      "categoryTag": "MEAL",
      "unitPriceKrw": 9000,
      "priceMinKrw": 8000,
      "priceMaxKrw": 11000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/d167a354-34c8-4451-a24a-de6583f51af9/it11",
      "targetScope": "BOTH",
      "sortOrder": 70,
      "isActive": true
    },
    {
      "id": "jeonju_pi_sundae",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 피순대",
      "nameEn": "Jeonju Pi-sundae (Authentic Blood Sausage)",
      "descKo": "당면 대신 신선한 선지와 찹쌀, 채소를 대창 속에 꽉 채워 쪄내 녹진하고 고소한 풍미가 일품이며, 초장에 들깻가루를 섞어 찍어 먹는 전주의 대표 향토 순대",
      "descEn": "Creamy traditional blood sausage hand-stuffed in natural casing, dipped in vinegared chili paste and enjoyed in boiling spicy stew",
      "categoryTag": "MEAL",
      "unitPriceKrw": 10000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 13000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/56f763ae-ef59-4d25-a46c-9ee5711c76e6/it11",
      "targetScope": "BOTH",
      "sortOrder": 71,
      "isActive": true
    },
    {
      "id": "jeonju_moju_pajeon",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 모주",
      "nameEn": "Jeonju Moju (Herbal Wine)",
      "descKo": "막걸리에 계피, 대추, 생강 등 한약재를 넣고 달여 은은하게 달콤한 저알콜 모주",
      "descEn": "Naturally sweet low-alcohol herbal wine simmered with cinnamon and dates, paired with a crisp and savory seafood pancake",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 12000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 16000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://aqfvmuytaukrkdmememh.supabase.co/storage/v1/object/public/admin_data/foods/jeonju-moju.png",
      "targetScope": "BOTH",
      "sortOrder": 75,
      "isActive": true
    },
    {
      "id": "jeonju_veteran_kalguksu",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 베테랑 들깨칼국수",
      "nameEn": "Jeonju Veteran Kalguksu (Egg Drop Perilla Noodle Soup)",
      "descKo": "달걀을 푼 구수하고 걸쭉한 국물에 들깨가루, 김가루, 고춧가루를 삼색으로 듬뿍 얹어 비벼 먹는 한옥마을 명물 칼국수",
      "descEn": "Comforting thick egg-drop broth noodles generously dusted with toasted perilla seeds, nori flakes, and spicy red pepper",
      "categoryTag": "MEAL",
      "unitPriceKrw": 9000,
      "priceMinKrw": 8000,
      "priceMaxKrw": 11000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/09/3423009_image2_1.png",
      "targetScope": "BOTH",
      "sortOrder": 76,
      "isActive": true
    },
    {
      "id": "jeonju_chocopie",
      "scope": "CITY_LOCAL",
      "cityCode": "JEONJU",
      "nameKo": "전주 수제 초코파이",
      "nameEn": "Jeonju Artisanal Choco Pie",
      "descKo": "달콤한 초콜릿 코팅과 부드러운 초코 시트 사이에 딸기잼과 하얀 마시멜로 크림, 호두가 씹히는 전주 전통 베이커리 빵",
      "descEn": "Famous handmade pastry featuring soft chocolate biscuit filled with sweet strawberry jam, cream, and crunchy walnuts",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 3500,
      "priceMinKrw": 2800,
      "priceMaxKrw": 5000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/4c8f89db-cbdc-44ba-93e5-637fc2d0b5df/it11",
      "targetScope": "BOTH",
      "sortOrder": 78,
      "isActive": true
    }
  ],
  "GANGNEUNG": [
    {
      "id": "gangneung_chodang_sundubu",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "강릉 초당 순두부",
      "nameEn": "Gangneung Chodang Sundubu (Sea-Water Soft Tofu)",
      "descKo": "동해안 청정 바닷물을 간수로 사용하여 콩 본연의 고소하고 달큰한 풍미가 가득한 400년 전통의 부드러운 순두부",
      "descEn": "Celebrated 400-year traditional soft tofu coagulated exclusively with pristine East Sea deep seawater for unmatched natural sweetness",
      "categoryTag": "MEAL",
      "unitPriceKrw": 11000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 14000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b7147b69-9259-4330-bdd1-66a2df15a222/it11",
      "targetScope": "BOTH",
      "sortOrder": 79,
      "isActive": true
    },
    {
      "id": "gangneung_jang_kalguksu",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "강릉 장칼국수",
      "nameEn": "Gangneung Jang Kalguksu (Spicy Paste Noodles)",
      "descKo": "구수한 된장과 칼칼한 고추장을 멸치 육수에 풀어 호박, 감자, 계란을 넣고 걸쭉하게 끓여낸 강릉의 소울 칼국수",
      "descEn": "Thick hand-cut knife noodles simmered in rich, fiery red broth seasoned with fermented red pepper paste and soybean paste",
      "categoryTag": "MEAL",
      "unitPriceKrw": 9000,
      "priceMinKrw": 8000,
      "priceMaxKrw": 11000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/83/2868983_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 80,
      "isActive": true
    },
    {
      "id": "gangneung_gamja_ongsimi",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "강릉 감자옹심이",
      "nameEn": "Gangneung Gamja Ongsimi (Chewy Potato Dumplings)",
      "descKo": "강원도 감자를 갈아 빚은 쫀득한 새알심(옹심이)을 구수한 멸치 메밀 육수에 끓여낸 토속 음식",
      "descEn": "Traditional Gangwon regional comfort soup featuring delightfully chewy, handcrafted potato starch dumplings in savory broth",
      "categoryTag": "MEAL",
      "unitPriceKrw": 10000,
      "priceMinKrw": 8500,
      "priceMaxKrw": 12000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/06/3050806_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 83,
      "isActive": true
    },
    {
      "id": "gangneung_ojingeo_sundae",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "주문진 오징어순대",
      "nameEn": "Jumunjin Ojingeo Sundae (Stuffed Squid)",
      "descKo": "통오징어 몸통 속에 찹쌀, 두부, 야채를 꽉 채워 쪄낸 후 달걀물을 입혀 철판에 노릇하게 부쳐낸 동해안 별미",
      "descEn": "Fresh whole squid tube stuffed with sticky rice, tofu, and minced vegetables, sliced and pan-fried in golden egg wash",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 15000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 18000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/f058add7-1adb-4a33-9f70-e81c062e4cd8/it11",
      "targetScope": "BOTH",
      "sortOrder": 85,
      "isActive": true
    },
    {
      "id": "gangneung_mulhoe_set",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "사천진리 해변 모둠물회",
      "nameEn": "Gangneung Mulhoe (Chilled Assorted Raw Fish Soup)",
      "descKo": "동해 바다의 싱싱한 광어, 오징어, 해삼을 살얼음 띄운 매콤새콤한 과일 초고추장 육수에 말아 소면과 먹는 여름 요리",
      "descEn": "Plentiful fresh raw fish and seafood served in an icy, sweet-and-sour red pepper broth garnished with fine somyeon noodles",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 18000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 22000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/95/2874095_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 86,
      "isActive": true
    },
    {
      "id": "gangneung_gaori_jjim",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "강릉 가오리 생선찜",
      "nameEn": "Gangneung Gaori-jjim (Braised Stingray Fish)",
      "descKo": "결대로 부드럽게 찢어지는 가오리 살과 포슬포슬한 감자, 무를 특제 매콤달콤 양념에 졸여낸 강릉 로컬 대표 찜 요리",
      "descEn": "Succulent braised stingray with tender cartilege simmered in thick sweet-spicy chili glaze with soft potatoes and radishes",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 25000,
      "priceMinKrw": 20000,
      "priceMaxKrw": 32000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/63/2872363_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 87,
      "isActive": true
    },
    {
      "id": "jumunjin_seafood_market",
      "scope": "CITY_LOCAL",
      "cityCode": "GANGNEUNG",
      "nameKo": "주문진 수산시장 생선구이",
      "nameEn": "Jumunjin Grilled Fish",
      "descKo": "주문진 활어 수산시장에서 갓 잡아 노릇하게 구워낸 모둠 생선구이",
      "descEn": "Golden charcoal-grilled fresh fish assortment paired with hearty East Sea clam knife noodles at bustling Jumunjin seafood port",
      "categoryTag": "MEAL",
      "unitPriceKrw": 20000,
      "priceMinKrw": 20000,
      "priceMaxKrw": 30000,
      "isMustEatTop3": true,
      "emoji": "🐟",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/94/2785894_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 91,
      "isActive": true
    }
  ],
  "SOKCHO": [
    {
      "id": "sokcho_abai_sundae",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 아바이순대",
      "nameEn": "Sokcho Abai Sundae (North Korean Style Sausage)",
      "descKo": "돼지 대창 속에 찹쌀, 선지, 숙주, 배추를 꽉 채워 쪄낸 실향민들의 전통 순대로 매콤달콤한 명태회무침과 곁들여 먹는 요리",
      "descEn": "Generously stuffed thick pork intestine sausage packed with sweet rice and vegetables, paired with sweet-and-sour seasoned pollack salad",
      "categoryTag": "MEAL",
      "unitPriceKrw": 14000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 18000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/378bbc80-1aae-4177-bf80-d7a9b39c745c/it11",
      "targetScope": "BOTH",
      "sortOrder": 92,
      "isActive": true
    },
    {
      "id": "sokcho_dakgangjeong",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 만석 닭강정",
      "nameEn": "Sokcho Dakgangjeong (Sweet & Crispy Fried Chicken)",
      "descKo": "가마솥 고온에서 바삭하게 튀겨낸 닭고기를 조청과 고추로 버무려 식어도 바삭한 속초 중앙시장의 명물",
      "descEn": "Famous crispy bite-sized fried chicken glazed with thick traditional grain syrup, chili peppers, and roasted almond flakes",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 20000,
      "priceMinKrw": 18000,
      "priceMaxKrw": 23000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/38013424-945e-49f3-b388-8b38d46c6367/it11",
      "targetScope": "BOTH",
      "sortOrder": 93,
      "isActive": true
    },
    {
      "id": "sokcho_bongpo_mulhoe",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 모둠 물회",
      "nameEn": "Sokcho Bongpo Mulhoe (Cold Seafood Soup)",
      "descKo": "성게, 해삼, 활어회, 전복을 과일 발효 초장에 시원한 살얼음과 비벼 소면과 함께 즐기는 속초의 1등 해산물 요리",
      "descEn": "Loaded cold bowl of live sea urchin, abalone, sea cucumber, and fresh raw fish slices bathed in slushy tangy chili broth",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 19000,
      "priceMinKrw": 17000,
      "priceMaxKrw": 24000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/05/4032905_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 94,
      "isActive": true
    },
    {
      "id": "sokcho_red_crab_feast",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 동해안 홍게 찜",
      "nameEn": "Sokcho Steamed Red Snow Crab",
      "descKo": "속초 앞바다 심해에서 갓 잡은 신선한 붉은 대게(홍게)를 찜기에 쪄서 꽉 찬 달콤한 속살과 게딱지 볶음밥을 먹는 요리",
      "descEn": "Fresh sweet East Sea red snow crabs steamed to order, served with fragrant crab shell fried rice seasoned with toasted nori and sesame oil",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 37000,
      "priceMinKrw": 30000,
      "priceMaxKrw": 50000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/95/2873995_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 95,
      "isActive": true
    },
    {
      "id": "sokcho_seopguk",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 자연산 섭국",
      "nameEn": "Sokcho Seopguk (Spicy Wild Mussel Soup)",
      "descKo": "동해 깊은 바다 갯바위에서 딴 큼직한 자연산 홍합(섭)을 된장과 고추장 육수에 부추, 미나리와 얼큰하게 끓여낸 향토 해장국",
      "descEn": "Robust spicy and comforting red broth soup cooked with giant wild East Sea mussels, fresh chives, and leeks",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 13000,
      "priceMinKrw": 11000,
      "priceMaxKrw": 16000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/58704b48-1069-4ff3-9737-a1225e7fdf9c/it11",
      "targetScope": "BOTH",
      "sortOrder": 97,
      "isActive": true
    },
    {
      "id": "sokcho_dongmyeong_sashimi",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "동명항 활어회",
      "nameEn": "Dongmyeong Port Fresh Sashimi Platter",
      "descKo": "속초 동명항 포차거리에서 갓 잡아 올린 도다리, 가자미, 오징어를 바닷바람을 맞으며 맛보는 자연산 활어회",
      "descEn": "Just-caught East Sea seasonal wild sashimi sliced fresh at dockside markets, enjoyed with savory ssamjang dip by the sea",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 30000,
      "priceMinKrw": 25000,
      "priceMaxKrw": 42000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/74/3488474_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 98,
      "isActive": true
    },
    {
      "id": "sokcho_grilled_fish",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 숯불 생선구이",
      "nameEn": "Sokcho Charcoal Grilled Fish Feast",
      "descKo": "고등어, 꽁치, 조기, 메로, 양미리, 열기 등 다양한 동해안 생선을 참숯불에 즉석에서 직접 구워 먹는 속초 명물 한상",
      "descEn": "Assorted seasonal East Sea fresh fish charcoal-grilled table-side over glowing embers until smoky and juicy",
      "categoryTag": "MEAL",
      "unitPriceKrw": 17000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 21000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/82/3555082_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 99,
      "isActive": true
    },
    {
      "id": "sokcho_makguksu",
      "scope": "CITY_LOCAL",
      "cityCode": "SOKCHO",
      "nameKo": "속초 동치미 막국수",
      "nameEn": "Sokcho Dongchimi Makguksu (Buckwheat Noodles)",
      "descKo": "항아리에서 숙성한 톡 쏘는 살얼음 동치미 무 육수를 순메밀 국수에 부어 들기름과 함께 담백하게 비벼 먹는 국수",
      "descEn": "Rustic buckwheat noodles served with naturally fermented icy radish water kimchi broth, perilla oil, and sesame seeds",
      "categoryTag": "MEAL",
      "unitPriceKrw": 10000,
      "priceMinKrw": 9000,
      "priceMaxKrw": 13000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/0611d261-71de-4172-9926-93ce1555072b/it11",
      "targetScope": "BOTH",
      "sortOrder": 100,
      "isActive": true
    }
  ],
  "GYEONGJU": [
    {
      "id": "gyeongju_hwangnambbang",
      "scope": "CITY_LOCAL",
      "cityCode": "GYEONGJU",
      "nameKo": "경주 찰보리빵",
      "nameEn": "Gyeongju Barley Bread",
      "descKo": "얇은 밀가루 피 속에 100% 국산 팥앙금을 가득 채워 구워낸 80년 전통의 경주 공인 전통 빵",
      "descEn": "Historic Gyeongju regional pastries featuring thin crust stuffed with silky sweet red bean paste and soft chewy barley pancakes",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 12000,
      "priceMinKrw": 10000,
      "priceMaxKrw": 15000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://i.namu.wiki/i/Ta91OH5svWQiSLADLlr22Lwwz465iaZOKnwgJb4Ws1iDXtRy8v_htu15mmcT2EpVCRfO3SG-sGRJOPpF2O9CJmDOSM7fU1JY0vdFoMBr5_pqQ7yhgOOsLaoB8kRzOfZFAxV6AnQWSd3G4bpzHrrP0w.webp",
      "targetScope": "BOTH",
      "sortOrder": 102,
      "isActive": true
    },
    {
      "id": "gyeongju_hanwoo_mulhoe",
      "scope": "CITY_LOCAL",
      "cityCode": "GYEONGJU",
      "nameKo": "경주 한우 물회",
      "nameEn": "Gyeongju Hanwoo Beef Mulhoe (Chilled Raw Beef)",
      "descKo": "신선한 최고급 경주 한우 육회를 살얼음 띄운 매콤달콤한 비법 육수에 소면, 오이와 함께 말아먹는 경주만의 독특한 별미",
      "descEn": "Premium Korean native beef tartare served in an icy, sweet-and-tangy cold soup with thin cucumber slices and somyeon noodles",
      "categoryTag": "MEAL",
      "unitPriceKrw": 14000,
      "priceMinKrw": 13000,
      "priceMaxKrw": 18000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20260826_198%2F1787735336548RAksw_JPEG%2F%25BF%25EC%25B8%25B6%25BF%25D5_%25B8%25DE%25B4%25BA_%25C7%25D1%25BF%25EC%25C0%25B0%25C8%25B8%25B9%25B0%25C8%25B82.jpg",
      "targetScope": "BOTH",
      "sortOrder": 103,
      "isActive": true
    },
    {
      "id": "gyeongju_10won_bread",
      "scope": "CITY_LOCAL",
      "cityCode": "GYEONGJU",
      "nameKo": "황리단길 십원빵",
      "nameEn": "Hwangridan-gil 10-Won Coin Cheese Bread",
      "descKo": "경주 다보탑이 새겨진 옛 10원짜리 동전 모양 빵 반죽 속에 고소한 모짜렐라 치즈가 길게 늘어나는 인기 길거리 디저트",
      "descEn": "Fun waffle pastry shaped like Korea's historic 10-won coin, filled with stretchy melted mozzarella cheese and sweet custard's historic 10-won coin, filled with stretchy melted mozzarella cheese and sweet custard",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 3500,
      "priceMinKrw": 3000,
      "priceMaxKrw": 4500,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220531_181%2F1653977753429F2beY_JPEG%2F27B852CA-F098-4A1B-9F49-BFD600D1443A.jpeg",
      "targetScope": "BOTH",
      "sortOrder": 109,
      "isActive": true
    },
    {
      "id": "gyeongju_mukbap",
      "scope": "CITY_LOCAL",
      "cityCode": "GYEONGJU",
      "nameKo": "경주 메밀 막국수",
      "nameEn": "Gyeongju Buckwheat Makguksu",
      "descKo": "구수한 메밀면 위에 시원하고 감칠맛 나는 동치미·사골 육수나 매콤달콤한 비빔 양념장을 얹어 아삭한 채소와 함께 즐기는 경주의 대표 별미 국수",
      "descEn": "Wholesome bowl of sliced buckwheat jelly served in chilled savory broth with finely chopped kimchi and seaweed",
      "categoryTag": "MEAL",
      "unitPriceKrw": 10000,
      "priceMinKrw": 8000,
      "priceMaxKrw": 12000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20190423_30%2F1556006280590IqxuY_JPEG%2FXLTRV2uoYT3fX3yDGAo_tBen.jpg",
      "targetScope": "BOTH",
      "sortOrder": 110,
      "isActive": true
    }
  ],
  "SUWON": [
    {
      "id": "suwon_wanggalbi",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원 왕갈비",
      "nameEn": "Suwon Wang-galbi (King Charcoal Beef Ribs)",
      "descKo": "정조대왕 시절부터 이어져 온 수원의 상징으로, 큼직한 소갈비에 소금과 마늘, 참기름으로 담백하게 간한 명품 숯불구이",
      "descEn": "Giant royal bone-in beef short ribs seasoned delicately with sea salt, sesame, and garlic, charcoal-grilled over hot coals's legendary meat dishes: massive prime beef ribs seasoned lightly with salt, garlic, and sesame",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 38000,
      "priceMinKrw": 32000,
      "priceMaxKrw": 52000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=472e0548-f287-4407-b728-318b1bd6dd36",
      "targetScope": "BOTH",
      "sortOrder": 113,
      "isActive": true
    },
    {
      "id": "suwon_chicken_street",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원 왕갈비 통닭",
      "nameEn": "Suwon Wang-galbi Fried Chicken",
      "descKo": "달콤짭조름한 특제 왕갈비 양념 소스를 바삭하게 튀긴 치킨에 버무려 전국적 인기를 얻은 수원의 대표 명물 통닭",
      "descEn": "Crispy fried chicken tossed in sweet, savory, and aromatic Wang-galbi barbecue sauce, a famous signature of Suwon",
      "categoryTag": "MEAL",
      "unitPriceKrw": 21000,
      "priceMinKrw": 19000,
      "priceMaxKrw": 24000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://cdn.visitkorea.or.kr/img/call?cmd=VIEW&id=9385c5d0-c078-4d8f-b0d8-1ae0d6b63ee5",
      "targetScope": "BOTH",
      "sortOrder": 114,
      "isActive": true
    },
    {
      "id": "suwon_wang_galbitang",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원 왕갈비탕",
      "nameEn": "Suwon Wang-galbitang (Giant Beef Rib Soup)",
      "descKo": "성인 팔뚝만 한 거대한 소갈비 뼈 2대를 맑은 육수에 푹 고아 파와 당면을 넣고 푸짐하게 끓여낸 든든한 보양탕",
      "descEn": "Enormous beef ribs cooked in clear aromatic broth with glass noodles and scallions, served with hot dipping mustard sauce",
      "categoryTag": "MEAL",
      "unitPriceKrw": 15000,
      "priceMinKrw": 13000,
      "priceMaxKrw": 18000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "/assets/suwon-wang-galbitang.jpg",
      "targetScope": "BOTH",
      "sortOrder": 115,
      "isActive": true
    },
    {
      "id": "suwon_boyoung_mandu",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원 군만두 & 쫄면",
      "nameEn": "Suwon Fried Mandu & Jjolmyeon",
      "descKo": "바삭하게 튀긴 육즙 가득한 수제 군만두를 양배추 가득한 새콤달콤 매운 쫄면에 싸 먹는 수원 행궁동의 대표 분식",
      "descEn": "Deep-fried crispy handmade pork dumplings paired with chewy noodles tossed in shredded cabbage and fiery spicy-sour sauce",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 9000,
      "priceMinKrw": 7500,
      "priceMaxKrw": 11500,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "/assets/suwon-mandu-jjolmyeon.jpg",
      "targetScope": "BOTH",
      "sortOrder": 116,
      "isActive": true
    },
    {
      "id": "suwon_jidong_sundae",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원 지동시장 순대곱창 볶음",
      "nameEn": "Jidong Market Sundae & Tripe Stir-fry",
      "descKo": "철판에 순대와 쫄깃한 돼지 곱창, 깻잎, 팽이버섯, 당면을 들깨가루와 매콤한 양념장에 볶아 먹는 100년 전통 지동시장 요리",
      "descEn": "Sizzling tabletop skillet stir-fry of blood sausage, pork intestine, perilla leaves, and chewy glass noodles in spicy sauce",
      "categoryTag": "MEAL",
      "unitPriceKrw": 12000,
      "priceMinKrw": 10000,
      "priceMaxKrw": 15000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "/assets/suwon-jidong-sundaebokkeum.jpg",
      "targetScope": "BOTH",
      "sortOrder": 117,
      "isActive": true
    },
    {
      "id": "suwon_hwaseong_dessert",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "생선구이 백반",
      "nameEn": "Grilled Fish Feast Baekban",
      "descKo": "노릇노릇 바삭하게 구워낸 신선한 모둠 생선구이와 정갈한 반찬, 따뜻한 밥과 국이 함께 나오는 푸짐한 한식 밥상",
      "descEn": "Crispy grilled whole seasonal fish served with warm steamed rice, hearty soup, and an array of traditional Korean side dishes",
      "categoryTag": "MEAL",
      "unitPriceKrw": 14000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 18000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "/assets/suwon-saengseongui-baekban.jpg",
      "targetScope": "BOTH",
      "sortOrder": 118,
      "isActive": true
    },
    {
      "id": "suwon_yakgwa",
      "scope": "CITY_LOCAL",
      "cityCode": "SUWON",
      "nameKo": "수원약과",
      "nameEn": "Suwon Yakgwa (Traditional Honey Pastry)",
      "descKo": "정조대왕 능행차 기록에도 등장하는 수원 전통 과자로, 켜켜이 결을 낸 반죽을 바삭하게 튀겨 꿀과 조청, 생강즙에 재워 부드럽고 깊은 풍미를 자랑하는 전통 모약과",
      "descEn": "Historic Suwon royal honey pastry featuring delicate flaky layers fried to golden crispness and soaked in rich honey, grain syrup, and ginger",
      "categoryTag": "DESSERT_CAFE",
      "unitPriceKrw": 6000,
      "priceMinKrw": 4500,
      "priceMaxKrw": 9000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "/assets/suwon-yakgwa.jpg",
      "targetScope": "BOTH",
      "sortOrder": 119,
      "isActive": true
    }
  ],
  "INCHEON": [
    {
      "id": "incheon_chinatown_jajang",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "인천 차이나타운 자장면",
      "nameEn": "Incheon Chinatown Original Jajangmyeon",
      "descKo": "1883년 개항 이후 화교들에 의해 탄생한 한국 자장면의 발상지 인천 차이나타운의 정통 자장면",
      "descEn": "Birthplace of Korean-Chinese black bean noodles in Incheon historic Chinatown, served with crispy sweet and sour pork",
      "categoryTag": "MEAL",
      "unitPriceKrw": 8000,
      "priceMinKrw": 12000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/6fac2b39-3720-4fc5-9486-4d8a478ea29b/it11",
      "targetScope": "BOTH",
      "sortOrder": 120,
      "isActive": true
    },
    {
      "id": "incheon_sinpo_dakgangjeong",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "신포 닭강정",
      "nameEn": "Sinpo Market Dakgangjeong (Spicy Glazed Chicken)",
      "descKo": "무쇠 가마솥에 바삭하게 튀긴 닭을 청양고추와 물엿 베이스의 매콤하고 쫀득한 붉은 소스에 즉석에서 볶아내는 신포시장 명물",
      "descEn": "Fiery, crispy fried chicken chunks glazed in a simmering cauldron of sticky sweet-spicy chili syrup with whole dried peppers",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 19000,
      "priceMinKrw": 17000,
      "priceMaxKrw": 22000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/aeda629e-490e-4582-b0df-fd84c6f11fb0/it11",
      "targetScope": "BOTH",
      "sortOrder": 121,
      "isActive": true
    },
    {
      "id": "incheon_baendaengi",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "연안부두 밴댕이회무침",
      "nameEn": "Incheon Baendaengi (Spicy Herring Salad)",
      "descKo": "연안부두 밴댕이 골목에서 갓 잡은 기름진 밴댕이 살을 미나리, 오이와 매콤새콤하게 버무려 밥에 비벼 먹는 별미",
      "descEn": "Plump local silver-striped round herring raw fillets tossed with water parsley, garlic, and vinegar chili paste over warm rice",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 12000,
      "priceMinKrw": 10000,
      "priceMaxKrw": 15000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/40/3518640_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 123,
      "isActive": true
    },
    {
      "id": "incheon_clay_oven_dumpling",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "차이나타운 화덕만두",
      "nameEn": "Chinatown Clay Oven Dumpling",
      "descKo": "200도가 넘는 옹기 화덕 안쪽 벽에 붙여 구워내 겉은 바삭하고 속은 육즙 가득한 고기만두",
      "descEn": "Unique charcoal tandoor-style clay oven baked buns stuffed with juicy minced pork, and crispy hollow honey-glazed crackers",
      "categoryTag": "STREET_SNACK",
      "unitPriceKrw": 4000,
      "priceMinKrw": 3000,
      "priceMaxKrw": 5500,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/b3b03597-a94f-4e21-841d-81efc3846a7c/it11",
      "targetScope": "BOTH",
      "sortOrder": 124,
      "isActive": true
    },
    {
      "id": "incheon_songdo_clam_noodles",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "영종도 바지락 해물칼국수",
      "nameEn": "Yeongjongdo Seafood Clam Kalguksu",
      "descKo": "서해 갯벌에서 캔 바지락과 가리비, 새우를 산더미처럼 넣고 끓여 맑고 시원한 감칠맛이 일품인 영종도 바닷가 국수",
      "descEn": "Enormous steaming shared bowl of fresh knife-cut noodles swimming with abundant sweet manila clams and prawns in sea broth",
      "categoryTag": "MEAL",
      "unitPriceKrw": 11000,
      "priceMinKrw": 9500,
      "priceMaxKrw": 14000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/24/2839524_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 128,
      "isActive": true
    },
    {
      "id": "incheon_wolmido_clam_bake",
      "scope": "CITY_LOCAL",
      "cityCode": "INCHEON",
      "nameKo": "월미도 조개구이",
      "nameEn": "Wolmido Oceanfront Grilled Shellfish BBQ",
      "descKo": "가리비, 키조개, 백합, 치즈구이를 연탄불 위에 지글지글 구워 초고추장에 찍어 먹는 월미도 바닷가의 대표 음식",
      "descEn": "Interactive seaside tabletop BBQ feast grilling fresh scallops, pen shells, clams, and melted cheese over hot briquettes",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 32000,
      "priceMinKrw": 28000,
      "priceMaxKrw": 42000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "http://tong.visitkorea.or.kr/cms/resource/46/2846846_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 129,
      "isActive": true
    }
  ],
  "YEOSU": [
    {
      "id": "yeosu_dolgejang",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 돌게장 백반",
      "nameEn": "Yeosu Dolgejang (Soy Marinated Rock Crab)",
      "descKo": "여수 바다의 단단한 돌게를 비법 간장과 청양고추로 숙성시켜 게딱지에 밥을 쓱쓱 비벼 먹는 여수 최고의 밥도둑 백반",
      "descEn": "Small native wild rock crabs steeped in aged seasoned soy sauce, packed with rich savory roe to mix with steamed rice",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 16000,
      "priceMinKrw": 14000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/7752c2ce-cca8-41b0-bdf5-c6b9c73ba154/it11",
      "targetScope": "BOTH",
      "sortOrder": 130,
      "isActive": true
    },
    {
      "id": "yeosu_nangman_samhap",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 해물삼합",
      "nameEn": "Yeosu Seafood Samhap (Kimchi, Pork & Octopus)",
      "descKo": "여수 돌산 갓김치와 생삼겹살, 살아있는 문어(낙지), 전복, 새우를 철판에 함께 지글지글 볶아 싸 먹는 낭만포차 시그니처",
      "descEn": "Sizzling iron plate surf-and-turf uniting famous Dolsan mustard greens kimchi, pork belly slices, fresh octopus, and abalone",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 24000,
      "priceMinKrw": 20000,
      "priceMaxKrw": 30000,
      "isMustEatTop3": true,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/74/2787574_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 131,
      "isActive": true
    },
    {
      "id": "yeosu_gatkimchi_samgyeop",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 돌산 갓김치",
      "nameEn": "Yeosu Dolsan Gat-Kimchi",
      "descKo": "특유의 톡 쏘는 알싸함과 깊은 감칠맛을 지닌 여수 돌산 갓김치",
      "descEn": "Sizzling pork belly grilled alongside intensely aromatic, pungent fermented mustard leaf kimchi (Gat Kimchi)",
      "categoryTag": "BBQ_FEAST",
      "unitPriceKrw": 12000,
      "priceMinKrw": 16000,
      "priceMaxKrw": 23000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/192abc4a-52f1-478c-a5bc-b9409651daf5/it11",
      "targetScope": "BOTH",
      "sortOrder": 133,
      "isActive": true
    },
    {
      "id": "yeosu_hamo_yubikki",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 갯장어 샤브샤브 (하모 유비끼)",
      "nameEn": "Yeosu Hamo Shabu-shabu (Sea Pike Eel)",
      "descKo": "칼집을 촘촘히 낸 갯장어 살을 한약재 육수에 살짝 담그면 눈꽃처럼 하얗게 피어나는 여수의 명품 여름 보양식",
      "descEn": "Finely scored fillet slices of sweet wild sea pike eel briefly dipped in hot herbal broth until blooming like white flowers",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 45000,
      "priceMinKrw": 32000,
      "priceMaxKrw": 50000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/09/3589209_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 134,
      "isActive": true
    },
    {
      "id": "yeosu_eel_soup",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 장어탕",
      "nameEn": "Yeosu Jangeo-tang (Spicy Eel Soup)",
      "descKo": "살이 통통한 바다장어(붕장어)를 통째로 넣고 우거지와 된장, 고춧가루로 얼큰하고 진하게 끓여낸 원기 회복 탕",
      "descEn": "Thick, deeply nourishing sea eel soup simmered with dried greens and spicy soybean paste, served with char-grilled fillets",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 12000,
      "priceMinKrw": 14000,
      "priceMaxKrw": 20000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://tong.visitkorea.or.kr/cms/resource/19/2788219_image2_1.jpg",
      "targetScope": "BOTH",
      "sortOrder": 136,
      "isActive": true
    },
    {
      "id": "yeosu_jeoneo_feast",
      "scope": "CITY_LOCAL",
      "cityCode": "YEOSU",
      "nameKo": "여수 전어구이",
      "nameEn": "Yeosu Jeoneo-gui (Grilled Gizzard Shad)",
      "descKo": "칼집을 내어 굵은소금을 뿌린 뒤 뼈째 노릇하게 구워내 특유의 기름지고 고소한 풍미를 머리부터 꼬리까지 즐기는 가을철 대표 생선구이",
      "descEn": "Whole seasonal autumn gizzard shad grilled with coarse sea salt, eaten bones and all for maximum buttery nutty richness",
      "categoryTag": "SEAFOOD",
      "unitPriceKrw": 30000,
      "priceMinKrw": 15000,
      "priceMaxKrw": 24000,
      "isMustEatTop3": false,
      "emoji": "",
      "imageUrl": "https://conlab.visitkorea.or.kr/api/depot/public/depot-flow/query/download-image/7a2a1e86-8a72-4884-b504-9dd792999c82/it11",
      "targetScope": "BOTH",
      "sortOrder": 137,
      "isActive": true
    }
  ]
};

// =========================================================================
// 3. 통합 카탈로그 및 헬퍼 함수
// =========================================================================

export const ALL_FOOD_ITEMS: FoodItemDefinition[] = [
  ...NATIONAL_K_FOODS,
  ...Object.values(CITY_SPECIALTY_FOODS).flat(),
];

export const FOOD_CATALOG_BY_ID: Map<string, FoodItemDefinition> = new Map(
  ALL_FOOD_ITEMS.map((item) => [item.id, item])
);

export function getNationalFoods(): FoodItemDefinition[] {
  return NATIONAL_K_FOODS;
}

export function getCityFoods(city: SupportedCity): FoodItemDefinition[] {
  return CITY_SPECIALTY_FOODS[city] || [];
}

export function getFoodById(id: string): FoodItemDefinition | undefined {
  return FOOD_CATALOG_BY_ID.get(id);
}

export function registerCustomFoodItems(items: FoodItemDefinition[]) {
  items.forEach((item) => {
    if (!item || !item.id) return;
    FOOD_CATALOG_BY_ID.set(item.id, item);

    const allIdx = ALL_FOOD_ITEMS.findIndex((f) => f.id === item.id);
    if (allIdx >= 0) {
      ALL_FOOD_ITEMS[allIdx] = item;
    } else {
      ALL_FOOD_ITEMS.push(item);
    }

    if (item.scope === "NATIONAL") {
      const natIdx = NATIONAL_K_FOODS.findIndex((f) => f.id === item.id);
      if (natIdx >= 0) NATIONAL_K_FOODS[natIdx] = item;
      else NATIONAL_K_FOODS.push(item);
    } else if (item.cityCode) {
      const list = CITY_SPECIALTY_FOODS[item.cityCode] || [];
      const cityIdx = list.findIndex((f) => f.id === item.id);
      if (cityIdx >= 0) list[cityIdx] = item;
      else list.push(item);
      CITY_SPECIALTY_FOODS[item.cityCode] = list;
    }
  });
}
