import { SupportedCity } from "../../../lib/trip-domain";
import { MealSlot } from "../domain/types";

export interface FoodCandidateSpot {
  id: string;
  cityCode: SupportedCity;
  nameKo: string;
  nameEn: string;
  descKo: string;
  descEn: string;
  pricePerPerson: number;
  recommendedSlot: MealSlot;
  tag: string;
  emoji: string;
  gradientBg: string;
}

export const FOOD_SPOTS_CATALOG: FoodCandidateSpot[] = [
  // === SEOUL ===
  {
    id: "seoul_food_samgyeopsal",
    cityCode: "SEOUL",
    nameKo: "명동 숙성 숯불 삼겹살 & 김치찌개",
    nameEn: "Myeongdong Aged Samgyeopsal BBQ",
    descKo: "두툼한 국내산 생삼겹살 구이와 얼큰한 뚝배기 김치찌개 조합",
    descEn: "Thick charcoal grilled Korean pork belly with savory kimchi stew",
    pricePerPerson: 18000,
    recommendedSlot: "DINNER",
    tag: "K-BBQ/인기",
    emoji: "🥓",
    gradientBg: "from-amber-500/15 to-rose-500/15",
  },
  {
    id: "seoul_food_gwangjang_market",
    cityCode: "SEOUL",
    nameKo: "광장시장 마약김밥 & 빈대떡 세트",
    nameEn: "Gwangjang Market Bindaetteok & Kimbap",
    descKo: "바삭한 녹두빈대떡과 겨자소스 마약김밥, 원조 시장 푸드",
    descEn: "Crispy mung bean pancake with addictive mini kimbap",
    pricePerPerson: 9000,
    recommendedSlot: "LUNCH",
    tag: "전통시장/스트릿",
    emoji: "🥞",
    gradientBg: "from-orange-500/15 to-yellow-500/15",
  },
  {
    id: "seoul_food_insadong_hanjeongsik",
    cityCode: "SEOUL",
    nameKo: "인사동 정갈한 모던 한정식 코스",
    nameEn: "Insadong Modern Hanjeongsik Course",
    descKo: "계절 정갈한 찬과 가마솥밥, 불고기가 차려지는 전통 한정식",
    descEn: "Traditional Korean course meal with seasonal side dishes & Bulgogi",
    pricePerPerson: 32000,
    recommendedSlot: "DINNER",
    tag: "한정식/정갈함",
    emoji: "🍱",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "seoul_food_gangnam_omakase",
    cityCode: "SEOUL",
    nameKo: "강남 프리미엄 한우 오마카세",
    nameEn: "Gangnam Premium Hanwoo Omakase",
    descKo: "최상급 1++ 한우 부위별 셰프 맞춤 다이닝 코스",
    descEn: "Chef custom fine dining course featuring highest grade 1++ Hanwoo beef",
    pricePerPerson: 75000,
    recommendedSlot: "DINNER",
    tag: "프리미엄/한우",
    emoji: "🥩",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "seoul_food_seongsu_bakery",
    cityCode: "SEOUL",
    nameKo: "성수 감성 디저트 & 소금빵 시그니처",
    nameEn: "Seongsu Salt Bread & Artisan Coffee",
    descKo: "겉바속촉 수제 소금빵과 스페셜티 갓 볶은 원두 로스터리 카페",
    descEn: "Artisan fresh baked salt bread with specialty roasted coffee",
    pricePerPerson: 8500,
    recommendedSlot: "SNACK_CAFE",
    tag: "핫플/디저트",
    emoji: "🥐",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
  },
  {
    id: "seoul_food_sinchon_gukbap",
    cityCode: "SEOUL",
    nameKo: "신촌 진한 순대국밥 & 모듬수육",
    nameEn: "Sinchon Deep Sundae Gukbap",
    descKo: "진한 사골 육수에 담긴 쫄깃한 순대와 머깃고기 수육",
    descEn: "Hearty Korean blood sausage soup with rich bone broth",
    pricePerPerson: 10000,
    recommendedSlot: "BREAKFAST",
    tag: "든든/국밥",
    emoji: "🍲",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },

  // === BUSAN ===
  {
    id: "busan_food_dwaejigukbap",
    cityCode: "BUSAN",
    nameKo: "자갈치 원조 돼지국밥 & 수육백반",
    nameEn: "Jagalchi Authentic Dwaeji-gukbap",
    descKo: "구수한 사골 육수와 부드러운 돼지고기 수육이 조화로운 부산 대표 소울푸드",
    descEn: "Busan signature pork soup with tender boiled pork slices",
    pricePerPerson: 10500,
    recommendedSlot: "BREAKFAST",
    tag: "소울푸드/대표",
    emoji: "🍲",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "busan_food_milmyeon",
    cityCode: "BUSAN",
    nameKo: "해운대 시원한 부산 밀면 & 왕만두",
    nameEn: "Haeundae Chilled Busan Milmyeon",
    descKo: "살얼음 동동 한약재 육수와 살짝 매콤한 다대기 밀면",
    descEn: "Refreshing chilled wheat noodles in iced herbal broth",
    pricePerPerson: 9000,
    recommendedSlot: "LUNCH",
    tag: "시원함/여름별미",
    emoji: "🍜",
    gradientBg: "from-sky-500/15 to-blue-500/15",
  },
  {
    id: "busan_food_gwangalli_clam",
    cityCode: "BUSAN",
    nameKo: "광안리 싱싱한 조개구이 & 해물라면",
    nameEn: "Gwangalli Fresh Clam Bake & Seafood Ramen",
    descKo: "바다 앞 치즈 가리비 조개구이와 칼칼한 해물라면 해장 세트",
    descEn: "Oceanfront grilled cheese scallops with spicy seafood ramen",
    pricePerPerson: 35000,
    recommendedSlot: "DINNER",
    tag: "조개구이/광안리",
    emoji: "🦪",
    gradientBg: "from-indigo-500/15 to-purple-500/15",
  },
  {
    id: "busan_food_minrak_rawfish",
    cityCode: "BUSAN",
    nameKo: "민락 수변공원 제철 싱싱 모듬회",
    nameEn: "Minrak Waterfront Seasonal Fresh Raw Fish",
    descKo: "자갈치/민락 회센터에서 갓 뜬 쫄깃한 광어/우럭 제철 회",
    descEn: "Freshly sliced seasonal raw fish platter from local fish market",
    pricePerPerson: 28000,
    recommendedSlot: "DINNER",
    tag: "싱싱회/수변공원",
    emoji: "🐟",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },
  {
    id: "busan_food_ssiathotteok",
    cityCode: "BUSAN",
    nameKo: "남포동 견과류 씨앗호떡 & 어묵",
    nameEn: "Nampo-dong Nut Seed Hotteok & Fishcake",
    descKo: "해바라기씨/견과류가 고소하게 씹히는 원조 길거리 호떡",
    descEn: "Famous sweet Korean pancake filled with crunchy seeds & nuts",
    pricePerPerson: 4500,
    recommendedSlot: "SNACK_CAFE",
    tag: "길거리/씨앗호떡",
    emoji: "🥞",
    gradientBg: "from-yellow-500/15 to-amber-500/15",
  },
  {
    id: "busan_food_haeundae_galbi",
    cityCode: "BUSAN",
    nameKo: "해운대 소문난 암소갈비 정식",
    nameEn: "Haeundae Prime Beef Rib BBQ",
    descKo: "특제 양념에 재운 부드러운 암소 갈비와 감자 사리 면",
    descEn: "Famous prime marinated beef short ribs with chewy potato noodles",
    pricePerPerson: 52000,
    recommendedSlot: "DINNER",
    tag: "암소갈비/명가",
    emoji: "🥩",
    gradientBg: "from-rose-500/15 to-pink-500/15",
  },

  // === JEJU ===
  {
    id: "jeju_food_blackpork",
    cityCode: "JEJU",
    nameKo: "애월 참숯 제주 흑돼지 참구이",
    nameEn: "Aewol Charcoal Grilled Jeju Black Pork",
    descKo: "멜젓소스에 찍어 먹는 고소한 두툼 오겹살과 목살 숯불구이",
    descEn: "Thick juicy Jeju black pork belly grilled over charcoal with anchovy dip",
    pricePerPerson: 25000,
    recommendedSlot: "DINNER",
    tag: "흑돼지/대표",
    emoji: "🥓",
    gradientBg: "from-amber-500/15 to-rose-500/15",
  },
  {
    id: "jeju_food_gokiguksu",
    cityCode: "JEJU",
    nameKo: "제주 진한 고기국수 & 돔베고기",
    nameEn: "Jeju Pork Noodle & Dombe Pork",
    descKo: "진한 뽀얀 도새기 육수에 두툼한 돔베고기가 올라간 제주 대표 국수",
    descEn: "Rich pork broth noodles topped with thick sliced boiled pork",
    pricePerPerson: 10000,
    recommendedSlot: "BREAKFAST",
    tag: "고기국수/도새기",
    emoji: "🍜",
    gradientBg: "from-orange-500/15 to-amber-500/15",
  },
  {
    id: "jeju_food_galbijorim",
    cityCode: "JEJU",
    nameKo: "함덕 통갈치조림 & 해물뚝배기",
    nameEn: "Hamdeok Whole Cutlassfish Stew",
    descKo: "매콤달콤 양념에 양파와 감자가 조려진 매콤한 제주 통갈치조림",
    descEn: "Braised long whole cutlassfish stew with spicy Korean seasoning",
    pricePerPerson: 32000,
    recommendedSlot: "LUNCH",
    tag: "통갈치/해물",
    emoji: "🐟",
    gradientBg: "from-red-500/15 to-pink-500/15",
  },
  {
    id: "jeju_food_dongmun_market",
    cityCode: "JEJU",
    nameKo: "동문야시장 흑돼지꼬치 & 감귤쥬스",
    nameEn: "Dongmun Night Market Black Pork Skewer",
    descKo: "불쇼 흑돼지 꼬치구이와 즉석 착즙 100% 한라봉 감귤 쥬스",
    descEn: "Flame grilled black pork skewer & fresh squeezed Hallabong juice",
    pricePerPerson: 8500,
    recommendedSlot: "SNACK_CAFE",
    tag: "야시장/감귤",
    emoji: "🍢",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
  },
  {
    id: "jeju_food_abalone_porridge",
    cityCode: "JEJU",
    nameKo: "서귀포 고소한 전복죽 & 전복구이",
    nameEn: "Seogwipo Abalone Rice Porridge",
    descKo: "전복 내장을 아끼지 않고 끓여낸 진하고 고소한 해녀 전복죽",
    descEn: "Nutritious savory green abalone porridge made by Jeju Haenyeo",
    pricePerPerson: 16000,
    recommendedSlot: "BREAKFAST",
    tag: "전복죽/해녀",
    emoji: "🥣",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "jeju_food_seafood_ramen",
    cityCode: "JEJU",
    nameKo: "애월 해물 라면 (문어 & 딱새우)",
    nameEn: "Aewol Ocean Crab & Shrimp Ramen",
    descKo: "통문어 다리와 딱새우, 꽃게가 듬뿍 들어간 바다 뷰 해물 라면",
    descEn: "Ocean view ramen stuffed with octopus leg and Jeju red shrimp",
    pricePerPerson: 15000,
    recommendedSlot: "LUNCH",
    tag: "해물라면/딱새우",
    emoji: "🦀",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },

  // === INCHEON ===
  {
    id: "incheon_food_jajangmyeon",
    cityCode: "INCHEON",
    nameKo: "차이나타운 원조 수제 짜장면 & 탕수육",
    nameEn: "Chinatown Authentic Jajangmyeon & Pork",
    descKo: "인천 차이나타운 100년 역사의 깊은 춘장 수제 짜장면과 바삭 탕수육",
    descEn: "Historic authentic black bean noodles & crispy sweet pork",
    pricePerPerson: 12000,
    recommendedSlot: "LUNCH",
    tag: "차이나타운/원조",
    emoji: "🍜",
    gradientBg: "from-amber-500/15 to-red-500/15",
  },
  {
    id: "incheon_food_wolmi_clam",
    cityCode: "INCHEON",
    nameKo: "월미도 치즈 조개구이 & 칼국수",
    nameEn: "Wolmido Cheese Clam Bake & Kalguksu",
    descKo: "바다 뷰 치즈 조개구이 세트와 국물이 시원한 해물 바지락 칼국수",
    descEn: "Seaside cheese clam bake with warm clam noodle soup",
    pricePerPerson: 28000,
    recommendedSlot: "DINNER",
    tag: "월미도/조개구이",
    emoji: "🦪",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },
  {
    id: "incheon_food_songdo_buffet",
    cityCode: "INCHEON",
    nameKo: "송도 센트럴 럭셔리 뷔페 다이닝",
    nameEn: "Songdo Central Luxury Buffet Dining",
    descKo: "신선한 스시, 바비큐, 프리미엄 디저트를 즐기는 호텔 뷔페",
    descEn: "Hotel fine buffet dining featuring fresh sushi and premium BBQ",
    pricePerPerson: 58000,
    recommendedSlot: "DINNER",
    tag: "송도/호텔뷔페",
    emoji: "🍣",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "incheon_food_gonggalbang",
    cityCode: "INCHEON",
    nameKo: "차이나타운 공갈빵 & 화덕만두",
    nameEn: "Chinatown Gonggalbang & Oven Dumplings",
    descKo: "담백하고 고소한 화덕 옹기 만두와 바삭한 공갈빵 디저트",
    descEn: "Crispy hollow pastry bread & clay oven baked juicy dumplings",
    pricePerPerson: 5000,
    recommendedSlot: "SNACK_CAFE",
    tag: "스트릿디저트",
    emoji: "🥟",
    gradientBg: "from-yellow-500/15 to-amber-500/15",
  },
  {
    id: "incheon_food_sinpo_chicken",
    cityCode: "INCHEON",
    nameKo: "신포국제시장 매콤 달콤 원조 닭강정",
    nameEn: "Sinpo Market Original Sweet & Spicy Chicken",
    descKo: "청양고추 매콤함과 바삭 가마솥 조림이 조화로운 원조 닭강정",
    descEn: "Famous original kettle fried sweet & spicy glazed chicken",
    pricePerPerson: 11000,
    recommendedSlot: "LUNCH",
    tag: "신포시장/닭강정",
    emoji: "🍗",
    gradientBg: "from-orange-500/15 to-red-500/15",
  },
  {
    id: "incheon_food_haemultang",
    cityCode: "INCHEON",
    nameKo: "소래포구 푸짐한 모듬 해물탕",
    nameEn: "Sorae Port Hearty Seafood Soup",
    descKo: "낙지, 전복, 꽃게가 살아 숨쉬는 얼큰 시원한 항구 해물탕",
    descEn: "Rich spicy seafood stew packed with octopus, abalone & crab",
    pricePerPerson: 22000,
    recommendedSlot: "DINNER",
    tag: "소래포구/해물탕",
    emoji: "🍲",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },

  // === SUWON ===
  {
    id: "suwon_food_galbi_chicken",
    cityCode: "SUWON",
    nameKo: "수원 통닭거리 원조 왕갈비통닭",
    nameEn: "Suwon Original King Galbi Chicken",
    descKo: "영화 '극한직업'의 실제 주인공! 달콤 짭조름한 왕갈비 소스 가마솥 치킨",
    descEn: "Famous crispy fried chicken coated in sweet savory ribs glaze",
    pricePerPerson: 13000,
    recommendedSlot: "DINNER",
    tag: "통닭거리/시그니처",
    emoji: "🍗",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "suwon_food_wanggalbi",
    cityCode: "SUWON",
    nameKo: "수원 전통 숯불 소왕갈비 구이",
    nameEn: "Suwon Traditional Charcoal Beef Rib BBQ",
    descKo: "큼직한 소왕갈비에 정성껏 입힌 양념과 마블링 참숯 구이",
    descEn: "Premium tender marinated beef short ribs grilled over charcoal",
    pricePerPerson: 42000,
    recommendedSlot: "DINNER",
    tag: "소왕갈비/명가",
    emoji: "🥩",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "suwon_food_haenggung_cafe",
    cityCode: "SUWON",
    nameKo: "행궁동 행리단길 주택 개조 감성 카페",
    nameEn: "Haenggung-dong Vintage House Cafe",
    descKo: "수원화성 성곽 뷰 루프탑과 아늑한 수제 디저트 에이드",
    descEn: "Rooftop house cafe overlooking historic fortress wall",
    pricePerPerson: 7500,
    recommendedSlot: "SNACK_CAFE",
    tag: "행리단길/성곽뷰",
    emoji: "☕",
    gradientBg: "from-purple-500/15 to-indigo-500/15",
  },
  {
    id: "suwon_food_bunsik",
    cityCode: "SUWON",
    nameKo: "수원 화성 남문 매콤 쫄면 & 군만두",
    nameEn: "Suwon Spicy Jjolmyeon & Fried Dumpling",
    descKo: "매콤새콤 중독성 있는 쫄면과 겉바속촉 튀김 군만두 세트",
    descEn: "Spicy chewy cold noodles paired with crispy pan-fried dumplings",
    pricePerPerson: 8500,
    recommendedSlot: "LUNCH",
    tag: "남문시장/분식",
    emoji: "🥟",
    gradientBg: "from-red-500/15 to-orange-500/15",
  },
  {
    id: "suwon_food_gukbap",
    cityCode: "SUWON",
    nameKo: "수원 지동시장 순대곱창 볶음",
    nameEn: "Suwon Jidong Market Stir-fried Sundae",
    descKo: "지동시장 순대타운의 들깨 매콤 양념 순대곱창 철판볶음",
    descEn: "Stir-fried Korean blood sausage & tripe with spicy perilla seasoning",
    pricePerPerson: 14000,
    recommendedSlot: "DINNER",
    tag: "지동시장/순대타운",
    emoji: "🥘",
    gradientBg: "from-red-600/15 to-amber-500/15",
  },
  {
    id: "suwon_food_seolleongtang",
    cityCode: "SUWON",
    nameKo: "수원 장안문 뽀얀 진한 설렁탕",
    nameEn: "Suwon Ox Bone Soup Seolleongtang",
    descKo: "24시간 푹 고아낸 뽀얀 사골 육수에 국수 소면과 깍두기",
    descEn: "Rich ox bone marrow soup served with noodles and radish kimchi",
    pricePerPerson: 11000,
    recommendedSlot: "BREAKFAST",
    tag: "설렁탕/사골",
    emoji: "🥣",
    gradientBg: "from-slate-500/15 to-blue-500/15",
  },

  // === JEONJU ===
  {
    id: "jeonju_food_bibimbap",
    cityCode: "JEONJU",
    nameKo: "전주 명가 육회 비빔밥 & 떡갈비",
    nameEn: "Jeonju Yukhoe Bibimbap & Tteokgalbi",
    descKo: "신선한 한우 육회와 놋그릇 황동에 담긴 대한민국 원조 전주비빔밥",
    descEn: "Authentic Jeonju bibimbap topped with fresh beef tartare",
    pricePerPerson: 16000,
    recommendedSlot: "LUNCH",
    tag: "원조비빔밥/육회",
    emoji: "🍲",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "jeonju_food_kongnamulgukbap",
    cityCode: "JEONJU",
    nameKo: "전주 잰내기 콩나물국밥 & 모주",
    nameEn: "Jeonju Bean Sprout Soup & Moju",
    descKo: "아삭한 콩나물과 수란, 달콤한 한방 모주 한 잔의 깊은 해장",
    descEn: "Refreshing bean sprout soup with poached egg and warm herbal drink",
    pricePerPerson: 9000,
    recommendedSlot: "BREAKFAST",
    tag: "콩나물국밥/해장",
    emoji: "🥣",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "jeonju_food_makgeolli_table",
    cityCode: "JEONJU",
    nameKo: "전주 막걸리 골목 푸짐한 막걸리 한상",
    nameEn: "Jeonju Makgeolli Feast Table",
    descKo: "막걸리 한 주전자에 제철 해산물, 전, 부침개가 20여 가지 쏟아지는 푸짐함",
    descEn: "Famous Jeonju rice wine feast table packed with 20+ side dishes",
    pricePerPerson: 25000,
    recommendedSlot: "DINNER",
    tag: "막걸리한상/안주",
    emoji: "🍶",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
  },
  {
    id: "jeonju_food_chocopie",
    cityCode: "JEONJU",
    nameKo: "전주 수제 수제초코파이 & 전통차",
    nameEn: "Jeonju Handmade Choco Pie & Tea",
    descKo: "달콤한 딸기잼과 호두가 조화로운 원조 수제 초코파이 디저트",
    descEn: "Original handmade chocolate pie filled with strawberry jam and walnuts",
    pricePerPerson: 4500,
    recommendedSlot: "SNACK_CAFE",
    tag: "수제초코파이",
    emoji: "🥧",
    gradientBg: "from-amber-700/15 to-amber-900/15",
  },
  {
    id: "jeonju_food_hanjeongsik",
    cityCode: "JEONJU",
    nameKo: "전주 명인 궁중 한정식 풀코스",
    nameEn: "Jeonju Master Royal Hanjeongsik",
    descKo: "신선로, 신선한 회, 갈비찜이 차려지는 조선 궁중 수라상 한정식",
    descEn: "Full Royal court dining course featuring traditional hot pot stew",
    pricePerPerson: 55000,
    recommendedSlot: "DINNER",
    tag: "궁중한정식/명인",
    emoji: "👑",
    gradientBg: "from-rose-500/15 to-amber-500/15",
  },
  {
    id: "jeonju_food_pikae_sundae",
    cityCode: "JEONJU",
    nameKo: "전주 남부시장 피순대 & 암뽕국밥",
    nameEn: "Jeonju Nambu Market Blood Sundae Soup",
    descKo: "남부시장 야시장의 진하고 묵직한 원조 피순대 뚝배기",
    descEn: "Traditional rich blood sausage soup in Nambu night market",
    pricePerPerson: 10000,
    recommendedSlot: "LUNCH",
    tag: "남부시장/피순대",
    emoji: "🍲",
    gradientBg: "from-red-500/15 to-orange-500/15",
  },

  // === GYEONGJU ===
  {
    id: "gyeongju_food_ssambap",
    cityCode: "GYEONGJU",
    nameKo: "황리단길 정갈한 떡갈비 쌈밥 정식",
    nameEn: "Hwangridan-gil Tteokgalbi Ssambap",
    descKo: "신선한 유기농 쌈채소와 수제 소떡갈비 숯불구이 한상차림",
    descEn: "Grilled minced beef patties served with organic wrap vegetables",
    pricePerPerson: 16000,
    recommendedSlot: "LUNCH",
    tag: "쌈밥정식/황리단길",
    emoji: "🥬",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },
  {
    id: "gyeongju_food_tenwonbbang",
    cityCode: "GYEONGJU",
    nameKo: "경주 황남 십원빵 & 십원 맥주",
    nameEn: "Gyeongju 10-Won Cheese Bread",
    descKo: "쭉쭉 늘어나는 고소한 모짜렐라 치즈 가득 십원 동전 모양 빵",
    descEn: "Hot coin-shaped pastry filled with stretchy mozzarella cheese",
    pricePerPerson: 4000,
    recommendedSlot: "SNACK_CAFE",
    tag: "십원빵/치즈",
    emoji: "🪙",
    gradientBg: "from-amber-500/15 to-yellow-500/15",
  },
  {
    id: "gyeongju_food_hanwoo_ribs",
    cityCode: "GYEONGJU",
    nameKo: "경주 보문 명품 수제 한우갈비",
    nameEn: "Gyeongju Bomun Premium Hanwoo Ribs",
    descKo: "경주 로컬 청정 한우 생갈비와 칼칼한 한우 우거지탕",
    descEn: "Premium fresh local Hanwoo beef ribs grilled over oak charcoal",
    pricePerPerson: 45000,
    recommendedSlot: "DINNER",
    tag: "한우갈비/보문호수",
    emoji: "🥩",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "gyeongju_food_milmyeon",
    cityCode: "GYEONGJU",
    nameKo: "경주 시내 살얼음 밀면 & 석쇠불고기",
    nameEn: "Gyeongju Chilled Milmyeon & Bulgogi",
    descKo: "시원한 살얼음 밀면 육수와 숯불 석쇠 불고기의 새콤달콤 조합",
    descEn: "Chilled wheat noodles served with charcoal grilled sliced beef",
    pricePerPerson: 10000,
    recommendedSlot: "LUNCH",
    tag: "밀면/석쇠불고기",
    emoji: "🍜",
    gradientBg: "from-sky-500/15 to-blue-500/15",
  },
  {
    id: "gyeongju_food_gukbap",
    cityCode: "GYEONGJU",
    nameKo: "경주 성동시장 한식 뷔페 & 우엉김밥",
    nameEn: "Gyeongju Seongdong Market Buffet & Kimbap",
    descKo: "달콤 짭조름한 우엉김밥과 성동시장 한식 반찬 뷔페",
    descEn: "Famous braised burdock root kimbap & market food buffet",
    pricePerPerson: 8500,
    recommendedSlot: "BREAKFAST",
    tag: "성동시장/우엉김밥",
    emoji: "🍱",
    gradientBg: "from-orange-500/15 to-amber-500/15",
  },
  {
    id: "gyeongju_food_cafe_dessert",
    cityCode: "GYEONGJU",
    nameKo: "황남 한옥 뷰 대릉원 감성 디저트 카페",
    nameEn: "Hwangnam Hanok View Tomb Cafe",
    descKo: "대릉원 능경 전경이 한눈에 들어오는 한옥 툇마루 크로플 카페",
    descEn: "Hanok cafe terrace with direct view of ancient royal tombs",
    pricePerPerson: 7500,
    recommendedSlot: "SNACK_CAFE",
    tag: "대릉원뷰/한옥카페",
    emoji: "☕",
    gradientBg: "from-emerald-500/15 to-green-600/15",
  },

  // === GANGNEUNG ===
  {
    id: "gangneung_food_chodang_tofu",
    cityCode: "GANGNEUNG",
    nameKo: "초당 순두부 마을 짬뽕 순두부",
    nameEn: "Chodang Soft Tofu Village Jjamppong Tofu",
    descKo: "동해 깨끗한 바닷물로 만든 고소한 순두부와 얼큰 불맛 짬뽕 육수",
    descEn: "Soft handmade tofu stewed in spicy seafood Jjamppong broth",
    pricePerPerson: 12000,
    recommendedSlot: "LUNCH",
    tag: "초당순두부/대표",
    emoji: "🍲",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "gangneung_food_mulhoe",
    cityCode: "GANGNEUNG",
    nameKo: "경포대 싱싱한 모듬 물회 & 미역국",
    nameEn: "Gyeongpo Cold Raw Fish Soup Mulhoe",
    descKo: "새콤달콤 살얼음 육수에 가자미/오징어 회가 듬뿍 들어간 시원한 물회",
    descEn: "Chilled spicy raw fish soup loaded with fresh seasonal squid",
    pricePerPerson: 18000,
    recommendedSlot: "LUNCH",
    tag: "물회/경포대",
    emoji: "🥣",
    gradientBg: "from-sky-500/15 to-blue-500/15",
  },
  {
    id: "gangneung_food_kingcrab",
    cityCode: "GANGNEUNG",
    nameKo: "주문진 붉은 대게 풀코스 & 볶음밥",
    nameEn: "Jumunjin Steamed King Crab Full Course",
    descKo: "갓 쪄낸 꽉 찬 대게 살과 고소한 게딱지 내장 볶음밥",
    descEn: "Steamed sweet snow crab with savory crab butter fried rice",
    pricePerPerson: 65000,
    recommendedSlot: "DINNER",
    tag: "대게코스/주문진",
    emoji: "🦀",
    gradientBg: "from-rose-500/15 to-red-500/15",
  },
  {
    id: "gangneung_food_anmok_coffee",
    cityCode: "GANGNEUNG",
    nameKo: "안목해변 핸드드립 커피 & 타르트",
    nameEn: "Anmok Beach Hand Drip Coffee & Tart",
    descKo: "강릉 바다 파도 소리를 들으며 즐기는 스페셜티 핸드드립 커피",
    descEn: "Specialty oceanfront hand drip coffee with fresh fruit tart",
    pricePerPerson: 8000,
    recommendedSlot: "SNACK_CAFE",
    tag: "안목커피/핸드드립",
    emoji: "☕",
    gradientBg: "from-amber-600/15 to-amber-800/15",
  },
  {
    id: "gangneung_food_jangkalguksu",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 중앙시장 걸쭉한 장칼국수",
    nameEn: "Gangneung Market Spicy Jang Kalguksu",
    descKo: "고추장과 된장 베이스의 걸쭉하고 시원한 강릉 전통 칼국수",
    descEn: "Thick hand-cut noodles served in spicy soybean paste broth",
    pricePerPerson: 8000,
    recommendedSlot: "BREAKFAST",
    tag: "장칼국수/중앙시장",
    emoji: "🍜",
    gradientBg: "from-red-500/15 to-orange-500/15",
  },
  {
    id: "gangneung_food_cockle_rice",
    cityCode: "GANGNEUNG",
    nameKo: "강릉 꼬막 비빔밥 & 육사시미 세트",
    nameEn: "Gangneung Cockle Bibimbap & Beef Sashimi",
    descKo: "쫄깃한 꼬막무침이 접시 가득 덮인 짭조름한 별미 비빔밥",
    descEn: "Plate filled with seasoned fresh cockles mixed with savory rice",
    pricePerPerson: 22000,
    recommendedSlot: "DINNER",
    tag: "꼬막비빔밥/별미",
    emoji: "🐚",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },

  // === SOKCHO ===
  {
    id: "sokcho_food_dakgangjeong",
    cityCode: "SOKCHO",
    nameKo: "속초 중앙시장 원조 닭강정 & 오징어순대",
    nameEn: "Sokcho Central Market Sweet Chicken & Squid Sundae",
    descKo: "식어도 바삭한 원조 닭강정과 노릇하게 구워낸 오징어순대 세트",
    descEn: "Famous crispy glaze chicken & pan-fried stuffed squid sundae",
    pricePerPerson: 15000,
    recommendedSlot: "LUNCH",
    tag: "속초중앙시장/대표",
    emoji: "🍗",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "sokcho_food_mulhoe",
    cityCode: "SOKCHO",
    nameKo: "속초 봉포 머구리 시원한 항아리 물회",
    nameEn: "Sokcho Bongpo Fresh Assorted Mulhoe",
    descKo: "전복, 해삼, 멍게가 한 그릇 가득한 속초 대표 살얼음 물회",
    descEn: "Chilled seafood raw fish soup packed with abalone & sea squirt",
    pricePerPerson: 19000,
    recommendedSlot: "LUNCH",
    tag: "봉포물회/해산물",
    emoji: "🥣",
    gradientBg: "from-sky-500/15 to-blue-500/15",
  },
  {
    id: "sokcho_food_abai_sundae",
    cityCode: "SOKCHO",
    nameKo: "속초 아바이마을 아바이순대국",
    nameEn: "Sokcho Abai Village Sundae Gukbap",
    descKo: "아바이 갯배 마을의 야채와 찹쌀이 듬뿍 들어간 순대국밥",
    descEn: "Traditional sticky rice stuffed sundae soup in Abai village",
    pricePerPerson: 10000,
    recommendedSlot: "BREAKFAST",
    tag: "아바이마을/순대국",
    emoji: "🍲",
    gradientBg: "from-orange-500/15 to-amber-500/15",
  },
  {
    id: "sokcho_food_redcrab",
    cityCode: "SOKCHO",
    nameKo: "속초 동명항 푸짐한 홍게찜 & 게딱지밥",
    nameEn: "Sokcho Dongmyeong Steamed Red Crab",
    descKo: "속초 동명항 갓 잡아 올린 싱싱한 붉은 홍게 찜 한상",
    descEn: "Steamed sweet red crab platter with savory rice stuffed in shell",
    pricePerPerson: 38000,
    recommendedSlot: "DINNER",
    tag: "동명항/홍게찜",
    emoji: "🦀",
    gradientBg: "from-rose-500/15 to-red-500/15",
  },
  {
    id: "sokcho_food_gelato",
    cityCode: "SOKCHO",
    nameKo: "속초 해변 감성 수제 감자 젤라또",
    nameEn: "Sokcho Beach Potato Gelato",
    descKo: "속초 감자와 옥수수로 만든 고소하고 독특한 수제 젤라또",
    descEn: "Handmade artisanal gelato made with local sweet potato & corn",
    pricePerPerson: 5500,
    recommendedSlot: "SNACK_CAFE",
    tag: "감자젤라또/디저트",
    emoji: "🍨",
    gradientBg: "from-yellow-500/15 to-amber-500/15",
  },
  {
    id: "sokcho_food_seafood_soup",
    cityCode: "SOKCHO",
    nameKo: "속초 설악산 산채 비빔밥 & 도토리묵",
    nameEn: "Seoraksan Mountain Herb Bibimbap",
    descKo: "설악산 자락 향긋한 산나물과 고소한 도토리묵 무침 세트",
    descEn: "Fresh mountain herbs bibimbap with acorn jelly salad",
    pricePerPerson: 13000,
    recommendedSlot: "LUNCH",
    tag: "설악산/산채비빔밥",
    emoji: "🏔️",
    gradientBg: "from-emerald-500/15 to-teal-500/15",
  },

  // === YEOSU ===
  {
    id: "yeosu_food_crab_set",
    cityCode: "YEOSU",
    nameKo: "여수 원조 간장게장 & 양념게장 백반",
    nameEn: "Yeosu Soy Sauce & Spicy Crab Set",
    descKo: "밥도둑 알배기 간장게장과 매콤달콤 양념게장이 끊임없이 리필되는 백반",
    descEn: "Famous soy sauce marinated raw crab & spicy crab refill set",
    pricePerPerson: 16000,
    recommendedSlot: "LUNCH",
    tag: "밥도둑/간장게장",
    emoji: "🦀",
    gradientBg: "from-amber-500/15 to-orange-500/15",
  },
  {
    id: "yeosu_food_seafood_samhap",
    cityCode: "YEOSU",
    nameKo: "여수 낭만포차 해물삼합 (문어+삼겹살+갓김치)",
    nameEn: "Yeosu Romantic Pocha Seafood Samhap",
    descKo: "통문어, 대패 삼겹살, 여수 돌산 갓김치가 불판 위에서 구워지는 삼합",
    descEn: "Famous grilled octopus, pork belly & Dolsan mustard kimchi combo",
    pricePerPerson: 25000,
    recommendedSlot: "DINNER",
    tag: "낭만포차/해물삼합",
    emoji: "🐙",
    gradientBg: "from-rose-500/15 to-purple-500/15",
  },
  {
    id: "yeosu_food_seodaehoe",
    cityCode: "YEOSU",
    nameKo: "여수 중앙동 매콤새콤 서대회무침",
    nameEn: "Yeosu Seasoned Seodae Fish Salad",
    descKo: "막걸리 식초의 새콤함이 오감을 자극하는 여수 별미 서대회무침",
    descEn: "Spicy & sour seasoned tongue sole fish salad mixed with rice",
    pricePerPerson: 14000,
    recommendedSlot: "LUNCH",
    tag: "서대회무침/별미",
    emoji: "🥗",
    gradientBg: "from-orange-500/15 to-red-500/15",
  },
  {
    id: "yeosu_food_eel_shabu",
    cityCode: "YEOSU",
    nameKo: "여수 돌산 고급 하모회 & 새조개 샤브",
    nameEn: "Yeosu Premium Sea Eel Shabu-Shabu",
    descKo: "여수 바다 하모(갯장어)를 한방 육수에 살짝 데쳐 먹는 담백한 샤브",
    descEn: "Premium sea eel shabu-shabu dipped in aromatic herbal broth",
    pricePerPerson: 48000,
    recommendedSlot: "DINNER",
    tag: "하모샤브/보양식",
    emoji: "🍲",
    gradientBg: "from-teal-500/15 to-emerald-500/15",
  },
  {
    id: "yeosu_food_baguette_burger",
    cityCode: "YEOSU",
    nameKo: "여수 이순신광장 수제 바게트버거 & 쑥아이월드",
    nameEn: "Yeosu Handmade Baguette Burger & Mugwort Ice Cream",
    descKo: "바삭 바게트 속에 다진 고기와 특제 소스, 여수 쑥 아이스크림 디저트",
    descEn: "Crispy baguette stuffed with seasoned meat & Yeosu mugwort ice cream",
    pricePerPerson: 6500,
    recommendedSlot: "SNACK_CAFE",
    tag: "바게트버거/쑥아이스",
    emoji: "🥖",
    gradientBg: "from-emerald-500/15 to-amber-500/15",
  },
  {
    id: "yeosu_food_seafood_soup",
    cityCode: "YEOSU",
    nameKo: "여수 오동도 시원한 전복 해물뚝배기",
    nameEn: "Yeosu Odongdo Abalone Seafood Hot Pot",
    descKo: "활전복과 홍합, 가리비가 뚝배기에 넘쳐나는 아침 해장 뚝배기",
    descEn: "Hot pot packed with live abalone, mussels & scallops",
    pricePerPerson: 15000,
    recommendedSlot: "BREAKFAST",
    tag: "전복뚝배기/시원함",
    emoji: "🥘",
    gradientBg: "from-blue-500/15 to-indigo-500/15",
  },
];
