import { BudgetTier, SupportedCity } from "../../../lib/trip-domain";
import { BudgetBasketDefinition, BudgetBasketId, BudgetCategory, MealSlot, FoodWishlistCollection, FoodItem } from "../domain/types";

export const MOCK_CATALOG_VERSION = "mock-v1";
export const MOCK_CATALOG_UPDATE_DATE = "2026-07-01";
export const MOCK_CATALOG_SOURCE_LABEL = "MVP Mock Price Catalog";

export const MOCK_PRICE_CATALOG: BudgetBasketDefinition[] = [
  // === Accommodation ===
  // Seoul
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 75000,
    priceMinKrw: 50000,
    priceMaxKrw: 90000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 135000,
    priceMinKrw: 100000,
    priceMaxKrw: 170000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 290000,
    priceMinKrw: 220000,
    priceMaxKrw: 400000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 65000,
    priceMinKrw: 45000,
    priceMaxKrw: 85000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 120000,
    priceMinKrw: 90000,
    priceMaxKrw: 155000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 250000,
    priceMinKrw: 190000,
    priceMaxKrw: 350000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Food ===
  // Seoul
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 15000,
    priceMaxKrw: 27000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 28000,
    priceMinKrw: 22000,
    priceMaxKrw: 38000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 38000,
    priceMaxKrw: 75000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 14000,
    priceMaxKrw: 25000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 26000,
    priceMinKrw: 20000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 46000,
    priceMinKrw: 35000,
    priceMaxKrw: 68000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === City Transportation ===
  // Seoul
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 6000,
    priceMinKrw: 4000,
    priceMaxKrw: 8000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 8000,
    priceMinKrw: 6000,
    priceMaxKrw: 11000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 12000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 5000,
    priceMinKrw: 3500,
    priceMaxKrw: 7000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 7000,
    priceMinKrw: 5000,
    priceMaxKrw: 10000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 10000,
    priceMaxKrw: 30000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Attractions ===
  // Seoul
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 10000,
    priceMinKrw: 0,
    priceMaxKrw: 20000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 25000,
    priceMaxKrw: 80000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 120000,
    priceMinKrw: 80000,
    priceMaxKrw: 200000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 8000,
    priceMinKrw: 0,
    priceMaxKrw: 18000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 40000,
    priceMinKrw: 20000,
    priceMaxKrw: 65000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 100000,
    priceMinKrw: 65000,
    priceMaxKrw: 170000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Intercity Transportation ===
  {
    id: "KTX_STANDARD",
    category: "INTERCITY_TRANSPORT",
    scope: "INTERCITY",
    supportedBudgetTier: "BUDGET", // Default mapping rules target this as fallback for all tiers
    applicableRoute: "SEOUL-BUSAN",
    representativePriceKrw: 59800,
    priceMinKrw: 59800,
    priceMaxKrw: 59800,
    pricingUnit: "PERSON_ONE_WAY",
    calculationStrategy: "PERSON_ONE_WAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Emergency Fund ===
  {
    id: "EMERGENCY_FIXED",
    category: "EMERGENCY_FUND",
    scope: "TRIP_WIDE",
    supportedBudgetTier: "STANDARD", // Default maps this for all tiers
    representativePriceKrw: 100000,
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    pricingUnit: "FIXED_AMOUNT",
    calculationStrategy: "FIXED_AMOUNT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
];

export const BUDGET_TIER_DEFAULT_BASKETS: Record<BudgetTier, Record<BudgetCategory, BudgetBasketId>> = {
  BUDGET: {
    ACCOMMODATION: "BUDGET_STAY",
    FOOD: "BUDGET_MEAL_PLAN",
    CITY_TRANSPORT: "BASIC_CITY_TRANSPORT",
    ATTRACTION: "MOSTLY_FREE",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  STANDARD: {
    ACCOMMODATION: "STANDARD_HOTEL",
    FOOD: "STANDARD_MEAL_PLAN",
    CITY_TRANSPORT: "STANDARD_CITY_TRANSPORT",
    ATTRACTION: "BALANCED",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  PREMIUM: {
    ACCOMMODATION: "PREMIUM_HERITAGE",
    FOOD: "PREMIUM_MEAL_PLAN",
    CITY_TRANSPORT: "COMFORT_CITY_TRANSPORT",
    ATTRACTION: "EXPERIENCE_RICH",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
};

export const MOCK_MEAL_SLOT_PRICES: Record<
  SupportedCity,
  Record<BudgetTier, Record<MealSlot, number>>
> = {
  SEOUL: {
    BUDGET: { BREAKFAST: 5000, LUNCH: 7000, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 7000, LUNCH: 9000, DINNER: 12000, SNACK_CAFE: 6000 },
    PREMIUM: { BREAKFAST: 10000, LUNCH: 15000, DINNER: 25000, SNACK_CAFE: 10000 },
  },
  BUSAN: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6000, DINNER: 7500, SNACK_CAFE: 3500 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 11000, SNACK_CAFE: 5000 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 14000, DINNER: 23000, SNACK_CAFE: 9000 },
  },
};

export const MOCK_FOOD_COLLECTIONS: FoodWishlistCollection[] = [
  {
    id: "ESSENTIALS",
    nameKo: "한국 대표 식단",
    nameEn: "Korean Essentials",
    descriptionKo: "한국 여행 시 꼭 맛봐야 하는 대표적인 필수 한식 메뉴입니다.",
    descriptionEn: "Essential Korean dishes you must try during your trip to Korea.",
  },
  {
    id: "INTERNATIONAL",
    nameKo: "외국인 선호 식단",
    nameEn: "Popular with International Visitors",
    descriptionKo: "전 세계 여행자들에게 큰 사랑을 받고 있는 대중적인 메뉴입니다.",
    descriptionEn: "Popular Korean dishes loved by international travelers worldwide.",
  },
  {
    id: "TRENDING",
    nameKo: "최신 트렌드 푸드",
    nameEn: "Trending in Korea",
    descriptionKo: "최근 한국에서 가장 핫한 트렌디 디저트 및 요리입니다.",
    descriptionEn: "The hottest trending foods and desserts in Korea right now.",
  },
  {
    id: "SPECIALTIES",
    nameKo: "도시별 로컬 별미",
    nameEn: "Selected City Specialties",
    descriptionKo: "각 방문 도시에서만 경험할 수 있는 대표 향토 음식입니다.",
    descriptionEn: "Local signature dishes that represent each destination city.",
  },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: "K_BBQ",
    nameKo: "삼겹살 구이",
    nameEn: "Korean pork belly BBQ",
    collectionIds: ["ESSENTIALS", "INTERNATIONAL"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 18000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "KIMCHI_STEW",
    nameKo: "김치찌개 정식",
    nameEn: "Kimchi stew set",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["LUNCH", "DINNER"],
    representativePriceKrw: 9000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "MARATANG",
    nameKo: "마라탕 셀프 바",
    nameEn: "Spicy Sichuan hotpot (Maratang)",
    collectionIds: ["TRENDING"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["LUNCH", "DINNER"],
    representativePriceKrw: 12000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "CROOKIE",
    nameKo: "크루키 & 음료",
    nameEn: "Crookie (Croissant Cookie) & Drink",
    collectionIds: ["TRENDING"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["SNACK_CAFE"],
    representativePriceKrw: 8000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SEOUL_SULLEONGTANG",
    nameKo: "서울 설렁탕",
    nameEn: "Seoul Sulgongtang (Beef bone soup)",
    collectionIds: ["SPECIALTIES"],
    applicableCities: ["SEOUL"],
    applicableSlots: ["BREAKFAST", "LUNCH", "DINNER"],
    representativePriceKrw: 11000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "BUSAN_PORK_SOUP",
    nameKo: "부산 돼지국밥",
    nameEn: "Busan Pork soup with rice",
    collectionIds: ["SPECIALTIES", "ESSENTIALS"],
    applicableCities: ["BUSAN"],
    applicableSlots: ["BREAKFAST", "LUNCH", "DINNER"],
    representativePriceKrw: 9000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "BUSAN_SEED_HOTTEOK",
    nameKo: "부산 씨앗호떡 & 식혜",
    nameEn: "Busan Seed Hotteok & Sweet rice drink",
    collectionIds: ["SPECIALTIES"],
    applicableCities: ["BUSAN"],
    applicableSlots: ["SNACK_CAFE"],
    representativePriceKrw: 5000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SHARED_JOKBAL",
    nameKo: "가족 사이즈 족발",
    nameEn: "Jokbal (Pork trotters) Family Size",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 38000,
    pricingUnit: "SHARED_DISH",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "TABLE_CHARGOL",
    nameKo: "참숯 테이블 세팅 비",
    nameEn: "Charcoal Table Setup Charge",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 10000,
    pricingUnit: "PER_TABLE",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
];
