import { BudgetTier, SupportedCity } from "../../../lib/trip-domain";
import { BudgetBasketDefinition, BudgetBasketId, BudgetCategory, MealSlot, FoodWishlistCollection, FoodItem, FoodAddOnItem, LocalTransitStyle } from "../domain/types";

export interface LocalTransitOptionDef {
  style: LocalTransitStyle;
  nameKo: string;
  nameEn: string;
  pricePerDayKrw: number;
  subwayTripsPerDay: number;
  taxiTripsPerDay: number;
  descriptionKo: string;
  descriptionEn: string;
  evidenceKo: string;
  evidenceEn: string;
  badgeKo?: string;
  badgeEn?: string;
}

export const LOCAL_TRANSIT_OPTIONS: LocalTransitOptionDef[] = [
  {
    style: "SUBWAY_BUS",
    nameKo: "대중교통",
    nameEn: "Subway & Bus",
    pricePerDayKrw: 6200,
    subwayTripsPerDay: 4,
    taxiTripsPerDay: 0,
    descriptionKo: "지하철과 시내버스로 주요 관광 명소를 이동합니다.",
    descriptionEn: "Explore cities efficiently using subways and city buses.",
    evidenceKo: "공식 인가요금 기준: 지하철 ₩1,550~₩1,600 / 시내버스 ₩1,500~₩1,550 × 1일 4회 이동 = 약 ₩6,200. (정기권/패스 이용 시 1일 ₩3,333~₩4,333 무제한)",
    evidenceEn: "Official fares: Subway ₩1,550-₩1,600 / Bus ₩1,500-₩1,550 × 4 rides/day = ~₩6,200. (Transit pass offers unlimited rides at ₩3,333-₩4,333/day)",
  },
  {
    style: "STANDARD_MIX",
    nameKo: "대중교통+택시",
    nameEn: "Metro + Taxi",
    pricePerDayKrw: 9500,
    subwayTripsPerDay: 3,
    taxiTripsPerDay: 1,
    descriptionKo: "기본 이동은 지하철/버스를 이용하고, 짐이 있거나 피로할 때 단거리 택시를 1회 탑승합니다.",
    descriptionEn: "Use metro for main travel, take a short taxi ride when tired or carrying bags.",
    evidenceKo: "공식 요금 기준: 지하철/버스 3회(약 ₩4,650~₩4,800) + 중형택시 단거리 1회(기본 ₩4,800 + 거리 가산, 약 5km 이동 ₩9,700 기준 2인 분할 ₩4,850) = ₩9,500.",
    evidenceEn: "Official fares: 3 transit rides (~₩4,650-₩4,800) + 1 short taxi trip (~5km ₩9,700, split ₩4,850/person for 2 travelers) = ₩9,500.",
  },
  {
    style: "COMFORT_TAXI",
    nameKo: "택시",
    nameEn: "Taxi / Uber",
    pricePerDayKrw: 22000,
    subwayTripsPerDay: 1,
    taxiTripsPerDay: 2,
    descriptionKo: "카카오T, Uber, 일반 택시를 주로 이용하여 환승 없이 편안하게 문 앞까지 이동합니다.",
    descriptionEn: "Door-to-door comfort using Kakao T, Uber, and local taxis.",
    evidenceKo: "공식 중형택시 요금 기준: 주간 기본 ₩4,800(1.6~2.0km) + 거리·시간 병산. 평균 5~7km 주행(1회 약 ₩11,000) × 2회 탑승 (2인 탑승 기준 1인당 약 ₩22,000).",
    evidenceEn: "Official standard taxi: Base fare ₩4,800 (1.6-2.0km) + distance/time charge. Average 5-7km trip (~₩11,000) × 2 rides/day (split per person).",
  },
];

/**
 * 도시별 공식 대중교통/택시 인가요금 상세 산출 근거 반환
 */
export function getCityTransitEvidence(city: SupportedCity, style: LocalTransitStyle, locale: "ko" | "en" = "ko"): { title: string; evidence: string } {
  if (city === "BUSAN") {
    if (style === "SUBWAY_BUS") {
      return {
        title: locale === "ko" ? "📊 부산시 대중교통 공식 인가요금 기준" : "📊 Busan Metro & Bus Official Fares",
        evidence: locale === "ko"
          ? "부산시 최신 인가요금 기준: 부산도시철도(휴메트로 2024.05.03 시행) 어른 교통카드 1구간 ₩1,600(2구간 ₩1,800) / 일반 시내버스(2023.10.06 시행) ₩1,550 × 1일 4회 = 약 ₩6,200~₩6,400. (휴메트로 1일권 ₩6,000 / 3일권 ₩13,000 구매 시 1일 ₩4,333 무제한)"
          : "Busan official fares: Busan Metro (HuMetro 2024.05.03) Adult Transit Card 1-zone ₩1,600(2-zone ₩1,800) / City Bus (2023.10.06) ₩1,550 × 4 rides = ~₩6,200. (HuMetro 1-day pass ₩6,000 / 3-day pass ₩13,000 at ₩4,333/day)",
      };
    }
    if (style === "STANDARD_MIX") {
      return {
        title: locale === "ko" ? "📊 부산시 대중교통·택시 공식 인가요금 기준" : "📊 Busan Transit & Taxi Official Fares",
        evidence: locale === "ko"
          ? "부산시 공식 요금 기준: 도시철도/버스 3회(₩4,800) + 중형택시(2023.06.01 시행: 기본 2.0km ₩4,800 + 132m당 100원, 약 5km 이동 시 ₩9,800 기준 2인 분할 ₩4,900) = 약 ₩9,500."
          : "Busan official fares: Metro/Bus 3 rides (₩4,800) + Standard Taxi (2023.06.01: Base 2km ₩4,800 + ₩100/132m, ~5km trip ₩9,800 split ₩4,900/person for 2) = ~₩9,500.",
      };
    }
    return {
      title: locale === "ko" ? "📊 부산시 중형택시 공식 인가요금 기준" : "📊 Busan Standard Taxi Official Fares",
      evidence: locale === "ko"
        ? "부산시 공식 중형택시 기준(2023.06.01 시행): 주간 기본 2.0km ₩4,800 + 거리(132m당 100원)/시간(33초당 100원) 병산. 평균 5~7km 주행(1회 약 ₩11,000) × 2회 탑승 (2인 분할 1인당 약 ₩22,000)."
        : "Busan standard taxi (2023.06.01): Base fare ₩4,800 (2.0km) + ₩100 per 132m & 33s. Average 5-7km trip (~₩11,000) × 2 rides/day (split per person).",
    };
  }

  if (city === "SEOUL") {
    if (style === "SUBWAY_BUS") {
      return {
        title: locale === "ko" ? "📊 서울시 대중교통 공식 인가요금 기준" : "📊 Seoul Public Transit Official Fares",
        evidence: locale === "ko"
          ? "서울시 공식 인가요금 기준: 지하철 기본 ₩1,550 / 시내버스(간·지선) ₩1,500 × 1일 4회 이동 = ₩6,200. (서울 기후동행카드 3일권 ₩10,000 이용 시 1일 ₩3,333 무제한)"
          : "Seoul official fares: Subway ₩1,550 / City Bus ₩1,500 × 4 rides/day = ₩6,200. (Climate Card 3-day pass ₩10,000 offers unlimited rides at ₩3,333/day)",
      };
    }
    if (style === "STANDARD_MIX") {
      return {
        title: locale === "ko" ? "📊 서울시 대중교통·택시 공식 인가요금 기준" : "📊 Seoul Transit & Taxi Official Fares",
        evidence: locale === "ko"
          ? "서울시 공식 요금 기준: 지하철 3회(₩4,650) + 중형택시 단거리 1회(2023.02.01 시행: 기본 1.6km ₩4,800 + 131m당 100원 거리 가산, 약 5km 이동 ₩9,700 기준 2인 분할 ₩4,850) = ₩9,500."
          : "Seoul official fares: 3 subway rides (₩4,650) + 1 short taxi trip (Base 1.6km ₩4,800 + ₩100/131m, ~5km ₩9,700, split ₩4,850/person for 2 travelers) = ₩9,500.",
      };
    }
    return {
      title: locale === "ko" ? "📊 서울시 중형택시 공식 인가요금 기준" : "📊 Seoul Standard Taxi Official Fares",
      evidence: locale === "ko"
        ? "서울시 공식 중형택시 요금 기준(2023.02.01 시행): 주간 기본 1.6km ₩4,800 + 거리(131m당 100원)·시간(30초당 100원) 병산. 평균 5~7km 주행(1회 약 ₩11,000) × 2회 탑승 (2인 탑승 기준 1인당 약 ₩22,000)."
        : "Seoul official standard taxi: Base fare ₩4,800 (1.6km) + ₩100 per 131m & 30s. Average 5-7km trip (~₩11,000) × 2 rides/day (split per person).",
    };
  }

  // 전국 기타 지역 기본
  if (style === "SUBWAY_BUS") {
    return {
      title: locale === "ko" ? "📊 대중교통 공식 인가요금 기준" : "📊 Public Transit Official Fares",
      evidence: locale === "ko"
        ? "지자체 공식 인가요금 기준: 시내버스/도시철도 기본 ₩1,500~₩1,700 × 1일 4회 이동 = 약 ₩6,200."
        : "Official fares: Local bus/metro ₩1,500-₩1,700 × 4 rides/day = ~₩6,200.",
    };
  }
  if (style === "STANDARD_MIX") {
    return {
      title: locale === "ko" ? "📊 대중교통·택시 공식 인가요금 기준" : "📊 Transit & Taxi Official Fares",
      evidence: locale === "ko"
        ? "공식 요금 기준: 시내버스 3회(₩4,650) + 중형택시 단거리 1회(기본 ₩4,800 + 거리 가산, 약 5km 이동 ₩9,700 기준 2인 분할 ₩4,850) = ₩9,500."
        : "Official fares: 3 bus rides (₩4,650) + 1 short taxi trip (~5km ₩9,700, split ₩4,850/person for 2 travelers) = ₩9,500.",
    };
  }
  return {
    title: locale === "ko" ? "📊 중형택시 공식 인가요금 기준" : "📊 Standard Taxi Official Fares",
    evidence: locale === "ko"
      ? "공식 중형택시 요금 기준: 주간 기본 ₩4,800 + 거리·시간 병산. 평균 5~7km 주행(1회 약 ₩11,000) × 2회 탑승 (2인 탑승 기준 1인당 약 ₩22,000)."
      : "Official standard taxi: Base fare ₩4,800 + distance/time charge. Average 5-7km trip (~₩11,000) × 2 rides/day (split per person).",
  };
}

export const MOCK_CATALOG_VERSION = "mock-v1";
export const MOCK_CATALOG_UPDATE_DATE = "2026-07-01";
export const MOCK_CATALOG_SOURCE_LABEL = "MVP Mock Price Catalog";

export const MOCK_PRICE_CATALOG: BudgetBasketDefinition[] = [
  // === Accommodation ===
  // Seoul
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 75000,
    priceMinKrw: 50000,
    priceMaxKrw: 90000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 135000,
    priceMinKrw: 100000,
    priceMaxKrw: 170000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 290000,
    priceMinKrw: 220000,
    priceMaxKrw: 400000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 65000,
    priceMinKrw: 45000,
    priceMaxKrw: 85000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 120000,
    priceMinKrw: 90000,
    priceMaxKrw: 155000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 250000,
    priceMinKrw: 190000,
    priceMaxKrw: 350000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Food ===
  // Seoul
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 15000,
    priceMaxKrw: 27000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 28000,
    priceMinKrw: 22000,
    priceMaxKrw: 38000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 38000,
    priceMaxKrw: 75000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 14000,
    priceMaxKrw: 25000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 26000,
    priceMinKrw: 20000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 46000,
    priceMinKrw: 35000,
    priceMaxKrw: 68000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === City Transportation ===
  // Seoul
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 6000,
    priceMinKrw: 4000,
    priceMaxKrw: 8000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 8000,
    priceMinKrw: 6000,
    priceMaxKrw: 11000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 12000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 5000,
    priceMinKrw: 3500,
    priceMaxKrw: 7000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 7000,
    priceMinKrw: 5000,
    priceMaxKrw: 10000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 10000,
    priceMaxKrw: 30000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Attractions ===
  // Seoul
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 10000,
    priceMinKrw: 0,
    priceMaxKrw: 20000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 30000,
    priceMinKrw: 15000,
    priceMaxKrw: 50000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 30000,
    priceMaxKrw: 90000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 10000,
    priceMinKrw: 0,
    priceMaxKrw: 20000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 30000,
    priceMinKrw: 15000,
    priceMaxKrw: 50000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 50000,
    priceMinKrw: 30000,
    priceMaxKrw: 90000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Intercity Transportation ===
  {
    id: "KTX_STANDARD",
    category: "INTERCITY_TRANSPORT",
    scope: "INTERCITY",
    supportedBudgetTier: "BUDGET", // Default mapping rules target this as fallback for all tiers
    applicableRoute: "SEOUL-BUSAN",
    representativePriceKrw: 59800,
    priceMinKrw: 59800,
    priceMaxKrw: 59800,
    pricingUnit: "PERSON_ONE_WAY",
    calculationStrategy: "PERSON_ONE_WAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Emergency Fund ===
  {
    id: "EMERGENCY_FIXED",
    category: "EMERGENCY_FUND",
    scope: "TRIP_WIDE",
    supportedBudgetTier: "STANDARD", // Default maps this for all tiers
    representativePriceKrw: 100000,
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    pricingUnit: "FIXED_AMOUNT",
    calculationStrategy: "FIXED_AMOUNT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
];

export const BUDGET_TIER_DEFAULT_BASKETS: Record<BudgetTier, Record<BudgetCategory, BudgetBasketId>> = {
  BUDGET: {
    ACCOMMODATION: "BUDGET_STAY",
    FOOD: "BUDGET_MEAL_PLAN",
    CITY_TRANSPORT: "BASIC_CITY_TRANSPORT",
    ATTRACTION: "MOSTLY_FREE",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  STANDARD: {
    ACCOMMODATION: "STANDARD_HOTEL",
    FOOD: "STANDARD_MEAL_PLAN",
    CITY_TRANSPORT: "STANDARD_CITY_TRANSPORT",
    ATTRACTION: "BALANCED",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  PREMIUM: {
    ACCOMMODATION: "PREMIUM_HERITAGE",
    FOOD: "PREMIUM_MEAL_PLAN",
    CITY_TRANSPORT: "COMFORT_CITY_TRANSPORT",
    ATTRACTION: "EXPERIENCE_RICH",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
};

export const MOCK_MEAL_SLOT_PRICES: Record<
  SupportedCity,
  Record<BudgetTier, Record<MealSlot, number>>
> = {
  SEOUL: {
    BUDGET: { BREAKFAST: 5000, LUNCH: 7000, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 7000, LUNCH: 9000, DINNER: 12000, SNACK_CAFE: 6000 },
    PREMIUM: { BREAKFAST: 10000, LUNCH: 15000, DINNER: 25000, SNACK_CAFE: 10000 },
  },
  BUSAN: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6000, DINNER: 7500, SNACK_CAFE: 3500 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 11000, SNACK_CAFE: 5000 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 14000, DINNER: 23000, SNACK_CAFE: 9000 },
  },
  JEJU: {
    BUDGET: { BREAKFAST: 5000, LUNCH: 7000, DINNER: 9000, SNACK_CAFE: 4500 },
    STANDARD: { BREAKFAST: 7000, LUNCH: 10000, DINNER: 14000, SNACK_CAFE: 6500 },
    PREMIUM: { BREAKFAST: 10000, LUNCH: 16000, DINNER: 28000, SNACK_CAFE: 10000 },
  },
  INCHEON: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 12000, SNACK_CAFE: 5500 },
    PREMIUM: { BREAKFAST: 9500, LUNCH: 14500, DINNER: 24000, SNACK_CAFE: 9500 },
  },
  GYEONGJU: {
    BUDGET: { BREAKFAST: 4000, LUNCH: 6000, DINNER: 7500, SNACK_CAFE: 3500 },
    STANDARD: { BREAKFAST: 6000, LUNCH: 8000, DINNER: 11000, SNACK_CAFE: 5000 },
    PREMIUM: { BREAKFAST: 8500, LUNCH: 13000, DINNER: 22000, SNACK_CAFE: 8500 },
  },
  JEONJU: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8000, SNACK_CAFE: 3500 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 11500, SNACK_CAFE: 5000 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 13500, DINNER: 23000, SNACK_CAFE: 8500 },
  },
  GANGNEUNG: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 12000, SNACK_CAFE: 5500 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 14000, DINNER: 24000, SNACK_CAFE: 9000 },
  },
  SUWON: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 12000, SNACK_CAFE: 5500 },
    PREMIUM: { BREAKFAST: 9500, LUNCH: 14500, DINNER: 24000, SNACK_CAFE: 9500 },
  },
  YEOSU: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8500, SNACK_CAFE: 3500 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 9000, DINNER: 12500, SNACK_CAFE: 5000 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 14500, DINNER: 25000, SNACK_CAFE: 9000 },
  },
  SOKCHO: {
    BUDGET: { BREAKFAST: 4500, LUNCH: 6500, DINNER: 8000, SNACK_CAFE: 4000 },
    STANDARD: { BREAKFAST: 6500, LUNCH: 8500, DINNER: 12000, SNACK_CAFE: 5500 },
    PREMIUM: { BREAKFAST: 9000, LUNCH: 14000, DINNER: 24000, SNACK_CAFE: 9000 },
  },
};

export const MOCK_FOOD_COLLECTIONS: FoodWishlistCollection[] = [
  {
    id: "ESSENTIALS",
    nameKo: "한국 대표 식단",
    nameEn: "Korean Essentials",
    descriptionKo: "한국 여행 시 꼭 맛봐야 하는 대표적인 필수 한식 메뉴입니다.",
    descriptionEn: "Essential Korean dishes you must try during your trip to Korea.",
  },
  {
    id: "INTERNATIONAL",
    nameKo: "외국인 선호 식단",
    nameEn: "Popular with International Visitors",
    descriptionKo: "전 세계 여행자들에게 큰 사랑을 받고 있는 대중적인 메뉴입니다.",
    descriptionEn: "Popular Korean dishes loved by international travelers worldwide.",
  },
  {
    id: "TRENDING",
    nameKo: "최신 트렌드 푸드",
    nameEn: "Trending in Korea",
    descriptionKo: "최근 한국에서 가장 핫한 트렌디 디저트 및 요리입니다.",
    descriptionEn: "The hottest trending foods and desserts in Korea right now.",
  },
  {
    id: "SPECIALTIES",
    nameKo: "도시별 로컬 별미",
    nameEn: "Selected City Specialties",
    descriptionKo: "각 방문 도시에서만 경험할 수 있는 대표 향토 음식입니다.",
    descriptionEn: "Local signature dishes that represent each destination city.",
  },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: "K_BBQ",
    nameKo: "삼겹살 구이",
    nameEn: "Korean pork belly BBQ",
    collectionIds: ["ESSENTIALS", "INTERNATIONAL"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 18000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "KIMCHI_STEW",
    nameKo: "김치찌개 정식",
    nameEn: "Kimchi stew set",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["LUNCH", "DINNER"],
    representativePriceKrw: 9000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "MARATANG",
    nameKo: "마라탕 셀프 바",
    nameEn: "Spicy Sichuan hotpot (Maratang)",
    collectionIds: ["TRENDING"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["LUNCH", "DINNER"],
    representativePriceKrw: 12000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "CROOKIE",
    nameKo: "크루키 & 음료",
    nameEn: "Crookie (Croissant Cookie) & Drink",
    collectionIds: ["TRENDING"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["SNACK_CAFE"],
    representativePriceKrw: 8000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SEOUL_SULLEONGTANG",
    nameKo: "서울 설렁탕",
    nameEn: "Seoul Sulgongtang (Beef bone soup)",
    collectionIds: ["SPECIALTIES"],
    applicableCities: ["SEOUL"],
    applicableSlots: ["BREAKFAST", "LUNCH", "DINNER"],
    representativePriceKrw: 11000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "BUSAN_PORK_SOUP",
    nameKo: "부산 돼지국밥",
    nameEn: "Busan Pork soup with rice",
    collectionIds: ["SPECIALTIES", "ESSENTIALS"],
    applicableCities: ["BUSAN"],
    applicableSlots: ["BREAKFAST", "LUNCH", "DINNER"],
    representativePriceKrw: 9000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "BUSAN_SEED_HOTTEOK",
    nameKo: "부산 씨앗호떡 & 식혜",
    nameEn: "Busan Seed Hotteok & Sweet rice drink",
    collectionIds: ["SPECIALTIES"],
    applicableCities: ["BUSAN"],
    applicableSlots: ["SNACK_CAFE"],
    representativePriceKrw: 5000,
    pricingUnit: "PER_PERSON",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SHARED_JOKBAL",
    nameKo: "가족 사이즈 족발",
    nameEn: "Jokbal (Pork trotters) Family Size",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL", "BUSAN"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 38000,
    pricingUnit: "SHARED_DISH",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "TABLE_CHARGOL",
    nameKo: "참숯 테이블 세팅 비",
    nameEn: "Charcoal Table Setup Charge",
    collectionIds: ["ESSENTIALS"],
    applicableCities: ["SEOUL"],
    applicableSlots: ["DINNER"],
    representativePriceKrw: 10000,
    pricingUnit: "PER_TABLE",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
];

export const MOCK_FOOD_ADD_ONS: FoodAddOnItem[] = [
  // 삼겹살(K_BBQ) 종속 Add-on 후보군
  {
    id: "RICE",
    nameKo: "공기밥",
    nameEn: "Steamed Rice",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 1000,
    pricingUnit: "PER_PERSON",
    maxQuantity: 5,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "KIMCHI_STEW_ADDON",
    nameKo: "후식 김치찌개",
    nameEn: "Kimchi Stew (Add-on)",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 7000,
    pricingUnit: "PER_SERVING",
    maxQuantity: 2,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SOUP_ADDON",
    nameKo: "후식 된장찌개",
    nameEn: "Soybean Paste Stew (Add-on)",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 6000,
    pricingUnit: "PER_SERVING",
    maxQuantity: 2,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "STEAMED_EGG",
    nameKo: "계란찜",
    nameEn: "Steamed Egg",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 4000,
    pricingUnit: "PER_SERVING",
    maxQuantity: 2,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "COLD_NOODLES",
    nameKo: "후식 냉면",
    nameEn: "Cold Noodles (Add-on)",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 8000,
    pricingUnit: "PER_PERSON",
    maxQuantity: 4,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "FRIED_RICE",
    nameKo: "날치알 볶음밥",
    nameEn: "Fried Rice (Add-on)",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 3000,
    pricingUnit: "PER_SERVING",
    maxQuantity: 3,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  // 주류 자동 미선택 검증용 항목
  {
    id: "SOJU_ADDON",
    nameKo: "참이슬 소주",
    nameEn: "Korean Soju",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 5000,
    pricingUnit: "PER_CUP",
    maxQuantity: 10,
    isAlcohol: true,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  // 7개 가격 단위 테스트용 특화 MOCK
  {
    id: "SET_MENU_ADDON",
    nameKo: "세트메뉴 번들",
    nameEn: "Bundle Set Menu",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL"],
    representativePriceKrw: 15000,
    pricingUnit: "SET_MENU",
    maxQuantity: 2,
    peoplePerSet: 2,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "SHARED_DISH_ADDON",
    nameKo: "공유 모둠 야채구이",
    nameEn: "Shared Grilled Vegetables",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 20000,
    pricingUnit: "SHARED_DISH",
    maxQuantity: 2,
    servingCapacity: 3,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "PER_TABLE_ADDON",
    nameKo: "참숯 테이블 이용료",
    nameEn: "Charcoal Table Service Fee",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL"],
    representativePriceKrw: 5000,
    pricingUnit: "PER_TABLE",
    maxQuantity: 2,
    tableCapacity: 4,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "PER_ITEM_ADDON",
    nameKo: "쌈무 추가",
    nameEn: "Sliced Pickled Radish Extra",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 2000,
    pricingUnit: "PER_ITEM",
    maxQuantity: 5,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
  {
    id: "BAD_PRICE_ADDON",
    nameKo: "잘못된 가격 음식",
    nameEn: "Invalid Price Addon",
    parentFoodItemIds: ["K_BBQ"],
    applicableCities: ["SEOUL", "BUSAN"],
    representativePriceKrw: 0, // Invalid price (must be positive)
    pricingUnit: "PER_SERVING",
    maxQuantity: 2,
    isAlcohol: false,
    isBeverage: false,
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
  },
];
