import { BudgetTier } from "../../../lib/trip-domain";
import { BudgetBasketDefinition, BudgetBasketId, BudgetCategory } from "../domain/types";

export const MOCK_CATALOG_VERSION = "mock-v1";
export const MOCK_CATALOG_UPDATE_DATE = "2026-07-01";
export const MOCK_CATALOG_SOURCE_LABEL = "MVP Mock Price Catalog";

export const MOCK_PRICE_CATALOG: BudgetBasketDefinition[] = [
  // === Accommodation ===
  // Seoul
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 75000,
    priceMinKrw: 50000,
    priceMaxKrw: 90000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 135000,
    priceMinKrw: 100000,
    priceMaxKrw: 170000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 290000,
    priceMinKrw: 220000,
    priceMaxKrw: 400000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_STAY",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 65000,
    priceMinKrw: 45000,
    priceMaxKrw: 85000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_HOTEL",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 120000,
    priceMinKrw: 90000,
    priceMaxKrw: 155000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_HERITAGE",
    category: "ACCOMMODATION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 250000,
    priceMinKrw: 190000,
    priceMaxKrw: 350000,
    pricingUnit: "ROOM_NIGHT",
    calculationStrategy: "ROOM_NIGHT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Food ===
  // Seoul
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 15000,
    priceMaxKrw: 27000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 28000,
    priceMinKrw: 22000,
    priceMaxKrw: 38000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 38000,
    priceMaxKrw: 75000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BUDGET_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 14000,
    priceMaxKrw: 25000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 26000,
    priceMinKrw: 20000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "PREMIUM_MEAL_PLAN",
    category: "FOOD",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 46000,
    priceMinKrw: 35000,
    priceMaxKrw: 68000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === City Transportation ===
  // Seoul
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 6000,
    priceMinKrw: 4000,
    priceMaxKrw: 8000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 8000,
    priceMinKrw: 6000,
    priceMaxKrw: 11000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 20000,
    priceMinKrw: 12000,
    priceMaxKrw: 35000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "BASIC_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 5000,
    priceMinKrw: 3500,
    priceMaxKrw: 7000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "STANDARD_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 7000,
    priceMinKrw: 5000,
    priceMaxKrw: 10000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "COMFORT_CITY_TRANSPORT",
    category: "CITY_TRANSPORT",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 18000,
    priceMinKrw: 10000,
    priceMaxKrw: 30000,
    pricingUnit: "PERSON_DAY",
    calculationStrategy: "PERSON_DAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Attractions ===
  // Seoul
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "SEOUL",
    representativePriceKrw: 10000,
    priceMinKrw: 0,
    priceMaxKrw: 20000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "SEOUL",
    representativePriceKrw: 50000,
    priceMinKrw: 25000,
    priceMaxKrw: 80000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "SEOUL",
    representativePriceKrw: 120000,
    priceMinKrw: 80000,
    priceMaxKrw: 200000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  // Busan
  {
    id: "MOSTLY_FREE",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "BUDGET",
    applicableCity: "BUSAN",
    representativePriceKrw: 8000,
    priceMinKrw: 0,
    priceMaxKrw: 18000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "BALANCED",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "STANDARD",
    applicableCity: "BUSAN",
    representativePriceKrw: 40000,
    priceMinKrw: 20000,
    priceMaxKrw: 65000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
  {
    id: "EXPERIENCE_RICH",
    category: "ATTRACTION",
    scope: "CITY",
    supportedBudgetTier: "PREMIUM",
    applicableCity: "BUSAN",
    representativePriceKrw: 100000,
    priceMinKrw: 65000,
    priceMaxKrw: 170000,
    pricingUnit: "PER_PERSON",
    calculationStrategy: "PER_PERSON_FIXED",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Intercity Transportation ===
  {
    id: "KTX_STANDARD",
    category: "INTERCITY_TRANSPORT",
    scope: "INTERCITY",
    supportedBudgetTier: "BUDGET", // Default mapping rules target this as fallback for all tiers
    applicableRoute: "SEOUL-BUSAN",
    representativePriceKrw: 59800,
    priceMinKrw: 59800,
    priceMaxKrw: 59800,
    pricingUnit: "PERSON_ONE_WAY",
    calculationStrategy: "PERSON_ONE_WAY",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },

  // === Emergency Fund ===
  {
    id: "EMERGENCY_FIXED",
    category: "EMERGENCY_FUND",
    scope: "TRIP_WIDE",
    supportedBudgetTier: "STANDARD", // Default maps this for all tiers
    representativePriceKrw: 100000,
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    pricingUnit: "FIXED_AMOUNT",
    calculationStrategy: "FIXED_AMOUNT",
    confidence: "MOCK",
    updatedAt: MOCK_CATALOG_UPDATE_DATE,
    sourceLabel: MOCK_CATALOG_SOURCE_LABEL,
    isActive: true,
  },
];

export const BUDGET_TIER_DEFAULT_BASKETS: Record<BudgetTier, Record<BudgetCategory, BudgetBasketId>> = {
  BUDGET: {
    ACCOMMODATION: "BUDGET_STAY",
    FOOD: "BUDGET_MEAL_PLAN",
    CITY_TRANSPORT: "BASIC_CITY_TRANSPORT",
    ATTRACTION: "MOSTLY_FREE",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  STANDARD: {
    ACCOMMODATION: "STANDARD_HOTEL",
    FOOD: "STANDARD_MEAL_PLAN",
    CITY_TRANSPORT: "STANDARD_CITY_TRANSPORT",
    ATTRACTION: "BALANCED",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
  PREMIUM: {
    ACCOMMODATION: "PREMIUM_HERITAGE",
    FOOD: "PREMIUM_MEAL_PLAN",
    CITY_TRANSPORT: "COMFORT_CITY_TRANSPORT",
    ATTRACTION: "EXPERIENCE_RICH",
    INTERCITY_TRANSPORT: "KTX_STANDARD",
    EMERGENCY_FUND: "EMERGENCY_FIXED",
  },
};
