import { TrendItem } from "./types";

export const MOCK_TRENDS: TrendItem[] = [
  {
    id: "seoul-bagel-cafe",
    category: "CAFE",
    categoryLabel: {
      ko: "카페",
      en: "Cafe",
    },
    city: "SEOUL",
    tags: ["Seoul", "Cafe", "Bagel", "Popular"],
    updatedAt: "2026-07-24",
    updatedText: {
      ko: "오늘 업데이트",
      en: "Updated Today",
    },
    badge: {
      ko: "🔥 인기 상승 중",
      en: "🔥 Trending Up",
    },
    badgeType: "HOT",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1000&auto=format&fit=crop",
    isHero: true,
    translations: {
      ko: {
        title: "서울 베이글 카페의 인기",
        overview: "다양한 크림치즈와 독특한 속재료를 넣은 '한국식 베이글'이 2030 세대 사이에서 큰 인기를 끌고 있습니다.",
        tip: "인기 매장은 오전에 조기 마감될 수 있으므로 오픈 시간에 맞춰 방문하는 것을 추천합니다.",
        whyPopular: "다양한 크림치즈와 독특한 속재료를 넣은 '한국식 베이글'이 2030 세대 사이에서 큰 인기를 끌고 있습니다. 오픈런은 기본이며, 인증샷을 부르는 인테리어도 한몫합니다.",
        reasonExplanation: "서울 방문 & 식비 카페 카테고리 선호 연관",
        priceDisplay: "₩ 15,000~ (1인 기준)",
        locationDisplay: "안국동, 압구정 등",
      },
      en: {
        title: "Rising Popularity of Seoul Bagel Cafes",
        overview: "Korean-style bagels stuffed with creative cream cheeses and unique fillings are extremely popular among young locals.",
        tip: "Popular spots often sell out early in the morning, so arriving right around opening time is recommended.",
        whyPopular: "Korean-style bagels featuring inventive cream cheese pairings have taken the cafe scene by storm, drawing crowds for aesthetic interiors and tasty bites.",
        reasonExplanation: "Matched with Seoul visit & Cafe preference",
        priceDisplay: "₩ 15,000~ (per person)",
        locationDisplay: "Anguk, Apgujeong, etc.",
      },
    },
  },
  {
    id: "seongsu-popup",
    category: "PLACE",
    categoryLabel: {
      ko: "장소",
      en: "Place",
    },
    city: "SEOUL",
    tags: ["Seoul", "Seongsu", "PopUp", "Shopping"],
    updatedAt: "2026-07-22",
    updatedText: {
      ko: "2일 전 업데이트",
      en: "Updated 2 days ago",
    },
    badge: {
      ko: "지금 인기",
      en: "Hot Now",
    },
    badgeType: "HOT",
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "성수동 팝업스토어",
        overview: "매주 새로운 브랜드가 열리는 성수동의 팝업스토어 거리. 한정판 굿즈와 독특한 체험을 무료로 즐겨보세요.",
        tip: "인기 팝업은 현장 캐치테이블 예약 후 근처 카페를 탐색하는 것이 좋습니다.",
        reasonExplanation: "서울 성수동 탐색 연관",
        priceDisplay: "무료",
        locationDisplay: "서울",
      },
      en: {
        title: "Seongsu-dong Pop-up Stores",
        overview: "The vibrant Seongsu-dong district hosts limited-edition pop-ups weekly with interactive experiences and exclusive items.",
        tip: "Use digital queue systems upon arrival and explore nearby coffee shops while waiting.",
        reasonExplanation: "Matched with Seongsu-dong area exploration",
        priceDisplay: "Free",
        locationDisplay: "Seoul",
      },
    },
  },
  {
    id: "cvs-dessert-combo",
    category: "FOOD",
    categoryLabel: {
      ko: "분식",
      en: "Food",
    },
    city: "ALL",
    tags: ["Nationwide", "CVS", "Dessert", "Food"],
    updatedAt: "2026-07-24",
    updatedText: {
      ko: "오늘 업데이트",
      en: "Updated Today",
    },
    badge: {
      ko: "에디터 주목",
      en: "Editor's Pick",
    },
    badgeType: "EDITOR",
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "편의점 디저트 조합",
        overview: "MZ세대 사이에서 유행하는 '나만의 편의점 디저트 레시피'. 가성비 좋은 달콤한 꿀조합을 소개합니다.",
        tip: "연유우유와 카스테라 빵 조합, 모찌롤과 딸기우유 조합을 도전해보세요.",
        reasonExplanation: "간식 및 실속 예산 연관",
        priceDisplay: "저렴함",
        locationDisplay: "전국 편의점",
      },
      en: {
        title: "Convenience Store Dessert Combos",
        overview: "Discover viral DIY convenience store dessert pairings created by Korean foodies at affordable prices.",
        tip: "Try pairing condensed milk milk with Castella cake for an ultra-soft sweet treat.",
        reasonExplanation: "Matched with budget snack planning",
        priceDisplay: "Budget Friendly",
        locationDisplay: "Nationwide Convenience Stores",
      },
    },
  },
  {
    id: "traditional-photo-studio",
    category: "CULTURE",
    categoryLabel: {
      ko: "문화",
      en: "Culture",
    },
    city: "SEOUL",
    tags: ["Seoul", "Retro", "Photo", "Culture"],
    updatedAt: "2026-07-17",
    updatedText: {
      ko: "1주 전 업데이트",
      en: "Updated 1 week ago",
    },
    badge: {
      ko: "최근 인기",
      en: "Recent Hit",
    },
    badgeType: "RECENT",
    imageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "전통시장 사진관",
        overview: "레트로 감성을 찾아 전통시장으로 향하는 발길. 흑백 필름으로 남기는 아날로그 추억 만들기.",
        tip: "사진 인화까지 약 30분 소요되며, 기다리는 동안 전통시장의 주전부리를 즐기기 좋습니다.",
        reasonExplanation: "문화 체험 연관",
        priceDisplay: "₩ 20,000~",
        locationDisplay: "서울",
      },
      en: {
        title: "Retro Market Photo Studio",
        overview: "Capture timeless monochrome portraits inside historical traditional markets for an authentic local memory.",
        tip: "Print processing takes around 30 minutes, perfect for snacking around the market.",
        reasonExplanation: "Matched with retro cultural activity",
        priceDisplay: "₩ 20,000~",
        locationDisplay: "Seoul",
      },
    },
  },
  {
    id: "busan-ocean-cafe",
    category: "CAFE",
    categoryLabel: {
      ko: "카페",
      en: "Cafe",
    },
    city: "BUSAN",
    tags: ["Busan", "OceanView", "Cafe"],
    updatedAt: "2026-07-21",
    updatedText: {
      ko: "3일 전 업데이트",
      en: "Updated 3 days ago",
    },
    badge: {
      ko: "계절 한정",
      en: "Seasonal",
    },
    badgeType: "SEASON",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "부산 오션뷰 카페",
        overview: "탁 트인 바다를 바라보며 즐기는 여유. 광안리와 해운대의 숨겨진 신상 뷰맛집 카페 리스트.",
        tip: "일몰 시간대(18:30~19:30)에 창가 자리를 미리 확보하면 해운대의 붉은 노을을 한눈에 담을 수 있습니다.",
        reasonExplanation: "부산 일정 및 카페 연관",
        priceDisplay: "₩ 7,000~",
        locationDisplay: "부산",
      },
      en: {
        title: "Busan Ocean View Cafes",
        overview: "Relax with panoramic sea views along Gwangalli and Haeundae beachside scenic cafes.",
        tip: "Arrive around sunset (6:30 PM - 7:30 PM) for breathtaking golden hour views over the ocean.",
        reasonExplanation: "Matched with Busan itinerary & Cafe spot",
        priceDisplay: "₩ 7,000~",
        locationDisplay: "Busan",
      },
    },
  },
  {
    id: "personal-color",
    category: "BEAUTY",
    categoryLabel: {
      ko: "뷰티",
      en: "Beauty",
    },
    city: "ALL",
    tags: ["Nationwide", "KBeauty", "PersonalColor"],
    updatedAt: "2026-07-24",
    updatedText: {
      ko: "오늘 업데이트",
      en: "Updated Today",
    },
    badge: {
      ko: "지금 인기",
      en: "Hot Now",
    },
    badgeType: "HOT",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "퍼스널 컬러 진단",
        overview: "나에게 가장 잘 어울리는 색은? 한국을 방문하는 외국인 관광객들의 필수 코스가 된 K-뷰티 체험.",
        tip: "분석 결과를 기반으로 로드샵 드럭스토어에서 어울리는 화장품까지 한 번에 쇼핑해보세요.",
        reasonExplanation: "K-뷰티 관심사 연관",
        priceDisplay: "₩ 50,000~",
        locationDisplay: "전국",
      },
      en: {
        title: "K-Beauty Personal Color Analysis",
        overview: "Discover your personalized seasonal color palette with expert beauty consultants, a top experience for travelers.",
        tip: "Use your personal color chart immediately when shopping at cosmetics stores nationwide.",
        reasonExplanation: "Matched with K-Beauty experience",
        priceDisplay: "₩ 50,000~",
        locationDisplay: "Nationwide",
      },
    },
  },
  {
    id: "baseball-food",
    category: "CULTURE",
    categoryLabel: {
      ko: "문화",
      en: "Culture",
    },
    city: "ALL",
    tags: ["Nationwide", "Baseball", "Food", "Culture"],
    updatedAt: "2026-07-19",
    updatedText: {
      ko: "5일 전 업데이트",
      en: "Updated 5 days ago",
    },
    badge: {
      ko: "🔥 인기 상승 중",
      en: "🔥 Trending Up",
    },
    badgeType: "TRENDING",
    imageUrl: "https://images.unsplash.com/photo-1562077772-3bd90403f7f0?q=80&w=800&auto=format&fit=crop",
    translations: {
      ko: {
        title: "야구장 먹거리",
        overview: "응원 문화만큼 유명한 한국 야구장의 특색 있는 먹거리 열전. 구장별 시그니처 메뉴를 확인하세요.",
        tip: "잠실구장 신천 파닭과 고척돔 크림새우는 경기 시작 1시간 전에 구매하는 것이 안전합니다.",
        reasonExplanation: "스포츠 문화 연관",
        priceDisplay: "₩ 15,000~",
        locationDisplay: "전국구장",
      },
      en: {
        title: "Korean Baseball Stadium Eats",
        overview: "Experience electric cheering culture along with iconic stadium snacks such as fried chicken and cream shrimp.",
        tip: "Grab signature stadium dishes at least 1 hour before first pitch to skip long lines.",
        reasonExplanation: "Matched with sports & local food culture",
        priceDisplay: "₩ 15,000~",
        locationDisplay: "Nationwide Stadiums",
      },
    },
  },
];
