import { PlaceItem } from "./types";

export const MOCK_PLACES: PlaceItem[] = [
  // ==========================================
  // SEOUL (13 Places)
  // ==========================================
  {
    id: "mock-seoul-acc-1",
    contentId: "2800001",
    city: "SEOUL",
    category: "ACCOMMODATION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-01",
    latitude: 37.5665,
    longitude: 126.978,
    repImageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    tags: ["호텔", "명동", "시티뷰", "가족"],
    translations: {
      ko: {
        title: "명동 스탠다드 시티 호텔",
        description: "명동 중심가에 위치하여 쇼핑과 대중교통 이용이 편리한 비즈니스 스타일 호텔입니다.",
        address: "서울특별시 중구 명동길 42",
      },
      en: {
        title: "Myeongdong Standard City Hotel",
        description: "A business-style hotel located in central Myeongdong with convenient access to shopping and transit.",
        address: "42 Myeongdong-gil, Jung-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-acc-2",
    contentId: "2800002",
    city: "SEOUL",
    category: "ACCOMMODATION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-02",
    latitude: 37.582,
    longitude: 126.983,
    repImageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop",
    tags: ["한옥", "북촌", "전통", "감성"],
    translations: {
      ko: {
        title: "북촌 헤리티지 한옥 스테이",
        description: "고즈넉한 고택의 멋과 현대적 편의시설이 어우러진 전통 한옥 게스트하우스입니다.",
        address: "서울특별시 종로구 계동길 88",
      },
      en: {
        title: "Bukchon Heritage Hanok Stay",
        description: "A traditional Hanok guesthouse combining historic architecture with modern comfort.",
        address: "88 Gyedong-gil, Jongno-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-res-1",
    contentId: "2800003",
    city: "SEOUL",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-05",
    latitude: 37.556,
    longitude: 126.924,
    repImageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop",
    tags: ["한식", "삼겹살", "홍대", "인기"],
    translations: {
      ko: {
        title: "홍대 구이 마당 (삼겹살 전문)",
        description: "숙성 생삼겹살과 김치찌개로 유명한 홍대 입구 분위기 있는 숯불 구이 전문점입니다.",
        address: "서울특별시 마포구 어울마당로 112",
      },
      en: {
        title: "Hongdae Gui Madang (Korean BBQ)",
        description: "Popular Korean charcoal BBQ spot near Hongdae specializing in aged pork belly and kimchi stew.",
        address: "112 Eoulmadang-ro, Mapo-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-res-2",
    contentId: "2800004",
    city: "SEOUL",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-06",
    latitude: 37.57,
    longitude: 126.986,
    repImageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop",
    tags: ["비빔밥", "전통 한식", "인사동"],
    translations: {
      ko: {
        title: "인사동 전주 전통 비빔밥",
        description: "신선한 산나물과 고추장 양념이 어우러진 전통 가마솥 비빔밥 전문 한식당입니다.",
        address: "서울특별시 종로구 인사동길 35-1",
      },
      en: {
        title: "Insadong Jeonju Bibimbap House",
        description: "Traditional Korean restaurant serving authentic Jeonju bibimbap with fresh vegetables and seasoned paste.",
        address: "35-1 Insadong-gil, Jongno-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-res-huchune",
    contentId: "curated-naver-2069788452",
    city: "SEOUL",
    category: "RESTAURANT",
    sourceName: "KTO",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-08-23",
    latitude: 37.4781708,
    longitude: 126.9573069,
    repImageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop",
    priceStatus: "OFFICIAL_PRICE",
    priceKrw: 25000,
    officialLink: "https://map.naver.com/p/entry/place/2069788452",
    tel: "0507-1316-0414",
    useTime: "17:00 ~ 01:00 (월요일 휴무)",
    tags: ["샤로수길", "일식당", "이자카야", "서울대입구", "하이볼", "유린기"],
    translations: {
      ko: {
        title: "후추네 (샤로수길 일식당 & 이자카야)",
        description: "서울대입구 샤로수길에 위치한 아늑한 분위기의 일식당 & 이자카야. 바삭한 유린기와 따뜻한 스키야키, 시원한 하이볼이 인기있는 핫플레이스입니다.",
        address: "서울특별시 관악구 관악로14길 87 1층 (봉천동 1620-21)",
      },
      en: {
        title: "Huchune (Sharosu-gil Japanese Dining Pub)",
        description: "A trendy and cozy Japanese izakaya nestled in Sharosu-gil near Seoul National Univ. Station. Known for crispy yurin-gi, sukiyaki hot pot, and signature highballs.",
        address: "87, Gwanak-ro 14-gil, Gwanak-gu, Seoul (1F)",
      },
    },
  },
  {
    id: "mock-seoul-res-3",
    contentId: "2800005",
    city: "SEOUL",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "INCOMPLETE", // 이미지 없는 테스트 케이스
    rawUpdatedAt: "2026-03-07",
    latitude: 37.561,
    longitude: 126.995,
    tags: ["시티", "치킨", "동대문", "야간"],
    translations: {
      ko: {
        title: "동대문 야시장 바삭 치킨",
        description: "수제 특제 양념과 바삭한 튀김 옷이 특징인 야간 치맥 전문점입니다.",
        address: "서울특별시 중구 장충단로 253",
      },
      en: {
        title: "Dongdaemun Night Market Crispy Chicken",
        description: "Late-night Korean fried chicken and beer pub famous for its crispy house special glaze.",
        address: "253 Jangchungdan-ro, Jung-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-cafe-1",
    contentId: "2800006",
    city: "SEOUL",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-08",
    latitude: 37.544,
    longitude: 127.056,
    repImageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop",
    tags: ["카페", "성수", "디저트", "베이커리"],
    translations: {
      ko: {
        title: "성수 로스터리 앤 아뜰리에 카페",
        description: "붉은 벽돌 공장을 개조하여 스페셜티 커피와 당일 생산 베이커리를 선보이는 성수동 핫플레이스입니다.",
        address: "서울특별시 성동구 아차산로 13길 11",
      },
      en: {
        title: "Seongsu Roastery & Atelier Cafe",
        description: "Converted industrial space in Seongsu offering specialty roasted coffee and fresh daily pastries.",
        address: "11 Achasan-ro 13-gil, Seongdong-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-cafe-2",
    contentId: "2800007",
    city: "SEOUL",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-09",
    latitude: 37.576,
    longitude: 126.985,
    repImageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop",
    tags: ["전통 다원", "삼청동", "찻집", "힐링"],
    translations: {
      ko: {
        title: "삼청동 달빛 다원 (전통 찻집)",
        description: "오미자차, 오디차와 전통 한과를 즐기며 조용히 쉬어갈 수 있는 정원이 예쁜 전통 찻집입니다.",
        address: "서울특별시 종로구 삼청로 72",
      },
      en: {
        title: "Samcheong Moonlight Tea House",
        description: "Serene traditional Korean tea house featuring seasonal herbal teas, Korean sweets, and a peaceful garden.",
        address: "72 Samcheong-ro, Jongno-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-cafe-3",
    contentId: "2800008",
    city: "SEOUL",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-10",
    latitude: 37.534,
    longitude: 126.994,
    repImageUrl: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop",
    tags: ["이태원", "전망", "에스프레소", "루프탑"],
    translations: {
      ko: {
        title: "이태원 루프탑 라운지 카페",
        description: "남산타워 전경을 한눈에 바라보며 오가닉 에스프레소와 에이드를 마실 수 있는 라운지형 카페입니다.",
        address: "서울특별시 용산구 이태원로 210",
      },
      en: {
        title: "Itaewon Rooftop Lounge Cafe",
        description: "Lounge-style coffee bar offering organic espresso and mocktails with scenic views of Namsan Tower.",
        address: "210 Itaewon-ro, Yongsan-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-att-1",
    contentId: "2800009",
    city: "SEOUL",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-11",
    latitude: 37.5796,
    longitude: 126.977,
    repImageUrl: "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800&auto=format&fit=crop",
    tags: ["경복궁", "고궁", "역사", "무료/할인"],
    translations: {
      ko: {
        title: "경복궁 (Gyeongbokgung Palace)",
        description: "조선 왕조의 대표적인 으뜸 궁궐로 근정전, 경회루 등 아름다운 백제·조선 건축 기양을 자랑합니다.",
        address: "서울특별시 종로구 사직로 161",
      },
      en: {
        title: "Gyeongbokgung Palace",
        description: "The main royal palace of the Joseon Dynasty featuring majestic halls, pavilions, and changing of guards.",
        address: "161 Sajik-ro, Jongno-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-att-2",
    contentId: "2800010",
    city: "SEOUL",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-12",
    latitude: 37.5512,
    longitude: 126.9882,
    repImageUrl: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800&auto=format&fit=crop",
    tags: ["남산", "전망대", "야경", "랜드마크"],
    translations: {
      ko: {
        title: "N서울타워 (N Seoul Tower)",
        description: "서울 중심 남산 정상에 위치하여 360도 도심 야경과 케이블카 체험을 제공하는 서울의 랜드마크입니다.",
        address: "서울특별시 용산구 남산공원길 105",
      },
      en: {
        title: "N Seoul Tower",
        description: "Seoul's iconic landmark at the top of Namsan Mountain offering panoramic city views and cable car rides.",
        address: "105 Namsangongwon-gil, Yongsan-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-att-3",
    contentId: "2800011",
    city: "SEOUL",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-13",
    latitude: 37.509,
    longitude: 127.06,
    repImageUrl: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&auto=format&fit=crop",
    tags: ["강남", "코엑스", "수족관", "쇼핑"],
    translations: {
      ko: {
        title: "코엑스 아쿠아리움 & 별마당 도서관",
        description: "수만 마리의 해양 생물 탐험과 함께 초대형 서가 건축으로 유명한 문화 복합 공간입니다.",
        address: "서울특별시 강남구 영동대로 513",
      },
      en: {
        title: "COEX Aquarium & Starfield Library",
        description: "Large-scale aquarium and open cultural library space located inside the World Trade Center COEX complex.",
        address: "513 Yeongdong-daero, Gangnam-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-cul-1",
    contentId: "2800012",
    city: "SEOUL",
    category: "CULTURE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-14",
    latitude: 37.5239,
    longitude: 126.9804,
    repImageUrl: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&auto=format&fit=crop",
    tags: ["박물관", "국립", "전시", "문화 heritage"],
    translations: {
      ko: {
        title: "국립중앙박물관 (National Museum of Korea)",
        description: "대한민국의 소중한 유물과 역사 기획 전시를 만날 수 있는 세계적 수준의 박물관입니다.",
        address: "서울특별시 용산구 서빙고로 137",
      },
      en: {
        title: "National Museum of Korea",
        description: "World-class museum displaying Korea's rich historical treasures, fine art, and cultural heritage.",
        address: "137 Seobinggo-ro, Yongsan-gu, Seoul",
      },
    },
  },
  {
    id: "mock-seoul-cul-2",
    contentId: "2800013",
    city: "SEOUL",
    category: "CULTURE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-15",
    latitude: 37.5667,
    longitude: 127.0094,
    repImageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop",
    tags: ["DDP", "디자인", "건축", "전시"],
    translations: {
      ko: {
        title: "동대문디자인플라자 (DDP)",
        description: "자하 하디드가 설계한 곡선미 넘치는 미래형 건축물로 다양한 디자인 전시와 패션쇼가 개최됩니다.",
        address: "서울특별시 중구 을지로 281",
      },
      en: {
        title: "Dongdaemun Design Plaza (DDP)",
        description: "Futuristic architectural landmark designed by Zaha Hadid, hosting global fashion, art, and design events.",
        address: "281 Eulji-ro, Jung-gu, Seoul",
      },
    },
  },

  // ==========================================
  // BUSAN (13 Places)
  // ==========================================
  {
    id: "mock-busan-acc-1",
    contentId: "2800014",
    city: "BUSAN",
    category: "ACCOMMODATION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-01",
    latitude: 35.1587,
    longitude: 129.1604,
    repImageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop",
    tags: ["해운대", "오션뷰", "호텔", "휴양"],
    translations: {
      ko: {
        title: "해운대 오션 하버 리조트 Hotel",
        description: "해운대 백사장 도보 1분 거리에 위치하여 탁 트인 에메랄드빛 바다 조망을 자랑하는 리조트입니다.",
        address: "부산광역시 해운대구 해운대해변로 264",
      },
      en: {
        title: "Haeundae Ocean Harbour Resort",
        description: "Beachfront resort hotel in Haeundae offering magnificent ocean views and modern amenities.",
        address: "264 Haeundaehaebyeon-ro, Haeundae-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-acc-2",
    contentId: "2800015",
    city: "BUSAN",
    category: "ACCOMMODATION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-02",
    latitude: 35.153,
    longitude: 129.118,
    repImageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    tags: ["광안리", "광안대교", "부티크"],
    translations: {
      ko: {
        title: "광안리 브릿지뷰 부티크 스테이",
        description: "밤마다 화려하게 빛나는 광안대교 야경을 객실에서 일몰부터 관람할 수 있는 부티크 숙소입니다.",
        address: "부산광역시 수영구 광안해변로 192",
      },
      en: {
        title: "Gwangan Bridge View Boutique Stay",
        description: "Cozy boutique stay featuring front-row views of the illuminated Gwangandaeyo bridge at night.",
        address: "192 Gwanganhaebyeon-ro, Suyeong-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-res-1",
    contentId: "2800016",
    city: "BUSAN",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-05",
    latitude: 35.115,
    longitude: 129.042,
    repImageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop",
    tags: ["돼지국밥", "부산역", "전통", "로컬"],
    translations: {
      ko: {
        title: "부산역 원조 소문난 돼지국밥",
        description: "깊고 진한 사골 육수에 담백한 수육이 푸짐하게 들어간 50년 전통의 부산 대표 국밥집입니다.",
        address: "부산광역시 동구 중앙대로 214번길 8",
      },
      en: {
        title: "Busan Station Original Dwaeji Gukbap",
        description: "50-year-old famous local restaurant serving iconic pork rice soup in rich broth.",
        address: "8 Churyang-dong, Dong-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-res-2",
    contentId: "2800017",
    city: "BUSAN",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-06",
    latitude: 35.097,
    longitude: 129.031,
    repImageUrl: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&auto=format&fit=crop",
    tags: ["자갈치", "회", "해산물", "시장"],
    translations: {
      ko: {
        title: "자갈치 시장 해녀 싱싱 회센터",
        description: "자갈치 시장에서 당일 직송한 활어회와 해물탕을 바다를 바라보며 즐길 수 있는 식당입니다.",
        address: "부산광역시 중구 자갈치해안로 52",
      },
      en: {
        title: "Jagalchi Haenyeo Fresh Seafood House",
        description: "Authentic seafood house at Jagalchi Market serving freshly caught raw fish and spicy seafood stew.",
        address: "52 Jagalchi-haeanro, Jung-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-res-3",
    contentId: "2800018",
    city: "BUSAN",
    category: "RESTAURANT",
    sourceName: "MOCK",
    qualityStatus: "INCOMPLETE", // 이미지 없는 테스트 케이스
    rawUpdatedAt: "2026-03-07",
    latitude: 35.155,
    longitude: 129.059,
    tags: ["밀면", "서면", "향토음식"],
    translations: {
      ko: {
        title: "서면 가야밀면 본가",
        description: "살얼음 동동 띄운 한약재 육수와 매콤달콤 양념장이 어우러진 부산 향토 밀면 전문점입니다.",
        address: "부산광역시 부산진구 서면로 68",
      },
      en: {
        title: "Seomyeon Gaya Milmyeon Main Branch",
        description: "Local favorite serving refreshing Busan-style wheat noodles in chilled spiced broth.",
        address: "68 Seomyeon-ro, Busanjin-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-cafe-1",
    contentId: "2800019",
    city: "BUSAN",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-08",
    latitude: 35.161,
    longitude: 129.178,
    repImageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop",
    tags: ["청사포", "해변열차", "오션뷰", "카페"],
    translations: {
      ko: {
        title: "청사포 수평선 베이커리 카페",
        description: "해변열차가 지나는 수평선 풍경과 시그니처 소금빵, 브루잉 커피를 맛볼 수 있는 힐링 카페입니다.",
        address: "부산광역시 해운대구 청사포로 128",
      },
      en: {
        title: "Cheongsapo Horizon Bakery Cafe",
        description: "Scenic coastal cafe overlooking the ocean train line, known for signature salt bread and pour-over coffee.",
        address: "128 Cheongsapo-ro, Haeundae-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-cafe-2",
    contentId: "2800020",
    city: "BUSAN",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-09",
    latitude: 35.093,
    longitude: 129.045,
    repImageUrl: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&auto=format&fit=crop",
    tags: ["영도", "피아크", "대형카페", "항구"],
    translations: {
      ko: {
        title: "영도 항구뷰 아뜰리에 카페",
        description: "부산항 컨테이너선과 북항대교를 오션뷰 테라스에서 조망하는 대형 문화 복합 카페입니다.",
        address: "부산광역시 영도구 해양로 247",
      },
      en: {
        title: "Yeongdo Portview Atelier Cafe",
        description: "Spacious cafe complex offering ocean terrace seating facing the shipping port and North Harbor Bridge.",
        address: "247 Haeyang-ro, Yeongdo-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-cafe-3",
    contentId: "2800021",
    city: "BUSAN",
    category: "CAFE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-10",
    latitude: 35.156,
    longitude: 129.065,
    repImageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop",
    tags: ["전포", "카페거리", "감성", "핸드드립"],
    translations: {
      ko: {
        title: "전포 카페거리 아늑 로스터리",
        description: "전포동 골목 안 잔잔한 클래식 음악과 직접 로스팅한 원두 핸드드립을 즐길 수 있는 카페입니다.",
        address: "부산광역시 부산진구 전포대로 209번길 15",
      },
      en: {
        title: "Jeonpo Cozy Roastery House",
        description: "Charming alleyway coffee lab in Jeonpo Cafe Street serving single-origin hand-drip coffees.",
        address: "15 Jeonpo-daero 209beon-gil, Busanjin-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-att-1",
    contentId: "2800022",
    city: "BUSAN",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-11",
    latitude: 35.0975,
    longitude: 129.0106,
    repImageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop",
    tags: ["감천문화마을", "산복도로", "포토존", "무료"],
    translations: {
      ko: {
        title: "감천문화마을 (Gamcheon Culture Village)",
        description: "알록달록한 계단식 주택과 조형물, 어린왕자 포토존이 이국적인 한국의 마추픽추로 불리는 마을입니다.",
        address: "부산광역시 사하구 감내2로 203",
      },
      en: {
        title: "Gamcheon Culture Village",
        description: "Colorful hillside village with terraced houses, artistic murals, galleries, and scenic photo spots.",
        address: "203 Gamnae 2-ro, Saha-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-att-2",
    contentId: "2800023",
    city: "BUSAN",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-12",
    latitude: 35.1947,
    longitude: 129.2225,
    repImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
    tags: ["해동용궁사", "절", "바다", "종교/역사"],
    translations: {
      ko: {
        title: "해동용궁사 (Haedong Yonggungsa Temple)",
        description: "바닷가 절벽에 세워져 시원한 파도 소리와 108계단을 경험할 수 있는 부산의 해안 사찰입니다.",
        address: "부산광역시 기장군 기장읍 용궁사로 86",
      },
      en: {
        title: "Haedong Yonggungsa Temple",
        description: "Rare coastal Buddhist temple built on dramatic ocean cliffs offering breathtaking seascape views.",
        address: "86 Yonggungsa-ro, Gijang-eup, Gijang-gun, Busan",
      },
    },
  },
  {
    id: "mock-busan-att-3",
    contentId: "2800024",
    city: "BUSAN",
    category: "ATTRACTION",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-13",
    latitude: 35.158,
    longitude: 129.158,
    repImageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    tags: ["해운대", "해변", "산책", "야경"],
    translations: {
      ko: {
        title: "해운대 해수욕장 & 동백섬 산책로",
        description: "부산을 대표하는 해변으로, 옆 동백섬 해안 산책로와 누리마루 APEC 하우스까지 거닐기 좋습니다.",
        address: "부산광역시 해운대구 우동 해운대해변로 264",
      },
      en: {
        title: "Haeundae Beach & Dongbaekseom Coastal Trail",
        description: "Busan's most famous white sand beach connected to the scenic Dongbaekseom pine forest walk.",
        address: "264 Haeundaehaebyeon-ro, Haeundae-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-cul-1",
    contentId: "2800025",
    city: "BUSAN",
    category: "CULTURE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-14",
    latitude: 35.1711,
    longitude: 129.1272,
    repImageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&auto=format&fit=crop",
    tags: ["영화의전당", "BIFF", "건축", "공연"],
    translations: {
      ko: {
        title: "영화의전당 (Busan Cinema Center)",
        description: "부산국제영화제(BIFF) 전용 개막식장이자 세계 최대 빅루프 LED 조명이 빛나는 문화 예술 센터입니다.",
        address: "부산광역시 해운대구 수영강변대로 120",
      },
      en: {
        title: "Busan Cinema Center",
        description: "Official venue of Busan International Film Festival featuring monumental architectural cantilevered roofs.",
        address: "120 Suyeonggangbyeon-daero, Haeundae-gu, Busan",
      },
    },
  },
  {
    id: "mock-busan-cul-2",
    contentId: "2800026",
    city: "BUSAN",
    category: "CULTURE",
    sourceName: "MOCK",
    qualityStatus: "READY",
    rawUpdatedAt: "2026-03-15",
    latitude: 35.1336,
    longitude: 128.9322,
    repImageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop",
    tags: ["현대미술관", "을숙도", "전시", "미술"],
    translations: {
      ko: {
        title: "부산현대미술관 (Museum of Contemporary Art Busan)",
        description: "을숙도 생태공원 내에 자리잡아 미디어아트와 수직정원, 현대 미술 기획전을 선보이는 미술관입니다.",
        address: "부산광역시 사하구 낙동남로 1191",
      },
      en: {
        title: "Museum of Contemporary Art Busan (MOCA)",
        description: "Contemporary art museum located in Eulsukdo eco-park featuring vertical gardens and media art exhibitions.",
        address: "1191 Nakdongnam-ro, Saha-gu, Busan",
      },
    },
  },
];
